import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "goldCardReturnAndRefundProgressFollow": "金卡退货退款进度跟进",
    "linWanru": "林婉如",
    "xiaoLian": "小琏",
    "theCustomerAppliedForAReturnOrder": "客户申请退货（订单 NO20260520331），已收到退货包裹，财务退款待确认。客户为金卡高价值用户，需优先处理并主动同步进度。",
    "system": "系统",
    "customerInitiatesReturnRequest": "客户发起退货申请",
    "warehouse": "仓库",
    "signForReturnPackageAndPassQuality": "退货包裹签收，质检通过",
    "xiaoLian2": "小琏",
    "financeHasBeenRemindedForAnUrgent": "已提醒财务加急退款，预计 1-3 个工作日",
    "sfLogisticsHasNoTrackUpdatesFor": "顺丰物流三天无轨迹更新",
    "sunYue": "孙悦",
    "ahu": "阿瑚",
    "theCustomerSExpressDeliveryHasBeen": "客户快递自 5-30 起轨迹停滞，多次催促情绪较激动。已联系承运商核查，承诺今晚更新并补偿无门槛券。",
    "system2": "系统",
    "intelligentAssistantToManual": "智能助手转人工",
    "ahu2": "阿瑚",
    "contactSfExpressCustomerServiceToExpedite": "联系顺丰客服催件",
    "ahu3": "阿瑚",
    "issueYuanCompensationCoupons": "发放 10 元补偿券",
    "appNotShippedAfterOrdering": "App 下单后未发货",
    "zhaoTiezhu": "赵铁柱",
    "theCustomerReportedThatYesterdaySOrder": "客户反映昨日订单 NO20260603887 未发货，要求加急。待坐席核实库存与仓配状态。",
    "system3": "系统",
    "createANewWorkOrderThroughWeb": "网页渠道新建工单",
    "heikaHomeAppliancesDoorToDoorInstallation": "黑卡家电上门安装预约",
    "zhouJie": "周杰",
    "wanqing": "晚晴",
    "theBlackCardCustomerHasMadeAn": "黑卡客户预约洗烘一体机安装，已排单至次日上午，待师傅确认后回复客户。",
    "zhouJie2": "周杰",
    "installationAppointmentInitiatedByPhone": "电话发起安装预约",
    "wanqing2": "晚晴",
    "makeAnAppointmentBetweenOClockTomorrow": "预约明日 9-11 点，待师傅确认",
    "dayNoQuestionsAskedExchangeForSneakers": "运动鞋 7 天无理由换货",
    "zhengKai": "郑凯",
    "xiaoLian3": "小琏",
    "theCustomerAppliedForCodeExchangeFor": "客户运动鞋磨脚申请换码，吊牌完整，已发起换货并完成闭环。",
    "zhengKai2": "郑凯",
    "initiateExchangeRequest": "发起换货申请",
    "xiaoLian4": "小琏",
    "exchangeCompletedCustomerSatisfied": "换货完成，客户满意",
    "motherAndBabyBottleMaterialAndSuitable": "母婴奶瓶材质与适用月龄咨询",
    "wuMin": "吴敏",
    "whenNewMothersInquireWhetherAntiColic": "新手妈妈咨询防胀气奶瓶是否适合 0-6 月龄，需提供专业导购话术。",
    "system4": "系统",
    "createANewWorkOrderOnThe": "App 渠道新建工单",
    "electronicInvoiceReIssuance": "电子发票重开",
    "zhaoTiezhu2": "赵铁柱",
    "ahu4": "阿瑚",
    "theCustomerAppliedForAnElectronicInvoice": "客户申请电子发票，已开具并发送至邮箱。",
    "zhaoTiezhu3": "赵铁柱",
    "applyForElectronicInvoice": "申请电子发票",
    "ahu5": "阿瑚",
    "invoiceIssuedAndSentToEmail": "已开票并发送邮箱",
    "couponsCannotBeUsedInCombination": "优惠券无法叠加使用",
    "sunYue2": "孙悦",
    "zhouMing": "周明",
    "customersReportedThatDiscountCouponsAndCategory": "客户反映满减券与品类券无法同用，需说明叠加规则并视情况补发。",
    "sunYue3": "孙悦",
    "feedbackAboutCouponIssues": "反馈优惠券问题",
    "zhouMing2": "周明",
    "verifyTheRulesAndPlanToReissue": "核实规则，拟补发一张品类券",
    "accountSecurityVerificationForRemoteLogin": "账号异地登录安全核验",
    "zhouJie3": "周杰",
    "wanqing3": "晚晴",
    "customersReceiveRemoteLoginRemindersToHelp": "客户收到异地登录提醒，协助完成身份核验与密码重置，账号安全。",
    "system5": "系统",
    "riskControlTriggersRemoteLoginReminder": "风控触发异地登录提醒",
    "wanqing4": "晚晴",
    "verificationPassedPasswordReset": "核验通过，已重置密码",
    "theSpecificationDescriptionOnTheProductDetails": "商品详情页规格描述有误",
    "zhengKai3": "郑凯",
    "xiaoLian5": "小琏",
    "theCustomerPointedOutThatTheSize": "客户指出某运动裤尺码表与实物不符，已转商品团队核对并拟更新详情页。",
    "zhengKai4": "郑凯",
    "feedbackAboutWrongSizeChart": "反馈尺码表错误",
    "xiaoLian6": "小琏",
    "transferredToProductTeamToBeUpdated": "已转商品团队，待更新",
  },
  en: {
    "goldCardReturnAndRefundProgressFollow": "Gold card return and refund progress follow-up",
    "linWanru": "Lin Wanru",
    "xiaoLian": "Xiao Lian",
    "theCustomerAppliedForAReturnOrder": "The return for order NO20260520331 has arrived and passed inspection. Finance still needs to confirm the refund. Prioritize this Gold member and proactively share each status update.",
    "system": "System",
    "customerInitiatesReturnRequest": "Customer initiates return request",
    "warehouse": "Warehouse",
    "signForReturnPackageAndPassQuality": "Return received and inspected",
    "xiaoLian2": "Xiao Lian",
    "financeHasBeenRemindedForAnUrgent": "Finance was asked to prioritize the refund. Expected arrival: 1-3 business days.",
    "sfLogisticsHasNoTrackUpdatesFor": "SF Logistics has no track updates for three days",
    "sunYue": "Sun Yue",
    "ahu": "Ahu",
    "theCustomerSExpressDeliveryHasBeen": "Tracking has not changed since May 30, despite several customer follow-ups. The carrier is investigating and has promised an update tonight; offer a no-minimum coupon for the delay.",
    "system2": "System",
    "intelligentAssistantToManual": "AI assistant transferred the conversation to an agent",
    "ahu2": "Ahu",
    "contactSfExpressCustomerServiceToExpedite": "Ask SF Express to trace and expedite the parcel",
    "ahu3": "Ahu",
    "issueYuanCompensationCoupons": "Issue a ¥10 compensation coupon",
    "appNotShippedAfterOrdering": "Order placed in the app has not shipped",
    "zhaoTiezhu": "Zhao Tiezhu",
    "theCustomerReportedThatYesterdaySOrder": "Order NO20260603887 was placed yesterday but has not shipped. The customer asked for expedited delivery; confirm inventory and the warehouse dispatch status.",
    "system3": "System",
    "createANewWorkOrderThroughWeb": "Ticket created from web conversation",
    "heikaHomeAppliancesDoorToDoorInstallation": "Black member appliance installation",
    "zhouJie": "Zhou Jie",
    "wanqing": "Wanqing",
    "theBlackCardCustomerHasMadeAn": "A Black member requested installation for a washer-dryer set. The preferred slot is tomorrow morning; the technician will confirm the appointment with the customer.",
    "zhouJie2": "Zhou Jie",
    "installationAppointmentInitiatedByPhone": "Installation appointment initiated by phone",
    "wanqing2": "Wanqing",
    "makeAnAppointmentBetweenOClockTomorrow": "Requested tomorrow between 09:00 and 11:00; awaiting technician confirmation",
    "dayNoQuestionsAskedExchangeForSneakers": "7-day sneaker exchange",
    "zhengKai": "Zheng Kai",
    "xiaoLian3": "Xiao Lian",
    "theCustomerAppliedForCodeExchangeFor": "The customer requested an exchange for tried-on sneakers. The tags are intact, so the exchange was approved and completed.",
    "zhengKai2": "Zheng Kai",
    "initiateExchangeRequest": "Initiate exchange request",
    "xiaoLian4": "Xiao Lian",
    "exchangeCompletedCustomerSatisfied": "Exchange completed, customer satisfied",
    "motherAndBabyBottleMaterialAndSuitable": "Baby bottle materials and age guidance",
    "wuMin": "Wu Min",
    "whenNewMothersInquireWhetherAntiColic": "The customer wants to know whether an anti-colic bottle is suitable for a baby aged 0-6 months. Provide material, age, and sterilization guidance.",
    "system4": "System",
    "createANewWorkOrderOnThe": "Ticket created from the app channel",
    "electronicInvoiceReIssuance": "Electronic invoice re-issuance",
    "zhaoTiezhu2": "Zhao Tiezhu",
    "ahu4": "Ahu",
    "theCustomerAppliedForAnElectronicInvoice": "The customer requested an electronic invoice. It was issued and sent by email.",
    "zhaoTiezhu3": "Zhao Tiezhu",
    "applyForElectronicInvoice": "Request electronic invoice",
    "ahu5": "Ahu",
    "invoiceIssuedAndSentToEmail": "Invoice issued and sent to email",
    "couponsCannotBeUsedInCombination": "Coupons cannot be used in combination",
    "sunYue2": "Sun Yue",
    "zhouMing": "Zhou Ming",
    "customersReportedThatDiscountCouponsAndCategory": "The customer cannot combine a discount coupon with a category coupon. Explain the stacking rules and issue an alternative coupon when appropriate.",
    "sunYue3": "Sun Yue",
    "feedbackAboutCouponIssues": "Feedback about coupon issues",
    "zhouMing2": "Zhou Ming",
    "verifyTheRulesAndPlanToReissue": "Verify the rules and plan to reissue a category coupon",
    "accountSecurityVerificationForRemoteLogin": "Account security verification for remote login",
    "zhouJie3": "Zhou Jie",
    "wanqing3": "Wanqing",
    "customersReceiveRemoteLoginRemindersToHelp": "The customer received an unfamiliar sign-in alert. Verify their identity and guide them through a password reset.",
    "system5": "System",
    "riskControlTriggersRemoteLoginReminder": "Risk system triggered an unfamiliar sign-in alert",
    "wanqing4": "Wanqing",
    "verificationPassedPasswordReset": "Identity verified; password reset",
    "theSpecificationDescriptionOnTheProductDetails": "The specification description on the product details page is incorrect.",
    "zhengKai3": "Zheng Kai",
    "xiaoLian5": "Xiao Lian",
    "theCustomerPointedOutThatTheSize": "The customer reported that the size chart for a pair of sweatpants does not match the product. The issue has been sent to the product team for verification and a product-page update.",
    "zhengKai4": "Zheng Kai",
    "feedbackAboutWrongSizeChart": "Feedback about wrong size chart",
    "xiaoLian6": "Xiao Lian",
    "transferredToProductTeamToBeUpdated": "Sent to the product team for correction",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-customer-service-data-tickets",
  content: t(content),
};

export default dictionary;
