import { copy } from "./tickets.content";
import type { Ticket } from "./types";

// 10 条工单，覆盖各优先级 / 状态 / 渠道，供列表与详情共用。
export const tickets: Ticket[] = [
  {
    id: "T-2087",
    subject: copy("goldCardReturnAndRefundProgressFollow"),
    customerName: copy("linWanru"),
    priority: "高",
    status: "处理中",
    assignee: copy("xiaoLian"),
    channel: "App",
    createdAt: "2026-05-30 09:12",
    updatedAt: "2026-06-04 14:26",
    description: copy("theCustomerAppliedForAReturnOrder"),
    timeline: [
      { at: "2026-05-30 09:12", actor: copy("system"), text: copy("customerInitiatesReturnRequest") },
      { at: "2026-05-31 10:40", actor: copy("warehouse"), text: copy("signForReturnPackageAndPassQuality") },
      { at: "2026-06-04 14:26", actor: copy("xiaoLian2"), text: copy("financeHasBeenRemindedForAnUrgent") },
    ],
  },
  {
    id: "T-2090",
    subject: copy("sfLogisticsHasNoTrackUpdatesFor"),
    customerName: copy("sunYue"),
    priority: "紧急",
    status: "处理中",
    assignee: copy("ahu"),
    channel: "微信",
    createdAt: "2026-06-02 14:06",
    updatedAt: "2026-06-04 14:10",
    description: copy("theCustomerSExpressDeliveryHasBeen"),
    timeline: [
      { at: "2026-06-02 14:06", actor: copy("system2"), text: copy("intelligentAssistantToManual") },
      { at: "2026-06-04 14:08", actor: copy("ahu2"), text: copy("contactSfExpressCustomerServiceToExpedite") },
      { at: "2026-06-04 14:10", actor: copy("ahu3"), text: copy("issueYuanCompensationCoupons") },
    ],
  },
  {
    id: "T-2093",
    subject: copy("appNotShippedAfterOrdering"),
    customerName: copy("zhaoTiezhu"),
    priority: "中",
    status: "待处理",
    assignee: "—",
    channel: "网页",
    createdAt: "2026-06-04 14:22",
    updatedAt: "2026-06-04 14:22",
    description: copy("theCustomerReportedThatYesterdaySOrder"),
    timeline: [{ at: "2026-06-04 14:22", actor: copy("system3"), text: copy("createANewWorkOrderThroughWeb") }],
  },
  {
    id: "T-2081",
    subject: copy("heikaHomeAppliancesDoorToDoorInstallation"),
    customerName: copy("zhouJie"),
    priority: "中",
    status: "待回复",
    assignee: copy("wanqing"),
    channel: "电话",
    createdAt: "2026-06-03 13:46",
    updatedAt: "2026-06-04 13:48",
    description: copy("theBlackCardCustomerHasMadeAn"),
    timeline: [
      { at: "2026-06-03 13:46", actor: copy("zhouJie2"), text: copy("installationAppointmentInitiatedByPhone") },
      { at: "2026-06-04 13:48", actor: copy("wanqing2"), text: copy("makeAnAppointmentBetweenOClockTomorrow") },
    ],
  },
  {
    id: "T-2061",
    subject: copy("dayNoQuestionsAskedExchangeForSneakers"),
    customerName: copy("zhengKai"),
    priority: "低",
    status: "已解决",
    assignee: copy("xiaoLian3"),
    channel: "网页",
    createdAt: "2026-01-18 11:38",
    updatedAt: "2026-01-19 16:20",
    description: copy("theCustomerAppliedForCodeExchangeFor"),
    timeline: [
      { at: "2026-01-18 11:38", actor: copy("zhengKai2"), text: copy("initiateExchangeRequest") },
      { at: "2026-01-19 16:20", actor: copy("xiaoLian4"), text: copy("exchangeCompletedCustomerSatisfied") },
    ],
  },
  {
    id: "T-2095",
    subject: copy("motherAndBabyBottleMaterialAndSuitable"),
    customerName: copy("wuMin"),
    priority: "低",
    status: "待处理",
    assignee: "—",
    channel: "App",
    createdAt: "2026-06-04 14:20",
    updatedAt: "2026-06-04 14:20",
    description: copy("whenNewMothersInquireWhetherAntiColic"),
    timeline: [{ at: "2026-06-04 14:20", actor: copy("system4"), text: copy("createANewWorkOrderOnThe") }],
  },
  {
    id: "T-2078",
    subject: copy("electronicInvoiceReIssuance"),
    customerName: copy("zhaoTiezhu2"),
    priority: "低",
    status: "已解决",
    assignee: copy("ahu4"),
    channel: "微信",
    createdAt: "2026-06-04 10:12",
    updatedAt: "2026-06-04 10:14",
    description: copy("theCustomerAppliedForAnElectronicInvoice"),
    timeline: [
      { at: "2026-06-04 10:12", actor: copy("zhaoTiezhu3"), text: copy("applyForElectronicInvoice") },
      { at: "2026-06-04 10:14", actor: copy("ahu5"), text: copy("invoiceIssuedAndSentToEmail") },
    ],
  },
  {
    id: "T-2070",
    subject: copy("couponsCannotBeUsedInCombination"),
    customerName: copy("sunYue2"),
    priority: "中",
    status: "待回复",
    assignee: copy("zhouMing"),
    channel: "App",
    createdAt: "2026-06-03 19:02",
    updatedAt: "2026-06-04 09:30",
    description: copy("customersReportedThatDiscountCouponsAndCategory"),
    timeline: [
      { at: "2026-06-03 19:02", actor: copy("sunYue3"), text: copy("feedbackAboutCouponIssues") },
      { at: "2026-06-04 09:30", actor: copy("zhouMing2"), text: copy("verifyTheRulesAndPlanToReissue") },
    ],
  },
  {
    id: "T-2066",
    subject: copy("accountSecurityVerificationForRemoteLogin"),
    customerName: copy("zhouJie3"),
    priority: "高",
    status: "已解决",
    assignee: copy("wanqing3"),
    channel: "网页",
    createdAt: "2026-05-29 22:14",
    updatedAt: "2026-05-30 08:05",
    description: copy("customersReceiveRemoteLoginRemindersToHelp"),
    timeline: [
      { at: "2026-05-29 22:14", actor: copy("system5"), text: copy("riskControlTriggersRemoteLoginReminder") },
      { at: "2026-05-30 08:05", actor: copy("wanqing4"), text: copy("verificationPassedPasswordReset") },
    ],
  },
  {
    id: "T-2059",
    subject: copy("theSpecificationDescriptionOnTheProductDetails"),
    customerName: copy("zhengKai3"),
    priority: "中",
    status: "处理中",
    assignee: copy("xiaoLian5"),
    channel: "网页",
    createdAt: "2026-06-04 08:40",
    updatedAt: "2026-06-04 11:00",
    description: copy("theCustomerPointedOutThatTheSize"),
    timeline: [
      { at: "2026-06-04 08:40", actor: copy("zhengKai4"), text: copy("feedbackAboutWrongSizeChart") },
      { at: "2026-06-04 11:00", actor: copy("xiaoLian6"), text: copy("transferredToProductTeamToBeUpdated") },
    ],
  },
];

export const ticketById = (id: string): Ticket | undefined => tickets.find((t) => t.id === id);
