import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    coralReef: "瑚琏 1.0",
    howSTheWeatherInBeijingToday: "北京今天天气怎么样",
    writeAQuickSortForMe: "帮我写一个快速排序",
    explainWhatAClosureIs: "解释一下什么是闭包",
    whatCanYouDo: "你能做什么？",
    deleteConversation: "删除对话？",
    thisActionCannotBeUndoneAndTheConversationLogWill: "此操作不可撤销，对话记录将永久删除。",
    remove: "删除",
    conversationDeleted: "对话已删除",
    toDeleteAConversation: "删除对话：{0}",
    coralAssistants: "瑚琏助手",
    searchConversations: "搜索对话",
    collapseSidebar: "收起侧栏",
    newConversation: "新建对话",
    account: "账户",
    demoNoAccessToLiveAccountSystem: "demo 演示，未接入真实账户体系",
    coralReefUsers: "瑚琏用户",
    freeVersion: "免费版",
    coral: "瑚",
    accountMenu: "账户菜单",
    personalSettings: "个人设置",
    upgradeToPro: "升级到 Pro",
    helpFeedback: "帮助与反馈",
    loggedOut: "已退出登录",
    logOut: "退出登录",
    thinkingDuration: "思考 {0}s",
    source: "来源：",
    thisIsASummaryOfTheOriginalTextOfThe:
      "这是引用来源的原文摘要。悬停在引用标签上可预览文章摘要，帮助读者快速判断引用内容的相关性和可信度，无需跳转即可获得上下文。",
    seeOriginalText: "查看原文 →",
    copiedToClipboard: "已复制到剪贴板",
    regenerating: "重新生成中…",
    thankYouForYourFeedback: "感谢你的反馈 👍",
    recordedAndWeWillContinueToImprove: "已记录，我们会继续改进",
    newConversationAlternate: "新对话",
    sessionList: "会话列表",
    expandSidebar: "展开侧栏",
    aiConversationTool: "AI 对话工具",
    switchedModel: "已切换到 {0}",
    selectModel: "选择模型",
    searchForAModel: "搜索模型…",
    startAConversation: "开始一段对话",
    askMeAboutTheWeatherAskMeToCodeOr: "问我天气、让我写代码、或解释一个概念",
    conversationMode: "对话模式",
    quickMode: "快速模式",
    expertMode: "专家模式",
    me: "我",
    sendAMessageToHulianSAssistant: "给瑚琏助手发消息…",
    deepThinking: "深度思考",
    smartSearch: "智能搜索",
    addAttachment: "添加附件",
    hualianAssistantMayMakeErrorsThisDemoIsAPure:
      "瑚琏助手可能会出错 · 本 demo 为纯前端交互演示，未接入真实模型",
    send: "发送",
  },
  en: {
    coralReef: "Hulian 1.0",
    howSTheWeatherInBeijingToday: "How's the weather in Beijing today?",
    writeAQuickSortForMe: "Write a quick sort for me",
    explainWhatAClosureIs: "Explain what a closure is",
    whatCanYouDo: "What can you do?",
    deleteConversation: "Delete conversation?",
    thisActionCannotBeUndoneAndTheConversationLogWill:
      "This action cannot be undone. The conversation will be permanently deleted.",
    remove: "Delete",
    conversationDeleted: "Conversation deleted",
    toDeleteAConversation: "Delete conversation: {0}",
    coralAssistants: "Hulian Assistant",
    searchConversations: "Search conversations",
    collapseSidebar: "Collapse sidebar",
    newConversation: "New conversation",
    account: "Account",
    demoNoAccessToLiveAccountSystem: "Demo only — no live account is connected.",
    coralReefUsers: "Hulian user",
    freeVersion: "Free plan",
    coral: "H",
    accountMenu: "Account menu",
    personalSettings: "Personal settings",
    upgradeToPro: "Upgrade to Pro",
    helpFeedback: "Help and feedback",
    loggedOut: "Logged out",
    logOut: "Log out",
    thinkingDuration: "Thought for {0}s",
    source: "Source:",
    thisIsASummaryOfTheOriginalTextOfThe:
      "Preview the cited passage here to judge its relevance and credibility without leaving the conversation.",
    seeOriginalText: "View source →",
    copiedToClipboard: "Copied to clipboard",
    regenerating: "Regenerating...",
    thankYouForYourFeedback: "Thank you for your feedback 👍",
    recordedAndWeWillContinueToImprove: "Feedback recorded. We'll keep improving.",
    newConversationAlternate: "New conversation",
    sessionList: "Conversation list",
    expandSidebar: "Expand sidebar",
    aiConversationTool: "AI chat",
    switchedModel: "Switched to {0}",
    selectModel: "Select model",
    searchForAModel: "Search for a model...",
    startAConversation: "Start a conversation",
    askMeAboutTheWeatherAskMeToCodeOr:
      "Ask about the weather, request some code, or explore a concept.",
    conversationMode: "Conversation mode",
    quickMode: "Quick mode",
    expertMode: "Expert mode",
    me: "Me",
    sendAMessageToHulianSAssistant: "Message Hulian Assistant...",
    deepThinking: "Deep thinking",
    smartSearch: "Web search",
    addAttachment: "Add attachment",
    hualianAssistantMayMakeErrorsThisDemoIsAPure:
      "Hulian Assistant can make mistakes · This front-end demo is not connected to a live model",
    send: "Send",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>(
    (text, value, index) => text.replaceAll(`{${index}}`, String(value)),
    content[DOCS_LOCALE][key],
  );
}

const dictionary: Dictionary = {
  key: "demo-ai-chat-page",
  content: t(content),
};

export default dictionary;
