import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

import { format } from "prettier";

import { repositoryRoot } from "../paths";
import type { InventoryEntry } from "./inventory";
import { buildRepositoryInventory } from "./repository";

const generatedPath = join(repositoryRoot, "apps/perf-lab/scenarios/generated.ts");
const nonRenderingPath = join(repositoryRoot, "apps/perf-lab/scenarios/non-rendering.json");

function quote(value: string): string {
  return JSON.stringify(value);
}

export function renderScenarioLoaders(inventory: InventoryEntry[]): string {
  const entries = inventory.filter(
    (
      entry,
    ): entry is InventoryEntry & {
      showcaseExport: string;
      showcaseSource: string;
      scenarioId: string;
    } =>
      entry.kind === "renderable" &&
      typeof entry.showcaseExport === "string" &&
      typeof entry.showcaseSource === "string" &&
      typeof entry.scenarioId === "string",
  );
  const loaderLines = entries.map(
    (entry) =>
      `  ${quote(entry.id)}: async () => (await import(${quote(
        `@hulianui/ui-internal/${entry.showcaseSource.slice(2)}`,
      )})).${entry.showcaseExport},`,
  );
  const metadataLines = entries.map(
    (entry) =>
      `  ${quote(entry.id)}: ${JSON.stringify({
        id: entry.id,
        scenarioId: entry.scenarioId,
        component: entry.exports[0] ?? entry.id,
        entry: entry.entry,
        categories: entry.categories,
        animated: entry.animated,
        webgl: entry.webgl,
        source: entry.source,
      })},`,
  );
  return format(
    [
      "// Generated by packages/hulian-scan/src/inventory/generate.ts. Do not edit.",
      'import type { ShowcaseSpec } from "@hulianui/ui";',
      "",
      "export const scenarioLoaders = {",
      ...loaderLines,
      "} satisfies Record<string, () => Promise<ShowcaseSpec>>;",
      "",
      "export const scenarioMetadata = {",
      ...metadataLines,
      "} as const;",
      "",
    ].join("\n"),
    { parser: "typescript" },
  );
}

function renderNonRendering(inventory: InventoryEntry[]): string {
  return `${JSON.stringify(
    inventory
      .filter((entry) => entry.kind === "non-rendering")
      .map(({ id, entry, source, exports, aliases, reason }) => ({
        id,
        entry,
        source,
        exports,
        aliases,
        reason,
      })),
    null,
    2,
  )}\n`;
}

async function writeAtomic(path: string, contents: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  const temporary = `${path}.${process.pid}.tmp`;
  await writeFile(temporary, contents, "utf8");
  await rename(temporary, path);
}

async function assertCurrent(path: string, expected: string): Promise<void> {
  let actual: string;
  try {
    actual = await readFile(path, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      throw new Error(`generated inventory file is missing: ${path}`);
    }
    throw error;
  }
  if (actual !== expected) {
    throw new Error(`generated inventory file is stale: ${path}`);
  }
}

export async function generateInventory(options: { check: boolean }): Promise<InventoryEntry[]> {
  const inventory = await buildRepositoryInventory();
  const generated = renderScenarioLoaders(inventory);
  const nonRendering = renderNonRendering(inventory);
  if (options.check) {
    await Promise.all([
      assertCurrent(generatedPath, generated),
      assertCurrent(nonRenderingPath, nonRendering),
    ]);
  } else {
    await Promise.all([
      writeAtomic(generatedPath, generated),
      writeAtomic(nonRenderingPath, nonRendering),
    ]);
  }
  const renderable = inventory.filter((entry) => entry.kind === "renderable");
  const unclassified = inventory.filter(
    (entry) => entry.kind === "renderable" && typeof entry.scenarioId !== "string",
  );
  if (unclassified.length > 0) {
    throw new Error(
      `unclassified renderable entries: ${unclassified.map((entry) => entry.id).join(", ")}`,
    );
  }
  console.log(
    `Hulian Scan inventory: ${renderable.length} renderable, ${
      inventory.length - renderable.length
    } non-rendering, 0 unclassified`,
  );
  return inventory;
}

const entry = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : undefined;
if (entry === import.meta.url) {
  generateInventory({ check: process.argv.slice(2).includes("--check") }).catch(
    (error: unknown) => {
      console.error(error instanceof Error ? error.message : String(error));
      process.exitCode = 1;
    },
  );
}
