import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    linYu: "林屿",
    fullStackEngineer: "全栈工程师",
    independentDeveloper: "独立开发者",
    productDesigner: "产品设计师",
    openSourceMaintainer: "开源作者",
    iBuildThingsIWantToUse: "我做能自己用的东西。",
    indieMakerHangzhou: "Indie maker · 杭州",
    hangzhouChina: "中国 · 杭州",
    iAmLinYuAnIndependentFullStackDeveloperAndProductMakerOverThePastSixYearsIHaveTurnedEveryIdeaIWa: "我是林屿，一个独立全栈开发者，也是独立产品作者。过去六年里我没有进过大厂——更准确地说，我把每一个「想自己用」的念头，都做成了能跑起来的产品。",
    iAlwaysBuildThingsInReverseFirstComesAProblemThatBothersMeEveryDayThenAProductConstantInterrupti: "做东西的顺序总是相反的：先有一个我自己每天都被它折磨的问题，然后才有产品。专注总被打断，于是有了「潮汐」；截图代码丑得没法发推，于是有了「码尺」；笔记散落在五个云端，于是有了本地优先的「墨册」。",
    iBelieveInSmallEnduringSoftwareThatOnePersonCanMaintainSustainAsABusinessAndUseForADecadeTechnol: "我相信小而美的软件：一个人能维护、能盈利、能用十年。技术只是手段，我更在意的是一个产品用起来「顺不顺手」——那 5% 的体验差距，往往是我花 50% 时间打磨的地方。",
    thisSiteIsAlsoDogfoodEveryPixelFromTheAuroraBackgroundToTheGuestbookIsBuiltWithMyOwnComponentLib: "这个站点本身也是一次 dogfood：从极光背景到留言板，每一个像素都由我自己的组件库搭成，没有引用任何外部 UI 库。",
    totalDownloads: "累计下载",
    productsShipped: "上线产品",
    coffeeForCoding: "写代码的咖啡",
    coffee: "杯",
    email: "邮箱",
    frontendReactTypescript: "前端 · React / TypeScript",
    componentLibrariesDesignSystemsMotion: "组件库 / 设计系统 / 动效",
    fullStackNodeRustGo: "全栈 · Node / Rust / Go",
    localFirstEdgeFunctionsCli: "本地优先 · 边缘函数 · CLI",
    mobileSwiftSwiftui: "移动端 · Swift / SwiftUI",
    nativeIosWatchos: "iOS / watchOS 原生",
    productDesignFigma: "产品设计 · Figma",
    visualAndInteractionDesignFromZeroToOne: "从 0 到 1 的视觉与交互",
    growthContentSeo: "增长 · 内容 / SEO",
    launchingAnIndependentProduct: "独立产品的冷启动",
    languages: "语言",
    frontEnd: "前端",
    backendInfrastructure: "后端 / 基建",
    designTools: "设计 / 工具",
    becameAFullTimeIndieDeveloper: "全职独立开发",
    leftMyJobToBuildIndependentProductsFullTimeSupportedByCodeframeAndTide: "辞职 all in 独立产品，靠「码尺」「潮汐」养活自己。",
    releasedTideOnTheAppStore: "「潮汐 Tide」上架 App Store",
    myFirstIndependentAppReached50000OrganicDownloadsInThreeMonths: "首个独立 APP，三个月内自然增长到 5 万下载。",
    openSourcedFlowctl: "开源「flowctl」",
    aLocalWorkflowCliWithMoreThan10000GithubStars: "一个本地工作流 CLI，GitHub 破万 star。",
    leftMySecondJob: "离开第二份工作",
    movedFromFullStackEngineeringTowardBecomingAGeneralistWhoCanShipAnEntireProductAlone: "从全栈工程师转向「能自己做完一个产品」的 generalist。",
    wroteMyFirstLineOfRust: "写下第一行 Rust",
    discoveredTheLocalFirstSoftwarePhilosophy: "被本地优先（local-first）软件理念击中。",
  },
  en: {
    linYu: "Lin Yu",
    fullStackEngineer: "Full-stack engineer",
    independentDeveloper: "Independent developer",
    productDesigner: "Product designer",
    openSourceMaintainer: "Open-source maintainer",
    iBuildThingsIWantToUse: "I build things I want to use.",
    indieMakerHangzhou: "Indie maker · Hangzhou",
    hangzhouChina: "Hangzhou, China",
    iAmLinYuAnIndependentFullStackDeveloperAndProductMakerOverThePastSixYearsIHaveTurnedEveryIdeaIWa: "I am Lin Yu, an independent full-stack developer and product maker. Over the past six years, I have turned every idea I wanted for myself into a working product.",
    iAlwaysBuildThingsInReverseFirstComesAProblemThatBothersMeEveryDayThenAProductConstantInterrupti: "I always build things in reverse: first comes a problem that bothers me every day, then a product. Constant interruptions led to Tide; ugly code screenshots led to CodeFrame; notes scattered across five clouds led to the local-first Inkbook.",
    iBelieveInSmallEnduringSoftwareThatOnePersonCanMaintainSustainAsABusinessAndUseForADecadeTechnol: "I believe in small, enduring software that one person can maintain, sustain as a business, and use for a decade. Technology is only a means; I care most about whether a product feels effortless. That final 5% of the experience often takes half my time.",
    thisSiteIsAlsoDogfoodEveryPixelFromTheAuroraBackgroundToTheGuestbookIsBuiltWithMyOwnComponentLib: "This site is also dogfood: every pixel, from the aurora background to the guestbook, is built with my own component library and no external UI kit.",
    totalDownloads: "Total downloads",
    productsShipped: "Products shipped",
    coffeeForCoding: "Coffee for coding",
    coffee: "coffee",
    email: "Email",
    frontendReactTypescript: "Frontend · React / TypeScript",
    componentLibrariesDesignSystemsMotion: "Component libraries / design systems / motion",
    fullStackNodeRustGo: "Full stack · Node / Rust / Go",
    localFirstEdgeFunctionsCli: "Local first · Edge functions · CLI",
    mobileSwiftSwiftui: "Mobile · Swift / SwiftUI",
    nativeIosWatchos: "Native iOS / watchOS",
    productDesignFigma: "Product design · Figma",
    visualAndInteractionDesignFromZeroToOne: "Visual and interaction design from zero to one",
    growthContentSeo: "Growth · Content / SEO",
    launchingAnIndependentProduct: "Launching an independent product",
    languages: "Languages",
    frontEnd: "front end",
    backendInfrastructure: "Backend / infrastructure",
    designTools: "Design / tools",
    becameAFullTimeIndieDeveloper: "Became a full-time indie developer",
    leftMyJobToBuildIndependentProductsFullTimeSupportedByCodeframeAndTide: "Left my job to build independent products full time, supported by CodeFrame and Tide.",
    releasedTideOnTheAppStore: "Released Tide on the App Store",
    myFirstIndependentAppReached50000OrganicDownloadsInThreeMonths: "My first independent app reached 50,000 organic downloads in three months.",
    openSourcedFlowctl: "Open-sourced flowctl",
    aLocalWorkflowCliWithMoreThan10000GithubStars: "A local workflow CLI with more than 10,000 GitHub stars.",
    leftMySecondJob: "Left my second job",
    movedFromFullStackEngineeringTowardBecomingAGeneralistWhoCanShipAnEntireProductAlone: "Moved from full-stack engineering toward becoming a generalist who can ship an entire product alone.",
    wroteMyFirstLineOfRust: "Wrote my first line of Rust",
    discoveredTheLocalFirstSoftwarePhilosophy: "Discovered the local-first software philosophy.",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>(
    (text, value, index) => text.replaceAll(`{${index}}`, String(value)),
    content[DOCS_LOCALE][key],
  );
}

const dictionary: Dictionary = {
  key: "demo-personal-data-profile",
  content: t(content),
};

export default dictionary;
