import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    codeframe: "码尺",
    turnCodeScreenshotsIntoArtworkWorthSharing: "把代码截图，变成能发推的艺术品。",
    online: "在线",
    unavailable: "已下架",
    beta: "Beta",
    tryOnline: "在线使用",
    source: "源码",
    codeframeIsABrowserBasedCodeImageToolPasteCodeChooseAThemeAndExportAHighResolutionImageWithWindo: "码尺是一个浏览器里的代码美化工具：粘贴代码，选主题，导出一张带窗口外壳、语法高亮、柔光阴影的高清图。",
    itBeganWithMyOwnFrustrationWhenSharingTechnicalPostsSystemScreenshotsLookedPoorAndCarbonFeltSlow: "它最初是我自己发技术推时的痛点——系统截图太丑、Carbon 太慢。码尺做到了「粘贴即所得」，导出走 Satori 在边缘函数渲染，3 秒出 2x 高清图。",
    text30ColorThemes: "30+ 配色主题",
    customizeEverythingIncludingBrandColorsAndWindowStyles: "全部可改，支持自定义品牌色与窗口样式",
    edgeRenderedExports: "边缘渲染导出",
    cloudflareWorkersSatoriHighResolution2x4xPngAndSvg: "Cloudflare Workers + Satori，2x/4x 高清 PNG/SVG",
    keyboardFirst: "快捷键优先",
    vToPasteEToExportNoMouseRequired: "⌘V 粘贴 → ⌘E 导出，全程不用鼠标",
    editorWorkspace: "编辑器主界面",
    themePicker: "主题选择面板",
    exportPreview: "导出预览",
    edgeRenderedExports2: "边缘函数渲染导出",
    renderCodeAsAnImageWithSatoriOnCloudflareWorkersImportSatoriFromSatoriExportAsyncFunctionRenderc: "// 在 Cloudflare Workers 用 Satori 把代码渲染成图\nimport satori from \"satori\";\n\nexport async function renderCode(code: string, theme: Theme) {\n  const svg = await satori(\n    <CodeCard code={code} theme={theme} />,\n    { width: 1200, fonts: await loadFonts() },\n  );\n  return new Response(svg, {\n    headers: { \"content-type\": \"image/svg+xml\" },\n  });\n}",
    monthlyActiveUsers: "月活",
    exportImage: "导出图片",
    text19m: "190 万+",
    themes: "主题",
    tide: "潮汐",
    letFocusRiseAndFallLikeTheTide: "像潮水一样，专注自然涨落。",
    productPage: "产品页",
    tideIsAnAntiPomodoroFocusAppInsteadOfForcingWorkInto25MinuteBlocksItFollowsYourRhythmWithABreath: "潮汐是一个反「番茄钟」的专注 APP：它不强迫你切成 25 分钟一段，而是顺着你的状态，用一段会呼吸的潮汐动效陪你进入心流。",
    myFirstIndependentAppStoreReleaseGrewOrganicallyTo50000DownloadsInThreeMonthsLockScreenWidgetsAn: "它是我第一个上架 App Store 的独立作品，三个月自然增长到 5 万下载。锁屏微件和实时活动让「正在专注」成为一种仪式感。",
    adaptiveFocus: "自适应专注",
    suggestBreaksAroundYourRhythmInsteadOfSlicingTimeIntoRigidBlocks: "不切碎时间，按你的节奏建议休息点",
    liveActivitiesWidgets: "实时活动 + 微件",
    dynamicIslandAndLockScreenShowTheCurrentFocusTideLive: "灵动岛与锁屏实时显示当前潮汐",
    syncEverywhere: "全端同步",
    cloudkitSyncsFocusHistoryWithoutAnAccount: "CloudKit 同步专注记录，零账号",
    focusDashboard: "专注主界面",
    analytics: "数据统计",
    lockScreenWidget: "锁屏微件",
    breathingAnimationInSwiftui: "SwiftUI 呼吸动效",
    aTideRingThatBreathesSlowlyThroughoutAFocusSessionStructTideringViewPrivateVarPhase00VarBodySome: "// 一段随专注时长缓慢呼吸的潮汐圆环\nstruct TideRing: View {\n  @State private var phase = 0.0\n  var body: some View {\n    Circle()\n      .scaleEffect(1 + 0.06 * sin(phase))\n      .animation(.easeInOut(duration: 4).repeatForever(), value: phase)\n      .onAppear { phase = .pi }\n  }\n}",
    download: "下载",
    text210k: "21 万+",
    text49Rating: "4.9 分",
    paidConversion: "付费转化",
    inkbook: "墨册",
    aLocalFirstMarkdownNotebookWhereYourDataAlwaysBelongsToYou: "本地优先的 Markdown 笔记，数据永远是你的。",
    desktopApp: "桌面应用",
    documentation: "文档",
    inkbookIsALocalFirstMarkdownNotebookDataStaysOnYourDevicesSyncsOnlyAfterEncryptionAndRemainsAvai: "墨册是一个本地优先的 Markdown 笔记应用：所有数据存在你自己的设备上，加密后才同步，断网也能用，云端只是备份而非主人。",
    builtOnTauriAndRustItIsOnly8MbAndColdStartsIn03SecondsAutomergeCrdtsMergeEditsAcrossDevicesWitho: "用 Tauri + Rust 打底，包体只有 8MB，冷启动 0.3 秒。Automerge 的 CRDT 让多设备无冲突合并，不需要任何账号。",
    localFirst: "本地优先",
    dataStaysInLocalSqliteAndReachesTheCloudOnlyAfterEndToEndEncryption: "数据存本地 SQLite，端到端加密后才上云",
    conflictFreeSync: "无冲突同步",
    automergeCrdtsMergeEditsAcrossDevicesAutomatically: "Automerge CRDT，多端编辑自动合并",
    exceptionallyLightweight: "极致轻量",
    text8MbTauriPackageWithA300MsColdStart: "Tauri 打包 8MB，冷启动 300ms",
    splitEditor: "双栏编辑",
    notebook: "笔记库",
    syncSettings: "同步设置",
    localEncryptedWritesInRust: "Rust 侧本地加密写入",
    encryptNotesWithTheDeviceKeyBeforeWritingTheCloudSeesOnlyCiphertextPubFnSaveNoteNoteNoteKeyKeyRe: "// 笔记落盘前用设备密钥加密，云端只见密文\npub fn save_note(note: &Note, key: &Key) -> Result<()> {\n    let plain = serde_json::to_vec(note)?;\n    let cipher = encrypt_xchacha20(&plain, key)?;\n    db::upsert(note.id, &cipher)?;\n    sync::enqueue(note.id);\n    Ok(())\n}",
    appSize: "包体",
    coldStart: "冷启动",
    paidUsers: "付费用户",
    orchestrateYourLocalWorkflowWithOneYamlFile: "用一个 YAML 编排你的本地工作流。",
    openSourceCli: "开源 CLI",
    openSource: "开源",
    flowctlIsALocalWorkflowOrchestratorDescribeRepetitiveDevelopmentTasksInYamlThenRunThemConcurrent: "flowctl 是一个本地工作流编排器：把重复的开发任务写成声明式 YAML，一条命令并发跑完，带依赖图、缓存和漂亮的终端进度。",
    thisIsMyMostPopularOpenSourceProjectWithMoreThan10000GithubStarsItsCoreIsADagSchedulerBuiltWithR: "它是我最受欢迎的开源项目，GitHub 破万 star。核心是一个用 Rust + Tokio 写的 DAG 调度器，插件用 WASM 沙箱跑，安全又跨平台。",
    declarativeDag: "声明式 DAG",
    describeTaskDependenciesInYamlWithAutomaticConcurrencyAndCaching: "YAML 描述任务依赖，自动并发与缓存",
    wasmPlugins: "WASM 插件",
    sandboxedPluginsWithZeroCrossPlatformDependencies: "插件在沙箱里跑，跨平台零依赖",
    polishedTty: "漂亮的 TTY",
    liveProgressTreeDurationFlameChartAndFailureReplay: "实时进度树、耗时火焰、失败重放",
    runProgress: "运行进度",
    dependencyGraph: "依赖图",
    configurationExample: "配置示例",
    flowYamlWorkflowDefinition: "flow.yaml 工作流定义",
    declareTasksAndDependenciesFlowctlSchedulesThemConcurrentlyTasksBuildRunCargoBuildReleaseTestNee: "# 声明任务与依赖，flowctl 自动并发调度\ntasks:\n  build:\n    run: cargo build --release\n  test:\n    needs: [build]\n    run: cargo test\n  lint:\n    run: cargo clippy -- -D warnings\n  ship:\n    needs: [test, lint]\n    run: ./scripts/release.sh",
    weeklyDownloads: "周下载",
    contributors: "贡献者",
    pulse: "脉搏",
    yourHealthAtAGlanceOnYourWrist: "手腕上的一眼健康。",
    watchosWidget: "watchOS 微件",
    pulseIsAnAppleWatchHealthWidgetThatBringsHeartRateHrvActivityRingsAndSleepIntoOneComplicationFor: "脉搏是一个 Apple Watch 健康微件：把心率、HRV、活动环、睡眠压缩进一个表盘复杂功能，抬腕一眼就知道身体状态。",
    nowInBetaThisIsMyFirstWatchosProjectTheHardestPartWasFittingFourDimensionsOfDataIntoATinyComplic: "目前在 Beta，这是我第一次做 watchOS。最难的是在表盘那一点点空间里，把四个维度的数据排得既好看又一眼可读。",
    watchComplication: "表盘复杂功能",
    heartRateHrvActivityAndSleepInOneView: "心率 / HRV / 活动 / 睡眠四合一",
    trendColoring: "趋势着色",
    colorAlertsAppearAutomaticallyWhenDataMovesOutsideItsBaseline: "数据偏离基线时自动变色提醒",
    batteryEfficient: "极省电",
    incrementalRefreshThatBarelyAffectsAFullDaySBattery: "增量刷新，全天不掉一格电",
    trendChart: "趋势图",
    settings: "设置",
    widgetkitTimelineRefresh: "WidgetKit 时间线刷新",
    refreshTheWatchComplicationIncrementallyToConserveBatteryStructPulseproviderTimelineproviderFunc: "// 增量刷新表盘复杂功能，省电优先\nstruct PulseProvider: TimelineProvider {\n  func timeline(in ctx: Context) async -> Timeline<Entry> {\n    let hr = await HealthStore.latestHeartRate()\n    let entry = Entry(date: .now, bpm: hr)\n    return Timeline(entries: [entry], policy: .after(.now + 600))\n  }\n}",
    betaUsers: "Beta 用户",
    refreshInterval: "刷新间隔",
    batteryUse: "耗电",
    text2Day: "< 2%/天",
    whitespace: "留白",
    turnAnyWebPageIntoACleanReadingExperience: "把任何网页，还原成干净的阅读。",
    browserExtension: "浏览器扩展",
    chromeWebStore: "Chrome 商店",
    whitespaceIsABrowserExtensionThatTurnsPagesCrowdedWithPopUpsAdsAndSidebarsIntoCalmReadingViewsAd: "留白是一个浏览器扩展：一键把塞满弹窗、广告和侧栏的网页，还原成只剩正文的安静阅读页，可调字号、字体与栏宽，像在读一本排好版的书。",
    itGrewFromAPersonalObsessionGoodWritingIsOftenRuinedByBadLayoutsWhitespaceExtractsTheArticleWith: "它来自我自己的洁癖——好文章常被糟糕的版式毁掉。留白用 Readability 提取正文，本地存一份「稍后读」，断网也能翻，全程不碰你的任何数据。",
    oneClickReadingMode: "一键阅读模式",
    extractTheArticleRemoveDistractionsAndCustomizeFontAndColumnWidth: "提取正文，去广告与干扰，自定义字体与栏宽",
    localReadLater: "本地稍后读",
    articlesAreStoredInIndexeddbForOfflineAccountFreeReading: "正文存进 IndexedDB，离线可读，零账号",
    keyboardOnly: "全键盘操作",
    pressRToReadAndJKToMoveBetweenSectionsEntirelyFromTheKeyboard: "⌥R 进入阅读，j / k 翻段，全程不用鼠标",
    readingMode: "阅读模式",
    readLaterList: "稍后读列表",
    appearance: "外观设置",
    extractArticlesWithReadability: "用 Readability 提取正文",
    contentScriptExtractCleanArticleHtmlAndStoreItLocallyImportReadabilityFromExportFunctionExtracta: "// content script：把当前页正文抽成干净 HTML 存本地\nimport { Readability } from \"@mozilla/readability\";\n\nexport function extractArticle() {\n  const doc = document.cloneNode(true) as Document;\n  const article = new Readability(doc).parse();\n  if (article) saveForLater(article); // 落 IndexedDB，离线可读\n  return article;\n}",
    installs: "安装量",
    text58k: "5.8 万+",
    storeRating: "商店评分",
    text48Rating: "4.8 分",
    cleanedArticles: "已净化文章",
    text32m: "320 万+",
  },
  en: {
    codeframe: "CodeFrame",
    turnCodeScreenshotsIntoArtworkWorthSharing: "Turn code screenshots into artwork worth sharing.",
    online: "Online",
    unavailable: "Unavailable",
    beta: "Beta",
    tryOnline: "Try online",
    source: "Source",
    codeframeIsABrowserBasedCodeImageToolPasteCodeChooseAThemeAndExportAHighResolutionImageWithWindo: "CodeFrame is a browser-based code image tool: paste code, choose a theme, and export a high-resolution image with window chrome, syntax highlighting, and soft shadows.",
    itBeganWithMyOwnFrustrationWhenSharingTechnicalPostsSystemScreenshotsLookedPoorAndCarbonFeltSlow: "It began with my own frustration when sharing technical posts: system screenshots looked poor and Carbon felt slow. CodeFrame is paste-and-go, with Satori rendering a 2x image at the edge in three seconds.",
    text30ColorThemes: "30+ color themes",
    customizeEverythingIncludingBrandColorsAndWindowStyles: "Customize everything, including brand colors and window styles",
    edgeRenderedExports: "Edge-rendered exports",
    cloudflareWorkersSatoriHighResolution2x4xPngAndSvg: "Cloudflare Workers + Satori, high-resolution 2x/4x PNG and SVG",
    keyboardFirst: "Keyboard first",
    vToPasteEToExportNoMouseRequired: "⌘V to paste → ⌘E to export, no mouse required",
    editorWorkspace: "Editor workspace",
    themePicker: "Theme picker",
    exportPreview: "Export preview",
    edgeRenderedExports2: "Edge-rendered exports",
    renderCodeAsAnImageWithSatoriOnCloudflareWorkersImportSatoriFromSatoriExportAsyncFunctionRenderc: "// Render code as an image with Satori on Cloudflare Workers\nimport satori from \"satori\";\n\nexport async function renderCode(code: string, theme: Theme) {\n  const svg = await satori(\n    <CodeCard code={code} theme={theme} />,\n    { width: 1200, fonts: await loadFonts() },\n  );\n  return new Response(svg, {\n    headers: { \"content-type\": \"image/svg+xml\" },\n  });\n}",
    monthlyActiveUsers: "Monthly active users",
    exportImage: "Export image",
    text19m: "1.9M+",
    themes: "Themes",
    tide: "Tide",
    letFocusRiseAndFallLikeTheTide: "Let focus rise and fall like the tide.",
    productPage: "Product page",
    tideIsAnAntiPomodoroFocusAppInsteadOfForcingWorkInto25MinuteBlocksItFollowsYourRhythmWithABreath: "Tide is an anti-Pomodoro focus app. Instead of forcing work into 25-minute blocks, it follows your rhythm with a breathing tide animation that eases you into flow.",
    myFirstIndependentAppStoreReleaseGrewOrganicallyTo50000DownloadsInThreeMonthsLockScreenWidgetsAn: "My first independent App Store release grew organically to 50,000 downloads in three months. Lock-screen widgets and Live Activities turn focusing into a small ritual.",
    adaptiveFocus: "Adaptive focus",
    suggestBreaksAroundYourRhythmInsteadOfSlicingTimeIntoRigidBlocks: "Suggest breaks around your rhythm instead of slicing time into rigid blocks",
    liveActivitiesWidgets: "Live Activities + widgets",
    dynamicIslandAndLockScreenShowTheCurrentFocusTideLive: "Dynamic Island and lock screen show the current focus tide live",
    syncEverywhere: "Sync everywhere",
    cloudkitSyncsFocusHistoryWithoutAnAccount: "CloudKit syncs focus history without an account",
    focusDashboard: "Focus dashboard",
    analytics: "Analytics",
    lockScreenWidget: "Lock-screen widget",
    breathingAnimationInSwiftui: "Breathing animation in SwiftUI",
    aTideRingThatBreathesSlowlyThroughoutAFocusSessionStructTideringViewPrivateVarPhase00VarBodySome: "// A tide ring that breathes slowly throughout a focus session\nstruct TideRing: View {\n  @State private var phase = 0.0\n  var body: some View {\n    Circle()\n      .scaleEffect(1 + 0.06 * sin(phase))\n      .animation(.easeInOut(duration: 4).repeatForever(), value: phase)\n      .onAppear { phase = .pi }\n  }\n}",
    download: "Download",
    text210k: "210K+",
    text49Rating: "4.9 rating",
    paidConversion: "Paid conversion",
    inkbook: "Inkbook",
    aLocalFirstMarkdownNotebookWhereYourDataAlwaysBelongsToYou: "A local-first Markdown notebook where your data always belongs to you.",
    desktopApp: "Desktop app",
    documentation: "Documentation",
    inkbookIsALocalFirstMarkdownNotebookDataStaysOnYourDevicesSyncsOnlyAfterEncryptionAndRemainsAvai: "Inkbook is a local-first Markdown notebook. Data stays on your devices, syncs only after encryption, and remains available offline; the cloud is a backup, not the owner.",
    builtOnTauriAndRustItIsOnly8MbAndColdStartsIn03SecondsAutomergeCrdtsMergeEditsAcrossDevicesWitho: "Built on Tauri and Rust, it is only 8 MB and cold-starts in 0.3 seconds. Automerge CRDTs merge edits across devices without conflicts or accounts.",
    localFirst: "Local first",
    dataStaysInLocalSqliteAndReachesTheCloudOnlyAfterEndToEndEncryption: "Data stays in local SQLite and reaches the cloud only after end-to-end encryption",
    conflictFreeSync: "Conflict-free sync",
    automergeCrdtsMergeEditsAcrossDevicesAutomatically: "Automerge CRDTs merge edits across devices automatically",
    exceptionallyLightweight: "Exceptionally lightweight",
    text8MbTauriPackageWithA300MsColdStart: "8 MB Tauri package with a 300 ms cold start",
    splitEditor: "Split editor",
    notebook: "Notebook",
    syncSettings: "Sync settings",
    localEncryptedWritesInRust: "Local encrypted writes in Rust",
    encryptNotesWithTheDeviceKeyBeforeWritingTheCloudSeesOnlyCiphertextPubFnSaveNoteNoteNoteKeyKeyRe: "// Encrypt notes with the device key before writing; the cloud sees only ciphertext\npub fn save_note(note: &Note, key: &Key) -> Result<()> {\n    let plain = serde_json::to_vec(note)?;\n    let cipher = encrypt_xchacha20(&plain, key)?;\n    db::upsert(note.id, &cipher)?;\n    sync::enqueue(note.id);\n    Ok(())\n}",
    appSize: "App size",
    coldStart: "Cold start",
    paidUsers: "Paid users",
    orchestrateYourLocalWorkflowWithOneYamlFile: "Orchestrate your local workflow with one YAML file.",
    openSourceCli: "Open-source CLI",
    openSource: "Open source",
    flowctlIsALocalWorkflowOrchestratorDescribeRepetitiveDevelopmentTasksInYamlThenRunThemConcurrent: "flowctl is a local workflow orchestrator. Describe repetitive development tasks in YAML, then run them concurrently with one command, complete with dependency graphs, caching, and polished terminal progress.",
    thisIsMyMostPopularOpenSourceProjectWithMoreThan10000GithubStarsItsCoreIsADagSchedulerBuiltWithR: "This is my most popular open-source project, with more than 10,000 GitHub stars. Its core is a DAG scheduler built with Rust and Tokio, while plugins run safely across platforms in a WASM sandbox.",
    declarativeDag: "Declarative DAG",
    describeTaskDependenciesInYamlWithAutomaticConcurrencyAndCaching: "Describe task dependencies in YAML with automatic concurrency and caching",
    wasmPlugins: "WASM plugins",
    sandboxedPluginsWithZeroCrossPlatformDependencies: "Sandboxed plugins with zero cross-platform dependencies",
    polishedTty: "Polished TTY",
    liveProgressTreeDurationFlameChartAndFailureReplay: "Live progress tree, duration flame chart, and failure replay",
    runProgress: "Run progress",
    dependencyGraph: "Dependency graph",
    configurationExample: "Configuration example",
    flowYamlWorkflowDefinition: "flow.yaml workflow definition",
    declareTasksAndDependenciesFlowctlSchedulesThemConcurrentlyTasksBuildRunCargoBuildReleaseTestNee: "# Declare tasks and dependencies; flowctl schedules them concurrently\ntasks:\n  build:\n    run: cargo build --release\n  test:\n    needs: [build]\n    run: cargo test\n  lint:\n    run: cargo clippy -- -D warnings\n  ship:\n    needs: [test, lint]\n    run: ./scripts/release.sh",
    weeklyDownloads: "Weekly downloads",
    contributors: "Contributors",
    pulse: "Pulse",
    yourHealthAtAGlanceOnYourWrist: "Your health at a glance on your wrist.",
    watchosWidget: "watchOS widget",
    pulseIsAnAppleWatchHealthWidgetThatBringsHeartRateHrvActivityRingsAndSleepIntoOneComplicationFor: "Pulse is an Apple Watch health widget that brings heart rate, HRV, activity rings, and sleep into one complication for an instant view of your wellbeing.",
    nowInBetaThisIsMyFirstWatchosProjectTheHardestPartWasFittingFourDimensionsOfDataIntoATinyComplic: "Now in beta, this is my first watchOS project. The hardest part was fitting four dimensions of data into a tiny complication while keeping it attractive and instantly readable.",
    watchComplication: "Watch complication",
    heartRateHrvActivityAndSleepInOneView: "Heart rate, HRV, activity, and sleep in one view",
    trendColoring: "Trend coloring",
    colorAlertsAppearAutomaticallyWhenDataMovesOutsideItsBaseline: "Color alerts appear automatically when data moves outside its baseline",
    batteryEfficient: "Battery efficient",
    incrementalRefreshThatBarelyAffectsAFullDaySBattery: "Incremental refresh that barely affects a full day's battery",
    trendChart: "Trend chart",
    settings: "Settings",
    widgetkitTimelineRefresh: "WidgetKit timeline refresh",
    refreshTheWatchComplicationIncrementallyToConserveBatteryStructPulseproviderTimelineproviderFunc: "// Refresh the watch complication incrementally to conserve battery\nstruct PulseProvider: TimelineProvider {\n  func timeline(in ctx: Context) async -> Timeline<Entry> {\n    let hr = await HealthStore.latestHeartRate()\n    let entry = Entry(date: .now, bpm: hr)\n    return Timeline(entries: [entry], policy: .after(.now + 600))\n  }\n}",
    betaUsers: "Beta users",
    refreshInterval: "Refresh interval",
    batteryUse: "Battery use",
    text2Day: "< 2%/day",
    whitespace: "Whitespace",
    turnAnyWebPageIntoACleanReadingExperience: "Turn any web page into a clean reading experience.",
    browserExtension: "Browser extension",
    chromeWebStore: "Chrome Web Store",
    whitespaceIsABrowserExtensionThatTurnsPagesCrowdedWithPopUpsAdsAndSidebarsIntoCalmReadingViewsAd: "Whitespace is a browser extension that turns pages crowded with pop-ups, ads, and sidebars into calm reading views. Adjust the type size, font, and column width until the page feels like a well-designed book.",
    itGrewFromAPersonalObsessionGoodWritingIsOftenRuinedByBadLayoutsWhitespaceExtractsTheArticleWith: "It grew from a personal obsession: good writing is often ruined by bad layouts. Whitespace extracts the article with Readability and stores a local read-later copy, available offline without sending your data anywhere.",
    oneClickReadingMode: "One-click reading mode",
    extractTheArticleRemoveDistractionsAndCustomizeFontAndColumnWidth: "Extract the article, remove distractions, and customize font and column width",
    localReadLater: "Local read later",
    articlesAreStoredInIndexeddbForOfflineAccountFreeReading: "Articles are stored in IndexedDB for offline, account-free reading",
    keyboardOnly: "Keyboard only",
    pressRToReadAndJKToMoveBetweenSectionsEntirelyFromTheKeyboard: "Press ⌥R to read and j/k to move between sections, entirely from the keyboard",
    readingMode: "Reading mode",
    readLaterList: "Read-later list",
    appearance: "Appearance",
    extractArticlesWithReadability: "Extract articles with Readability",
    contentScriptExtractCleanArticleHtmlAndStoreItLocallyImportReadabilityFromExportFunctionExtracta: "// Content script: extract clean article HTML and store it locally\nimport { Readability } from \"@mozilla/readability\";\n\nexport function extractArticle() {\n  const doc = document.cloneNode(true) as Document;\n  const article = new Readability(doc).parse();\n  if (article) saveForLater(article); // Store in IndexedDB for offline reading\n  return article;\n}",
    installs: "Installs",
    text58k: "58K+",
    storeRating: "Store rating",
    text48Rating: "4.8 rating",
    cleanedArticles: "Cleaned articles",
    text32m: "3.2M+",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>(
    (text, value, index) => text.replaceAll(`{${index}}`, String(value)),
    content[DOCS_LOCALE][key],
  );
}

const dictionary: Dictionary = {
  key: "demo-personal-data-works",
  content: t(content),
};

export default dictionary;
