import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "yunqiDataCenterMechanicalAndElectricalInstallation": "云栖数据中心机电安装工程",
    "yunqiTechnologyCoLtd": "云栖科技股份有限公司",
    "hongjiElectromechanicalTeam": "鸿基机电班组",
    "chenGong": "陈工",
    "noYunqiTownYuhangDistrictHangzhouCity": "杭州市余杭区云栖小镇 18 号",
    "zhejiangHangzhou": "浙江·杭州",
    "electromechanical": "机电",
    "keyProjects": "重点工程",
    "ruikangPharmaceuticalGmpCleanWorkshopDecorationProject": "瑞康制药 GMP 洁净车间装饰工程",
    "ruikangPharmaceuticalCoLtd": "瑞康制药有限公司",
    "goldenDomeDecorationTeam": "金顶装饰队",
    "zhouLei": "周磊",
    "suzhouIndustrialParkBiomedicalIndustrialParkC3": "苏州市工业园区生物医药产业园 C3",
    "jiangsuSuzhou": "江苏·苏州",
    "decoration": "装饰",
    "clean": "洁净",
    "auroraNewEnergyChargingStationElectricalInstallation": "极光新能源充电站电气安装",
    "auroraNewEnergyTechnologyCompany": "极光新能源科技公司",
    "hengtongInstallationTeam": "恒通安装队",
    "highSensitivity": "高敏",
    "ningboYinzhouDistrictSmartIndustrialPark": "宁波市鄞州区智慧产业园",
    "zhejiangNingbo": "浙江·宁波",
    "electrical": "电气",
    "newEnergy": "新能源",
    "chenguangCommercialComplexHeatingAndVentilationProject": "晨光商业综合体暖通工程",
    "chenguangRealEstateGroup": "晨光置业集团",
    "yuandaHvacTeam": "远大暖通队",
    "suJianguo": "苏建国",
    "noJiangdongMiddleRoadJianyeDistrictNanjing": "南京市建邺区江东中路 200 号",
    "jiangsuNanjing": "江苏·南京",
    "hvac": "暖通",
    "large": "大型",
    "zhixingEducationExperimentalBuildingWeakCurrentIntelligentizatio": "知行教育实验楼弱电智能化",
    "zhixingEducationTechnologyCompany": "知行教育科技公司",
    "hengtongInstallationTeam2": "恒通安装队",
    "liTao": "李韬",
    "noInnovationAvenueHighTechZoneHefei": "合肥市高新区创新大道 99 号",
    "anhuiHefei": "安徽·合肥",
    "weakCurrent": "弱电",
    "intelligent": "智能化",
    "greenfieldAgriculturalColdChainStorageAndRefrigeration": "绿野农业冷链仓储制冷工程",
    "greenfieldAgriculturalDevelopmentCorp": "绿野农业发展公司",
    "yuandaHvacTeam2": "远大暖通队",
    "chenGong2": "陈工",
    "weifangShouguangVegetableLogisticsPark": "潍坊市寿光蔬菜物流园",
    "shandongWeifang": "山东·潍坊",
    "refrigeration": "制冷",
    "coldChain": "冷链",
    "heyuHotelCentralAirConditioningRenovation": "和裕酒店中央空调改造",
    "heyuHotelManagementCompany": "和裕酒店管理公司",
    "yuandaHvacTeam3": "远大暖通队",
    "zhouLei2": "周磊",
    "noNanjingEastRoadHuangpuDistrictShanghai": "上海市黄浦区南京东路 358 号",
    "shanghai": "上海",
    "airConditioning": "空调",
    "transformation": "改造",
    "xinghaiSquareLandscapeLightingProject": "星海广场景观照明工程",
    "xinghaiCulturalTourismInvestmentCompany": "星海文旅投资公司",
    "jianfaCivilEngineeringTeam": "建发土建队",
    "highSensitivity2": "高敏",
    "xinghaiPlazaShahekouDistrictDalianCity": "大连市沙河口区星海广场",
    "liaoningDalian": "辽宁·大连",
    "lighting": "照明",
    "landscape": "景观",
    "siteSurvey": "现场勘测",
    "quotationConfirmation": "报价确认",
    "enteringTheMarketToExplain": "进场交底",
    "mainConstruction": "主体施工",
    "completionAcceptance": "竣工验收",
    "settlementAndInvoicing": "结算开票",
    "siteSurvey2": "现场勘测",
    "earlyStage": "前期",
    "deepenDesignAndQuotation": "深化设计与报价",
    "earlyStage2": "前期",
    "bridgeAndPipelineLaying": "桥架与管线敷设",
    "construction4": "施工",
    "equipmentInstalledInPlace": "设备就位安装",
    "construction5": "施工",
    "systemDebugging": "系统调试",
    "construction6": "施工",
    "completionAcceptanceAndSettlement": "竣工验收与结算",
    "finishing": "收尾",
    "eventPhotoUpload": "上传 3 张冷冻机房管道安装照片",
    "eventTrayInstalled": "桥架敷设完成，进入设备就位阶段",
    "eventSecondPayment": "收到第二期进度款 ¥858,000",
    "eventInvoiceIssued": "开具增值税专用发票 INV-2026-002",
    "eventQuoteAccepted": "报价单 QT-2026-001 经甲方确认",
    "eventCleanlinessPassed": "洁净度检测通过，准备竣工验收",
    "eventVentPhotos": "上传 5 张吊顶高效送风口验收照片",
    "eventGroundingIssue": "现场记录配电箱接地隐患待整改",
    "eventSiteBriefing": "完成进场交底，材料分批进场",
    "finance": "财务",
  },
  en: {
    "yunqiDataCenterMechanicalAndElectricalInstallation": "Yunqi Data Center Mechanical and Electrical Installation Project",
    "yunqiTechnologyCoLtd": "Yunqi Technology Co., Ltd.",
    "hongjiElectromechanicalTeam": "Hongji electromechanical team",
    "chenGong": "Chen Gong",
    "noYunqiTownYuhangDistrictHangzhouCity": "No. 18, Yunqi Town, Yuhang District, Hangzhou City",
    "zhejiangHangzhou": "Zhejiang · Hangzhou",
    "electromechanical": "Electromechanical",
    "keyProjects": "Key projects",
    "ruikangPharmaceuticalGmpCleanWorkshopDecorationProject": "Ruikang Pharmaceutical GMP clean workshop decoration project",
    "ruikangPharmaceuticalCoLtd": "Ruikang Pharmaceutical Co., Ltd.",
    "goldenDomeDecorationTeam": "Golden Dome Decoration Team",
    "zhouLei": "Zhou Lei",
    "suzhouIndustrialParkBiomedicalIndustrialParkC3": "Suzhou Industrial Park Biomedical Industrial Park C3",
    "jiangsuSuzhou": "Jiangsu · Suzhou",
    "decoration": "decoration",
    "clean": "clean",
    "auroraNewEnergyChargingStationElectricalInstallation": "Aurora New Energy Charging Station Electrical Installation",
    "auroraNewEnergyTechnologyCompany": "Aurora New Energy Technology Company",
    "hengtongInstallationTeam": "Hengtong installation team",
    "highSensitivity": "Gao Min",
    "ningboYinzhouDistrictSmartIndustrialPark": "Ningbo Yinzhou District Smart Industrial Park",
    "zhejiangNingbo": "Zhejiang · Ningbo",
    "electrical": "Electrical",
    "newEnergy": "new energy",
    "chenguangCommercialComplexHeatingAndVentilationProject": "Chenguang commercial complex heating and ventilation project",
    "chenguangRealEstateGroup": "Chenguang Real Estate Group",
    "yuandaHvacTeam": "Yuanda HVAC team",
    "suJianguo": "Su Jianguo",
    "noJiangdongMiddleRoadJianyeDistrictNanjing": "No. 200, Jiangdong Middle Road, Jianye District, Nanjing",
    "jiangsuNanjing": "Jiangsu · Nanjing",
    "hvac": "HVAC",
    "large": "Large",
    "zhixingEducationExperimentalBuildingWeakCurrentIntelligentizatio": "Zhixing Education Experimental Building Weak Current Intelligentization",
    "zhixingEducationTechnologyCompany": "Zhixing Education Technology Company",
    "hengtongInstallationTeam2": "Hengtong installation team",
    "liTao": "Li Tao",
    "noInnovationAvenueHighTechZoneHefei": "No. 99, Innovation Avenue, High-tech Zone, Hefei City",
    "anhuiHefei": "Anhui · Hefei",
    "weakCurrent": "Weak current",
    "intelligent": "Intelligent",
    "greenfieldAgriculturalColdChainStorageAndRefrigeration": "Greenfield agricultural cold chain storage and refrigeration project",
    "greenfieldAgriculturalDevelopmentCorp": "greenfield agricultural development corp.",
    "yuandaHvacTeam2": "Yuanda HVAC team",
    "chenGong2": "Chen Gong",
    "weifangShouguangVegetableLogisticsPark": "Weifang Shouguang Vegetable Logistics Park",
    "shandongWeifang": "Shandong · Weifang",
    "refrigeration": "Refrigeration",
    "coldChain": "cold chain",
    "heyuHotelCentralAirConditioningRenovation": "Heyu Hotel Central Air Conditioning Renovation",
    "heyuHotelManagementCompany": "Heyu Hotel Management Company",
    "yuandaHvacTeam3": "Yuanda HVAC team",
    "zhouLei2": "Zhou Lei",
    "noNanjingEastRoadHuangpuDistrictShanghai": "No. 358, Nanjing East Road, Huangpu District, Shanghai",
    "shanghai": "Shanghai",
    "airConditioning": "Air conditioning",
    "transformation": "Transformation",
    "xinghaiSquareLandscapeLightingProject": "Xinghai Square Landscape Lighting Project",
    "xinghaiCulturalTourismInvestmentCompany": "Xinghai Cultural Tourism Investment Company",
    "jianfaCivilEngineeringTeam": "Jianfa Civil Engineering Team",
    "highSensitivity2": "Gao Min",
    "xinghaiPlazaShahekouDistrictDalianCity": "Xinghai Plaza, Shahekou District, Dalian City",
    "liaoningDalian": "Liaoning · Dalian",
    "lighting": "lighting",
    "landscape": "landscape",
    "siteSurvey": "Site survey",
    "quotationConfirmation": "Quote confirmation",
    "enteringTheMarketToExplain": "Entering the market to explain",
    "mainConstruction": "Main construction",
    "completionAcceptance": "Completion acceptance",
    "settlementAndInvoicing": "Settlement and invoicing",
    "siteSurvey2": "Site survey",
    "earlyStage": "Early stage",
    "deepenDesignAndQuotation": "Deepen design and quote",
    "earlyStage2": "Early stage",
    "bridgeAndPipelineLaying": "Bridge and pipeline laying",
    "construction4": "construction",
    "equipmentInstalledInPlace": "Equipment installed in place",
    "construction5": "construction",
    "systemDebugging": "System debugging",
    "construction6": "construction",
    "completionAcceptanceAndSettlement": "Completion acceptance and settlement",
    "finishing": "Finishing",
    "eventPhotoUpload": "Uploaded 3 photos of the chiller-room piping installation",
    "eventTrayInstalled": "Cable tray installation completed; equipment placement is next",
    "eventSecondPayment": "Received the second progress payment of ¥858,000",
    "eventInvoiceIssued": "Issued VAT special invoice INV-2026-002",
    "eventQuoteAccepted": "Client accepted quote QT-2026-001",
    "eventCleanlinessPassed": "Cleanliness test passed; preparing for final acceptance",
    "eventVentPhotos": "Uploaded 5 acceptance photos of the ceiling supply-air outlets",
    "eventGroundingIssue": "Recorded a grounding issue in the distribution box for remediation",
    "eventSiteBriefing": "Completed the site briefing; materials will arrive in batches",
    "finance": "Finance",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-projects-data-projects",
  content: t(content),
};

export default dictionary;
