import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "yunqiDataCenterMechanicalAndElectricalInstallation": "云栖数据中心机电安装工程",
    "yunqiTechnologyCoLtd": "云栖科技股份有限公司",
    "chenGong": "陈工",
    "includesMainMaterialsAuxiliaryMaterialsAndInstallation": "含主材、辅材及安装人工；不含甲供设备搬运。质保期 24 个月。",
    "galvanizedBridgeAndAccessories": "镀锌桥架及配件",
    "hotDipGalvanized": "200×100 热镀锌",
    "meters": "米",
    "cableLayingYjv": "电缆敷设 YJV",
    "meters2": "米",
    "refrigerationUnitInstallation": "冷冻机组安装",
    "centrifugalRt": "离心式 800RT",
    "taiwan": "台",
    "installationAndDebuggingOfPowerDistributionCabinet": "配电柜安装调试",
    "gckLowVoltageCabinet": "GCK 低压柜",
    "noodles": "面",
    "pipeInsulation": "管道保温",
    "rubberAndPlasticGradeB1": "橡塑 B1 级",
    "squareMeters": "平方米",
    "chenguangCommercialComplexHeatingAndVentilationProject": "晨光商业综合体暖通工程",
    "chenguangRealEstateGroup": "晨光置业集团",
    "suJianguo": "苏建国",
    "constructionWillBeCarriedOutInTwo": "分两期进场施工，价格含设备吊装。",
    "multiLineOutdoorUnit": "多联机室外机",
    "taiwan2": "台",
    "airDuctProductionAndInstallation": "风管制作安装",
    "galvanized": "镀锌 δ1.0",
    "squareMeters2": "平方米",
    "fanCoilUnit": "风机盘管",
    "taiwan3": "台",
    "refrigerantCopperPipe": "冷媒铜管",
    "meters3": "米",
    "zhixingEducationExperimentalBuildingWeakCurrentIntelligentizatio": "知行教育实验楼弱电智能化",
    "zhixingEducationTechnologyCompany": "知行教育科技公司",
    "liTao": "李韬",
    "generalContractingOfWeakCurrentIntelligentSystems": "弱电智能化系统总承包，含三年免费维护。",
    "integratedWiring": "综合布线",
    "categoryUnshielded": "六类非屏蔽",
    "point": "点",
    "networkSwitch": "网络交换机",
    "gConvergence": "万兆汇聚",
    "taiwan4": "台",
    "videoSurveillance": "视频监控",
    "millionHemispheres": "400 万半球",
    "road": "路",
    "allInOneAccessControlMachine": "门禁一体机",
    "faceRecognition": "人脸识别",
    "taiwan5": "台",
    "xinghaiSquareLandscapeLightingProject": "星海广场景观照明工程",
    "xinghaiCulturalTourismInvestmentCompany": "星海文旅投资公司",
    "highSensitivity": "高敏",
    "thePlanWillBeAdjustedAfterParty": "方案待甲方确认灯具品牌后调整。",
    "ledFloodLight": "LED 投光灯",
    "wFullColor": "200W 全彩",
    "set": "套",
    "lineLight": "线条灯",
    "dmx512Controllable": "DMX512 可控",
    "meters4": "米",
    "lightingControlSystem": "灯光控制系统",
    "centralController": "中央控制器",
    "set2": "套",
    "auroraNewEnergyChargingStationElectricalInstallation": "极光新能源充电站电气安装",
    "auroraNewEnergyTechnologyCompany": "极光新能源科技公司",
    "highSensitivity2": "高敏",
    "chargingPilePowerDistributionAndLightningProtection": "充电桩配电及防雷接地工程。",
    "dcChargingPileInstallation": "直流充电桩安装",
    "kwDoubleGun": "120kW 双枪",
    "taiwan6": "台",
    "boxTypeSubstation": "箱式变电站",
    "seat": "座",
    "cableLaying": "电缆敷设",
    "meters5": "米",
    "ruikangPharmaceuticalGmpCleanWorkshopDecorationProject": "瑞康制药 GMP 洁净车间装饰工程",
    "ruikangPharmaceuticalCoLtd": "瑞康制药有限公司",
    "zhouLei": "周磊",
    "theFirstEditionQuotationIsSubjectTo": "首版报价，后经变更签证以 v2 为准。",
    "colorSteelPlatePartitionWall": "彩钢板隔墙",
    "mmRockWool": "50mm 岩棉",
    "squareMeters3": "平方米",
    "efficientAirOutlet": "高效送风口",
    "a": "个",
  },
  en: {
    "yunqiDataCenterMechanicalAndElectricalInstallation": "Yunqi Data Center Mechanical and Electrical Installation Project",
    "yunqiTechnologyCoLtd": "Yunqi Technology Co., Ltd.",
    "chenGong": "Chen Gong",
    "includesMainMaterialsAuxiliaryMaterialsAndInstallation": "Includes main materials, auxiliary materials and installation labor; does not include equipment handling. Warranty period 24 months.",
    "galvanizedBridgeAndAccessories": "Galvanized bridge and accessories",
    "hotDipGalvanized": "200×100 hot dip galvanized",
    "meters": "meters",
    "cableLayingYjv": "Cable laying YJV",
    "meters2": "meters",
    "refrigerationUnitInstallation": "Refrigeration unit installation",
    "centrifugalRt": "Centrifugal 800RT",
    "taiwan": "Taiwan",
    "installationAndDebuggingOfPowerDistributionCabinet": "Installation and debugging of power distribution cabinet",
    "gckLowVoltageCabinet": "GCK low voltage cabinet",
    "noodles": "noodles",
    "pipeInsulation": "Pipe insulation",
    "rubberAndPlasticGradeB1": "Rubber and plastic grade B1",
    "squareMeters": "square meters",
    "chenguangCommercialComplexHeatingAndVentilationProject": "Chenguang commercial complex heating and ventilation project",
    "chenguangRealEstateGroup": "Chenguang Real Estate Group",
    "suJianguo": "Su Jianguo",
    "constructionWillBeCarriedOutInTwo": "Construction will be carried out in two phases, and the price includes equipment hoisting.",
    "multiLineOutdoorUnit": "Multi-line outdoor unit",
    "taiwan2": "Taiwan",
    "airDuctProductionAndInstallation": "Air duct production and installation",
    "galvanized": "Galvanized δ1.0",
    "squareMeters2": "square meters",
    "fanCoilUnit": "fan coil unit",
    "taiwan3": "Taiwan",
    "refrigerantCopperPipe": "Refrigerant copper pipe",
    "meters3": "meters",
    "zhixingEducationExperimentalBuildingWeakCurrentIntelligentizatio": "Zhixing Education Experimental Building Weak Current Intelligentization",
    "zhixingEducationTechnologyCompany": "Zhixing Education Technology Company",
    "liTao": "Li Tao",
    "generalContractingOfWeakCurrentIntelligentSystems": "General contracting of weak current intelligent systems, including three years of free maintenance.",
    "integratedWiring": "Integrated wiring",
    "categoryUnshielded": "Category 6 unshielded",
    "point": "point",
    "networkSwitch": "network switch",
    "gConvergence": "10G convergence",
    "taiwan4": "Taiwan",
    "videoSurveillance": "video surveillance",
    "millionHemispheres": "4 million hemispheres",
    "road": "road",
    "allInOneAccessControlMachine": "All-in-one access control machine",
    "faceRecognition": "face recognition",
    "taiwan5": "Taiwan",
    "xinghaiSquareLandscapeLightingProject": "Xinghai Square Landscape Lighting Project",
    "xinghaiCulturalTourismInvestmentCompany": "Xinghai Cultural Tourism Investment Company",
    "highSensitivity": "Gao Min",
    "thePlanWillBeAdjustedAfterParty": "The plan will be adjusted after Client confirms the brand of lighting fixtures.",
    "ledFloodLight": "LED flood light",
    "wFullColor": "200W full color",
    "set": "set",
    "lineLight": "Line light",
    "dmx512Controllable": "DMX512 controllable",
    "meters4": "meters",
    "lightingControlSystem": "Lighting control system",
    "centralController": "central controller",
    "set2": "set",
    "auroraNewEnergyChargingStationElectricalInstallation": "Aurora New Energy Charging Station Electrical Installation",
    "auroraNewEnergyTechnologyCompany": "Aurora New Energy Technology Company",
    "highSensitivity2": "Gao Min",
    "chargingPilePowerDistributionAndLightningProtection": "Charging pile power distribution and lightning protection grounding project.",
    "dcChargingPileInstallation": "DC charging pile installation",
    "kwDoubleGun": "120kW double gun",
    "taiwan6": "Taiwan",
    "boxTypeSubstation": "Box type substation",
    "seat": "seat",
    "cableLaying": "Cable laying",
    "meters5": "meters",
    "ruikangPharmaceuticalGmpCleanWorkshopDecorationProject": "Ruikang Pharmaceutical GMP clean workshop decoration project",
    "ruikangPharmaceuticalCoLtd": "Ruikang Pharmaceutical Co., Ltd.",
    "zhouLei": "Zhou Lei",
    "theFirstEditionQuotationIsSubjectTo": "The first edition quote is subject to v2 if the visa is changed later.",
    "colorSteelPlatePartitionWall": "Color steel plate partition wall",
    "mmRockWool": "50mm rock wool",
    "squareMeters3": "square meters",
    "efficientAirOutlet": "Efficient air outlet",
    "a": "a",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-projects-data-quotes",
  content: t(content),
};

export default dictionary;
