import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "valueMillion": "{0} 万",
    "zeroOneTwoThreeFourFiveSix": "零壹贰叁肆伍陆柒捌玖",
    "pickUp": "拾",
    "hundred": "佰",
    "thousand": "仟",
    "million": "万",
    "billion": "亿",
    "zeroYuan": "零元整",
    "zero": "零",
    "negative": "负",
    "yuan": "元",
    "whole": "整",
    "angle": "角",
    "zero4": "零",
    "points": "分",
    "stageSurvey": "勘测",
    "stageQuote": "报价",
    "stageMobilization": "进场",
    "stageConstruction": "施工",
    "stageAcceptance": "验收",
    "stageSettlement": "结算",
    "statusNotStarted": "待开工",
    "statusInProgress": "进行中",
    "statusPaused": "已暂停",
    "statusCompleted": "已完工",
    "statusSettled": "已结算",
    "quoteDraft": "草稿",
    "quoteSent": "已发送",
    "quoteAccepted": "已确认",
    "quoteExpired": "已失效",
    "invoicePending": "待开",
    "invoiceIssued": "已开",
    "invoiceMailed": "已寄送",
    "paymentUnpaid": "未回款",
    "paymentPartial": "部分回款",
    "paymentPaid": "已结清",
    "checkoutAwaiting": "待支付",
    "checkoutProcessing": "支付中",
    "checkoutPaid": "已支付",
    "checkoutClosed": "已关闭",
    "photoProgress": "进度",
    "photoIssue": "隐患",
    "photoAcceptance": "验收",
    "photoMaterials": "材料",
    "invoiceVatSpecial": "增值税专用发票",
    "invoiceVatStandard": "增值税普通发票",
    "invoiceVatSpecialShort": "增专",
    "invoiceVatStandardShort": "增普",
    "payWechat": "微信支付",
    "payAlipay": "支付宝",
    "payCorporateBanking": "对公网银",
    "payCard": "银行卡",
    "payBankTransfer": "银行转账",
    "payAcceptanceBill": "承兑汇票",
    "payCash": "现金",
    "eventMilestone": "里程碑",
    "eventQuote": "报价",
    "eventInvoice": "开票",
    "eventPayment": "回款",
    "eventPhoto": "照片",
    "eventNote": "备注",
    "currencyPrefix": "￥",
  },
  en: {
    "valueMillion": "{0} million",
    "zeroOneTwoThreeFourFiveSix": "Zero, one, two, three, four, five, six, eight, nine",
    "pickUp": "pick up",
    "hundred": "Hundred",
    "thousand": "Thousand",
    "million": "million",
    "billion": "billion",
    "zeroYuan": "Zero Yuan",
    "zero": "zero",
    "negative": "Negative",
    "yuan": "Yuan",
    "whole": "whole",
    "angle": "angle",
    "zero4": "zero",
    "points": "points",
    "stageSurvey": "Survey",
    "stageQuote": "Quoting",
    "stageMobilization": "Mobilization",
    "stageConstruction": "Construction",
    "stageAcceptance": "Acceptance",
    "stageSettlement": "Settlement",
    "statusNotStarted": "Not started",
    "statusInProgress": "In progress",
    "statusPaused": "Paused",
    "statusCompleted": "Completed",
    "statusSettled": "Settled",
    "quoteDraft": "Draft",
    "quoteSent": "Sent",
    "quoteAccepted": "Accepted",
    "quoteExpired": "Expired",
    "invoicePending": "Pending issue",
    "invoiceIssued": "Issued",
    "invoiceMailed": "Mailed",
    "paymentUnpaid": "Unpaid",
    "paymentPartial": "Partially paid",
    "paymentPaid": "Paid in full",
    "checkoutAwaiting": "Awaiting payment",
    "checkoutProcessing": "Processing",
    "checkoutPaid": "Paid",
    "checkoutClosed": "Closed",
    "photoProgress": "Progress",
    "photoIssue": "Issue",
    "photoAcceptance": "Acceptance",
    "photoMaterials": "Materials",
    "invoiceVatSpecial": "VAT special invoice",
    "invoiceVatStandard": "VAT standard invoice",
    "invoiceVatSpecialShort": "VAT special",
    "invoiceVatStandardShort": "VAT standard",
    "payWechat": "WeChat Pay",
    "payAlipay": "Alipay",
    "payCorporateBanking": "Corporate online banking",
    "payCard": "Bank card",
    "payBankTransfer": "Bank transfer",
    "payAcceptanceBill": "Bank acceptance bill",
    "payCash": "Cash",
    "eventMilestone": "Milestone",
    "eventQuote": "Quote",
    "eventInvoice": "Invoice",
    "eventPayment": "Payment",
    "eventPhoto": "Photo",
    "eventNote": "Note",
    "currencyPrefix": "CNY ",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-projects-data-status",
  content: t(content),
};

export default dictionary;
