import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    recommended: "综合排序",
    priceLowToHigh: "价格从低到高",
    priceHighToLow: "价格从高到低",
    bestSelling: "销量优先",
    topRated: "好评优先",
    obsidianBlack: "曜石黑",
    micaWhite: "云母白",
    hazeBlue: "雾霾蓝",
    vintageGreen: "复古绿",
    updated: "已刷新",
    flashSale: "限时秒杀",
    flashSaleTimeRemaining: "剩余 02:48:33",
    addedToCart: "已加入购物车",
    productAddedToCart: "{0} 已加入购物车",
    recommendedForYou: "猜你喜欢",
    flashSaleBadge: "秒杀",
    chooseASortOrder: "选择排序方式",
    sortedBy: "已切换为",
    chooseOptions: "选规格",
    chooseSizeColor: "选择尺寸 / 颜色",
    selected: "已选：",
    add: "加购",
    yourCartIsEmpty: "购物车是空的",
    delete: "删除",
    removed: "已移除",
    total: "合计：",
    openingCheckoutDemo: "跳转结算页（demo）",
    checkout: "结算 (",
    awaitingPayment: "待付款",
    preparingShipment: "待发货",
    inTransit: "待收货",
    completed: "已完成",
    h: "瀚",
    hanshopCustomer: "瀚选用户",
    vipMember3280Points: "VIP 会员 · 积分 3,280",
    myOrders: "我的订单",
    viewAllOrdersDemo: "查看全部订单（demo）",
    allGt: "全部 >",
    demo: "（demo）",
    myFavorites: "我的收藏",
    noFavoritesYet: "暂无收藏",
    addressBook: "地址管理",
    manageShippingAddresses: "管理收货地址",
    coupons: "优惠券",
    viewMyCoupons: "查看我的优惠券",
    feedback: "意见反馈",
    shareYourSuggestions: "告诉我们您的建议",
    aboutHanshop: "关于瀚选",
    version100: "版本 1.0.0",
    home: "首页",
    categories: "分类",
    cart: "购物车",
    profile: "我的",
    backAtTheTop: "已回到顶部",
    hanshop: "瀚选",
    searchDemo: "搜索功能（demo）",
    search: "搜索",
    support: "客服",
    liveSupport: "在线客服",
    connectingToSupportDemo: "接入客服（demo）",
    backToTop: "回到顶部",
  },
  en: {
    recommended: "Recommended",
    priceLowToHigh: "Price: low to high",
    priceHighToLow: "Price: high to low",
    bestSelling: "Best selling",
    topRated: "Top rated",
    obsidianBlack: "Obsidian black",
    micaWhite: "Mica white",
    hazeBlue: "Haze blue",
    vintageGreen: "Vintage green",
    updated: "Updated",
    flashSale: "Flash sale",
    flashSaleTimeRemaining: "02:48:33 remaining",
    addedToCart: "Added to cart",
    productAddedToCart: "Added {0} to cart",
    recommendedForYou: "Recommended for you",
    flashSaleBadge: "Flash sale",
    chooseASortOrder: "Choose a sort order",
    sortedBy: "Sorted by ",
    chooseOptions: "Choose options",
    chooseSizeColor: "Choose size / color",
    selected: "Selected: ",
    add: "Add",
    yourCartIsEmpty: "Your cart is empty",
    delete: "Delete",
    removed: "Removed",
    total: "Total:",
    openingCheckoutDemo: "Opening checkout (demo)",
    checkout: "Checkout (",
    awaitingPayment: "Awaiting payment",
    preparingShipment: "Preparing shipment",
    inTransit: "In transit",
    completed: "Completed",
    h: "H",
    hanshopCustomer: "HanShop customer",
    vipMember3280Points: "VIP member · 3,280 points",
    myOrders: "My orders",
    viewAllOrdersDemo: "View all orders (demo)",
    allGt: "All >",
    demo: " (demo)",
    myFavorites: "My favorites",
    noFavoritesYet: "No favorites yet",
    addressBook: "Address book",
    manageShippingAddresses: "Manage shipping addresses",
    coupons: "Coupons",
    viewMyCoupons: "View my coupons",
    feedback: "Feedback",
    shareYourSuggestions: "Share your suggestions",
    aboutHanshop: "About HanShop",
    version100: "Version 1.0.0",
    home: "Home",
    categories: "Categories",
    cart: "Cart",
    profile: "Profile",
    backAtTheTop: "Back at the top",
    hanshop: "HanShop",
    searchDemo: "Search (demo)",
    search: "Search",
    support: "Support",
    liveSupport: "Live support",
    connectingToSupportDemo: "Connecting to support (demo)",
    backToTop: "Back to top",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = { key: "demo-shop-components-mobile-store", content: t(content) };
export default dictionary;
