import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    productDetails: "商品详情",
    specifications: "规格参数",
    customerReviews: "用户评价",
    shoeSize: "码数",
    footLengthCm: "脚长 (cm)",
    recommendedWeightKg: "建议净体重 (kg)",
    optionSize: "规格",
    chestCm: "胸围 (cm)",
    waistCm: "腰围 (cm)",
    heightCm: "身高 (cm)",
    measurementsAreAGuideOnlyReferToTheProductLabelForFinalSizing: "* 以上数据仅供参考，实际以商品吊牌为准",
    productNotFound: "商品不存在",
    thisItemIsSoldOut: "该商品已售罄",
    chooseAColor: "请选择颜色",
    chooseAnOption: "请选择规格",
    addedToCart: "已加入购物车：",
    selectedOptionsSeparator: "（",
    selectedOptionsClose: "）",
    chooseAColorFirst: "请先选择颜色",
    chooseAnOptionFirst: "请先选择规格",
    openingCheckoutDemo: "跳转结算页面…（demo 演示）",
    addedToFavorites: "已加入收藏",
    removedFromFavorites: "已取消收藏",
    home: "首页",
    allProducts: "全部商品",
    productGalleryLabel: "{0}商品图廊",
    productImageAlt: "{0}图片{1}",
    flashSale: "限时秒杀",
    new: "新品",
    soldOut: "售罄",
    reviews: "条评价",
    monthlySales: "月售",
    ofListPrice: "折",
    taxIncludedFreeNationwideShippingRemoteAreasExcluded: "含税 · 全国包邮（偏远地区除外）",
    color: "颜色",
    select: "请选择",
    sizeChart: "尺码对照表",
    sizeGuide: "尺码对照",
    quantity: "数量",
    stock: "库存",
    stockRemaining: "剩余 {0} 件",
    stockCount: "{0} 件",
    items: "件",
    addToCart: "加入购物车",
    buyNow: "立即购买",
    removeFromFavorites: "取消收藏",
    addToFavorites: "加入收藏",
    showMoreProductInformation: "展开更多商品说明",
    developedBy: "本商品由",
    thisProductCombinesAdvancedManufacturingWithThoughtfulDesignToDeliverAnExceptionalExperienceInEv: "精心研制，融合先进工艺与匠心设计，力求在每一个细节上给用户带来卓越体验。\n                    我们严格把控原材料选择与生产工艺，确保每件产品都达到最高品质标准。",
    reviewTheSpecificationsBeforeOrderingAndContactSupportWithAnyQuestionsSevenDayReturnsAndShipping: "购买前请仔细阅读规格参数，如有疑问可联系客服。支持 7 天无理由退换货，\n                    运费险全程保障，让您购物无忧。",
    detailImageAlt: "{0}详情图{1}",
    brand: "品牌",
    category: "品类",
    productId: "商品编号",
    rating: "评分",
    outOfStock: "暂无货",
    colorOptions: "颜色规格",
    sizeCapacity: "尺寸/容量",
    features: "卖点标签",
    noOptionSelected: "未选规格",
    listSeparator: "、",
  },
  en: {
    productDetails: "Product details",
    specifications: "Specifications",
    customerReviews: "Customer reviews",
    shoeSize: "Size",
    footLengthCm: "Foot length (cm)",
    recommendedWeightKg: "Recommended weight (kg)",
    optionSize: "Size",
    chestCm: "Chest (cm)",
    waistCm: "Waist (cm)",
    heightCm: "Height (cm)",
    measurementsAreAGuideOnlyReferToTheProductLabelForFinalSizing: "* Measurements are a guide only. Refer to the product label for final sizing.",
    productNotFound: "Product not found",
    thisItemIsSoldOut: "This item is sold out",
    chooseAColor: "Choose a color",
    chooseAnOption: "Choose an option",
    addedToCart: "Added to cart: ",
    selectedOptionsSeparator: " (",
    selectedOptionsClose: ")",
    chooseAColorFirst: "Choose a color first",
    chooseAnOptionFirst: "Choose an option first",
    openingCheckoutDemo: "Opening checkout... (demo)",
    addedToFavorites: "Added to favorites",
    removedFromFavorites: "Removed from favorites",
    home: "Home",
    allProducts: "All products",
    productGalleryLabel: "{0} product gallery",
    productImageAlt: "{0} image {1}",
    flashSale: "Flash sale",
    new: "New",
    soldOut: "Sold out",
    reviews: " reviews",
    monthlySales: "Monthly sales",
    ofListPrice: "% of list price",
    taxIncludedFreeNationwideShippingRemoteAreasExcluded: "Tax included · Free nationwide shipping (remote areas excluded)",
    color: "Color",
    select: "Select",
    sizeChart: "Size chart",
    sizeGuide: "Size guide",
    quantity: "quantity",
    stock: "Stock",
    stockRemaining: "Only {0} left",
    stockCount: "{0} items",
    items: "items",
    addToCart: "Add to cart",
    buyNow: "Buy now",
    removeFromFavorites: "Remove from favorites",
    addToFavorites: "Add to favorites",
    showMoreProductInformation: "Show more product information",
    developedBy: "Developed by ",
    thisProductCombinesAdvancedManufacturingWithThoughtfulDesignToDeliverAnExceptionalExperienceInEv: ", this product combines advanced manufacturing with thoughtful design to deliver an exceptional experience in every detail. We carefully control materials and production so every item meets our quality standards.",
    reviewTheSpecificationsBeforeOrderingAndContactSupportWithAnyQuestionsSevenDayReturnsAndShipping: "Review the specifications before ordering, and contact support with any questions. Seven-day returns and shipping protection make shopping worry-free.",
    detailImageAlt: "{0} detail image {1}",
    brand: "Brand",
    category: "Category",
    productId: "Product ID",
    rating: "Rating",
    outOfStock: "Out of stock",
    colorOptions: "Color options",
    sizeCapacity: "Size / capacity",
    features: "Features",
    noOptionSelected: "No option selected",
    listSeparator: ", ",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = { key: "demo-shop-components-product-detail-client", content: t(content) };
export default dictionary;
