import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "suitableForIndividualDevelopersToStart": "适合个人开发者起步",
    "teamDailyCalls": "团队日常调用",
    "mediumVolumeProductionEnvironment": "中量生产环境",
    "popular": "热门",
    "highConcurrencyMultipleProjects": "高并发 / 多项目",
    "date": "日期",
    "numberOfRequests": "请求数",
    "cost": "花费",
    "rechargeSuccessfulArrivalValue": "充值成功 · 到账 {0}",
    "includingHandlingFeeValueActualPaymentValue": "含手续费 {0}，实付 {1}",
    "billedRecharge": "计费充值",
    "balanceManagementQuotaRechargeUsageQuotaBill": "余额管理 · 额度充值 · 用量配额 · 账单明细",
    "accountBalance": "账户余额",
    "expectedToBeAvailable": "预计可用",
    "day": "天",
    "availableBalance": "可用余额",
    "dailyConsumption": "日消费 $",
    "thisMonthSUsageQuota": "本月用量配额",
    "usedCredit": "已用额度",
    "usedTotal": "已用 / 总额",
    "currentGear": "当前档位",
    "payAsYouGo": "按量计费",
    "speedLimit": "限速",
    "theFreePlanIsReqMinReq": "免费档 20 req/min · 200 req/day；包月档解除限速并享 9 折。",
    "thisMonthSQuotaHasBeenUsed": "本月额度已使用",
    "youCanRechargeInAdvanceOrUpgrade": "%，可提前充值或升级包月档以避免触发限速。",
    "accountRecharge": "账户充值",
    "rechargeAmountLevel": "充值额度档位",
    "customAmount": "自定义金额（$）",
    "customizedRechargeAmount": "自定义充值金额",
    "creditLimit": "到账额度",
    "handlingFeeStartingAt": "手续费（5.5%，$0.80 起）",
    "totalActualPayment": "实付合计",
    "rechargeNow": "立即充值",
    "billDetailsLastDays": "账单明细（近 7 日）",
    "billExporting": "账单导出中…",
    "csvWillBeSentToAccountEmail": "CSV 将发送至账户邮箱",
    "export": "导出",
    "byokBringYourOwnUpstreamKey": "BYOK · 自带上游密钥",
    "bindYourOwnUpstreamVendorApiKey": "绑定你自己的上游厂商 API Key（OpenAI / Anthropic / Google 等），网关",
    "noMarkUpRatio": "免加价倍率",
    "directPassThroughOnlyReceive": "直接透传，仅收取",
    "handlingFee": "5% 手续费",
    "usedForRoutingAndAccounting": "用于路由与计费。",
    "freeOfMagnification": "免倍率",
    "handlingFee2": "5% 手续费",
    "usageIsIncludedInTheBill": "用量统一计入账单",
  },
  en: {
    "suitableForIndividualDevelopersToStart": "Suitable for individual developers to start",
    "teamDailyCalls": "Team daily calls",
    "mediumVolumeProductionEnvironment": "Medium volume production environment",
    "popular": "Popular",
    "highConcurrencyMultipleProjects": "High concurrency / multiple projects",
    "date": "Date",
    "numberOfRequests": "Number of requests",
    "cost": "cost",
    "rechargeSuccessfulArrivalValue": "Recharge successful · Arrival {0}",
    "includingHandlingFeeValueActualPaymentValue": "Including handling fee {0}, actual payment {1}",
    "billedRecharge": "Billed recharge",
    "balanceManagementQuotaRechargeUsageQuotaBill": "Balance management · Quota recharge · Usage quota · Bill details",
    "accountBalance": "Account balance",
    "expectedToBeAvailable": "Expected to be available",
    "day": "day",
    "availableBalance": "available balance",
    "dailyConsumption": "Daily consumption $",
    "thisMonthSUsageQuota": "This month's usage quota",
    "usedCredit": "Used credit",
    "usedTotal": "Used / Total",
    "currentGear": "Current gear",
    "payAsYouGo": "Pay as you go",
    "speedLimit": "speed limit",
    "theFreePlanIsReqMinReq": "The free plan is 20 req/min · 200 req/day; the monthly plan removes the speed limit and enjoys a 10% discount.",
    "thisMonthSQuotaHasBeenUsed": "This month's quota has been used",
    "youCanRechargeInAdvanceOrUpgrade": "%, you can recharge in advance or upgrade the monthly package to avoid triggering speed limits.",
    "accountRecharge": "Account recharge",
    "rechargeAmountLevel": "Recharge amount level",
    "customAmount": "Custom amount ($)",
    "customizedRechargeAmount": "Customized recharge amount",
    "creditLimit": "Credit limit",
    "handlingFeeStartingAt": "Handling fee (5.5%, starting at $0.80)",
    "totalActualPayment": "Total actual payment",
    "rechargeNow": "Recharge now",
    "billDetailsLastDays": "Bill details (last 7 days)",
    "billExporting": "Bill exporting...",
    "csvWillBeSentToAccountEmail": "CSV will be sent to account email",
    "export": "Export",
    "byokBringYourOwnUpstreamKey": "BYOK · Bring your own upstream key",
    "bindYourOwnUpstreamVendorApiKey": "Bind your own upstream vendor API Key (OpenAI / Anthropic / Google, etc.), gateway",
    "noMarkUpRatio": "No mark-up ratio",
    "directPassThroughOnlyReceive": "Direct pass-through, only receive",
    "handlingFee": "5% handling fee",
    "usedForRoutingAndAccounting": "Used for routing and accounting.",
    "freeOfMagnification": "Free of magnification",
    "handlingFee2": "5% handling fee",
    "usageIsIncludedInTheBill": "Usage is included in the bill",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanhub-app-billing-page",
  content: t(content),
};

export default dictionary;
