import { t, type Dictionary } from "intlayer";

export const docsSearchContent = {
  "zh-CN": {
    trigger: "搜索文档",
    triggerPlaceholder: "搜索文档…",
    dialogLabel: "全站搜索",
    placeholder: "搜页面、区块、组件、模版或指南，也可以直接描述任务…",
    count: "{shown} / {total}",
    viewAllType: "查看{name}的全部 {count} 条",
    viewAllQuery: "查看“{query}”的全部结果",
    approximate: "近似结果（按“{query}”）",
    alternatives: "换个找法",
    browsePages: "浏览全部页面",
    browsePagesDescription: "由区块拼成的完整整页，最省事的起点",
    browseBlocks: "浏览全部区块",
    browseBlocksDescription: "自包含的页面区块，复制即用",
    browseComponents: "浏览全部组件",
    browseComponentsDescription: "按分类查看 {count} 个组件",
    registry: "打开 registry",
    registryDescription: "shadcn CLI 可直接消费的机器可读清单",
    empty: "没有匹配的内容",
    pages: "页面",
    blocks: "区块",
    components: "组件",
    metadataTitle: "搜索 · 瑚琏 Hulian",
    metadataDescription: "跨页面、区块、组件、模版与指南的全站搜索。描述任务即可找到可复用积木。",
    pageTitle: "搜索",
    pageDescription: "跨页面、区块、组件、模版与指南。直接描述任务，优先返回可以整块复用的内容。",
    inputPlaceholder: "描述任务或输入名称、导出名或 slug…",
    inputLabel: "搜索站内内容",
    all: "全部",
    allCategories: "全部分类",
    emptyQuery: "输入关键词开始搜索",
    emptyQueryMatch: "没有匹配“{query}”的内容",
    emptyFilteredDescription: "当前还叠加了类型或分类筛选，先清除筛选以查看全部结果。",
    emptyDescription: "换个说法，或直接从页面与区块开始浏览。",
    clearFilters: "清除筛选",
    tryQuery: "试试“{query}”",
    loading: "加载中…",
  },
  en: {
    trigger: "Search documentation",
    triggerPlaceholder: "Search docs...",
    dialogLabel: "Site-wide search",
    placeholder: "Search pages, blocks, components, demos, or guides, or describe your task...",
    count: "{shown} of {total}",
    viewAllType: "View all {count} {name} results",
    viewAllQuery: "View all results for \"{query}\"",
    approximate: "Similar results for \"{query}\"",
    alternatives: "Try another route",
    browsePages: "Browse all pages",
    browsePagesDescription: "Complete pages assembled from blocks, often the fastest starting point",
    browseBlocks: "Browse all blocks",
    browseBlocksDescription: "Self-contained page sections ready to copy",
    browseComponents: "Browse all components",
    browseComponentsDescription: "Explore {count} components by category",
    registry: "Open the registry",
    registryDescription: "A machine-readable catalog consumed directly by the shadcn CLI",
    empty: "No matching documentation",
    pages: "Pages",
    blocks: "Blocks",
    components: "Components",
    metadataTitle: "Search · Hulian UI",
    metadataDescription: "Search across pages, blocks, components, demos, and guides. Describe a task to find reusable building blocks.",
    pageTitle: "Search",
    pageDescription: "Search pages, blocks, components, demos, and guides. Describe your task to see reusable high-level building blocks first.",
    inputPlaceholder: "Describe a task or enter a name, export, or slug...",
    inputLabel: "Search site content",
    all: "All",
    allCategories: "All categories",
    emptyQuery: "Enter a keyword to start searching",
    emptyQueryMatch: "No content matches \"{query}\"",
    emptyFilteredDescription: "Type or category filters are active. Clear them to inspect every result.",
    emptyDescription: "Try different wording, or begin with complete pages and blocks.",
    clearFilters: "Clear filters",
    tryQuery: "Try \"{query}\"",
    loading: "Loading...",
  },
} as const;

const dictionary: Dictionary = {
  key: "docs-search",
  content: t(docsSearchContent),
};

export default dictionary;
