export const sharedChromeContent = {
  "zh-CN": {
    breadcrumb: "面包屑",
    brand: "瑚琏 Hulian",
    copyMarkdown: "复制 MD",
    copied: "已复制",
    copyAria: "{label}（复制本页文档给 AI 编程助手）",
    docsSections: "文档分区",
    components: "组件",
    theme: "主题",
    browseCategories: "浏览分类",
    browseList: "浏览列表",
    viewAllComponents: "查看全部组件",
    mirrorClose: "不再提示",
    mirrorAction: "切换到镜像 →",
    mirrorMessage: "检测到你在中国大陆，访问镜像站点更快",
    openMenu: "打开菜单",
    closeMenu: "关闭菜单",
    toggleTheme: "切换颜色主题",
    languageGroup: "语言 / Language",
    chinese: "中文",
    english: "EN",
    switchChinese: "切换到中文",
    switchEnglish: "Switch to English",
    copyCode: "复制",
    copiedCode: "已复制",
    codeLabel: "代码",
    backToTop: "回到顶部",
  },
  en: {
    breadcrumb: "Breadcrumb",
    brand: "Hulian UI",
    copyMarkdown: "Copy MD",
    copied: "Copied",
    copyAria: "{label}; copy this page for an AI coding assistant",
    docsSections: "Documentation sections",
    components: "Components",
    theme: "Theme",
    browseCategories: "Browse categories",
    browseList: "Browse list",
    viewAllComponents: "View all components",
    mirrorClose: "Dismiss",
    mirrorAction: "Switch to the mirror ->",
    mirrorMessage: "A regional mirror may load faster from mainland China.",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    toggleTheme: "Toggle color theme",
    languageGroup: "Language",
    chinese: "Chinese",
    english: "English",
    switchChinese: "Switch to Chinese",
    switchEnglish: "Switch to English",
    copyCode: "Copy",
    copiedCode: "Copied",
    codeLabel: "code",
    backToTop: "Back to top",
  },
} as const;
