import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "textGeneration": "文本生成",
    "code": "代码",
    "image": "图像",
    "translation": "翻译",
    "retrievalEnhancement": "检索增强",
    "structuredExtraction": "结构化抽取",
    "contentReview": "内容审核",
    "multiAgentOrchestration": "多 agent 编排",
    "pendingExecution": "待执行",
    "inExecution": "执行中",
    "downgrading": "降级中",
    "failure": "失败",
    "done": "完成",
    "valueMinutesValueSeconds": "{0}分{1}秒",
    "theMissionDoesNotExist": "任务不存在",
    "tasksWithIdValueNotFoundMay": "未找到 id 为「{0}」的任务，可能已被清理或链接失效。",
    "returnToTheQuestQueue": "返回任务队列",
    "slaAchievedEndToEndValueMargin": "SLA 达成 · 端到端 {0}，余量 {1}（阈值 {2}）",
    "slaNearExpiryUsedValueRemainingValue": "SLA 临期 · 已用 {0}，剩余 {1}（阈值 {2}，占用 {3}%）",
    "slaBreachEndToEndValueHas": "SLA 违约 · 端到端 {0} 已超阈值 {1}（超 {2}）",
    "waitingValue": "等待 {0}",
    "taskJoiningValuePriorityValue": "任务入队 · {0} · 优先级 {1}",
    "intelligentRouting": "智能路由",
    "valueSelectedValue": "{0}（选中 {1}）",
    "downgradeFailover": "降级 failover",
    "operationDegradation": "运行降级",
    "completed": "已完成",
    "arrangementCompletedCostValue": "编排完成 · 花费 ¥{0}",
    "failure2": "失败",
    "missionFailedSpentValue": "任务失败 · 已花费 ¥{0}",
    "taskQueue": "任务队列 /",
    "cancelled": "取消",
    "reset": "重置",
    "running": "运行中…",
    "rerun": "重新运行",
    "receivingActuator": "承接执行器：",
    "costBudget": "成本预算：",
    "slaGoals": "SLA 目标：",
    "submitter": "提交人：",
    "rerun2": "重新运行",
    "cancelled2": "取消",
    "subtaskList": "子任务清单",
    "thisTaskIsPerformedInASingle": "该任务为单步执行，无子任务 DAG。",
    "totalTimeSpentOnSubtasks": "子任务总耗时",
    "totalSubtaskCost": "子任务总成本",
    "multiAgentOrchestrationOfDags": "多 agent 编排 DAG",
    "valueSubtasksValueDependencies": "{0} 个子任务 · {1} 条依赖",
    "noDag": "无 DAG",
    "aOneStepTask": "单步任务",
    "noMultiAgentOrchestrationDirectlyAssignedTo": "无多 agent 编排，直接派给单一执行器。",
    "executionProcess": "执行过程",
    "stop": "停止",
    "run": "运行",
    "thisTimeExpensesBudget": "本次花费 / 预算",
    "fullLinkTimeline": "全链路时间线",
    "orchestrationExecution": "编排执行中…",
  },
  en: {
    "textGeneration": "Text generation",
    "code": "Code",
    "image": "Image",
    "translation": "Translation",
    "retrievalEnhancement": "Retrieval enhancement",
    "structuredExtraction": "Structured extraction",
    "contentReview": "Content review",
    "multiAgentOrchestration": "Multi-agent orchestration",
    "pendingExecution": "Pending execution",
    "inExecution": "Running",
    "downgrading": "Using fallback",
    "failure": "Failed",
    "done": "Done",
    "valueMinutesValueSeconds": "{0} minutes {1} seconds",
    "theMissionDoesNotExist": "The task does not exist",
    "tasksWithIdValueNotFoundMay": "Task \"{0}\" was not found. It may have been removed, or the link may be stale.",
    "returnToTheQuestQueue": "Return to the task queue",
    "slaAchievedEndToEndValueMargin": "SLA achieved · End-to-end {0}, margin {1} (threshold {2})",
    "slaNearExpiryUsedValueRemainingValue": "SLA at risk · {0} elapsed, {1} remaining (threshold {2}, {3}% used)",
    "slaBreachEndToEndValueHas": "SLA breached · End-to-end time {0} exceeded the {1} threshold by {2}",
    "waitingValue": "Waiting {0}",
    "taskJoiningValuePriorityValue": "Task queued · {0} · Priority {1}",
    "intelligentRouting": "Intelligent routing",
    "valueSelectedValue": "{0} (Selected {1})",
    "downgradeFailover": "Fallback: failover",
    "operationDegradation": "Runtime fallback",
    "completed": "Completed",
    "arrangementCompletedCostValue": "Orchestration completed · Cost ¥{0}",
    "failure2": "Failed",
    "missionFailedSpentValue": "Task failed · Spent ¥{0}",
    "taskQueue": "Task queue /",
    "cancelled": "Cancelled",
    "reset": "Reset",
    "running": "Running...",
    "rerun": "Rerun",
    "receivingActuator": "Assigned executor:",
    "costBudget": "Cost budget:",
    "slaGoals": "SLA target:",
    "submitter": "Submitter:",
    "rerun2": "Rerun",
    "cancelled2": "Cancelled",
    "subtaskList": "Subtask list",
    "thisTaskIsPerformedInASingle": "This task runs as a single step without a subtask DAG.",
    "totalTimeSpentOnSubtasks": "Total time spent on subtasks",
    "totalSubtaskCost": "Total subtask cost",
    "multiAgentOrchestrationOfDags": "Multi-agent orchestration DAG",
    "valueSubtasksValueDependencies": "{0} subtasks · {1} dependencies",
    "noDag": "No DAG",
    "aOneStepTask": "A one-step task",
    "noMultiAgentOrchestrationDirectlyAssignedTo": "This task is assigned directly to one executor without multi-agent orchestration.",
    "executionProcess": "Execution process",
    "stop": "Stop",
    "run": "Run",
    "thisTimeExpensesBudget": "Run cost / budget",
    "fullLinkTimeline": "End-to-end timeline",
    "orchestrationExecution": "Running orchestration...",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanhelm-components-task-detail",
  content: t(content),
};

export default dictionary;
