import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    reviewOrder: "确认订单",
    payment: "支付",
    complete: "完成",
    sanZhang: "张三",
    selectAShippingAddress: "请选择收货地址",
    enterTheRecipientSName: "请填写收货人姓名",
    selectAPaymentMethod: "请选择支付方式",
    paymentSuccessful: "支付成功",
    checkout: "结算",
    shippingInformation: "收货信息",
    shippingAddresses: "收货地址",
    selectProvinceCityDistrict: "选择省 / 市 / 区",
    recipient: "收货人",
    enterAName: "请输入姓名",
    phone: "联系电话",
    enterAPhoneNumber: "请输入手机号",
    deliveryMethod: "配送方式",
    standardDelivery35DaysFreeOnOrdersOver199: "标准快递（3-5 天）— 免运费满 ¥199",
    sfExpress12Days12Surcharge: "顺丰特快（1-2 天）— 另付 ¥12",
    items: "商品清单（",
    products: "种）",
    yourCartIsEmpty: "购物车为空，",
    backToCart: "返回购物车",
    coupons: "优惠券",
    orderNotes: "订单备注",
    notesOptional: "备注（选填）",
    addAnySpecialRequestsSuchAsColorOrSizePreferences: "如有特殊要求请在此注明（颜色、规格偏好等）",
    orderSummary: "金额明细",
    subtotal: "商品总额",
    shipping: "运费",
    free: "免运费",
    couponDiscount: "优惠券折扣",
    totalDue: "实付金额",
    continueToPayment: "确认订单，去支付",
    chooseAPaymentMethod: "选择支付方式",
    paymentMethods: "支付方式",
    wechatPay: "微信支付",
    alipay: "支付宝",
    bankCard: "银行卡",
    total: "共",
    products2: "件商品",
    totalDue2: "实付：",
    back: "上一步",
    processingPayment: "支付中...",
    payNow: "立即支付",
    orderPlaced: "下单成功！",
    order: "订单号",
    estimatedDispatchIn35BusinessDays: "，预计 3-5 个工作日内发货。",
    continueShopping: "继续购物",
    backToHome: "返回首页",
  },
  en: {
    reviewOrder: "Review order",
    payment: "Payment",
    complete: "Complete",
    sanZhang: "San Zhang",
    selectAShippingAddress: "Select a shipping address",
    enterTheRecipientSName: "Enter the recipient's name",
    selectAPaymentMethod: "Select a payment method",
    paymentSuccessful: "Payment successful",
    checkout: "Checkout",
    shippingInformation: "Shipping information",
    shippingAddresses: "Shipping addresses",
    selectProvinceCityDistrict: "Select province / city / district",
    recipient: "Recipient",
    enterAName: "Enter a name",
    phone: "Phone",
    enterAPhoneNumber: "Enter a phone number",
    deliveryMethod: "Delivery method",
    standardDelivery35DaysFreeOnOrdersOver199: "Standard delivery (3–5 days) — free on orders over ¥199",
    sfExpress12Days12Surcharge: "SF Express (1–2 days) — ¥12 surcharge",
    items: "Items (",
    products: " products)",
    yourCartIsEmpty: "Your cart is empty. ",
    backToCart: "Back to cart",
    coupons: "Coupons",
    orderNotes: "Order notes",
    notesOptional: "Notes (optional)",
    addAnySpecialRequestsSuchAsColorOrSizePreferences: "Add any special requests, such as color or size preferences",
    orderSummary: "Order summary",
    subtotal: "Subtotal",
    shipping: "Shipping",
    free: "Free",
    couponDiscount: "Coupon discount",
    totalDue: "Total due",
    continueToPayment: "Continue to payment",
    chooseAPaymentMethod: "Choose a payment method",
    paymentMethods: "Payment methods",
    wechatPay: "WeChat Pay",
    alipay: "Alipay",
    bankCard: "Bank card",
    total: "Total: ",
    products2: " products",
    totalDue2: "Total due:",
    back: "Back",
    processingPayment: "Processing payment...",
    payNow: "Pay now",
    orderPlaced: "Order placed",
    order: "Order ",
    estimatedDispatchIn35BusinessDays: ". Estimated dispatch in 3–5 business days.",
    continueShopping: "Continue shopping",
    backToHome: "Back to home",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = { key: "demo-shop-shop-checkout-page", content: t(content) };
export default dictionary;
