import type { Order } from "./types";

export const SEED_ORDERS: Order[] = [
  {
    id: "o1",
    serviceId: "s1",
    serviceTitle: "深度保洁 · 全屋",
    serviceCategory: "家政保洁",
    workerName: "张阿姨",
    status: "待评价",
    price: 88,
    quantity: 1,
    unit: "次",
    appointedAt: "2026-06-03 10:00",
    address: "朝阳区望京 SOHO T2 2502",
  },
  {
    id: "o2",
    serviceId: "s2",
    serviceTitle: "空调清洗消毒",
    serviceCategory: "家电维修",
    workerName: "李师傅",
    status: "服务中",
    price: 59,
    quantity: 2,
    unit: "台",
    appointedAt: "2026-06-04 14:30",
    address: "海淀区中关村大厦 1201",
  },
  {
    id: "o3",
    serviceId: "s3",
    serviceTitle: "上门美甲 · 精品款",
    serviceCategory: "上门美甲",
    workerName: "小雅",
    status: "待确认",
    price: 128,
    quantity: 1,
    unit: "次",
    appointedAt: "2026-06-05 15:00",
    address: "西城区金融街 B304",
  },
  {
    id: "o4",
    serviceId: "s8",
    serviceTitle: "日常保洁 · 2 小时",
    serviceCategory: "家政保洁",
    workerName: "孙阿姨",
    status: "已完成",
    price: 58,
    quantity: 1,
    unit: "次",
    appointedAt: "2026-05-28 09:00",
    address: "朝阳区望京 SOHO T2 2502",
  },
  {
    id: "o5",
    serviceId: "s4",
    serviceTitle: "马桶/下水道疏通",
    serviceCategory: "管道疏通",
    workerName: "王师傅",
    status: "已取消",
    price: 99,
    quantity: 1,
    unit: "次",
    appointedAt: "2026-05-20 11:00",
    address: "丰台区总部基地 A1-301",
  },
];

export const ORDER_STATUS_TONE: Record<string, "neutral" | "brand" | "success" | "warning" | "danger"> = {
  待确认: "warning",
  服务中: "brand",
  待评价: "success",
  已完成: "neutral",
  已取消: "danger",
};
