import { copy } from "./orders.content";
import type { Order } from "./types";

export const SEED_ORDERS: Order[] = [
  {
    id: "o1",
    serviceId: "s1",
    serviceTitle: copy("deepWholeHomeCleaning"),
    serviceCategory: "家政保洁",
    workerName: copy("msZhang"),
    status: "待评价",
    price: 88,
    quantity: 1,
    unit: copy("service"),
    appointedAt: "2026-06-03 10:00",
    address: copy("room2502Tower2WangjingSohoChaoyangDistrict"),
  },
  {
    id: "o2",
    serviceId: "s2",
    serviceTitle: copy("airConditionerCleaningAndSanitizing"),
    serviceCategory: "家电维修",
    workerName: copy("mrLi"),
    status: "服务中",
    price: 59,
    quantity: 2,
    unit: copy("unit"),
    appointedAt: "2026-06-04 14:30",
    address: copy("room1201ZhongguancunTowerHaidianDistrict"),
  },
  {
    id: "o3",
    serviceId: "s3",
    serviceTitle: copy("premiumAtHomeManicure"),
    serviceCategory: "上门美甲",
    workerName: copy("xiaoya"),
    status: "待确认",
    price: 128,
    quantity: 1,
    unit: copy("service"),
    appointedAt: "2026-06-05 15:00",
    address: copy("b304FinancialStreetXichengDistrict"),
  },
  {
    id: "o4",
    serviceId: "s8",
    serviceTitle: copy("routineCleaning2Hours"),
    serviceCategory: "家政保洁",
    workerName: copy("msSun"),
    status: "已完成",
    price: 58,
    quantity: 1,
    unit: copy("service"),
    appointedAt: "2026-05-28 09:00",
    address: copy("room2502Tower2WangjingSohoChaoyangDistrict"),
  },
  {
    id: "o5",
    serviceId: "s4",
    serviceTitle: copy("toiletAndDrainClearing"),
    serviceCategory: "管道疏通",
    workerName: copy("mrWang"),
    status: "已取消",
    price: 99,
    quantity: 1,
    unit: copy("service"),
    appointedAt: "2026-05-20 11:00",
    address: copy("a1301AdvancedBusinessParkFengtaiDistrict"),
  },
];

export const ORDER_STATUS_TONE: Record<string, "neutral" | "brand" | "success" | "warning" | "danger"> = {
  待确认: "warning",
  服务中: "brand",
  待评价: "success",
  已完成: "neutral",
  已取消: "danger",
};

export const ORDER_STATUS_LABELS: Record<Order["status"], string> = {
  待确认: copy("pendingConfirmation"),
  服务中: copy("inProgress"),
  待评价: copy("awaitingReview"),
  已完成: copy("completed"),
  已取消: copy("canceled"),
};
