import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    deepWholeHomeCleaning: "深度保洁 · 全屋",
    service: "次",
    bestseller: "爆款",
    msZhang: "张阿姨",
    zhang: "张",
    aThoroughWholeHomeCleanByAProfessionalIncludingKitchenAndBathroomDescalingFurnitureWipeDownsAndF: "专业深度保洁，全屋彻底清洁，厨卫除垢，家具表面擦拭，地板打蜡。包工具包耗材，服务时长约 4 小时。",
    airConditionerCleaningAndSanitizing: "空调清洗消毒",
    unit: "台",
    topRated: "好评",
    mrLi: "李师傅",
    li: "李",
    professionalAirConditionerCleaningWithHighTemperatureSteamSanitizingMoldRemovalAndFullIndoorAndO: "专业空调清洗，高温蒸汽消毒，除霉杀菌，清洗内外机，提升制冷效率。可同时清洗多台，数量越多越优惠。",
    premiumAtHomeManicure: "上门美甲 · 精品款",
    popular: "热门",
    xiaoya: "小雅",
    y: "雅",
    anAtHomeManicureWithPremiumDesignsAndImportedPolishChooseGradientsFrenchTipsOrCrystalAccentsTool: "美甲师上门服务，精品款式，进口甲油，可选渐变、法式、钻饰。包工具，服务时长约 90 分钟。",
    toiletAndDrainClearing: "马桶/下水道疏通",
    urgentRepair: "急修",
    mrWang: "王师傅",
    wang: "王",
    aProfessionalTechnicianClearsStubbornBlockagesWithAHighPressureWaterJetSameDayArrivalAndNoCharge: "专业疏通师，高压水枪疏通，彻底清除堵塞。小时内上门，疏通不通不收费。适用马桶、厨房下水、地漏。",
    smallMoveWithFullHomePacking: "小型搬家·整屋打包",
    movingIncluded: "包搬运",
    movingTeam: "搬运队",
    m: "搬",
    aTwoPersonMovingTeamWithProfessionalPackingMaterialsAndProtectiveFurnitureWrappingDesignedToFini: "2 人搬运团队，专业打包材料，小心搬运，覆盖家具贴膜保护。3 小时内完成，超时另议。",
    lockOpeningAndCylinderReplacement: "开锁·换锁芯",
    fastArrival: "快速上门",
    mrChen: "陈师傅",
    chen: "陈",
    aProfessionalLocksmithArrivesWithin30MinutesAndCanOpenMajorBrandsOfSecurityDoorsReplacementCylin: "专业开锁师傅，30 分钟内上门，各品牌防盗门可开。如需换锁芯，提供多品牌锁芯，当场安装。",
    waterHeaterInstallationAndRepair: "热水器安装/维修",
    warranty: "保修",
    mrLiu: "刘师傅",
    liu: "刘",
    installationRepairsAndDescalingForGasElectricAndTanklessWaterHeatersRepairsIncludeAThreeMonthWar: "热水器安装、故障维修、水垢清洗。支持燃气热水器、电热水器、即热式。维修后保修 3 个月。",
    routineCleaning2Hours: "日常保洁 · 2 小时",
    greatValue: "超值",
    msSun: "孙阿姨",
    sun: "孙",
    routineHomeCleaningCoveringFloorsKitchenCountersBathroomsAndLightTidyingIdealForRegularUpkeepSer: "日常家务保洁，扫地拖地、厨房台面、卫生间清洁、整理归纳。适合维持日常卫生，服务时长 2 小时。",
    homeCleaning: "家政保洁",
    applianceRepair: "家电维修",
    atHomeManicure: "上门美甲",
    drainClearing: "管道疏通",
    movingServices: "搬家搬运",
    locksmith: "开锁换锁",
  },
  en: {
    deepWholeHomeCleaning: "Deep whole-home cleaning",
    service: "service",
    bestseller: "Bestseller",
    msZhang: "Ms. Zhang",
    zhang: "Zhang",
    aThoroughWholeHomeCleanByAProfessionalIncludingKitchenAndBathroomDescalingFurnitureWipeDownsAndF: "A thorough whole-home clean by a professional, including kitchen and bathroom descaling, furniture wipe-downs, and floor waxing. Tools and supplies are included; service takes about four hours.",
    airConditionerCleaningAndSanitizing: "Air-conditioner cleaning and sanitizing",
    unit: "unit",
    topRated: "Top rated",
    mrLi: "Mr. Li",
    li: "Li",
    professionalAirConditionerCleaningWithHighTemperatureSteamSanitizingMoldRemovalAndFullIndoorAndO: "Professional air-conditioner cleaning with high-temperature steam sanitizing, mold removal, and full indoor and outdoor unit cleaning to improve cooling efficiency. Multi-unit discounts are available.",
    premiumAtHomeManicure: "Premium at-home manicure",
    popular: "Popular",
    xiaoya: "Xiaoya",
    y: "Y",
    anAtHomeManicureWithPremiumDesignsAndImportedPolishChooseGradientsFrenchTipsOrCrystalAccentsTool: "An at-home manicure with premium designs and imported polish. Choose gradients, French tips, or crystal accents. Tools are included; service takes about 90 minutes.",
    toiletAndDrainClearing: "Toilet and drain clearing",
    urgentRepair: "Urgent repair",
    mrWang: "Mr. Wang",
    wang: "Wang",
    aProfessionalTechnicianClearsStubbornBlockagesWithAHighPressureWaterJetSameDayArrivalAndNoCharge: "A professional technician clears stubborn blockages with a high-pressure water jet. Same-day arrival, and no charge if the blockage cannot be cleared. Suitable for toilets, kitchen drains, and floor drains.",
    smallMoveWithFullHomePacking: "Small move with full-home packing",
    movingIncluded: "Moving included",
    movingTeam: "Moving team",
    m: "M",
    aTwoPersonMovingTeamWithProfessionalPackingMaterialsAndProtectiveFurnitureWrappingDesignedToFini: "A two-person moving team with professional packing materials and protective furniture wrapping. Designed to finish within three hours; additional time is quoted separately.",
    lockOpeningAndCylinderReplacement: "Lock opening and cylinder replacement",
    fastArrival: "Fast arrival",
    mrChen: "Mr. Chen",
    chen: "Chen",
    aProfessionalLocksmithArrivesWithin30MinutesAndCanOpenMajorBrandsOfSecurityDoorsReplacementCylin: "A professional locksmith arrives within 30 minutes and can open major brands of security doors. Replacement cylinders from multiple brands can be installed on site.",
    waterHeaterInstallationAndRepair: "Water heater installation and repair",
    warranty: "Warranty",
    mrLiu: "Mr. Liu",
    liu: "Liu",
    installationRepairsAndDescalingForGasElectricAndTanklessWaterHeatersRepairsIncludeAThreeMonthWar: "Installation, repairs, and descaling for gas, electric, and tankless water heaters. Repairs include a three-month warranty.",
    routineCleaning2Hours: "Routine cleaning · 2 hours",
    greatValue: "Great value",
    msSun: "Ms. Sun",
    sun: "Sun",
    routineHomeCleaningCoveringFloorsKitchenCountersBathroomsAndLightTidyingIdealForRegularUpkeepSer: "Routine home cleaning covering floors, kitchen counters, bathrooms, and light tidying. Ideal for regular upkeep; service takes two hours.",
    homeCleaning: "Home cleaning",
    applianceRepair: "Appliance repair",
    atHomeManicure: "At-home manicure",
    drainClearing: "Drain clearing",
    movingServices: "Moving services",
    locksmith: "Locksmith",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>(
    (text, value, index) => text.replaceAll(`{${index}}`, String(value)),
    content[DOCS_LOCALE][key],
  );
}

const dictionary: Dictionary = {
  key: "demo-mobile-data-services",
  content: t(content),
};

export default dictionary;
