import { copy } from "./customers.content";
import { canonicalIndustry, canonicalOwner } from "./protocol";
import type { Customer } from "./types";

// 24 条客户主数据（跨行业 / 等级 / 状态 / 负责人，供列表/详情/看板/工作台共用）。
export const customers: Customer[] = [
  { id: "C1001", name: copy("morningLightStationery"), company: copy("shanghaiChenguangStationeryCoLtd"), contactName: copy("chenChen"), phone: "138-0011-2233", email: "chen@mgstationery.com", level: "重要", status: "已成交", owner: canonicalOwner("linWanqing"), industry: canonicalIndustry("manufacturing"), region: copy("shanghai"), amount: 1286000, lastFollowAt: "2026-05-30", createdAt: "2025-08-12", tags: [copy("bigCustomers"), copy("renewContract")] },
  { id: "C1002", name: copy("yunqiTechnology"), company: copy("hangzhouYunqiNetworkTechnologyCoLtd"), contactName: copy("guyu"), phone: "139-2244-5566", email: "gu@yunqi.io", level: "重要", status: "跟进中", owner: canonicalOwner("zhouMingyuan"), industry: canonicalIndustry("internet"), region: copy("hangzhou"), amount: 740000, lastFollowAt: "2026-06-02", createdAt: "2025-11-03", tags: ["SaaS", copy("highPotential")] },
  { id: "C1003", name: copy("baiweiCatering"), company: copy("chengduBaiweiCateringManagementCoLtd"), contactName: copy("luoMin"), phone: "137-7788-9900", email: "luo@baiwei.com", level: "普通", status: "跟进中", owner: canonicalOwner("highSensitivity"), industry: canonicalIndustry("catering"), region: copy("chengdu"), amount: 96000, lastFollowAt: "2026-05-28", createdAt: "2026-01-19", tags: [copy("chain")] },
  { id: "C1004", name: copy("hengkangMedical"), company: copy("guangzhouHengkangMedicalEquipmentCoLtd"), contactName: copy("dengWei"), phone: "135-3322-1100", email: "deng@hkmed.com", level: "重要", status: "已成交", owner: canonicalOwner("chenCe"), industry: canonicalIndustry("medical"), region: copy("guangzhou"), amount: 2050000, lastFollowAt: "2026-05-21", createdAt: "2025-06-30", tags: [copy("bigCustomers2"), copy("tender")] },
  { id: "C1005", name: copy("knowledgeAndActionEducation"), company: copy("beijingZhixingOnlineEducationCoLtd"), contactName: copy("xiaYu"), phone: "136-9988-7766", email: "xia@zhixingedu.cn", level: "普通", status: "待分配", owner: canonicalOwner("suXiao"), industry: canonicalIndustry("education"), region: copy("beijing"), amount: 0, lastFollowAt: "2026-06-01", createdAt: "2026-05-26", tags: [copy("newClues")] },
  { id: "C1006", name: copy("shundaLogistics"), company: copy("shenzhenShundaSupplyChainLogisticsCoLtd"), contactName: copy("maTao"), phone: "133-4455-6677", email: "ma@sdwl.com", level: "重要", status: "跟进中", owner: canonicalOwner("linWanqing2"), industry: canonicalIndustry("logistics"), region: copy("shenzhen"), amount: 530000, lastFollowAt: "2026-05-31", createdAt: "2025-09-14", tags: [copy("supplyChain")] },
  { id: "C1007", name: copy("jinxiuTextile"), company: copy("suzhouJinxiuTextileIndustrialCoLtd"), contactName: copy("qianFang"), phone: "131-1212-3434", email: "qian@jxtex.com", level: "普通", status: "已流失", owner: canonicalOwner("zhouMingyuan2"), industry: canonicalIndustry("manufacturing2"), region: copy("suzhou"), amount: 178000, lastFollowAt: "2026-03-12", createdAt: "2025-07-22", tags: [copy("loss"), copy("priceSensitive")] },
  { id: "C1008", name: copy("starMedia"), company: copy("shanghaiStarCultureMediaCoLtd"), contactName: copy("hanLei"), phone: "150-6677-8899", email: "han@xingchen.tv", level: "普通", status: "跟进中", owner: canonicalOwner("highSensitivity2"), industry: canonicalIndustry("media"), region: copy("shanghai2"), amount: 64000, lastFollowAt: "2026-05-29", createdAt: "2026-02-08", tags: [copy("content")] },
  { id: "C1009", name: copy("dingfengRealEstate"), company: copy("chongqingDingfengRealEstateDevelopmentCoLtd"), contactName: copy("caoYong"), phone: "151-2323-4545", email: "cao@dingfeng.com", level: "重要", status: "已成交", owner: canonicalOwner("chenCe2"), industry: canonicalIndustry("realEstate"), region: copy("chongqing"), amount: 1680000, lastFollowAt: "2026-05-18", createdAt: "2025-05-11", tags: [copy("bigCustomers3")] },
  { id: "C1010", name: copy("greenfieldAgriculture"), company: copy("shandongLuyeModernAgricultureCoLtd"), contactName: copy("kongXue"), phone: "152-3434-5656", email: "kong@lvye.agri", level: "潜在", status: "待分配", owner: canonicalOwner("suXiao2"), industry: canonicalIndustry("agriculture"), region: copy("jinan"), amount: 0, lastFollowAt: "2026-06-03", createdAt: "2026-06-01", tags: [copy("newClues2")] },
  { id: "C1011", name: copy("intelligentLinkSoftware"), company: copy("nanjingZhilianSoftwareTechnologyCoLtd"), contactName: copy("luJun"), phone: "153-4545-6767", email: "lu@zhilian.dev", level: "重要", status: "跟进中", owner: canonicalOwner("zhouMingyuan3"), industry: canonicalIndustry("internet2"), region: copy("nanjing"), amount: 420000, lastFollowAt: "2026-06-02", createdAt: "2025-10-20", tags: [copy("customDevelopment")] },
  { id: "C1012", name: copy("hailanAquaticProducts"), company: copy("qingdaoHailanAquaticProductsTradingCoLtd"), contactName: copy("yinHang"), phone: "155-5656-7878", email: "yin@hailan.com", level: "普通", status: "跟进中", owner: canonicalOwner("highSensitivity3"), industry: canonicalIndustry("trade"), region: copy("qingdao"), amount: 132000, lastFollowAt: "2026-05-27", createdAt: "2025-12-15", tags: [copy("export")] },
  { id: "C1013", name: copy("huameiHomeFurnishing"), company: copy("foshanHuameiHomeFurnishingManufacturingCoLtd"), contactName: copy("yuanMan"), phone: "156-6767-8989", email: "yuan@huamei.com", level: "普通", status: "已成交", owner: canonicalOwner("linWanqing3"), industry: canonicalIndustry("manufacturing3"), region: copy("foshan"), amount: 388000, lastFollowAt: "2026-05-20", createdAt: "2025-08-30", tags: [copy("furniture")] },
  { id: "C1014", name: copy("ruikangPharmaceutical"), company: copy("shijiazhuangRuikangPharmaceuticalCoLtd"), contactName: copy("houLiang"), phone: "158-7878-9090", email: "hou@ruikang.com", level: "重要", status: "跟进中", owner: canonicalOwner("chenCe3"), industry: canonicalIndustry("medical2"), region: copy("shijiazhuang"), amount: 610000, lastFollowAt: "2026-06-01", createdAt: "2025-09-02", tags: ["GMP"] },
  { id: "C1015", name: copy("travelSmoothly"), company: copy("wuhanChangxingTravelTechnologyCoLtd"), contactName: copy("whiteBirch"), phone: "159-8989-0101", email: "bai@changxing.io", level: "潜在", status: "待分配", owner: canonicalOwner("suXiao3"), industry: canonicalIndustry("internet3"), region: copy("wuhan"), amount: 0, lastFollowAt: "2026-05-30", createdAt: "2026-05-24", tags: [copy("travel")] },
  { id: "C1016", name: copy("goldenHarvestBank"), company: copy("jinsuiCityCommercialBank"), contactName: copy("logan"), phone: "186-0101-1212", email: "tang@jinsui.bank", level: "重要", status: "已成交", owner: canonicalOwner("zhouMingyuan4"), industry: canonicalIndustry("finance"), region: copy("zhengzhou"), amount: 3120000, lastFollowAt: "2026-05-15", createdAt: "2025-04-18", tags: [copy("bigCustomers4"), copy("finance2")] },
  { id: "C1017", name: copy("youmiECommerce"), company: copy("ningboYoumiECommerceCoLtd"), contactName: copy("fanLin"), phone: "187-1212-2323", email: "fan@youmi.shop", level: "普通", status: "跟进中", owner: canonicalOwner("highSensitivity4"), industry: canonicalIndustry("retail"), region: copy("ningbo"), amount: 152000, lastFollowAt: "2026-06-03", createdAt: "2026-01-05", tags: [copy("eCommerce")] },
  { id: "C1018", name: copy("tiangongMachinery"), company: copy("wuxiTiangongPrecisionMachineryCoLtd"), contactName: copy("duanFei"), phone: "188-2323-3434", email: "duan@tiangong.com", level: "普通", status: "已流失", owner: canonicalOwner("chenCe4"), industry: canonicalIndustry("manufacturing4"), region: copy("wuxi"), amount: 240000, lastFollowAt: "2026-02-26", createdAt: "2025-06-12", tags: [copy("loss2")] },
  { id: "C1019", name: copy("clearSkyTravel"), company: copy("xiamenClearSkyAviationTravelCoLtd"), contactName: copy("mengLu"), phone: "189-3434-4545", email: "meng@qingkong.travel", level: "普通", status: "跟进中", owner: canonicalOwner("linWanqing4"), industry: canonicalIndustry("travel2"), region: copy("xiamen"), amount: 88000, lastFollowAt: "2026-05-31", createdAt: "2026-03-09", tags: [copy("businessTrip")] },
  { id: "C1020", name: copy("guangyuanBuildingMaterials"), company: copy("changshaGuangyuanBuildingMaterialsCoLtd"), contactName: copy("leiZhen"), phone: "180-4545-5656", email: "lei@guangyuan.com", level: "潜在", status: "待分配", owner: canonicalOwner("suXiao4"), industry: canonicalIndustry("buildingMaterials"), region: copy("changsha"), amount: 0, lastFollowAt: "2026-06-02", createdAt: "2026-05-29", tags: [copy("newClues3")] },
  { id: "C1021", name: copy("hongtuPrinting"), company: copy("dongguanHongtuPackagingAndPrintingCoLtd"), contactName: copy("jiaLe"), phone: "181-5656-6767", email: "jia@hongtu.com", level: "普通", status: "跟进中", owner: canonicalOwner("zhouMingyuan5"), industry: canonicalIndustry("manufacturing5"), region: copy("dongguan"), amount: 116000, lastFollowAt: "2026-05-28", createdAt: "2025-11-22", tags: [copy("packaging")] },
  { id: "C1022", name: copy("ruisiConsulting"), company: copy("beijingRuisiEnterpriseManagementConsultingCoLtd"), contactName: copy("xueBing"), phone: "182-6767-7878", email: "xue@ruisi.com", level: "重要", status: "已成交", owner: canonicalOwner("chenCe5"), industry: canonicalIndustry("consultation"), region: copy("beijing2"), amount: 560000, lastFollowAt: "2026-05-23", createdAt: "2025-07-08", tags: [copy("consultation2")] },
  { id: "C1023", name: copy("jiaheFood"), company: copy("zhengzhouJiaheFoodCoLtd"), contactName: copy("evergreen"), phone: "183-7878-8989", email: "wan@jiahe.food", level: "普通", status: "跟进中", owner: canonicalOwner("highSensitivity5"), industry: canonicalIndustry("food"), region: copy("zhengzhou2"), amount: 204000, lastFollowAt: "2026-06-01", createdAt: "2025-10-11", tags: [copy("food2")] },
  { id: "C1024", name: copy("auroraNewEnergy"), company: copy("hefeiAuroraNewEnergyTechnologyCoLtd"), contactName: copy("jinpeng"), phone: "184-8989-9090", email: "jin@aurora.energy", level: "重要", status: "跟进中", owner: canonicalOwner("linWanqing5"), industry: canonicalIndustry("energy"), region: copy("hefei"), amount: 880000, lastFollowAt: "2026-06-03", createdAt: "2025-12-01", tags: [copy("newEnergy"), copy("highPotential2")] },
];

export function customerById(id: string): Customer | undefined {
  return customers.find((c) => c.id === id);
}
