import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "morningLightStationery": "晨光文具",
    "shanghaiChenguangStationeryCoLtd": "上海晨光文具股份有限公司",
    "chenChen": "陈晨",
    "linWanqing": "林晚晴",
    "manufacturing": "制造",
    "shanghai": "上海",
    "bigCustomers": "大客户",
    "renewContract": "续约",
    "yunqiTechnology": "云栖科技",
    "hangzhouYunqiNetworkTechnologyCoLtd": "杭州云栖网络科技有限公司",
    "guyu": "顾屿",
    "zhouMingyuan": "周明远",
    "internet": "互联网",
    "hangzhou": "杭州",
    "highPotential": "高潜",
    "baiweiCatering": "百味餐饮",
    "chengduBaiweiCateringManagementCoLtd": "成都百味餐饮管理有限公司",
    "luoMin": "罗敏",
    "highSensitivity": "高敏",
    "catering": "餐饮",
    "chengdu": "成都",
    "chain": "连锁",
    "hengkangMedical": "恒康医疗",
    "guangzhouHengkangMedicalEquipmentCoLtd": "广州恒康医疗器械有限公司",
    "dengWei": "邓伟",
    "chenCe": "陈策",
    "medical": "医疗",
    "guangzhou": "广州",
    "bigCustomers2": "大客户",
    "tender": "招标",
    "knowledgeAndActionEducation": "知行教育",
    "beijingZhixingOnlineEducationCoLtd": "北京知行在线教育有限公司",
    "xiaYu": "夏雨",
    "suXiao": "苏晓",
    "education": "教育",
    "beijing": "北京",
    "newClues": "新线索",
    "shundaLogistics": "顺达物流",
    "shenzhenShundaSupplyChainLogisticsCoLtd": "深圳顺达供应链物流有限公司",
    "maTao": "马涛",
    "linWanqing2": "林晚晴",
    "logistics": "物流",
    "shenzhen": "深圳",
    "supplyChain": "供应链",
    "jinxiuTextile": "锦绣纺织",
    "suzhouJinxiuTextileIndustrialCoLtd": "苏州锦绣纺织实业有限公司",
    "qianFang": "钱芳",
    "zhouMingyuan2": "周明远",
    "manufacturing2": "制造",
    "suzhou": "苏州",
    "loss": "流失",
    "priceSensitive": "价格敏感",
    "starMedia": "星辰传媒",
    "shanghaiStarCultureMediaCoLtd": "上海星辰文化传媒有限公司",
    "hanLei": "韩磊",
    "highSensitivity2": "高敏",
    "media": "传媒",
    "shanghai2": "上海",
    "content": "内容",
    "dingfengRealEstate": "鼎峰地产",
    "chongqingDingfengRealEstateDevelopmentCoLtd": "重庆鼎峰房地产开发有限公司",
    "caoYong": "曹勇",
    "chenCe2": "陈策",
    "realEstate": "地产",
    "chongqing": "重庆",
    "bigCustomers3": "大客户",
    "greenfieldAgriculture": "绿野农业",
    "shandongLuyeModernAgricultureCoLtd": "山东绿野现代农业有限公司",
    "kongXue": "孔雪",
    "suXiao2": "苏晓",
    "agriculture": "农业",
    "jinan": "济南",
    "newClues2": "新线索",
    "intelligentLinkSoftware": "智联软件",
    "nanjingZhilianSoftwareTechnologyCoLtd": "南京智联软件技术有限公司",
    "luJun": "卢俊",
    "zhouMingyuan3": "周明远",
    "internet2": "互联网",
    "nanjing": "南京",
    "customDevelopment": "定制开发",
    "hailanAquaticProducts": "海蓝水产",
    "qingdaoHailanAquaticProductsTradingCoLtd": "青岛海蓝水产贸易有限公司",
    "yinHang": "尹航",
    "highSensitivity3": "高敏",
    "trade": "贸易",
    "qingdao": "青岛",
    "export": "出口",
    "huameiHomeFurnishing": "华美家居",
    "foshanHuameiHomeFurnishingManufacturingCoLtd": "佛山华美家居制造有限公司",
    "yuanMan": "袁满",
    "linWanqing3": "林晚晴",
    "manufacturing3": "制造",
    "foshan": "佛山",
    "furniture": "家具",
    "ruikangPharmaceutical": "瑞康制药",
    "shijiazhuangRuikangPharmaceuticalCoLtd": "石家庄瑞康制药有限公司",
    "houLiang": "侯亮",
    "chenCe3": "陈策",
    "medical2": "医疗",
    "shijiazhuang": "石家庄",
    "travelSmoothly": "畅行出行",
    "wuhanChangxingTravelTechnologyCoLtd": "武汉畅行出行科技有限公司",
    "whiteBirch": "白桦",
    "suXiao3": "苏晓",
    "internet3": "互联网",
    "wuhan": "武汉",
    "travel": "出行",
    "goldenHarvestBank": "金穗银行",
    "jinsuiCityCommercialBank": "金穗城市商业银行",
    "logan": "唐婉",
    "zhouMingyuan4": "周明远",
    "finance": "金融",
    "zhengzhou": "郑州",
    "bigCustomers4": "大客户",
    "finance2": "金融",
    "youmiECommerce": "优米电商",
    "ningboYoumiECommerceCoLtd": "宁波优米电子商务有限公司",
    "fanLin": "范琳",
    "highSensitivity4": "高敏",
    "retail": "零售",
    "ningbo": "宁波",
    "eCommerce": "电商",
    "tiangongMachinery": "天工机械",
    "wuxiTiangongPrecisionMachineryCoLtd": "无锡天工精密机械有限公司",
    "duanFei": "段飞",
    "chenCe4": "陈策",
    "manufacturing4": "制造",
    "wuxi": "无锡",
    "loss2": "流失",
    "clearSkyTravel": "晴空航旅",
    "xiamenClearSkyAviationTravelCoLtd": "厦门晴空航空旅游有限公司",
    "mengLu": "孟璐",
    "linWanqing4": "林晚晴",
    "travel2": "旅游",
    "xiamen": "厦门",
    "businessTrip": "差旅",
    "guangyuanBuildingMaterials": "广源建材",
    "changshaGuangyuanBuildingMaterialsCoLtd": "长沙广源建筑材料有限公司",
    "leiZhen": "雷震",
    "suXiao4": "苏晓",
    "buildingMaterials": "建材",
    "changsha": "长沙",
    "newClues3": "新线索",
    "hongtuPrinting": "宏图印刷",
    "dongguanHongtuPackagingAndPrintingCoLtd": "东莞宏图包装印刷有限公司",
    "jiaLe": "贾乐",
    "zhouMingyuan5": "周明远",
    "manufacturing5": "制造",
    "dongguan": "东莞",
    "packaging": "包装",
    "ruisiConsulting": "睿思咨询",
    "beijingRuisiEnterpriseManagementConsultingCoLtd": "北京睿思企业管理咨询有限公司",
    "xueBing": "薛冰",
    "chenCe5": "陈策",
    "consultation": "咨询",
    "beijing2": "北京",
    "consultation2": "咨询",
    "jiaheFood": "嘉禾食品",
    "zhengzhouJiaheFoodCoLtd": "郑州嘉禾食品有限公司",
    "evergreen": "万青",
    "highSensitivity5": "高敏",
    "food": "食品",
    "zhengzhou2": "郑州",
    "food2": "食品",
    "auroraNewEnergy": "极光新能源",
    "hefeiAuroraNewEnergyTechnologyCoLtd": "合肥极光新能源科技有限公司",
    "jinpeng": "金鹏",
    "linWanqing5": "林晚晴",
    "energy": "能源",
    "hefei": "合肥",
    "newEnergy": "新能源",
    "highPotential2": "高潜",
  },
  en: {
    "morningLightStationery": "M&G Stationery",
    "shanghaiChenguangStationeryCoLtd": "Shanghai Chenguang Stationery Co., Ltd.",
    "chenChen": "Chen Chen",
    "linWanqing": "Lin Wanqing",
    "manufacturing": "Manufacturing",
    "shanghai": "Shanghai",
    "bigCustomers": "Key account",
    "renewContract": "Renew contract",
    "yunqiTechnology": "Yunqi Technology",
    "hangzhouYunqiNetworkTechnologyCoLtd": "Hangzhou Yunqi Network Technology Co., Ltd.",
    "guyu": "Guyu",
    "zhouMingyuan": "Zhou Mingyuan",
    "internet": "Internet",
    "hangzhou": "Hangzhou",
    "highPotential": "High potential",
    "baiweiCatering": "Baiwei Catering",
    "chengduBaiweiCateringManagementCoLtd": "Chengdu Baiwei Catering Management Co., Ltd.",
    "luoMin": "Luo Min",
    "highSensitivity": "Gao Min",
    "catering": "Catering",
    "chengdu": "Chengdu",
    "chain": "Chain",
    "hengkangMedical": "Hengkang Medical",
    "guangzhouHengkangMedicalEquipmentCoLtd": "Guangzhou Hengkang Medical Equipment Co., Ltd.",
    "dengWei": "Deng Wei",
    "chenCe": "Chen Ce",
    "medical": "Healthcare",
    "guangzhou": "Guangzhou",
    "bigCustomers2": "Key account",
    "tender": "Tender",
    "knowledgeAndActionEducation": "Knowledge and Action Education",
    "beijingZhixingOnlineEducationCoLtd": "Beijing Zhixing Online Education Co., Ltd.",
    "xiaYu": "Xia Yu",
    "suXiao": "Su Xiao",
    "education": "Education",
    "beijing": "Beijing",
    "newClues": "New lead",
    "shundaLogistics": "Shunda Logistics",
    "shenzhenShundaSupplyChainLogisticsCoLtd": "Shenzhen Shunda Supply Chain Logistics Co., Ltd.",
    "maTao": "Ma Tao",
    "linWanqing2": "Lin Wanqing",
    "logistics": "Logistics",
    "shenzhen": "Shenzhen",
    "supplyChain": "supply chain",
    "jinxiuTextile": "Jinxiu Textile",
    "suzhouJinxiuTextileIndustrialCoLtd": "Suzhou Jinxiu Textile Industrial Co., Ltd.",
    "qianFang": "Qian Fang",
    "zhouMingyuan2": "Zhou Mingyuan",
    "manufacturing2": "Manufacturing",
    "suzhou": "Suzhou",
    "loss": "Loss",
    "priceSensitive": "Price sensitive",
    "starMedia": "Star Media",
    "shanghaiStarCultureMediaCoLtd": "Shanghai Star Culture Media Co., Ltd.",
    "hanLei": "Han Lei",
    "highSensitivity2": "Gao Min",
    "media": "Media",
    "shanghai2": "Shanghai",
    "content": "content",
    "dingfengRealEstate": "Dingfeng Real Estate",
    "chongqingDingfengRealEstateDevelopmentCoLtd": "Chongqing Dingfeng Real Estate Development Co., Ltd.",
    "caoYong": "Cao Yong",
    "chenCe2": "Chen Ce",
    "realEstate": "Real estate",
    "chongqing": "Chongqing",
    "bigCustomers3": "Key account",
    "greenfieldAgriculture": "Greenfield Agriculture",
    "shandongLuyeModernAgricultureCoLtd": "Shandong Luye Modern Agriculture Co., Ltd.",
    "kongXue": "Kong Xue",
    "suXiao2": "Su Xiao",
    "agriculture": "Agriculture",
    "jinan": "Jinan",
    "newClues2": "New lead",
    "intelligentLinkSoftware": "Intelligent Link Software",
    "nanjingZhilianSoftwareTechnologyCoLtd": "Nanjing Zhilian Software Technology Co., Ltd.",
    "luJun": "Lu Jun",
    "zhouMingyuan3": "Zhou Mingyuan",
    "internet2": "Internet",
    "nanjing": "Nanjing",
    "customDevelopment": "Custom development",
    "hailanAquaticProducts": "Hailan Aquatic Products",
    "qingdaoHailanAquaticProductsTradingCoLtd": "Qingdao Hailan Aquatic Products Trading Co., Ltd.",
    "yinHang": "Yin Hang",
    "highSensitivity3": "Gao Min",
    "trade": "Trade",
    "qingdao": "Qingdao",
    "export": "export",
    "huameiHomeFurnishing": "Huamei Home Furnishing",
    "foshanHuameiHomeFurnishingManufacturingCoLtd": "Foshan Huamei Home Furnishing Manufacturing Co., Ltd.",
    "yuanMan": "Yuan Man",
    "linWanqing3": "Lin Wanqing",
    "manufacturing3": "Manufacturing",
    "foshan": "Foshan",
    "furniture": "furniture",
    "ruikangPharmaceutical": "Ruikang Pharmaceutical",
    "shijiazhuangRuikangPharmaceuticalCoLtd": "Shijiazhuang Ruikang Pharmaceutical Co., Ltd.",
    "houLiang": "Hou Liang",
    "chenCe3": "Chen Ce",
    "medical2": "Healthcare",
    "shijiazhuang": "Shijiazhuang",
    "travelSmoothly": "Travel smoothly",
    "wuhanChangxingTravelTechnologyCoLtd": "Wuhan Changxing Travel Technology Co., Ltd.",
    "whiteBirch": "Bai Hua",
    "suXiao3": "Su Xiao",
    "internet3": "Internet",
    "wuhan": "Wuhan",
    "travel": "Travel",
    "goldenHarvestBank": "Golden Harvest Bank",
    "jinsuiCityCommercialBank": "Jinsui City Commercial Bank",
    "logan": "Luo Gan",
    "zhouMingyuan4": "Zhou Mingyuan",
    "finance": "Finance",
    "zhengzhou": "Zhengzhou",
    "bigCustomers4": "Key account",
    "finance2": "Finance",
    "youmiECommerce": "Youmi e-commerce",
    "ningboYoumiECommerceCoLtd": "Ningbo Youmi E-Commerce Co., Ltd.",
    "fanLin": "Fan Lin",
    "highSensitivity4": "Gao Min",
    "retail": "Retail",
    "ningbo": "Ningbo",
    "eCommerce": "E-commerce",
    "tiangongMachinery": "Tiangong Machinery",
    "wuxiTiangongPrecisionMachineryCoLtd": "Wuxi Tiangong Precision Machinery Co., Ltd.",
    "duanFei": "Duan Fei",
    "chenCe4": "Chen Ce",
    "manufacturing4": "Manufacturing",
    "wuxi": "Wuxi",
    "loss2": "Loss",
    "clearSkyTravel": "Clear Sky Travel",
    "xiamenClearSkyAviationTravelCoLtd": "Xiamen Clear Sky Aviation Travel Co., Ltd.",
    "mengLu": "Meng Lu",
    "linWanqing4": "Lin Wanqing",
    "travel2": "Travel",
    "xiamen": "Xiamen",
    "businessTrip": "Business trip",
    "guangyuanBuildingMaterials": "Guangyuan Building Materials",
    "changshaGuangyuanBuildingMaterialsCoLtd": "Changsha Guangyuan Building Materials Co., Ltd.",
    "leiZhen": "Lei Zhen",
    "suXiao4": "Su Xiao",
    "buildingMaterials": "Building materials",
    "changsha": "Changsha",
    "newClues3": "New lead",
    "hongtuPrinting": "Hongtu printing",
    "dongguanHongtuPackagingAndPrintingCoLtd": "Dongguan Hongtu Packaging and Printing Co., Ltd.",
    "jiaLe": "Jia Le",
    "zhouMingyuan5": "Zhou Mingyuan",
    "manufacturing5": "Manufacturing",
    "dongguan": "Dongguan",
    "packaging": "packaging",
    "ruisiConsulting": "Ruisi Consulting",
    "beijingRuisiEnterpriseManagementConsultingCoLtd": "Beijing Ruisi Enterprise Management Consulting Co., Ltd.",
    "xueBing": "Xue Bing",
    "chenCe5": "Chen Ce",
    "consultation": "Consulting",
    "beijing2": "Beijing",
    "consultation2": "Consulting",
    "jiaheFood": "Jiahe Food",
    "zhengzhouJiaheFoodCoLtd": "Zhengzhou Jiahe Food Co., Ltd.",
    "evergreen": "Chang Qing",
    "highSensitivity5": "Gao Min",
    "food": "Food",
    "zhengzhou2": "Zhengzhou",
    "food2": "Food",
    "auroraNewEnergy": "Aurora New Energy",
    "hefeiAuroraNewEnergyTechnologyCoLtd": "Hefei Aurora New Energy Technology Co., Ltd.",
    "jinpeng": "Jin Peng",
    "linWanqing5": "Lin Wanqing",
    "energy": "Energy",
    "hefei": "Hefei",
    "newEnergy": "New energy",
    "highPotential2": "High potential",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-crm-data-customers",
  content: t(content),
};

export default dictionary;
