import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "chenguangStationeryErpRenewal": "晨光文具 2026 ERP 续约",
    "morningLightStationery": "晨光文具",
    "linWanqing": "林晚晴",
    "yunqiTechnologySaasSeatExpansion": "云栖科技 SaaS 席位扩容",
    "yunqiTechnology": "云栖科技",
    "zhouMingyuan": "周明远",
    "baiweiCateringStoreManagementSystem": "百味餐饮 门店管理系统",
    "baiweiCatering": "百味餐饮",
    "highSensitivity": "高敏",
    "hengkangMedicalBiddingAndProcurementProject": "恒康医疗 招标采购项目",
    "hengkangMedical": "恒康医疗",
    "chenCe": "陈策",
    "zhixingEducationOnlineCoursePlatform": "知行教育 在线课程平台",
    "knowledgeAndActionEducation": "知行教育",
    "suXiao": "苏晓",
    "shundaLogisticsTmsSchedulingUpgrade": "顺达物流 TMS 调度升级",
    "shundaLogistics": "顺达物流",
    "linWanqing2": "林晚晴",
    "zhilianSoftwareCustomDevelopmentOutsourcing": "智联软件 定制开发外包",
    "intelligentLinkSoftware": "智联软件",
    "zhouMingyuan2": "周明远",
    "hailanAquaticProductsExportDeclarationSystem": "海蓝水产 出口报关系统",
    "hailanAquaticProducts": "海蓝水产",
    "highSensitivity2": "高敏",
    "ruikangPharmaceuticalGmpQualityTraceability": "瑞康制药 GMP 质量追溯",
    "ruikangPharmaceutical": "瑞康制药",
    "chenCe2": "陈策",
    "jinsuiBankDataCenterPhaseIi": "金穗银行 数据中台二期",
    "goldenHarvestBank": "金穗银行",
    "zhouMingyuan3": "周明远",
    "youmiECommerceMarketingAutomation": "优米电商 营销自动化",
    "youmiECommerce": "优米电商",
    "highSensitivity3": "高敏",
    "tiangongMachineryMesProductionLineTransformation": "天工机械 MES 产线改造",
    "tiangongMachinery": "天工机械",
    "chenCe3": "陈策",
    "ruisiConsultingKnowledgeManagementPlatform": "睿思咨询 知识管理平台",
    "ruisiConsulting": "睿思咨询",
    "chenCe4": "陈策",
    "jiaheFoodTraceabilityMiniProgram": "嘉禾食品 溯源小程序",
    "jiaheFood": "嘉禾食品",
    "highSensitivity4": "高敏",
    "auroraNewEnergyChargingNetworkManagementPlatform": "极光新能源 充电网管平台",
    "auroraNewEnergy": "极光新能源",
    "linWanqing3": "林晚晴",
    "dingfengRealEstateSmartParkSolution": "鼎峰地产 智慧园区方案",
    "dingfengRealEstate": "鼎峰地产",
    "chenCe5": "陈策",
  },
  en: {
    "chenguangStationeryErpRenewal": "Chenguang Stationery 2026 ERP Renewal",
    "morningLightStationery": "M&G Stationery",
    "linWanqing": "Lin Wanqing",
    "yunqiTechnologySaasSeatExpansion": "Yunqi Technology SaaS seat expansion",
    "yunqiTechnology": "Yunqi Technology",
    "zhouMingyuan": "Zhou Mingyuan",
    "baiweiCateringStoreManagementSystem": "Baiwei Catering Store Management System",
    "baiweiCatering": "Baiwei Catering",
    "highSensitivity": "Gao Min",
    "hengkangMedicalBiddingAndProcurementProject": "Hengkang Medical Bidding and Procurement Project",
    "hengkangMedical": "Hengkang Medical",
    "chenCe": "Chen Ce",
    "zhixingEducationOnlineCoursePlatform": "Zhixing Education Online Course Platform",
    "knowledgeAndActionEducation": "Knowledge and Action Education",
    "suXiao": "Su Xiao",
    "shundaLogisticsTmsSchedulingUpgrade": "Shunda Logistics TMS Scheduling Upgrade",
    "shundaLogistics": "Shunda Logistics",
    "linWanqing2": "Lin Wanqing",
    "zhilianSoftwareCustomDevelopmentOutsourcing": "Zhilian Software Custom Development Outsourcing",
    "intelligentLinkSoftware": "Intelligent Link Software",
    "zhouMingyuan2": "Zhou Mingyuan",
    "hailanAquaticProductsExportDeclarationSystem": "Hailan Aquatic Products Export Declaration System",
    "hailanAquaticProducts": "Hailan Aquatic Products",
    "highSensitivity2": "Gao Min",
    "ruikangPharmaceuticalGmpQualityTraceability": "Ruikang Pharmaceutical GMP Quality Traceability",
    "ruikangPharmaceutical": "Ruikang Pharmaceutical",
    "chenCe2": "Chen Ce",
    "jinsuiBankDataCenterPhaseIi": "Jinsui Bank Data Center Phase II",
    "goldenHarvestBank": "Golden Harvest Bank",
    "zhouMingyuan3": "Zhou Mingyuan",
    "youmiECommerceMarketingAutomation": "Youmi e-commerce marketing automation",
    "youmiECommerce": "Youmi e-commerce",
    "highSensitivity3": "Gao Min",
    "tiangongMachineryMesProductionLineTransformation": "Tiangong Machinery MES production line transformation",
    "tiangongMachinery": "Tiangong Machinery",
    "chenCe3": "Chen Ce",
    "ruisiConsultingKnowledgeManagementPlatform": "Ruisi Consulting Knowledge Management Platform",
    "ruisiConsulting": "Ruisi Consulting",
    "chenCe4": "Chen Ce",
    "jiaheFoodTraceabilityMiniProgram": "Jiahe Food Traceability Mini Program",
    "jiaheFood": "Jiahe Food",
    "highSensitivity4": "Gao Min",
    "auroraNewEnergyChargingNetworkManagementPlatform": "Aurora New Energy Charging Network Management Platform",
    "auroraNewEnergy": "Aurora New Energy",
    "linWanqing3": "Lin Wanqing",
    "dingfengRealEstateSmartParkSolution": "Dingfeng Real Estate Smart Park Solution",
    "dingfengRealEstate": "Dingfeng Real Estate",
    "chenCe5": "Chen Ce",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-crm-data-opportunities",
  content: t(content),
};

export default dictionary;
