import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    liveBuildLogsAndDeploymentPreviewsWithAnIsolatedEnvironmentForEveryPullRequest: "实时构建日志与部署预览，每个 PR 自动生成独立环境",
    rollBackToAnyPreviousVersionInOneClickWithAnAverageRecoveryTimeUnder30Seconds: "一键回滚到任意历史版本，平均恢复时间 < 30 秒",
    metricsLogsAndTracesInOneViewSoInvestigationsStayInOneTool: "指标 / 日志 / 链路追踪同屏，问题定位不再跳工具",
    production: "生产",
    live: "已上线",
    text12SecondsAgo: "12 秒前",
    preview: "预览",
    building: "构建中",
    justNow: "刚刚",
    text3MinutesAgo: "3 分钟前",
    running: "运行中",
    requestsMin: "请求 / 分",
    p95Latency: "P95 延迟",
    errorRate: "错误率",
    recentDeployments: "最近部署",
    buildFailed: "构建失败",
    featCheckout12MinutesAgo: "feat/checkout · 12 分钟前",
    memoryThresholdExceeded: "内存超阈值",
    hancloudWebProdJustNow: "hancloud-web-prod · 刚刚",
    recovered: "已恢复",
    fullRollbackCompleted: "全量回滚完成",
    v231Deployed3MinutesAgo: "v2.3.1 已上线 · 3 分钟前",
    hancloudAlerts: "瀚云告警",
    text2Unread: "2 未读",
    connectedAllServicesOperational: "已连接 · 所有服务正常",
    deploymentsToday: "今日部署",
    successRate: "成功率",
    averageDuration: "平均耗时",
    console: "控制台",
    mainProduction: "main → 生产",
    featPayPreview: "feat/pay → 预览",
    fixTzPreview: "fix/tz → 预览",
    everythingInOneView: "一屏掌控",
    deployMonitorAndRollBackFromOneDashboard: "部署、监控、回滚，都在同一块面板",
    stopJumpingBetweenCiMonitoringAndLogPlatformsHancloudBringsTheEntireDeliveryPipelineIntoOneClear: "不必在 CI、监控、日志平台之间反复横跳。瀚云把交付链路收进一个清爽的控制台。",
    bookAOneOnOneDemo: "预约一对一演示",
    anywhereAnytime: "随时随地",
    receiveAlertsOnMobileAndTrackDeploymentStatusAnywhere: "移动端同步告警，随时掌控部署状态",
    alertsArriveDirectlyOnYourPhoneSoP0IncidentsAreImpossibleToMissNativeIosAndAndroidAppsKeepTheExp: "告警推送直达手机，P0 故障一触即知；iOS、Android 原生 App 体验一致，告别盯桌面。",
    tieredP0P1NotificationsWithImmediateDeliveryForCriticalAlerts: "P0/P1 分级推送，关键告警零延迟",
    rollBackFromYourPhoneInOneTapWithoutWaitingForAComputer: "一键回滚，手机直接操作不等 PC",
    setCustomQuietHoursSoNoncriticalAlertsDoNotInterruptYourNight: "告警静默时段自定义，夜间不被打扰",
    exploreMobileFeatures: "了解移动端功能",
  },
  en: {
    liveBuildLogsAndDeploymentPreviewsWithAnIsolatedEnvironmentForEveryPullRequest: "Live build logs and deployment previews, with an isolated environment for every pull request",
    rollBackToAnyPreviousVersionInOneClickWithAnAverageRecoveryTimeUnder30Seconds: "Roll back to any previous version in one click, with an average recovery time under 30 seconds",
    metricsLogsAndTracesInOneViewSoInvestigationsStayInOneTool: "Metrics, logs, and traces in one view, so investigations stay in one tool",
    production: "Production",
    live: "Live",
    text12SecondsAgo: "12 seconds ago",
    preview: "Preview",
    building: "Building",
    justNow: "just now",
    text3MinutesAgo: "3 minutes ago",
    running: "Running",
    requestsMin: "Requests / min",
    p95Latency: "P95 latency",
    errorRate: "Error rate",
    recentDeployments: "Recent deployments",
    buildFailed: "Build failed",
    featCheckout12MinutesAgo: "feat/checkout · 12 minutes ago",
    memoryThresholdExceeded: "Memory threshold exceeded",
    hancloudWebProdJustNow: "hancloud-web-prod · Just now",
    recovered: "Recovered",
    fullRollbackCompleted: "Full rollback completed",
    v231Deployed3MinutesAgo: "v2.3.1 deployed · 3 minutes ago",
    hancloudAlerts: "HanCloud alerts",
    text2Unread: "2 unread",
    connectedAllServicesOperational: "Connected · All services operational",
    deploymentsToday: "Deployments today",
    successRate: "Success rate",
    averageDuration: "Average duration",
    console: "Console",
    mainProduction: "main → Production",
    featPayPreview: "feat/pay → Preview",
    fixTzPreview: "fix/tz → Preview",
    everythingInOneView: "Everything in one view",
    deployMonitorAndRollBackFromOneDashboard: "Deploy, monitor, and roll back from one dashboard",
    stopJumpingBetweenCiMonitoringAndLogPlatformsHancloudBringsTheEntireDeliveryPipelineIntoOneClear: "Stop jumping between CI, monitoring, and log platforms. HanCloud brings the entire delivery pipeline into one clear console.",
    bookAOneOnOneDemo: "Book a one-on-one demo",
    anywhereAnytime: "Anywhere, anytime",
    receiveAlertsOnMobileAndTrackDeploymentStatusAnywhere: "Receive alerts on mobile and track deployment status anywhere",
    alertsArriveDirectlyOnYourPhoneSoP0IncidentsAreImpossibleToMissNativeIosAndAndroidAppsKeepTheExp: "Alerts arrive directly on your phone, so P0 incidents are impossible to miss. Native iOS and Android apps keep the experience consistent without tying you to a desktop.",
    tieredP0P1NotificationsWithImmediateDeliveryForCriticalAlerts: "Tiered P0/P1 notifications with immediate delivery for critical alerts",
    rollBackFromYourPhoneInOneTapWithoutWaitingForAComputer: "Roll back from your phone in one tap, without waiting for a computer",
    setCustomQuietHoursSoNoncriticalAlertsDoNotInterruptYourNight: "Set custom quiet hours so noncritical alerts do not interrupt your night",
    exploreMobileFeatures: "Explore mobile features",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>(
    (text, value, index) => text.replaceAll(`{${index}}`, String(value)),
    content[DOCS_LOCALE][key],
  );
}

const dictionary: Dictionary = {
  key: "demo-website-components-sections-product",
  content: t(content),
};

export default dictionary;
