import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "openapiTaskSubmission": "OpenAPI 任务提交",
    "postV1TasksDirectConnectionToInternal": "POST /v1/tasks · 内部业务系统直连",
    "online": "在线",
    "wecomApprovalFlow": "企业微信审批流",
    "approvalIsGrantedAndTheTaskIs": "审批通过自动建任务",
    "online2": "在线",
    "scheduledBatchScheduling": "定时批处理调度",
    "batchOnboardingForOfflineTasksAtDaily": "每日 02:00 离线任务批量入队",
    "downgrade": "降级",
    "kafkaEventBus": "Kafka 事件总线",
    "topicAiTasksDelayedConsumptionAlert": "topic: ai-tasks · 消费滞后告警",
    "offline": "离线",
    "settingsSaved": "设置已保存",
    "globalSchedulingStrategyAndNotificationConfigurationHave": "全局调度策略与通知配置已生效（mock）。",
    "setup": "设置",
    "taskAccessTeamMembersGlobalSchedulingStrategy": "任务接入 · 团队成员 · 全局调度策略 · 告警通知",
    "saveTheSettings": "保存设置",
    "taskSourceAccessIsProvided": "任务来源接入",
    "connectsTheExternalSystemSWebhookCredentials": "对接外部系统的 Webhook 凭证与已接来源",
    "accessKeyToken": "接入密钥 Token",
    "carryThisKeyWhenExternalSystemsCall": "外部系统调用任务提交 API 时携带此密钥；泄露请立即吊销重置。",
    "theAccessKeyHasBeenCopied": "已复制接入密钥",
    "theKeyHasBeenRegenerated": "已重新生成密钥",
    "theOldKeyImmediatelyBecameInvalid": "旧密钥即刻失效。",
    "reset": "重置",
    "sourceReceived": "已接来源",
    "teamMembers": "团队成员",
    "schedulingPlatformCollaborationMembersAndRolePermissions": "调度平台协作成员与角色权限",
    "online3": "在线",
    "offline2": "离线",
    "memberId": "成员 ID ·",
    "globalSchedulingStrategy": "全局调度策略",
    "taskDefaultValuesAndDegradationBehaviorUpon": "任务默认值与失败时的降级行为",
    "defaultPriority": "默认优先级",
    "tasksWithoutExplicitPriorityAreGivenThis": "未显式指定优先级的任务采用此默认值。",
    "globalCostCapYuanTask": "全局成本上限（元 / 任务）",
    "ifTheCumulativeCostOfASingle": "单任务累计成本超过上限即触发降级 / 暂停。",
    "globalCostCap": "全局成本上限",
    "defaultDowngradeStrategy": "默认降级策略",
    "catchAllActionWhenActuatorFailsIs": "执行器失败 / 超载 / 超预算时的兜底动作。",
    "defaultDowngradeStrategy2": "默认降级策略",
    "downgradedToACheaperModel": "降级到便宜模型",
    "switchToLowCostActuatorsByDowngrade": "按降级链切换至低成本执行器，保完成不保质量。",
    "retryTheOriginalActuator": "原执行器重试",
    "indexRetreatRetriesTheCurrentActuatorUp": "指数退避重试当前执行器，最多 3 次后转人工。",
    "pauseAndAlert": "暂停并告警",
    "tasksAreSuspendedAndNotifiedOnDuty": "挂起任务并通知值班，等待人工介入决策。",
    "alertNotification": "告警通知",
    "alertReachChannelsAndTimingOfNotifications": "告警触达渠道与通知时机",
    "alertChannels": "告警渠道",
    "reachChannelsForSlaBreachesFailureRates": "SLA 违约 / 失败率 / 队列积压 / 成本超预算时的触达渠道（可多选）。",
    "alertChannels2": "告警渠道",
    "wechatWork": "企业微信",
    "dutyGroupRobotPushes": "值班群机器人推送",
    "sms": "短信",
    "p0CriticalIsASafetyNet": "P0 critical 兜底",
    "email": "邮件",
    "dailyWeeklyReportSummary": "日报 / 周报汇总",
    "integrationWithPagerdutyFeishu": "对接 PagerDuty / 飞书",
    "notifyTheTiming": "通知时机",
    "notificationIsSentImmediatelyWhenAnAlarm": "告警触发即通知",
    "notificationIsSentImmediatelyWhenAnAlarm2": "告警触发即通知",
    "realTimePushNotificationsAtTheInstant": "规则命中阈值的瞬间实时推送。",
    "alertAndRestorationNotification": "告警恢复通知",
    "alertAndRestorationNotification2": "告警恢复通知",
    "whenTheIndicatorFallsBackToThe": "指标回落至阈值内时推送恢复消息。",
    "dailySummarySummary": "每日汇总摘要",
    "dailySummarySummary2": "每日汇总摘要",
    "dailySummaryOfYesterdaySSlaCosts": "每日 09:00 汇总昨日 SLA / 成本 / 失败概览。",
  },
  en: {
    "openapiTaskSubmission": "Submit tasks through the OpenAPI",
    "postV1TasksDirectConnectionToInternal": "POST /v1/tasks · Direct connection to internal business systems",
    "online": "Online",
    "wecomApprovalFlow": "WeCom approval flow",
    "approvalIsGrantedAndTheTaskIs": "Approval is granted, and the task is automatically created",
    "online2": "Online",
    "scheduledBatchScheduling": "Scheduled batch scheduling",
    "batchOnboardingForOfflineTasksAtDaily": "Batch onboarding for offline tasks at 02:00 daily",
    "downgrade": "Downgrade",
    "kafkaEventBus": "Kafka event bus",
    "topicAiTasksDelayedConsumptionAlert": "topic: ai-tasks · Delayed consumption alert",
    "offline": "Offline",
    "settingsSaved": "Settings saved",
    "globalSchedulingStrategyAndNotificationConfigurationHave": "Global scheduling strategy and notification configuration have been implemented (mock).",
    "setup": "Setup",
    "taskAccessTeamMembersGlobalSchedulingStrategy": "Task Access · Team Members · Global Scheduling Strategy · Alarm Notifications",
    "saveTheSettings": "Save the settings",
    "taskSourceAccessIsProvided": "Task source access is provided",
    "connectsTheExternalSystemSWebhookCredentials": "Connects the external system's Webhook credentials with the source of the connection",
    "accessKeyToken": "Access key token",
    "carryThisKeyWhenExternalSystemsCall": "Carry this key when external systems call task subtask APIs; If leaked, revoke and reset immediately.",
    "theAccessKeyHasBeenCopied": "The access key has been copied",
    "theKeyHasBeenRegenerated": "The key has been regenerated",
    "theOldKeyImmediatelyBecameInvalid": "The old key immediately became invalid.",
    "reset": "Reset",
    "sourceReceived": "Source received",
    "teamMembers": "Team members",
    "schedulingPlatformCollaborationMembersAndRolePermissions": "Manage collaborators and role permissions for the orchestration platform",
    "online3": "Online",
    "offline2": "Offline",
    "memberId": "Member ID ·",
    "globalSchedulingStrategy": "Global scheduling strategy",
    "taskDefaultValuesAndDegradationBehaviorUpon": "Task default values and degradation behavior upon failure",
    "defaultPriority": "Default priority",
    "tasksWithoutExplicitPriorityAreGivenThis": "Tasks without explicit priority are given this default value.",
    "globalCostCapYuanTask": "Global cost cap (yuan / task)",
    "ifTheCumulativeCostOfASingle": "If the cumulative cost of a single task exceeds the limit, a downgrade/pause will be triggered.",
    "globalCostCap": "Global cost cap",
    "defaultDowngradeStrategy": "Default downgrade strategy",
    "catchAllActionWhenActuatorFailsIs": "Catch-all action when executor fails, is overloaded, or exceeds budget.",
    "defaultDowngradeStrategy2": "Default downgrade strategy",
    "downgradedToACheaperModel": "Downgraded to a cheaper model",
    "switchToLowCostActuatorsByDowngrade": "Switch to low-cost executors by downgrade chain, ensuring completion but not quality.",
    "retryTheOriginalActuator": "Retry the original executor",
    "indexRetreatRetriesTheCurrentActuatorUp": "Retry the current executor with exponential backoff up to three times, then require manual handling.",
    "pauseAndAlert": "Pause and alert",
    "tasksAreSuspendedAndNotifiedOnDuty": "Tasks are suspended and notified on duty, waiting for human intervention to make decisions.",
    "alertNotification": "Alert notification",
    "alertReachChannelsAndTimingOfNotifications": "Alert reach channels and timing of notifications",
    "alertChannels": "Alert channels",
    "reachChannelsForSlaBreachesFailureRates": "Reach channels for SLA breaches / failure rates / queue backlog / cost exceeding budget (multiple options allowed).",
    "alertChannels2": "Alert channels",
    "wechatWork": "WeChat Work",
    "dutyGroupRobotPushes": "Duty group robot pushes",
    "sms": "SMS",
    "p0CriticalIsASafetyNet": "P0 critical is a safety net",
    "email": "Email",
    "dailyWeeklyReportSummary": "Daily / Weekly Report Summary",
    "integrationWithPagerdutyFeishu": "Integration with PagerDuty / Feishu",
    "notifyTheTiming": "Notify the timing",
    "notificationIsSentImmediatelyWhenAnAlarm": "Notification is sent immediately when an alarm is triggered",
    "notificationIsSentImmediatelyWhenAnAlarm2": "Notification is sent immediately when an alarm is triggered",
    "realTimePushNotificationsAtTheInstant": "Real-time push notifications at the instant of rule hit thresholds.",
    "alertAndRestorationNotification": "Alert and Restoration Notification",
    "alertAndRestorationNotification2": "Alert and Restoration Notification",
    "whenTheIndicatorFallsBackToThe": "When the indicator falls back to the threshold, a recovery message is pushed.",
    "dailySummarySummary": "Daily summary summary",
    "dailySummarySummary2": "Daily summary summary",
    "dailySummaryOfYesterdaySSlaCosts": "Daily 09:00 Summary of yesterday's SLA / Costs / Failures.",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanhelm-app-settings-page",
  content: t(content),
};

export default dictionary;
