import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "fixWwwMocksAiChatDeploymentStation": "fix(www,mocks): ai-chat 部署站无响应——加 prod 客户端内存回退",
    "hulian": "瑚琏",
    "coral": "瑚",
    "featUiGitcommitDeploystatusComponent": "feat(ui): GitCommit + DeployStatus 组件",
    "hulian2": "瑚琏",
    "coral2": "瑚",
    "featWwwAddTheLoadingTsxSkeleton": "feat(www): 组件页加 loading.tsx 骨架，切组件时右侧即时反馈",
    "hulian3": "瑚琏",
    "coral3": "瑚",
    "featWwwGlobalRoutingProgressBarFix": "feat(www): 全局路由进度条，修复 App Router 导航零反馈",
    "hulian4": "瑚琏",
    "coral4": "瑚",
    "fixBlocksBlockGalleryThumbnailOutOf": "fix(blocks): 区块画廊缩略图越界",
    "linyu": "林屿",
    "forest": "林",
    "docsReadmeAddReleaseMaintainerChapterUpdate": "docs(readme): 加「发版（维护者）」章节 + 更新当前版本/文档站链接",
    "hulian5": "瑚琏",
    "coral5": "瑚",
    "choreReleaseHulianuiUiHulianuiTokensHair": "chore(release): @hulianui/ui@0.1.2 + @hulianui/tokens@0.1.1（发丝边框）",
    "hulian6": "瑚琏",
    "coral6": "瑚",
    "linyu2": "林屿",
    "forest2": "林",
    "featCartCouponOverlayRulesSettlementPage": "feat(cart): 优惠券叠加规则 + 结算页地址级联",
    "zhouLan": "周岚",
    "week": "周",
    "featPdpSkuGalleryMagnifyingGlass": "feat(pdp): SKU 图廊放大镜",
    "zhouLan2": "周岚",
    "week2": "周",
    "fixCheckoutTheOrderButtonIsNot": "fix(checkout): 库存为 0 时下单按钮未禁用",
    "zhouLan3": "周岚",
    "week3": "周",
    "perfListLazyLoadingOfTheFirst": "perf(list): 商品列表首屏图片懒加载",
    "zhouLan4": "周岚",
    "week4": "周",
    "contentUpdatedPricingPageAddedCustomerTestimonials": "content: 更新定价页 + 新增客户证言",
    "chenMo": "陈默",
    "chen": "陈",
    "featHeroNewFirstScreenBentoLayout": "feat(hero): 新首屏 Bento 布局",
    "chenMo2": "陈默",
    "chen2": "陈",
    "fixSeoSitemapMissingSubpages": "fix(seo): sitemap 缺失子页面",
    "chenMo3": "陈默",
    "chen3": "陈",
    "featKeysKeyGroupingLimitOneTime": "feat(keys): 密钥分组限额 + 一次性展示",
    "hulian7": "瑚琏",
    "coral7": "瑚",
    "featHealthChannelSpeedTestCircuitBreaker": "feat(health): 渠道测速 + 熔断转移",
    "hulian8": "瑚琏",
    "coral8": "瑚",
    "choreFixEslintWarning": "chore: 修 eslint 告警",
    "linyu3": "林屿",
    "forest3": "林",
    "initStaticHostingOfEdgeGateway": "init: 边缘网关静态托管",
    "hulian9": "瑚琏",
    "coral9": "瑚",
    "featEdgeCachingStrategy": "feat: 边缘缓存策略",
    "hulian10": "瑚琏",
    "coral10": "瑚",
    "cloneRepository": "克隆仓库",
    "installDependenciesPnpmInstall": "安装依赖（pnpm install）",
    "buildNextBuild": "构建（next build）",
    "uploadProductsToEdgeNetwork": "上传产物到边缘网络",
    "assignDomainNameTakeEffect": "分配域名 / 生效",
    "cloneHulianuiHulianBranchMasterCommitB9": "正在克隆 hulianui/hulian (分支 master, commit 10577b9)…",
    "warehouseCloningCompleted": "✓ 仓库克隆完成",
    "framePresetDetectedNextJsOutputExport": "检测到框架预设：Next.js（output: export）",
    "lockfileHitReuseCacheDependsOnPackages": "Lockfile 命中，复用缓存依赖 1284 个包",
    "dependencyInstallationCompletedS": "✓ 依赖安装完成 (46.2s)",
    "unoptimizedImgSDetectedExpectedBehaviorIn": "⚠ 检测到 2 个 unoptimized <img>（export 模式预期行为）",
    "constructionCompletedStaticPagesExported": "✓ 构建完成：导出 218 个静态页面",
    "uploadProductToEdgeNetworkFilesMb": "上传产物到边缘网络（142 个文件，6.8 MB）…",
    "uploadCompletedAndDistributedToEdgeNodes": "✓ 上传完成，已分发到 310 个边缘节点",
    "readyToDeployHttpsHulianuiHaloritualCom": "✓ 部署就绪 → https://hulianui.haloritual.com",
  },
  en: {
    "fixWwwMocksAiChatDeploymentStation": "fix(www,mocks): ai-chat deployment station is unresponsive - add prod client memory fallback",
    "hulian": "Hulian",
    "coral": "coral",
    "featUiGitcommitDeploystatusComponent": "feat(ui): GitCommit + DeployStatus component",
    "hulian2": "Hulian",
    "coral2": "coral",
    "featWwwAddTheLoadingTsxSkeleton": "feat(www): Add the loading.tsx skeleton to the component page, and provide instant feedback on the right side when cutting components",
    "hulian3": "Hulian",
    "coral3": "coral",
    "featWwwGlobalRoutingProgressBarFix": "feat(www): Global routing progress bar, fix App Router navigation zero feedback",
    "hulian4": "Hulian",
    "coral4": "coral",
    "fixBlocksBlockGalleryThumbnailOutOf": "fix(blocks): Block gallery thumbnail out of bounds",
    "linyu": "Linyu",
    "forest": "forest",
    "docsReadmeAddReleaseMaintainerChapterUpdate": "docs(readme): Add \"Release (Maintainer)\" chapter + update current version/documentation site link",
    "hulian5": "Hulian",
    "coral5": "coral",
    "choreReleaseHulianuiUiHulianuiTokensHair": "chore(release): @hulianui/ui@0.1.2 + @hulianui/tokens@0.1.1 (hair border)",
    "hulian6": "Hulian",
    "coral6": "coral",
    "linyu2": "Linyu",
    "forest2": "forest",
    "featCartCouponOverlayRulesSettlementPage": "feat(cart): Coupon overlay rules + settlement page address cascade",
    "zhouLan": "Zhou Lan",
    "week": "week",
    "featPdpSkuGalleryMagnifyingGlass": "feat(pdp): SKU gallery magnifying glass",
    "zhouLan2": "Zhou Lan",
    "week2": "week",
    "fixCheckoutTheOrderButtonIsNot": "fix(checkout): The order button is not disabled when the inventory is 0",
    "zhouLan3": "Zhou Lan",
    "week3": "week",
    "perfListLazyLoadingOfTheFirst": "perf(list): lazy loading of the first screen image of the product list",
    "zhouLan4": "Zhou Lan",
    "week4": "week",
    "contentUpdatedPricingPageAddedCustomerTestimonials": "content: Updated pricing page + added customer testimonials",
    "chenMo": "Chen Mo",
    "chen": "Chen",
    "featHeroNewFirstScreenBentoLayout": "feat(hero): New first screen Bento layout",
    "chenMo2": "Chen Mo",
    "chen2": "Chen",
    "fixSeoSitemapMissingSubpages": "fix(seo): sitemap missing subpages",
    "chenMo3": "Chen Mo",
    "chen3": "Chen",
    "featKeysKeyGroupingLimitOneTime": "feat(keys): key grouping limit + one-time display",
    "hulian7": "Hulian",
    "coral7": "coral",
    "featHealthChannelSpeedTestCircuitBreaker": "feat(health): channel speed test + circuit breaker transfer",
    "hulian8": "Hulian",
    "coral8": "coral",
    "choreFixEslintWarning": "chore: fix eslint warning",
    "linyu3": "Linyu",
    "forest3": "forest",
    "initStaticHostingOfEdgeGateway": "init: static hosting of edge gateway",
    "hulian9": "Hulian",
    "coral9": "coral",
    "featEdgeCachingStrategy": "feat: edge caching strategy",
    "hulian10": "Hulian",
    "coral10": "coral",
    "cloneRepository": "Clone repository",
    "installDependenciesPnpmInstall": "Install dependencies (pnpm install)",
    "buildNextBuild": "build(next build)",
    "uploadProductsToEdgeNetwork": "Upload products to edge network",
    "assignDomainNameTakeEffect": "Assign domain name / take effect",
    "cloneHulianuiHulianBranchMasterCommitB9": "Clone hulianui/hulian (branch master, commit 10577b9)...",
    "warehouseCloningCompleted": "✓ Repository cloning completed",
    "framePresetDetectedNextJsOutputExport": "Frame preset detected: Next.js (output: export)",
    "lockfileHitReuseCacheDependsOnPackages": "Lockfile hit, reuse cache depends on 1284 packages",
    "dependencyInstallationCompletedS": "✓ Dependency installation completed (46.2s)",
    "unoptimizedImgSDetectedExpectedBehaviorIn": "⚠ 2 unoptimized <img>s detected (expected behavior in export mode)",
    "constructionCompletedStaticPagesExported": "✓ Construction completed: 218 static pages exported",
    "uploadProductToEdgeNetworkFilesMb": "Upload product to edge network (142 files, 6.8 MB)...",
    "uploadCompletedAndDistributedToEdgeNodes": "✓ Upload completed and distributed to 310 edge nodes",
    "readyToDeployHttpsHulianuiHaloritualCom": "✓ Ready to deploy → https://hulianui.haloritual.com",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanship-data-store",
  content: t(content),
};

export default dictionary;
