import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "mainDomain": "主域",
    "redirect": "重定向",
    "preview": "预览",
    "issued": "已签发",
    "issuing": "签发中",
    "failed": "失败",
    "alreadyEffective": "已生效",
    "toBeEffective": "待生效",
    "configurationError": "配置错误",
    "pleaseEnterDomainName": "请输入域名",
    "pleaseSelectAnItem": "请选择项目",
    "pleaseSelectType": "请选择类型",
    "verificationInitiated": "已发起验证",
    "recheckingDnsRecordsForValue": "正在重新检查 {0} 的 DNS 记录",
    "domainNameHasBeenDeleted": "域名已删除",
    "domainName": "域名",
    "project": "项目",
    "sslCertificate": "SSL 证书",
    "add": "添加",
    "operation": "操作",
    "verifyValue": "验证 {0}",
    "verify": "验证",
    "recheckDnsAndCertificates": "重新检查 DNS 与证书",
    "deleteThisDomainName": "删除该域名？",
    "valueWillNoLongerPointToThis": "{0} 将不再指向本项目。",
    "delete": "删除",
    "cancel": "取消",
    "delete2": "删除",
    "domainName2": "域名",
    "manageCustomDomainNamesSslCertificatesAnd": "管理自定义域名、SSL 证书与 DNS 解析。",
    "addDomainName": "添加域名",
    "dnsForValueDomainsIsNotConfigured": "{0} 个域名 DNS 未正确配置",
    "pleaseClickDnsRecordsToBeConfigured": "请按下方「待配置 DNS 记录」添加 CNAME 记录后点击「验证」。",
    "allDomainNames": "全部域名",
    "noCustomDomainNameYet": "还没有自定义域名",
    "addADomainNameAutomaticallyIssueAn": "添加一个域名，自动签发 SSL 证书并接入边缘网络。",
    "addDomainName2": "添加域名",
    "dnsRecordsToBeConfigured": "待配置 DNS 记录",
    "type": "类型",
    "name": "名称",
    "value": "值",
    "addDomainName3": "添加域名",
    "add2": "添加",
    "theDomainNameHasBeenAddedAnd": "域名已添加，正在签发证书",
    "domainName3": "域名",
    "forExampleAppExampleCom": "例如 app.example.com",
    "project2": "项目",
    "type2": "类型",
  },
  en: {
    "mainDomain": "main domain",
    "redirect": "Redirect",
    "preview": "Preview",
    "issued": "issued",
    "issuing": "Issuing",
    "failed": "failed",
    "alreadyEffective": "Already effective",
    "toBeEffective": "To be effective",
    "configurationError": "Configuration error",
    "pleaseEnterDomainName": "Please enter domain name",
    "pleaseSelectAnItem": "Please select an item",
    "pleaseSelectType": "Please select type",
    "verificationInitiated": "Verification initiated",
    "recheckingDnsRecordsForValue": "Rechecking DNS records for {0}",
    "domainNameHasBeenDeleted": "Domain name has been deleted",
    "domainName": "domain name",
    "project": "Project",
    "sslCertificate": "SSL certificate",
    "add": "add",
    "operation": "Operation",
    "verifyValue": "Verify {0}",
    "verify": "Verify",
    "recheckDnsAndCertificates": "Recheck DNS and certificates",
    "deleteThisDomainName": "Delete this domain name?",
    "valueWillNoLongerPointToThis": "{0} will no longer point to this project.",
    "delete": "Delete",
    "cancel": "Cancel",
    "delete2": "Delete",
    "domainName2": "domain name",
    "manageCustomDomainNamesSslCertificatesAnd": "Manage custom domain names, SSL certificates, and DNS resolution.",
    "addDomainName": "Add domain name",
    "dnsForValueDomainsIsNotConfigured": "DNS for {0} domains is not configured correctly",
    "pleaseClickDnsRecordsToBeConfigured": "Please click \"DNS records to be configured\" below to add CNAME records and click \"Verify\".",
    "allDomainNames": "All domain names",
    "noCustomDomainNameYet": "No custom domain name yet",
    "addADomainNameAutomaticallyIssueAn": "Add a domain name, automatically issue an SSL certificate and connect to the edge network.",
    "addDomainName2": "Add domain name",
    "dnsRecordsToBeConfigured": "DNS records to be configured",
    "type": "Type",
    "name": "Name",
    "value": "value",
    "addDomainName3": "Add domain name",
    "add2": "add",
    "theDomainNameHasBeenAddedAnd": "The domain name has been added and the certificate is being issued",
    "domainName3": "domain name",
    "forExampleAppExampleCom": "For example app.example.com",
    "project2": "Project",
    "type2": "Type",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanship-app-domains-page",
  content: t(content),
};

export default dictionary;
