import { copy } from "./channels.content";
import type { Channel, ProbeRecord } from "./types";

export const channels: Channel[] = [
  {
    id: "c-openai-1",
    name: copy("openaiOfficialMain"),
    provider: "openai",
    health: "online",
    latencyMs: 86,
    successRate: 0.998,
    trend: [1, 1, 0.99, 1, 1, 1, 0.98, 1, 1, 1, 0.99, 1],
    weight: 70,
    priority: 1,
    rpmHeadroom: 0.62,
    models: ["gpt-5.5", "gpt-5.4", "gpt-5-mini"],
    lastProbe: copy("secondsAgo"),
  },
  {
    id: "c-openai-2",
    name: copy("openaiAgentPrepared"),
    provider: "openai",
    health: "degraded",
    latencyMs: 412,
    successRate: 0.94,
    trend: [1, 0.98, 0.95, 0.9, 0.93, 0.96, 0.92, 0.88, 0.95, 0.94, 0.93, 0.94],
    weight: 30,
    priority: 2,
    rpmHeadroom: 0.81,
    models: ["gpt-5.4", "gpt-5-mini"],
    lastProbe: copy("secondsAgo2"),
  },
  {
    id: "c-anthropic-1",
    name: copy("anthropicOfficial"),
    provider: "anthropic",
    health: "online",
    latencyMs: 124,
    successRate: 0.996,
    trend: [1, 1, 1, 0.99, 1, 1, 1, 0.99, 1, 1, 1, 1],
    weight: 100,
    priority: 1,
    rpmHeadroom: 0.74,
    models: ["claude-opus-4-7", "claude-sonnet-4-6", "claude-haiku-4-5"],
    lastProbe: copy("secondsAgo3"),
  },
  {
    id: "c-google-1",
    name: "Google Vertex",
    provider: "google",
    health: "online",
    latencyMs: 152,
    successRate: 0.992,
    trend: [1, 0.99, 1, 1, 0.98, 1, 1, 1, 0.99, 1, 1, 0.99],
    weight: 100,
    priority: 1,
    rpmHeadroom: 0.88,
    models: ["gemini-3-pro", "gemini-3-flash"],
    lastProbe: copy("secondsAgo4"),
  },
  {
    id: "c-deepseek-1",
    name: copy("deepseekOfficial"),
    provider: "deepseek",
    health: "online",
    latencyMs: 98,
    successRate: 0.997,
    trend: [1, 1, 1, 1, 0.99, 1, 1, 1, 1, 0.99, 1, 1],
    weight: 100,
    priority: 1,
    rpmHeadroom: 0.91,
    models: ["deepseek-v4"],
    lastProbe: copy("secondsAgo5"),
  },
  {
    id: "c-alibaba-1",
    name: copy("aliBailian"),
    provider: "alibaba",
    health: "maintenance",
    latencyMs: 0,
    successRate: 0,
    trend: [1, 1, 0.99, 1, 0.5, 0, 0, 0, 0, 0, 0, 0],
    weight: 0,
    priority: 3,
    rpmHeadroom: 1,
    models: ["qwen3-max", "mimo-flash"],
    lastProbe: copy("underMaintenance"),
  },
  {
    id: "c-moonshot-1",
    name: copy("darkSideOfTheMoon"),
    provider: "moonshot",
    health: "offline",
    latencyMs: 0,
    successRate: 0,
    trend: [1, 0.9, 0.7, 0.4, 0.2, 0.1, 0, 0, 0, 0, 0, 0],
    weight: 0,
    priority: 2,
    rpmHeadroom: 1,
    models: ["kimi-k2"],
    lastProbe: copy("minutesAgo"),
  },
];

export const probeHistory: ProbeRecord[] = [
  { time: "10:42:08", channel: copy("openaiOfficialMain2"), ok: true, latencyMs: 86, note: "200 OK" },
  { time: "10:42:05", channel: copy("anthropicOfficial2"), ok: true, latencyMs: 124, note: "200 OK" },
  { time: "10:41:50", channel: copy("openaiAgentPrepared2"), ok: true, latencyMs: 412, note: copy("okDelayIsHigh") },
  { time: "10:40:12", channel: copy("darkSideOfTheMoon2"), ok: false, latencyMs: 0, note: copy("connectionTimeoutMeltedTransfer") },
  { time: "10:38:44", channel: copy("aliBailian2"), ok: false, latencyMs: 0, note: copy("plannedMaintenancePauseRouting") },
  { time: "10:37:01", channel: copy("deepseekOfficial2"), ok: true, latencyMs: 98, note: "200 OK" },
  { time: "10:35:22", channel: "Google Vertex", ok: true, latencyMs: 152, note: "200 OK" },
];
