import type { RequestLog } from "./types";

// 请求日志 —— 每条带完整 OpenAI 兼容 req/resp body，供 JsonViewer 真实展开。
export const requestLogs: RequestLog[] = [
  {
    id: "req_9hk2f7a1",
    time: "2026-06-05T10:42:08+08:00",
    model: "claude-opus-4-7",
    channel: "Anthropic 官方",
    keyName: "生产环境 · 主服务",
    status: "success",
    httpStatus: 200,
    latencyMs: 1284,
    promptTokens: 128,
    completionTokens: 42,
    costUsd: 0.00169,
    request: {
      model: "claude-opus-4-7",
      messages: [
        { role: "system", content: "你是一个简洁的天气助手。" },
        { role: "user", content: "杭州今天适合户外吗？" },
      ],
      temperature: 0.7,
      max_tokens: 1024,
      tools: [
        {
          type: "function",
          function: {
            name: "get_weather",
            description: "查询城市天气",
            parameters: { type: "object", properties: { city: { type: "string" } }, required: ["city"] },
          },
        },
      ],
    },
    response: {
      id: "chatcmpl-9hk2f7",
      object: "chat.completion",
      model: "claude-opus-4-7",
      created: 1749091328,
      choices: [
        {
          index: 0,
          finish_reason: "tool_calls",
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              { id: "call_a1", type: "function", function: { name: "get_weather", arguments: '{"city":"杭州"}' } },
            ],
          },
        },
      ],
      usage: { prompt_tokens: 128, completion_tokens: 42, total_tokens: 170 },
    },
  },
  {
    id: "req_8gd1e4b2",
    time: "2026-06-05T10:41:55+08:00",
    model: "gpt-5.4",
    channel: "OpenAI 官方 · 主",
    keyName: "移动端 App",
    status: "success",
    httpStatus: 200,
    latencyMs: 942,
    promptTokens: 312,
    completionTokens: 188,
    costUsd: 0.00360,
    request: {
      model: "gpt-5.4",
      messages: [{ role: "user", content: "用一句话解释 RAG。" }],
      temperature: 0.3,
      stream: true,
    },
    response: {
      id: "chatcmpl-8gd1e4",
      object: "chat.completion",
      model: "gpt-5.4",
      created: 1749091315,
      choices: [
        {
          index: 0,
          finish_reason: "stop",
          message: {
            role: "assistant",
            content: "RAG 是先从知识库检索相关片段、再让大模型基于这些片段生成回答的方法。",
          },
        },
      ],
      usage: { prompt_tokens: 312, completion_tokens: 188, total_tokens: 500 },
    },
  },
  {
    id: "req_7fc0d3c3",
    time: "2026-06-05T10:41:30+08:00",
    model: "deepseek-v4",
    channel: "DeepSeek 官方",
    keyName: "数据看板 · 只读分析",
    status: "success",
    httpStatus: 200,
    latencyMs: 1620,
    promptTokens: 1840,
    completionTokens: 96,
    costUsd: 0.00122,
    request: {
      model: "deepseek-v4",
      messages: [{ role: "user", content: "汇总这段销售数据的环比趋势……" }],
      temperature: 0,
    },
    response: {
      id: "chatcmpl-7fc0d3",
      object: "chat.completion",
      model: "deepseek-v4",
      created: 1749091290,
      choices: [{ index: 0, finish_reason: "stop", message: { role: "assistant", content: "整体环比上升 12.4%……" } }],
      usage: { prompt_tokens: 1840, completion_tokens: 96, total_tokens: 1936 },
    },
  },
  {
    id: "req_6eb9c2d4",
    time: "2026-06-05T10:40:12+08:00",
    model: "kimi-k2",
    channel: "月之暗面",
    keyName: "实验 · Playground",
    status: "timeout",
    httpStatus: 504,
    latencyMs: 30000,
    promptTokens: 64,
    completionTokens: 0,
    costUsd: 0,
    request: {
      model: "kimi-k2",
      messages: [{ role: "user", content: "写一首关于秋天的诗。" }],
      temperature: 1,
    },
    response: {
      error: {
        type: "upstream_timeout",
        message: "Upstream channel 月之暗面 timed out after 30000ms; request failed over but no healthy channel.",
        code: "channel_timeout",
        param: null,
      },
    },
  },
  {
    id: "req_5da8b1e5",
    time: "2026-06-05T10:39:40+08:00",
    model: "gpt-5.5",
    channel: "OpenAI 官方 · 主",
    keyName: "生产环境 · 主服务",
    status: "rate_limited",
    httpStatus: 429,
    latencyMs: 38,
    promptTokens: 0,
    completionTokens: 0,
    costUsd: 0,
    request: {
      model: "gpt-5.5",
      messages: [{ role: "user", content: "批量翻译以下 50 条……" }],
    },
    response: {
      error: {
        type: "rate_limit_exceeded",
        message: "Rate limit reached for key 「生产环境 · 主服务」: 600 RPM. Please retry after 1s.",
        code: "rate_limited",
        param: null,
      },
    },
  },
  {
    id: "req_4c97a0f6",
    time: "2026-06-05T10:38:18+08:00",
    model: "gemini-3-pro",
    channel: "Google Vertex",
    keyName: "移动端 App",
    status: "success",
    httpStatus: 200,
    latencyMs: 1108,
    promptTokens: 256,
    completionTokens: 320,
    costUsd: 0.00435,
    request: {
      model: "gemini-3-pro",
      messages: [{ role: "user", content: "看这张图里有哪些品牌？", name: "u" }],
      temperature: 0.5,
    },
    response: {
      id: "chatcmpl-4c97a0",
      object: "chat.completion",
      model: "gemini-3-pro",
      created: 1749091098,
      choices: [{ index: 0, finish_reason: "stop", message: { role: "assistant", content: "图中可识别到 3 个品牌……" } }],
      usage: { prompt_tokens: 256, completion_tokens: 320, total_tokens: 576 },
    },
  },
  {
    id: "req_3b86f9a7",
    time: "2026-06-05T10:37:02+08:00",
    model: "claude-haiku-4-5",
    channel: "Anthropic 官方",
    keyName: "数据看板 · 只读分析",
    status: "success",
    httpStatus: 200,
    latencyMs: 486,
    promptTokens: 88,
    completionTokens: 24,
    costUsd: 0.00021,
    request: { model: "claude-haiku-4-5", messages: [{ role: "user", content: "把这句话改写得更礼貌。" }] },
    response: {
      id: "chatcmpl-3b86f9",
      object: "chat.completion",
      model: "claude-haiku-4-5",
      created: 1749091022,
      choices: [{ index: 0, finish_reason: "stop", message: { role: "assistant", content: "好的，已为你优化……" } }],
      usage: { prompt_tokens: 88, completion_tokens: 24, total_tokens: 112 },
    },
  },
  {
    id: "req_2a75e8b8",
    time: "2026-06-05T10:35:44+08:00",
    model: "qwen3-max",
    channel: "阿里百炼",
    keyName: "生产环境 · 主服务",
    status: "error",
    httpStatus: 503,
    latencyMs: 12,
    promptTokens: 0,
    completionTokens: 0,
    costUsd: 0,
    request: { model: "qwen3-max", messages: [{ role: "user", content: "生成营销文案……" }] },
    response: {
      error: {
        type: "channel_unavailable",
        message: "Channel 阿里百炼 is under maintenance. No alternative channel serves model qwen3-max.",
        code: "service_unavailable",
        param: null,
      },
    },
  },
];
