import { copy } from "./logs.content";
import type { RequestLog } from "./types";

// 请求日志 —— 每条带完整 OpenAI 兼容 req/resp body，供 JsonViewer 真实展开。
export const requestLogs: RequestLog[] = [
  {
    id: "req_9hk2f7a1",
    time: "2026-06-05T10:42:08+08:00",
    model: "claude-opus-4-7",
    channel: copy("anthropicOfficial"),
    keyName: copy("productionEnvironmentMainService"),
    status: "success",
    httpStatus: 200,
    latencyMs: 1284,
    promptTokens: 128,
    completionTokens: 42,
    costUsd: 0.00169,
    request: {
      model: "claude-opus-4-7",
      messages: [
        { role: "system", content: copy("youAreANeatWeatherAssistant") },
        { role: "user", content: copy("isHangzhouSuitableForOutdoorUseToday") },
      ],
      temperature: 0.7,
      max_tokens: 1024,
      tools: [
        {
          type: "function",
          function: {
            name: "get_weather",
            description: copy("checkCityWeather"),
            parameters: { type: "object", properties: { city: { type: "string" } }, required: ["city"] },
          },
        },
      ],
    },
    response: {
      id: "chatcmpl-9hk2f7",
      object: "chat.completion",
      model: "claude-opus-4-7",
      created: 1749091328,
      choices: [
        {
          index: 0,
          finish_reason: "tool_calls",
          message: {
            role: "assistant",
            content: null,
            tool_calls: [
              { id: "call_a1", type: "function", function: { name: "get_weather", arguments: copy("cityHangzhou") } },
            ],
          },
        },
      ],
      usage: { prompt_tokens: 128, completion_tokens: 42, total_tokens: 170 },
    },
  },
  {
    id: "req_8gd1e4b2",
    time: "2026-06-05T10:41:55+08:00",
    model: "gpt-5.4",
    channel: copy("openaiOfficialMain"),
    keyName: copy("mobileApp"),
    status: "success",
    httpStatus: 200,
    latencyMs: 942,
    promptTokens: 312,
    completionTokens: 188,
    costUsd: 0.00360,
    request: {
      model: "gpt-5.4",
      messages: [{ role: "user", content: copy("explainRagInOneSentence") }],
      temperature: 0.3,
      stream: true,
    },
    response: {
      id: "chatcmpl-8gd1e4",
      object: "chat.completion",
      model: "gpt-5.4",
      created: 1749091315,
      choices: [
        {
          index: 0,
          finish_reason: "stop",
          message: {
            role: "assistant",
            content: copy("ragIsAMethodThatFirstRetrieves"),
          },
        },
      ],
      usage: { prompt_tokens: 312, completion_tokens: 188, total_tokens: 500 },
    },
  },
  {
    id: "req_7fc0d3c3",
    time: "2026-06-05T10:41:30+08:00",
    model: "deepseek-v4",
    channel: copy("deepseekOfficial"),
    keyName: copy("dataDashboardReadOnlyAnalysis"),
    status: "success",
    httpStatus: 200,
    latencyMs: 1620,
    promptTokens: 1840,
    completionTokens: 96,
    costUsd: 0.00122,
    request: {
      model: "deepseek-v4",
      messages: [{ role: "user", content: copy("summarizeTheMonthOnMonthTrendOf") }],
      temperature: 0,
    },
    response: {
      id: "chatcmpl-7fc0d3",
      object: "chat.completion",
      model: "deepseek-v4",
      created: 1749091290,
      choices: [{ index: 0, finish_reason: "stop", message: { role: "assistant", content: copy("theOverallMonthOnMonthIncreaseWas") } }],
      usage: { prompt_tokens: 1840, completion_tokens: 96, total_tokens: 1936 },
    },
  },
  {
    id: "req_6eb9c2d4",
    time: "2026-06-05T10:40:12+08:00",
    model: "kimi-k2",
    channel: copy("darkSideOfTheMoon"),
    keyName: copy("experimentPlayground"),
    status: "timeout",
    httpStatus: 504,
    latencyMs: 30000,
    promptTokens: 64,
    completionTokens: 0,
    costUsd: 0,
    request: {
      model: "kimi-k2",
      messages: [{ role: "user", content: copy("writeAPoemAboutAutumn") }],
      temperature: 1,
    },
    response: {
      error: {
        type: "upstream_timeout",
        message: copy("upstreamChannelDarkSideOfTheMoon"),
        code: "channel_timeout",
        param: null,
      },
    },
  },
  {
    id: "req_5da8b1e5",
    time: "2026-06-05T10:39:40+08:00",
    model: "gpt-5.5",
    channel: copy("openaiOfficialMain2"),
    keyName: copy("productionEnvironmentMainService2"),
    status: "rate_limited",
    httpStatus: 429,
    latencyMs: 38,
    promptTokens: 0,
    completionTokens: 0,
    costUsd: 0,
    request: {
      model: "gpt-5.5",
      messages: [{ role: "user", content: copy("translateTheFollowingItemsInBatches") }],
    },
    response: {
      error: {
        type: "rate_limit_exceeded",
        message: copy("rateLimitReachedForKeyProductionEnvironment"),
        code: "rate_limited",
        param: null,
      },
    },
  },
  {
    id: "req_4c97a0f6",
    time: "2026-06-05T10:38:18+08:00",
    model: "gemini-3-pro",
    channel: "Google Vertex",
    keyName: copy("mobileApp2"),
    status: "success",
    httpStatus: 200,
    latencyMs: 1108,
    promptTokens: 256,
    completionTokens: 320,
    costUsd: 0.00435,
    request: {
      model: "gemini-3-pro",
      messages: [{ role: "user", content: copy("whatBrandsAreThereInThisPicture"), name: "u" }],
      temperature: 0.5,
    },
    response: {
      id: "chatcmpl-4c97a0",
      object: "chat.completion",
      model: "gemini-3-pro",
      created: 1749091098,
      choices: [{ index: 0, finish_reason: "stop", message: { role: "assistant", content: copy("brandsCanBeIdentifiedInThePicture") } }],
      usage: { prompt_tokens: 256, completion_tokens: 320, total_tokens: 576 },
    },
  },
  {
    id: "req_3b86f9a7",
    time: "2026-06-05T10:37:02+08:00",
    model: "claude-haiku-4-5",
    channel: copy("anthropicOfficial2"),
    keyName: copy("dataDashboardReadOnlyAnalysis2"),
    status: "success",
    httpStatus: 200,
    latencyMs: 486,
    promptTokens: 88,
    completionTokens: 24,
    costUsd: 0.00021,
    request: { model: "claude-haiku-4-5", messages: [{ role: "user", content: copy("rewriteThisSentenceToBeMorePolite") }] },
    response: {
      id: "chatcmpl-3b86f9",
      object: "chat.completion",
      model: "claude-haiku-4-5",
      created: 1749091022,
      choices: [{ index: 0, finish_reason: "stop", message: { role: "assistant", content: copy("okOptimizedForYou") } }],
      usage: { prompt_tokens: 88, completion_tokens: 24, total_tokens: 112 },
    },
  },
  {
    id: "req_2a75e8b8",
    time: "2026-06-05T10:35:44+08:00",
    model: "qwen3-max",
    channel: copy("aliBailian"),
    keyName: copy("productionEnvironmentMainService3"),
    status: "error",
    httpStatus: 503,
    latencyMs: 12,
    promptTokens: 0,
    completionTokens: 0,
    costUsd: 0,
    request: { model: "qwen3-max", messages: [{ role: "user", content: copy("generateMarketingCopy") }] },
    response: {
      error: {
        type: "channel_unavailable",
        message: copy("channelAlibabaBailianIsUnderMaintenanceNo"),
        code: "service_unavailable",
        param: null,
      },
    },
  },
];
