import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "pleaseEnterAKeyName": "请输入密钥名称",
    "pleaseSetSpeedLimit": "请设置限速",
    "keyCreated": "密钥已创建",
    "pleaseCopyItImmediatelyAndKeepIt": "请立即复制并妥善保存，完整密钥仅展示这一次。",
    "keyHasBeenReset": "密钥已重置",
    "theOldKeyIsInvalidImmediatelyPlease": "旧密钥立即失效，请更新你的服务配置。",
    "keyRevoked": "密钥已吊销",
    "nameGroup": "名称 / 分组",
    "create": "创建",
    "expirationValue": " · 到期 {0}",
    "longTermEffective": " · 长期有效",
    "limitedToValueModels": " · 限 {0} 个模型",
    "allModels": " · 全部模型",
    "key": "密钥",
    "keyCopied": "已复制密钥",
    "usageThisMonth": "本月用量",
    "noLimit": "/ 不限",
    "speedLimit": "限速",
    "status": "状态",
    "startAndStopValue": "启停 {0}",
    "operation": "操作",
    "reset": "重置",
    "revoke": "吊销",
    "apiKey": "API 密钥",
    "useOneKeyToAccessAllUpstream": "用一把密钥访问全部上游模型 · 按分组管控限额与限速",
    "createNewKey": "新建密钥",
    "key2": "密钥「",
    "createdTheCompleteKeyWillOnlyBe": "」已创建 —— 完整密钥仅此一次展示，请立即复制保存。",
    "completeKeyCopied": "已复制完整密钥",
    "afterClosingThisPromptYouWillNot": "关闭此提示后将无法再次查看完整密钥，只能重置。",
    "keyList": "密钥列表",
    "keyCountOpen": "（",
    "enabledTotal": "个启用 · 共",
    "localizedText": "个）",
    "createNewApiKey": "新建 API 密钥",
    "createKey": "创建密钥",
    "keyName": "密钥名称",
    "suchAsProductionEnvironmentMainService": "如：生产环境 · 主服务",
    "groupToWhichItBelongs": "所属分组",
    "monthlyLimitUsdEmptyNoLimit": "月度限额（USD，空 = 不限）",
    "monthlyLimit": "月度限额",
    "speedLimitRpm": "限速（RPM）",
    "speedLimit2": "限速",
    "expirationDateOptional": "到期日（可选）",
    "adjustableModelRange": "可调模型范围",
    "allModels2": "全部模型",
    "allModels3": "全部模型",
  },
  en: {
    "pleaseEnterAKeyName": "Please enter a key name",
    "pleaseSetSpeedLimit": "Please set speed limit",
    "keyCreated": "Key created",
    "pleaseCopyItImmediatelyAndKeepIt": "Please copy it immediately and keep it in a safe place. The complete key will only be displayed this time.",
    "keyHasBeenReset": "Key has been reset",
    "theOldKeyIsInvalidImmediatelyPlease": "The old key is invalid immediately, please update your service configuration.",
    "keyRevoked": "Key revoked",
    "nameGroup": "name/group",
    "create": "create",
    "expirationValue": "· Expiration {0}",
    "longTermEffective": "· Long term effective",
    "limitedToValueModels": "· Limited to {0} models",
    "allModels": "· All models",
    "key": "key",
    "keyCopied": "Key copied",
    "usageThisMonth": "Usage this month",
    "noLimit": "/ no limit",
    "speedLimit": "speed limit",
    "status": "Status",
    "startAndStopValue": "Start and stop {0}",
    "operation": "Operation",
    "reset": "reset",
    "revoke": "Revoke",
    "apiKey": "API key",
    "useOneKeyToAccessAllUpstream": "Use one key to access all upstream models · Manage quotas and speed limits by group",
    "createNewKey": "Create new key",
    "key2": "Key \"",
    "createdTheCompleteKeyWillOnlyBe": "\"Created - the complete key will only be displayed once, please copy and save it immediately.",
    "completeKeyCopied": "Complete key copied",
    "afterClosingThisPromptYouWillNot": "After closing this prompt you will not be able to view the full key again, only reset it.",
    "keyList": "Key list",
    "keyCountOpen": "(",
    "enabledTotal": "enabled · total",
    "localizedText": ")",
    "createNewApiKey": "Create new API key",
    "createKey": "Create key",
    "keyName": "Key name",
    "suchAsProductionEnvironmentMainService": "Such as: production environment · main service",
    "groupToWhichItBelongs": "Group to which it belongs",
    "monthlyLimitUsdEmptyNoLimit": "Monthly limit (USD, empty = no limit)",
    "monthlyLimit": "monthly limit",
    "speedLimitRpm": "Speed limit (RPM)",
    "speedLimit2": "speed limit",
    "expirationDateOptional": "Expiration date (optional)",
    "adjustableModelRange": "Adjustable model range",
    "allModels2": "All models",
    "allModels3": "All models",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanhub-app-keys-page",
  content: t(content),
};

export default dictionary;
