import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    hancloud: "瀚云",
    theIntegratedCloudNativeApplicationPlatform: "一体化云原生应用平台",
    hancloudTakesYouFromGitPushToAGlobalReleaseWithDeploymentElasticComputeAndEndToEndObservabilityO: "从 git push 到全球上线，瀚云把部署、弹性算力与端到端可观测收进同一个平台。",
    capabilities: "能力",
    customers: "客户",
    pricing: "定价",
    contact: "联系",
    totalDeployments: "累计部署次数",
    enterpriseCustomers: "企业客户",
    serviceAvailability: "服务可用性",
    globalEdgeNodes: "全球边缘节点",
    oneClickDeployment: "一键部署",
    deployOnGitPushCompleteCachedBuildsInSecondsAndRollBackAFailedReleaseToAnyPreviousVersionInOneCl: "git push 即上线，构建缓存命中秒级完成，异常一键回滚到任意历史版本。",
    elasticCompute: "弹性算力",
    automaticallyScalesUpAndDownBasedOnRequestsAndReturnsToZeroWhenIdleWithoutBilling: "按请求自动伸缩，闲时归零不计费。",
    globalEdgeNetwork: "全球边缘网络",
    serveStaticAssetsAndFunctionsCloseToUsersFrom320EdgeNodes: "320 个边缘节点就近响应，静态资源与函数同图下发。",
    endToEndObservability: "端到端可观测",
    metricsLogsAndDistributedTracesWorkOutOfTheBoxWithNoCollectionStackToMaintain: "指标、日志、链路追踪开箱即用，无需自建采集栈。",
    enterpriseGradeSecurity: "企业级安全",
    soc2TypeIiAndMlpsLevel3ComplianceWithManagedSecretsAndCompleteAuditing: "SOC 2 Type II 与等保三级合规，密钥托管与审计全覆盖。",
    teamwork: "团队协作",
    fineGrainedRolePermissionsEnvironmentIsolationAndChangeAuditingAllowMultipleTeamsToSafelyShareAP: "细粒度角色权限、环境隔离与变更审计，多团队安全共用一套平台。",
    afterMovingToHancloudWeWentFromOneReleaseAWeekToMoreThanTenADayAndOurOnCallEngineersCanRollBackW: "迁移到瀚云后，我们的发布频率从每周一次提升到每天十几次，回滚再也不用值班同学手抖。",
    chenHang: "陈航",
    auroraTechnologyEngineeringVp: "极光科技 · 工程 VP",
    chen: "陈",
    scalingElasticComputeToZeroWhenIdleCutOurStagingBillBy70: "弹性算力闲时归零这一条，直接把我们的预发环境账单砍掉了七成。",
    linYue: "林悦",
    yuntuDataHeadOfInfrastructure: "云图数据 · 基础架构负责人",
    lin: "林",
    observabilityWorksOutOfTheBoxSoNewEngineersCanTraceProductionIssuesOnDayOneWithoutBuildingATelem: "可观测开箱即用，新同事第一天就能顺着链路追踪定位线上问题，省掉了搭一整套采集栈的活。",
    globalEdgeNodesCutInitialPageLoadTimeForInternationalUsersFrom18STo04SWithAClearLiftInConversion: "全球边缘节点让海外用户的首屏时间从 1.8s 降到 0.4s，转化率肉眼可见地涨了。",
    suQing: "苏晴",
    farsailGlobalCto: "远帆出海 · CTO",
    su: "苏",
    complianceUsedToConsumeAnEngineerSEntireQuarterHancloudSAuditTrailAndManagedKeysHelpedUsPassTheS: "合规这块原本要专人盯一个季度，瀚云的审计与密钥托管让我们一次过了等保。",
    zhaoMingyuan: "赵明远",
    wenxinFinancialSecurityDirector: "稳信金融 · 安全总监",
    zhao: "赵",
    theSameWorkflowTookUsFromDemoToProductionHancloudStaysOutOfTheWayBetterThanAnyPlatformWeVeUsed: "从 Demo 到生产，团队只学了一套心智模型。瀚云是我们用过最不打扰开发的平台。",
    gettingStarted: "入门",
    personalProjectsAndPrototypeVerification: "个人项目与原型验证",
    text1ProductionProject: "1 个生产项目",
    text100GbPerMonth: "每月 100 GB 流量",
    communitySupport: "社区支持",
    automaticHttpsAndGlobalCdn: "自动 HTTPS 与全球 CDN",
    forIndividuals: "单人协作",
    startForFree: "免费开始",
    professional: "专业",
    growingTeamAndProductionOperations: "成长中的团队与生产业务",
    unlimitedProjects: "无限项目",
    text1TbPerMonth: "每月 1 TB 流量",
    autoscalingCompute: "弹性算力自动伸缩",
    metricsLogsDistributedTraces: "指标 / 日志 / 链路追踪",
    upTo10Members: "最多 10 名成员",
    fourHourTicketResponse: "工单 4 小时响应",
    startA14DayTrial: "开始 14 天试用",
    enterprise: "企业",
    compliancePrivateDeploymentAndDedicatedSupport: "合规、私有化与专属支持",
    custom: "定制",
    dedicatedEdgeNodesAndComputePool: "专属边缘节点与算力池",
    soc2ClassIiiCompliance: "SOC 2 / 等保三级合规",
    ssoAndFineGrainedAuditing: "SSO 与细粒度审计",
    dedicatedCustomerSuccessManager: "专属客户成功经理",
    text9999SlaGuaranteed: "99.99% SLA 保障",
    privateDeploymentOptional: "私有化部署可选",
    bookADemo: "预约演示",
    isItDifficultToMigrateToHancloud: "从其他平台迁移瀚云复杂吗？",
    mostProjectsNeedNoCodeChangesConnectARepositoryAndHancloudDetectsTheFrameworkAndCreatesTheBuildC: "大多数项目无需改代码。瀚云自动识别框架并生成构建配置，你只需连接代码仓库；我们也提供一对一迁移协助。",
    areThereAnyHiddenLimitationsInTheFreeVersion: "免费版会不会有隐藏限制？",
    freeIncludesOneProductionProject100GbOfMonthlyTrafficAndAGlobalCdnEnoughForRealPersonalProjectsW: "免费版包含 1 个生产项目、每月 100 GB 流量与全球 CDN，足以承载真实的个人项目，且不会因到期强制升级。",
    howIsElasticComputeBilled: "弹性算力是如何计费的？",
    payOnlyForRequestExecutionTimeWithNoIdleChargesAfterScalingToZeroSetABudgetCapForEachEnvironment: "按实际请求时长计费，闲时自动归零不产生费用。你可以为每个环境设置预算上限，超出前会提前告警。",
    whatComplianceCertificationsAreSupported: "支持哪些合规认证？",
    proAndEnterpriseRunOnSoc2TypeIiAuditedInfrastructureEnterpriseAlsoIncludesMlpsLevel3ComplianceSs: "专业版与企业版均运行在通过 SOC 2 Type II 审计的基础设施上，企业版额外提供等保三级、SSO 与私有化部署。",
    howDoIGetHelpDuringAnIncident: "出现故障时如何获得支持？",
    freeIncludesCommunitySupportProIncludesAFourHourTicketResponseAndEnterpriseIncludesADedicatedCus: "免费版享社区支持，专业版工单 4 小时内响应，企业版配备专属客户成功经理与 99.99% SLA。",
    products: "产品",
    edgeNetwork: "边缘网络",
    observability: "可观测",
    solutions: "解决方案",
    startups: "初创团队",
    globalEcommerce: "电商出海",
    aiApplications: "AI 应用",
    resources: "资源",
    documentation: "文档",
    blog: "博客",
    serviceStatus: "服务状态",
    changelog: "更新日志",
    company: "公司",
    aboutUs: "关于我们",
    careers: "加入我们",
    contactSales: "联系销售",
    privacyPolicy: "隐私政策",
  },
  en: {
    hancloud: "HanCloud",
    theIntegratedCloudNativeApplicationPlatform: "The integrated cloud-native application platform",
    hancloudTakesYouFromGitPushToAGlobalReleaseWithDeploymentElasticComputeAndEndToEndObservabilityO: "HanCloud takes you from git push to a global release with deployment, elastic compute, and end-to-end observability on one platform.",
    capabilities: "Capabilities",
    customers: "Customers",
    pricing: "Pricing",
    contact: "Contact",
    totalDeployments: "Total deployments",
    enterpriseCustomers: "Enterprise customers",
    serviceAvailability: "Service availability",
    globalEdgeNodes: "Global edge nodes",
    oneClickDeployment: "One-click deployment",
    deployOnGitPushCompleteCachedBuildsInSecondsAndRollBackAFailedReleaseToAnyPreviousVersionInOneCl: "Deploy on git push, complete cached builds in seconds, and roll back a failed release to any previous version in one click.",
    elasticCompute: "Elastic compute",
    automaticallyScalesUpAndDownBasedOnRequestsAndReturnsToZeroWhenIdleWithoutBilling: "Automatically scales up and down based on requests, and returns to zero when idle without billing.",
    globalEdgeNetwork: "Global Edge Network",
    serveStaticAssetsAndFunctionsCloseToUsersFrom320EdgeNodes: "Serve static assets and functions close to users from 320 edge nodes.",
    endToEndObservability: "End-to-end observability",
    metricsLogsAndDistributedTracesWorkOutOfTheBoxWithNoCollectionStackToMaintain: "Metrics, logs, and distributed traces work out of the box, with no collection stack to maintain.",
    enterpriseGradeSecurity: "Enterprise-grade security",
    soc2TypeIiAndMlpsLevel3ComplianceWithManagedSecretsAndCompleteAuditing: "SOC 2 Type II and MLPS Level 3 compliance, with managed secrets and complete auditing.",
    teamwork: "Teamwork",
    fineGrainedRolePermissionsEnvironmentIsolationAndChangeAuditingAllowMultipleTeamsToSafelyShareAP: "Fine-grained role permissions, environment isolation and change auditing allow multiple teams to safely share a platform.",
    afterMovingToHancloudWeWentFromOneReleaseAWeekToMoreThanTenADayAndOurOnCallEngineersCanRollBackW: "After moving to HanCloud, we went from one release a week to more than ten a day, and our on-call engineers can roll back with confidence.",
    chenHang: "Chen Hang",
    auroraTechnologyEngineeringVp: "Aurora Technology · Engineering VP",
    chen: "Chen",
    scalingElasticComputeToZeroWhenIdleCutOurStagingBillBy70: "Scaling elastic compute to zero when idle cut our staging bill by 70%.",
    linYue: "Lin Yue",
    yuntuDataHeadOfInfrastructure: "Yuntu Data · Head of Infrastructure",
    lin: "Lin",
    observabilityWorksOutOfTheBoxSoNewEngineersCanTraceProductionIssuesOnDayOneWithoutBuildingATelem: "Observability works out of the box, so new engineers can trace production issues on day one without building a telemetry stack first.",
    globalEdgeNodesCutInitialPageLoadTimeForInternationalUsersFrom18STo04SWithAClearLiftInConversion: "Global edge nodes cut initial page load time for international users from 1.8 s to 0.4 s, with a clear lift in conversion.",
    suQing: "Su Qing",
    farsailGlobalCto: "FarSail Global · CTO",
    su: "Su",
    complianceUsedToConsumeAnEngineerSEntireQuarterHancloudSAuditTrailAndManagedKeysHelpedUsPassTheS: "Compliance used to consume an engineer's entire quarter. HanCloud's audit trail and managed keys helped us pass the security assessment on the first attempt.",
    zhaoMingyuan: "Zhao Mingyuan",
    wenxinFinancialSecurityDirector: "Wenxin Financial · Security Director",
    zhao: "Zhao",
    theSameWorkflowTookUsFromDemoToProductionHancloudStaysOutOfTheWayBetterThanAnyPlatformWeVeUsed: "The same workflow took us from demo to production. HanCloud stays out of the way better than any platform we've used.",
    gettingStarted: "Getting started",
    personalProjectsAndPrototypeVerification: "Personal projects and prototype verification",
    text1ProductionProject: "1 production project",
    text100GbPerMonth: "100 GB per month",
    communitySupport: "Community support",
    automaticHttpsAndGlobalCdn: "Automatic HTTPS and global CDN",
    forIndividuals: "For individuals",
    startForFree: "Start for free",
    professional: "Professional",
    growingTeamAndProductionOperations: "Growing team and production operations",
    unlimitedProjects: "Unlimited projects",
    text1TbPerMonth: "1 TB per month",
    autoscalingCompute: "Autoscaling compute",
    metricsLogsDistributedTraces: "Metrics / logs / distributed traces",
    upTo10Members: "Up to 10 members",
    fourHourTicketResponse: "Four-hour ticket response",
    startA14DayTrial: "Start a 14-day trial",
    enterprise: "enterprise",
    compliancePrivateDeploymentAndDedicatedSupport: "Compliance, private deployment, and dedicated support",
    custom: "Custom",
    dedicatedEdgeNodesAndComputePool: "Dedicated edge nodes and compute pool",
    soc2ClassIiiCompliance: "SOC 2 / Class III compliance",
    ssoAndFineGrainedAuditing: "SSO and fine-grained auditing",
    dedicatedCustomerSuccessManager: "Dedicated Customer Success Manager",
    text9999SlaGuaranteed: "99.99% SLA guaranteed",
    privateDeploymentOptional: "Private deployment optional",
    bookADemo: "Book a demo",
    isItDifficultToMigrateToHancloud: "Is it difficult to migrate to HanCloud?",
    mostProjectsNeedNoCodeChangesConnectARepositoryAndHancloudDetectsTheFrameworkAndCreatesTheBuildC: "Most projects need no code changes. Connect a repository and HanCloud detects the framework and creates the build configuration; one-to-one migration help is also available.",
    areThereAnyHiddenLimitationsInTheFreeVersion: "Are there any hidden limitations in the free version?",
    freeIncludesOneProductionProject100GbOfMonthlyTrafficAndAGlobalCdnEnoughForRealPersonalProjectsW: "Free includes one production project, 100 GB of monthly traffic, and a global CDN—enough for real personal projects, with no forced upgrade deadline.",
    howIsElasticComputeBilled: "How is elastic compute billed?",
    payOnlyForRequestExecutionTimeWithNoIdleChargesAfterScalingToZeroSetABudgetCapForEachEnvironment: "Pay only for request execution time, with no idle charges after scaling to zero. Set a budget cap for each environment and receive alerts before you reach it.",
    whatComplianceCertificationsAreSupported: "What compliance certifications are supported?",
    proAndEnterpriseRunOnSoc2TypeIiAuditedInfrastructureEnterpriseAlsoIncludesMlpsLevel3ComplianceSs: "Pro and Enterprise run on SOC 2 Type II-audited infrastructure. Enterprise also includes MLPS Level 3 compliance, SSO, and private deployment.",
    howDoIGetHelpDuringAnIncident: "How do I get help during an incident?",
    freeIncludesCommunitySupportProIncludesAFourHourTicketResponseAndEnterpriseIncludesADedicatedCus: "Free includes community support, Pro includes a four-hour ticket response, and Enterprise includes a dedicated customer success manager and a 99.99% SLA.",
    products: "Products",
    edgeNetwork: "edge network",
    observability: "Observability",
    solutions: "Solutions",
    startups: "Startups",
    globalEcommerce: "Global ecommerce",
    aiApplications: "AI applications",
    resources: "Resources",
    documentation: "Documentation",
    blog: "Blog",
    serviceStatus: "Service status",
    changelog: "Changelog",
    company: "Company",
    aboutUs: "About us",
    careers: "Careers",
    contactSales: "Contact sales",
    privacyPolicy: "Privacy Policy",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>(
    (text, value, index) => text.replaceAll(`{${index}}`, String(value)),
    content[DOCS_LOCALE][key],
  );
}

const dictionary: Dictionary = {
  key: "demo-website-data-site",
  content: t(content),
};

export default dictionary;
