import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "serious": "严重",
    "warning": "警告",
    "tip": "提示",
    "triggering": "触发中",
    "confirmed": "已确认",
    "resolved": "已解决",
    "contractDocumentTranslation": "合同/文档翻译",
    "codeGenerationReview": "代码生成/审查",
    "ragSearchQA": "RAG 检索问答",
    "realTimeContentReview": "实时内容审核",
    "structuredExtraction": "结构化抽取",
    "multiAgentOrchestration": "多 agent 编排",
    "slaAlert": "SLA 告警",
    "achievementMonitoringSimulatorRulesEventFlow": "达成监控 · 模拟器 · 规则 · 事件流",
    "triggeringAnAlarm": "触发中告警",
    "confirmed2": "已确认",
    "resolved2": "已解决",
    "currentlyP95IsLate": "当前 P95 延迟",
    "slaAchievesMonitoring": "SLA 达成监控",
    "p50P95LatencyVsSlaThresholdsFor": "各任务类别 P50 / P95 延迟 vs SLA 阈值（近 24 时刻）",
    "taskCategories": "任务类别",
    "achieved": "达成",
    "achieved2": "达成",
    "theAppointedTimeApproached": "临期",
    "breachOfContract": "违约",
    "alarmSimulator": "告警模拟器",
    "dragTheP95ThresholdToPreviewThe": "拖动 P95 阈值，实时预演触发次数",
    "p95DelayThreshold": "P95 延迟阈值",
    "p95DelayThreshold2": "P95 延迟阈值",
    "basedOnTheCurrentThreshold": "按当前阈值",
    "itWillBeTriggeredInTheNear": "，\n              近 24 时刻将触发",
    "nextTheAlarm": "次告警。",
    "peakQueueDepth": "峰值队列深度",
    "stripTheLowerTheThresholdTheMore": "条 · 阈值越低越灵敏但噪声越多。",
    "alertRules": "告警规则",
    "thresholdTriggersNotificationChannels": "阈值触发 → 通知渠道",
    "right": "当",
    "valueStartAndStop": "{0} 启停",
    "defaultNotificationChannelsMultipleChoices": "默认通知渠道（多选）",
    "wechatWork": "企业微信",
    "realTimePushNotificationsFromTheDuty": "值班群实时推送",
    "sms": "短信",
    "seriousDirectContactResponsiblePerson": "严重级直达负责人",
    "email": "邮件",
    "costSubmitterNotice": "成本/提交人通知",
    "phone": "电话",
    "p0SlaDefaultsAndEscalation": "P0 SLA 违约升级",
    "alertIncidentStream": "告警事件流",
    "recentlyTriggeredAlertsAndActions": "最近触发的告警与处置",
  },
  en: {
    "serious": "Serious",
    "warning": "Warning",
    "tip": "Tip",
    "triggering": "Triggering",
    "confirmed": "Confirmed",
    "resolved": "Resolved",
    "contractDocumentTranslation": "Contract/document translation",
    "codeGenerationReview": "Code generation/review",
    "ragSearchQA": "RAG search Q&A",
    "realTimeContentReview": "Real-time content review",
    "structuredExtraction": "Structured extraction",
    "multiAgentOrchestration": "Multi-agent orchestration",
    "slaAlert": "SLA alert",
    "achievementMonitoringSimulatorRulesEventFlow": "Achievement monitoring · Simulator · Rules · Event flow",
    "triggeringAnAlarm": "Triggering an alarm",
    "confirmed2": "Confirmed",
    "resolved2": "Resolved",
    "currentlyP95IsLate": "Current P95 status",
    "slaAchievesMonitoring": "SLA compliance monitor",
    "p50P95LatencyVsSlaThresholdsFor": "P50 and P95 latency against SLA thresholds by task type (last 24 intervals)",
    "taskCategories": "Task categories",
    "achieved": "Achieved",
    "achieved2": "Achieved",
    "theAppointedTimeApproached": "SLA deadline approaching",
    "breachOfContract": "SLA breached",
    "alarmSimulator": "Alarm simulator",
    "dragTheP95ThresholdToPreviewThe": "Drag the P95 threshold to preview the number of triggers in real time",
    "p95DelayThreshold": "P95 Delay Threshold",
    "p95DelayThreshold2": "P95 Delay Threshold",
    "basedOnTheCurrentThreshold": "Based on the current threshold",
    "itWillBeTriggeredInTheNear": ", the simulator predicts ",
    "nextTheAlarm": " alerts in the next 24 hours.",
    "peakQueueDepth": "Peak queue depth",
    "stripTheLowerTheThresholdTheMore": "Tip: lower thresholds detect issues earlier but create more noise.",
    "alertRules": "Alert rules",
    "thresholdTriggersNotificationChannels": "Threshold triggers → notification channels",
    "right": "Enabled",
    "valueStartAndStop": "{0} enabled",
    "defaultNotificationChannelsMultipleChoices": "Default notification channels (multiple choices)",
    "wechatWork": "WeChat Work",
    "realTimePushNotificationsFromTheDuty": "Real-time push notifications from the duty group",
    "sms": "SMS",
    "seriousDirectContactResponsiblePerson": "Critical alerts contact the owner directly",
    "email": "Email",
    "costSubmitterNotice": "Cost/Submitter Notice",
    "phone": "Phone",
    "p0SlaDefaultsAndEscalation": "P0 SLA breaches and escalation",
    "alertIncidentStream": "Alert incident stream",
    "recentlyTriggeredAlertsAndActions": "Recently triggered alerts and actions",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanhelm-app-alerts-page",
  content: t(content),
};

export default dictionary;
