import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "all": "全部",
    "customerUpdated": "客户已更新",
    "new": "新建",
    "newCustomerHasBeenCreated": "已新建客户",
    "customer": "客户",
    "contactPerson": "联系人",
    "level": "等级",
    "status": "状态",
    "personInCharge": "负责人",
    "accumulatedTransactions": "累计成交",
    "latestFollowUp": "最近跟进",
    "operation": "操作",
    "view": "查看",
    "editCustomer": "编辑客户",
    "deleteThisCustomer": "删除该客户？",
    "theDataCannotBeRecoveredAfterDeletion": "删除后数据不可恢复（demo 内存态，刷新还原）。",
    "delete": "删除",
    "customerDeleted": "已删除客户",
    "deleteCustomer": "删除客户",
    "pleaseEnterTheCustomerSShortName": "请输入客户简称",
    "pleaseEnterFullCompanyName": "请输入公司全称",
    "phoneNumberMustIncludeNumbers": "电话需含数字",
    "emailMustContain": "邮箱需含 @",
    "tryAgain": "重试",
    "customerList": "客户列表",
    "createNewCustomer": "新建客户",
    "keywords": "关键词",
    "customerCompanyContact": "客户 / 公司 / 联系人",
    "status2": "状态",
    "level2": "等级",
    "personInCharge2": "负责人",
    "editCustomer2": "编辑客户",
    "createNewCustomer2": "新建客户",
    "customerAbbreviation": "客户简称",
    "suchAsMorningLightStationery": "如：晨光文具",
    "personInCharge3": "负责人",
    "fullCompanyName": "公司全称",
    "fullNameOfBusinessLicense": "营业执照全称",
    "contactPerson2": "联系人",
    "nameOfContactPerson": "对接人姓名",
    "contactNumber": "联系电话",
    "cellPhoneLandline": "手机 / 座机",
    "email": "邮箱",
    "area": "所在地区",
    "provinceCityDistrictCounty": "省 / 市 / 区县",
    "customerLevel": "客户等级",
    "followUpStatus": "跟进状态",
    "industry": "所属行业",
  },
  en: {
    "all": "All",
    "customerUpdated": "Customer updated",
    "new": "New",
    "newCustomerHasBeenCreated": "New customer has been created",
    "customer": "Customer",
    "contactPerson": "Contact person",
    "level": "Tier",
    "status": "Status",
    "personInCharge": "Owner",
    "accumulatedTransactions": "Lifetime value",
    "latestFollowUp": "Last activity",
    "operation": "Actions",
    "view": "View",
    "editCustomer": "Edit customer",
    "deleteThisCustomer": "Delete this customer?",
    "theDataCannotBeRecoveredAfterDeletion": "This removes the customer from the current demo session. Refresh the page to restore the original data.",
    "delete": "Delete",
    "customerDeleted": "Customer deleted",
    "deleteCustomer": "Delete customer",
    "pleaseEnterTheCustomerSShortName": "Enter a display name.",
    "pleaseEnterFullCompanyName": "Enter the legal company name.",
    "phoneNumberMustIncludeNumbers": "Enter a valid phone number.",
    "emailMustContain": "Enter a valid email address.",
    "tryAgain": "Try again",
    "customerList": "Customer list",
    "createNewCustomer": "Create new customer",
    "keywords": "Search",
    "customerCompanyContact": "Customer, company, or contact",
    "status2": "Status",
    "level2": "Tier",
    "personInCharge2": "Owner",
    "editCustomer2": "Edit customer",
    "createNewCustomer2": "Create new customer",
    "customerAbbreviation": "Display name",
    "suchAsMorningLightStationery": "For example, M&G Stationery",
    "personInCharge3": "Owner",
    "fullCompanyName": "Legal company name",
    "fullNameOfBusinessLicense": "Name shown on the business license",
    "contactPerson2": "Contact person",
    "nameOfContactPerson": "Primary contact name",
    "contactNumber": "Contact number",
    "cellPhoneLandline": "Mobile or landline",
    "email": "Email",
    "area": "Region",
    "provinceCityDistrictCounty": "State, city, or region",
    "customerLevel": "Customer level",
    "followUpStatus": "Follow up status",
    "industry": "Industry",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-crm-app-customers-page",
  content: t(content),
};

export default dictionary;
