import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    frontEndDevelopment: "前端开发",
    design: "设计",
    artificialIntelligence: "人工智能",
    careerGrowth: "职业成长",
    beginner: "入门",
    intermediate: "进阶",
    advanced: "高级",
    overview: "概览",
    keyPointsDisassembly: "要点拆解",
    handsOnDemonstration: "实操演示",
    summary: "小结",
    reactModernFrontEndEngineeringBattle: "React 现代前端工程实战",
    systemsLessonsFromComponentThinkingToHooksStateManagementAnd:
      "从组件化思维到 Hooks、状态管理与性能优化的系统课",
    hayashiMikawa: "林见川",
    frontEndArchitectFormerManufacturerTechLead: "前端架构师 · 前大厂 Tech Lead",
    startingFromComponentizedThinkingThisCourseTakesYouThroughReact:
      "本课程从**组件化思维**出发，带你吃透 React 的渲染模型、Hooks 心智模型与状态管理范式，并落到真实项目的性能优化。\n\n- 不堆 API，讲清「为什么这样设计」\n- 每章配可运行示例与练习\n- 覆盖 TypeScript 类型体操在组件中的实战",
    chapterComponentThinking: "第一章 · 组件化思维",
    courseGuidanceAndEnvironmentConstruction: "01 课程导学与环境搭建",
    componentsPropsAndCombinationsOutperformInheritance: "02 组件、Props 与组合优于继承",
    controlledVsUncontrolledComponents: "03 受控与非受控组件",
    chapterHooksModelOfMind: "第二章 · Hooks 心智模型",
    usestateAndRenderingTiming: "04 useState 与渲染时机",
    closureTrap: "闭包陷阱",
    batchProcessing: "批处理",
    functionalUpdates: "函数式更新",
    useeffectDependenciesAndCleanup: "05 useEffect 依赖与清理",
    usememoUseCallbackWhenToUse: "06 useMemo / useCallback 何时该用",
    chapterStateManagementAndPerformance: "第三章 · 状态管理与性能",
    contextCorrectPosture: "07 Context 的正确姿势",
    listVirtualizationAndRenderingPerformance: "08 列表虚拟化与渲染性能",
    projectsInActionDashboardRefactoring: "09 项目实战：仪表盘重构",
    courseMaterials: "课程资料",
    courseOutlinePdf: "课程大纲.pdf",
    sampleSourceCodeZip: "示例源码.zip",
    exerciseQuestionsAndAnswersMd: "练习题与答案.md",
    cheatSheetHooksPdf: "速查表-Hooks.pdf",
    typescriptTypeGymnasticsAdvanced: "TypeScript 类型体操进阶",
    writeTheTypeSystemAsALanguageAndEradicateAny: "把类型系统当成一门语言来写，根治「any 漫天飞」",
    typeSystem: "类型系统",
    shenMo: "沈墨",
    openSourceAuthorTypeToolLibraryMaintainer: "开源作者 · 类型工具库维护者",
    genericsConditionTypesMappingTypesTemplateLiteralsThisLessonTakes:
      "泛型、条件类型、映射类型、模板字面量类型——本课带你把 TypeScript 类型系统玩成一门**图灵完备的语言**，并落到真实的库类型设计。",
    chapterGenericsAndConstraints: "第一章 · 泛型与约束",
    natureOfGenerics: "01 泛型的本质",
    constraintsAndDefaultTypes: "02 约束与默认类型",
    chapterTypeOperations: "第二章 · 类型运算",
    conditionTypesAndInfers: "03 条件类型与 infer",
    mappingTypesAndKeyRemapping: "04 映射类型与 key remapping",
    templateLiteralsType: "05 模板字面量类型",
    typeChallengeQuestionsZip: "类型挑战 100 题.zip",
    designTheSystemFromTo: "设计系统从 0 到 1",
    engineeringForTokenComponentLibraryAndDesignRDCollaboration:
      "Token、组件库与设计-研发协作的工程化落地",
    designSystem: "设计系统",
    suWan: "苏晚",
    seniorProductDesignerHeadOfDesignSystems: "资深产品设计师 · 设计系统负责人",
    theDesignSystemIsNotAUIKitButA:
      "设计系统不是一套 UI Kit，而是**一致性的工程化基础设施**。本课从 Design Token 体系讲到组件库 API 设计与设计-研发的协作流程。",
    chapterTheTokenSystem: "第一章 · Token 体系",
    whatIsADesignToken: "01 什么是设计 Token",
    semanticLayerVsBasicLayer: "02 语义层 vs 基础层",
    darkModeMultiTopics: "03 暗色模式与多主题",
    chapterComponentLibraryProject: "第二章 · 组件库工程",
    componentAPIDesignPrinciples: "04 组件 API 设计原则",
    accessibilityAndComposability: "05 无障碍与可组合性",
    tokenSpecificationTemplatePdf: "Token 规范模板.pdf",
    figmaVariableExportExampleJson: "Figma 变量导出示例.json",
    interfaceDynamicEffectDesignAndImplementation: "界面动效设计与实现",
    makingInteractionsAlivePrinciplesCurvesAndPerformanceOfDynamics:
      "让交互「有生命」——动效的原则、曲线与性能",
    dynamicEffect: "动效",
    interaction: "交互",
    heWei: "何缦",
    dynamicDesigner: "动效设计师",
    fromDisneySTwelvePrinciplesToTheEasingCurveTo:
      "从迪士尼十二原则到缓动曲线，再到 Web 动效的性能边界，建立你的动效审美与工程直觉。",
    chapterPrincipleOfKineticEffect: "第一章 · 动效原则",
    whyDoesKineticEffectExist: "01 动效为何存在",
    easingCurvesAndRhythms: "02 缓动曲线与节奏",
    chapterWebImplementation: "第二章 · Web 实现",
    transformWithSyntheticLayer: "03 transform 与合成层",
    reducedMotionAndAccessibility: "04 reduced-motion 与可达性",
    easingCurveQuickCheckPdf: "缓动曲线速查.pdf",
    practicalApplicationDevelopmentOfLargeModels: "大模型应用开发实战",
    fromPromptEngineeringToRagAgentToolCalls: "从 Prompt 工程到 RAG、Agent 与工具调用",
    zhouYe: "周野",
    aiApplicationEngineer: "AI 应用工程师",
    thisCourseFocusesOnLandingHowToConnectLargeModels:
      "本课程聚焦**落地**：如何把大模型接进真实产品。从 Prompt 工程的工程化，到 RAG 检索增强、Agent 编排与工具调用，每章都有可跑的项目。",
    chapterPromptProject: "第一章 · Prompt 工程",
    promptSStructuredDesign: "01 Prompt 的结构化设计",
    fewShotAndThoughtChain: "02 Few-shot 与思维链",
    outputConstraintsAndStructuralAnalysis: "03 输出约束与结构化解析",
    chapterRagRetrievalEnhancement: "第二章 · RAG 检索增强",
    vectorRetrievalAndSlicingStrategies: "04 向量检索与切片策略",
    rearrangementAndRecallEvaluation: "05 重排与召回评估",
    chapterAgentAndToolCalls: "第三章 · Agent 与工具调用",
    toolCallProtocol: "06 工具调用协议",
    multiStepTaskChoreographyAndGuardrails: "07 多步任务编排与护栏",
    projectCode: "项目代码",
    promptTemplateSetMd: "Prompt 模板集.md",
    fundamentalsOfMachineLearningMathematics: "机器学习数学基础",
    linearAlgebraProbabilityAndOptimizationCompletingTheFoundationOfML:
      "线性代数、概率与最优化——补齐 ML 的地基",
    mathematics: "数学",
    machineLearning: "机器学习",
    huoQing: "霍青",
    doctorOfAppliedMathematics: "应用数学博士",
    useGeometricIntuitionToUnderstandLinearAlgebraProbabilityDistributionAnd:
      "不靠死记公式，用几何直觉理解线性代数、概率分布与梯度下降，为深入机器学习打牢地基。",
    chapterLinearAlgebraicIntuition: "第一章 · 线性代数直觉",
    vectorAndSpace: "01 向量与空间",
    matricesAreTransformations: "02 矩阵即变换",
    chapterProbabilityAndOptimization: "第二章 · 概率与最优化",
    distributionAndExpectations: "03 分布与期望",
    gradientDescentGeometry: "04 梯度下降几何",
    formulaManualPdf: "公式手册.pdf",
    engineerExpressionAndInfluence: "工程师的表达与影响力",
    writeTechnicalDocumentationClarifyScenariosAndPromoteCrossTeamCollaboration:
      "写好技术文档、讲清方案、推动跨团队协作",
    communication: "沟通",
    document: "文档",
    collaboration: "协作",
    heYi: "贺一",
    technicalDirector: "技术总监",
    technicalAbilityDeterminesTheLowerLimitExpressionAndInfluenceDetermine:
      "技术能力决定下限，表达与影响力决定上限。本课教你结构化表达、写让人读得下去的文档、把方案讲到位。",
    chapterStructuredExpression: "第一章 · 结构化表达",
    pyramidPrinciple: "01 金字塔原理",
    makingComplexitySimple: "02 把复杂讲简单",
    chapterTechnicalWriting: "第二章 · 技术写作",
    readerAwarenessOfDocuments: "03 文档的读者意识",
    reviewAndPersuasion: "04 评审与说服",
    documentTemplatesZip: "文档模板.zip",
    programmerCareerAdvancementMap: "程序员职业进阶地图",
    planYourTechnicalAndCareerPathFromJuniorToSenior: "从初级到资深，规划你的技术与职业路径",
    careerPlanning: "职业规划",
    promotion: "晋升",
    lori: "罗芮",
    headOfTechnicalRecruitmentCareerCoach: "技术招聘负责人 · 职业教练",
    useAMapToSeeWhatAbilitiesShouldBeAccumulated:
      "用一张地图看清不同阶段该攒什么能力、避什么坑，把「努力」用在能复利的地方。",
    chapterAbilityCoordinates: "第一章 · 能力坐标",
    technicalDepthAndBreadth: "01 技术深度与广度",
    sourcesOfInfluence: "02 影响力的来源",
    chapterPromotionAndJobHopping: "第二章 · 晋升与跳槽",
    preparingForPromotionReview: "03 晋升评审准备",
    interviewsAndSalaryTalks: "04 面试与谈薪",
    competencySelfAssessmentFormPdf: "能力自评表.pdf",
    free: "免费",
    xiaXiaoman: "夏小满",
    learners: "学员",
    daysAgo: "2 天前",
    theClosureTrapMentionedInSectionIsTooInPlace:
      "第 4 节讲的闭包陷阱太到位了，之前一直没理解为什么 setState 拿到的是旧值。",
    instructor: "讲师",
    dayAgo: "1 天前",
    rememberThatEachRenderHasItsOwnSnapshotOfThe:
      "👍 记住「每次渲染都有自己的一份 state 快照」就通了，函数式更新能绕开它。",
    chenQi: "陈起",
    daysAgoAlternate: "5 天前",
    inTheVirtualizationSchemeInSectionWhatShouldBeDone:
      "请问第 8 节的虚拟化方案，列表项高度不固定时怎么处理？",
  },
  en: {
    frontEndDevelopment: "Front-end development",
    design: "Design",
    artificialIntelligence: "Artificial intelligence",
    careerGrowth: "Career growth",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    overview: "Overview",
    keyPointsDisassembly: "Key concept breakdown",
    handsOnDemonstration: "Hands-on demo",
    summary: "Summary",
    reactModernFrontEndEngineeringBattle: "Modern React Engineering in Practice",
    systemsLessonsFromComponentThinkingToHooksStateManagementAnd:
      "From component thinking to Hooks, state management, and performance",
    hayashiMikawa: "Lin Chuan",
    frontEndArchitectFormerManufacturerTechLead:
      "Front-end architect · Former tech lead at a major company",
    startingFromComponentizedThinkingThisCourseTakesYouThroughReact:
      "Starting with **component thinking**, this course explains React's rendering model, the mental model behind Hooks, state management, and performance work in real projects.\n\n- Understand why the APIs are designed this way\n- Run examples and exercises in every chapter\n- Apply advanced TypeScript types to production components",
    chapterComponentThinking: "Chapter 1 · Component thinking",
    courseGuidanceAndEnvironmentConstruction: "01 Course orientation and environment setup",
    componentsPropsAndCombinationsOutperformInheritance:
      "02 Components, props, and composition over inheritance",
    controlledVsUncontrolledComponents: "03 Controlled and uncontrolled components",
    chapterHooksModelOfMind: "Chapter 2 · The Hooks mental model",
    usestateAndRenderingTiming: "04 useState and rendering timing",
    closureTrap: "Closure traps",
    batchProcessing: "Batching",
    functionalUpdates: "Functional updates",
    useeffectDependenciesAndCleanup: "05 useEffect dependencies and cleanup",
    usememoUseCallbackWhenToUse: "06 useMemo and useCallback: when to use them",
    chapterStateManagementAndPerformance: "Chapter 3 · State management and performance",
    contextCorrectPosture: "07 The right way to use Context",
    listVirtualizationAndRenderingPerformance: "08 List virtualization and rendering performance",
    projectsInActionDashboardRefactoring: "09 Project: refactor a dashboard",
    courseMaterials: "Course materials",
    courseOutlinePdf: "Course outline.pdf",
    sampleSourceCodeZip: "Sample source code.zip",
    exerciseQuestionsAndAnswersMd: "Exercise solutions.md",
    cheatSheetHooksPdf: "Hooks cheat sheet.pdf",
    typescriptTypeGymnasticsAdvanced: "Advanced TypeScript Type Programming",
    writeTheTypeSystemAsALanguageAndEradicateAny:
      "Treat the type system as a language and eliminate unsafe any",
    typeSystem: "Type system",
    shenMo: "Shen Mo",
    openSourceAuthorTypeToolLibraryMaintainer:
      "Open-source author · Type utility library maintainer",
    genericsConditionTypesMappingTypesTemplateLiteralsThisLessonTakes:
      "Generics, conditional types, mapped types, and template literals turn TypeScript's type system into a **Turing-complete language**. This course applies them to real library APIs.",
    chapterGenericsAndConstraints: "Chapter 1 · Generics and constraints",
    natureOfGenerics: "01 How generics work",
    constraintsAndDefaultTypes: "02 Constraints and default types",
    chapterTypeOperations: "Chapter 2 · Type operations",
    conditionTypesAndInfers: "03 Conditional types and infer",
    mappingTypesAndKeyRemapping: "04 Mapped types and key remapping",
    templateLiteralsType: "05 Template literal types",
    typeChallengeQuestionsZip: "100 Type Challenges.zip",
    designTheSystemFromTo: "Build a Design System from 0 to 1",
    engineeringForTokenComponentLibraryAndDesignRDCollaboration:
      "Engineering design tokens, component libraries, and designer-developer collaboration",
    designSystem: "Design systems",
    suWan: "Su Wan",
    seniorProductDesignerHeadOfDesignSystems: "Senior product designer · Design systems lead",
    theDesignSystemIsNotAUIKitButA:
      "A design system is more than a UI kit: it is **consistent, engineered infrastructure**. Learn design token architecture, component API design, and a practical designer-developer workflow.",
    chapterTheTokenSystem: "Chapter 1 · Design token system",
    whatIsADesignToken: "01 What is a design token?",
    semanticLayerVsBasicLayer: "02 Semantic and primitive tokens",
    darkModeMultiTopics: "03 Dark mode and themes",
    chapterComponentLibraryProject: "Chapter 2 · Building a component library",
    componentAPIDesignPrinciples: "04 Component API design principles",
    accessibilityAndComposability: "05 Accessibility and composability",
    tokenSpecificationTemplatePdf: "Design token specification.pdf",
    figmaVariableExportExampleJson: "Figma variable export.json",
    interfaceDynamicEffectDesignAndImplementation: "Designing and Implementing UI Motion",
    makingInteractionsAlivePrinciplesCurvesAndPerformanceOfDynamics:
      "Bring interactions to life: motion principles, easing curves, and performance",
    dynamicEffect: "Motion design",
    interaction: "Interaction",
    heWei: "He Wei",
    dynamicDesigner: "Motion designer",
    fromDisneySTwelvePrinciplesToTheEasingCurveTo:
      "From Disney's 12 principles through easing curves and web performance boundaries, build sound motion instincts for both design and engineering.",
    chapterPrincipleOfKineticEffect: "Chapter 1 · Principles of motion",
    whyDoesKineticEffectExist: "01 Why motion matters",
    easingCurvesAndRhythms: "02 Easing curves and rhythm",
    chapterWebImplementation: "Chapter 2 · Web implementation",
    transformWithSyntheticLayer: "03 Transforms and compositor layers",
    reducedMotionAndAccessibility: "04 Reduced motion and accessibility",
    easingCurveQuickCheckPdf: "Easing curve cheat sheet.pdf",
    practicalApplicationDevelopmentOfLargeModels: "Building Production LLM Applications",
    fromPromptEngineeringToRagAgentToolCalls:
      "From prompt engineering to RAG, agents, and tool calling",
    zhouYe: "Zhou Ye",
    aiApplicationEngineer: "AI Application Engineer",
    thisCourseFocusesOnLandingHowToConnectLargeModels:
      "This course focuses on **shipping** LLM features in real products. Each chapter includes a runnable project, from structured prompts through RAG retrieval, reranking, agent orchestration, and tool calling.",
    chapterPromptProject: "Chapter 1 · Prompt engineering",
    promptSStructuredDesign: "01 Structuring prompts",
    fewShotAndThoughtChain: "02 Few-shot prompting and chain-of-thought",
    outputConstraintsAndStructuralAnalysis: "03 Output constraints and structured parsing",
    chapterRagRetrievalEnhancement: "Chapter 2 · Retrieval-augmented generation (RAG)",
    vectorRetrievalAndSlicingStrategies: "04 Vector retrieval and chunking",
    rearrangementAndRecallEvaluation: "05 Reranking and recall evaluation",
    chapterAgentAndToolCalls: "Chapter 3 · Agents and tool calling",
    toolCallProtocol: "06 The tool-calling protocol",
    multiStepTaskChoreographyAndGuardrails: "07 Multi-step orchestration and guardrails",
    projectCode: "Project source code",
    promptTemplateSetMd: "Prompt templates.md",
    fundamentalsOfMachineLearningMathematics: "Mathematics for Machine Learning",
    linearAlgebraProbabilityAndOptimizationCompletingTheFoundationOfML:
      "Linear algebra, probability, and optimization for a solid ML foundation",
    mathematics: "Mathematics",
    machineLearning: "Machine Learning",
    huoQing: "Huo Qing",
    doctorOfAppliedMathematics: "Applied mathematics PhD",
    useGeometricIntuitionToUnderstandLinearAlgebraProbabilityDistributionAnd:
      "Use geometric intuition to understand linear algebra, probability distributions, and gradient descent without relying on rote memorization.",
    chapterLinearAlgebraicIntuition: "Chapter 1 · Linear algebra intuition",
    vectorAndSpace: "01 Vectors and spaces",
    matricesAreTransformations: "02 Matrices as transformations",
    chapterProbabilityAndOptimization: "Chapter 2 · Probability and optimization",
    distributionAndExpectations: "03 Distributions and expectations",
    gradientDescentGeometry: "04 The geometry of gradient descent",
    formulaManualPdf: "Formula handbook.pdf",
    engineerExpressionAndInfluence: "Communication and Influence for Engineers",
    writeTechnicalDocumentationClarifyScenariosAndPromoteCrossTeamCollaboration:
      "Write clear technical documents, align decisions, and collaborate across teams",
    communication: "Communication",
    document: "Document",
    collaboration: "Collaboration",
    heYi: "He Yi",
    technicalDirector: "Engineering leader",
    technicalAbilityDeterminesTheLowerLimitExpressionAndInfluenceDetermine:
      "Technical skill sets your floor; communication and influence raise your ceiling. Learn to structure an argument, write for busy readers, and move a proposal toward a decision.",
    chapterStructuredExpression: "Chapter 1 · Structured communication",
    pyramidPrinciple: "01 The Pyramid Principle",
    makingComplexitySimple: "02 Make complexity clear",
    chapterTechnicalWriting: "Chapter 2 · Technical writing",
    readerAwarenessOfDocuments: "03 Write for your reader",
    reviewAndPersuasion: "04 Reviews and persuasion",
    documentTemplatesZip: "Technical writing templates.zip",
    programmerCareerAdvancementMap: "Software Engineer Career Roadmap",
    planYourTechnicalAndCareerPathFromJuniorToSenior: "Plan a path from junior to senior engineer",
    careerPlanning: "Career planning",
    promotion: "Career growth",
    lori: "Luo Rui",
    headOfTechnicalRecruitmentCareerCoach: "Technical recruiting lead · Career coach",
    useAMapToSeeWhatAbilitiesShouldBeAccumulated:
      "See which capabilities matter at each career stage, avoid common traps, and invest your effort where it can compound.",
    chapterAbilityCoordinates: "Chapter 1 · Capability map",
    technicalDepthAndBreadth: "01 Technical depth and breadth",
    sourcesOfInfluence: "02 Sources of influence",
    chapterPromotionAndJobHopping: "Chapter 2 · Promotion and job changes",
    preparingForPromotionReview: "03 Preparing for a promotion review",
    interviewsAndSalaryTalks: "04 Interviews and compensation discussions",
    competencySelfAssessmentFormPdf: "Capability self-assessment.pdf",
    free: "Free",
    xiaXiaoman: "Xia Xiaoman",
    learners: "Learners",
    daysAgo: "2 days ago",
    theClosureTrapMentionedInSectionIsTooInPlace:
      "The closure explanation in lesson 4 finally made stale state click for me. I hadn't understood why setState read the old value.",
    instructor: "Instructor",
    dayAgo: "1 day ago",
    rememberThatEachRenderHasItsOwnSnapshotOfThe:
      "👍 Remember: each render owns a snapshot of state. Use a functional update when the next value depends on the previous one.",
    chenQi: "Chen Qi",
    daysAgoAlternate: "5 days ago",
    inTheVirtualizationSchemeInSectionWhatShouldBeDone:
      "For the virtualization approach in lesson 8, how should we handle list items with variable heights?",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>(
    (text, value, index) => text.replaceAll(`{${index}}`, String(value)),
    content[DOCS_LOCALE][key],
  );
}

const dictionary: Dictionary = {
  key: "demo-learn-data-courses",
  content: t(content),
};

export default dictionary;
