import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "shenYanzhi": "沈砚之",
    "owner": "拥有者",
    "sink": "沈",
    "luHeng": "陆衡",
    "administrator": "管理员",
    "land": "陆",
    "zhouNan": "周南",
    "member": "成员",
    "week": "周",
    "hanXu": "韩叙",
    "member2": "成员",
    "korea": "韩",
    "xuQing": "许清",
    "readOnly": "只读",
    "xu": "许",
    "accountSettings": "账户设置",
    "manageYourProfileTeamsAndNotificationPreferences": "管理你的资料、团队与通知偏好。",
    "personalData": "个人资料",
    "setWorkingStatusEmoticon": "设置工作状态表情",
    "jobStatusUpdatedToValue": "工作状态已更新为 {0}",
    "owner2": "拥有者",
    "currentStatus": "当前状态：{0}",
    "saySomething": "说点什么…",
    "teamMember": "团队成员",
    "seatsAlreadyUsed": "已使用 {0} / {1} 席",
    "activeIn": "活跃于",
    "billNotification": "账单通知",
    "depositsAndDeductions": "出账与扣款",
    "emailNotificationForEachSuccessfulFailedDeduction": "每次成功 / 失败扣款邮件通知",
    "usageWarning": "用量预警",
    "alertWhenResourceUsageReaches": "资源用量达 90% 时提醒",
    "productNews": "产品动态",
    "newFeaturesAndPromotions": "新功能与优惠活动",
    "subscriptionStatus": "订阅状态",
    "annualPayment": "年付",
    "monthlyPayment": "月付",
    "subscriptionSummary": "当前为 {0}（{1}）· {2} 席 · {3}/月",
    "recordedAndCanBeRestoredAtAny": "已记录，可在续费日前随时恢复",
    "unsubscribe": "取消订阅",
    "afterCancellationTheServiceWillContinueUntil": "取消后服务将持续到本计费周期结束，到期不再续费，数据保留 90 天。",
  },
  en: {
    "shenYanzhi": "Shen Yanzhi",
    "owner": "Owner",
    "sink": "SY",
    "luHeng": "Lu Heng",
    "administrator": "Administrator",
    "land": "LH",
    "zhouNan": "Zhou Nan",
    "member": "Member",
    "week": "ZN",
    "hanXu": "Han Xu",
    "member2": "Member",
    "korea": "HX",
    "xuQing": "Xu Qing",
    "readOnly": "Read only",
    "xu": "XQ",
    "accountSettings": "Account settings",
    "manageYourProfileTeamsAndNotificationPreferences": "Manage your profile, teams and notification preferences.",
    "personalData": "Profile",
    "setWorkingStatusEmoticon": "Set working status emoticon",
    "jobStatusUpdatedToValue": "Job status updated to {0}",
    "owner2": "Owner",
    "currentStatus": "Current status: {0}",
    "saySomething": "Say something...",
    "teamMember": "Team members",
    "seatsAlreadyUsed": "{0} of {1} seats used",
    "activeIn": "Active ",
    "billNotification": "Billing notifications",
    "depositsAndDeductions": "Payment activity",
    "emailNotificationForEachSuccessfulFailedDeduction": "Email me after each successful or failed payment",
    "usageWarning": "Usage warning",
    "alertWhenResourceUsageReaches": "Alert when resource usage reaches 90%",
    "productNews": "Product news",
    "newFeaturesAndPromotions": "New features and promotions",
    "subscriptionStatus": "Subscription",
    "annualPayment": "annual billing",
    "monthlyPayment": "monthly billing",
    "subscriptionSummary": "Current plan: {0} ({1}) · {2} seats · {3}/month",
    "recordedAndCanBeRestoredAtAny": "Cancellation scheduled. You can undo it before the renewal date.",
    "unsubscribe": "Cancel subscription",
    "afterCancellationTheServiceWillContinueUntil": "After cancellation, the service will continue until the end of this billing cycle and will not be renewed upon expiration. Data will be retained for 90 days.",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-billing-app-settings-page",
  content: t(content),
};

export default dictionary;
