import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    hanselectHostAnan: "瀚选优品 · 主播阿楠",
    text286kFollowers326Streams: "粉丝 28.6w · 直播 326 场",
    theHostIsAmazing: "主播好飒！",
    doesThisJacketComeInPlusSizes: "这件外套有大码吗",
    pleaseShareProduct3: "求 3 号链接",
    canThePriceGoAnyLower: "价格还能再低点不",
    orderedWaitingForDelivery: "已拍下，等发货~",
    isTheFabricPureCotton: "面料是纯棉的吗",
    firstTimeInTheStream: "新人第一次进直播间",
    fanBadgeSupport: "灯牌应援 🔆",
    frontrowviewer: "前排围观",
    theHostSoundsGreat: "主播声音真好听",
    thisIsAGreatDeal: "这个真的划算",
    waitingToSeeTheFit: "蹲一个上身效果",
    isShippingFree: "包邮吗包邮吗",
    iBoughtThisBeforeGreatQuality: "买过，质量很好",
    whenWillItShip: "什么时候发货呀",
    howManyColorsAreThere: "颜色有几种",
    likedFollowedAndShared: "已三连 ❤️",
    canIGetACoupon: "求个优惠券",
    tellUsAboutTheInsulatedBottle: "讲讲保温杯那个",
    justOrdered: "下单了下单了",
    isThisAvailableInXl: "这件有 XL 码吗？",
    howManyMillilitersDoesTheBottleHold: "保温杯能装多少毫升？",
    howLongDoTheHeadphonesLast: "耳机续航多久？",
    canTheAmbientLightChangeColors: "氛围灯能调色吗？",
    doesTheJacketShed: "外套掉毛吗？",
    whenWillItShip2: "什么时候发货？",
    doYouOfferSevenDayReturns: "支持七天无理由吗？",
    abai: "阿白",
    nightvoyager: "夜航船",
    deer: "小鹿",
    doudoudragon: "豆豆龙",
    titmouse: "山雀",
    seabreeze: "海风",
    ananfan: "阿楠的粉",
    colanoice: "可乐不加冰",
    eveningbreeze: "晚风",
    sunflower: "向日葵",
    returningcustomerzhang: "老顾客张姐",
    techfan: "数码控",
    savvyshopper: "省钱小能手",
    xixi: "西西",
    bigspender: "土豪哥",
    icecream: "甜筒",
    chestnut: "栗子",
    azhou: "阿洲",
    heart: "小心心",
    lollipop: "棒棒糖",
    rocket: "火箭",
    sportsCar: "跑车",
    castle: "城堡",
    unisexHeavyweightWinterSherpaJacketLiveExclusivePrice: "冬季加厚羊羔绒外套 男女同款 直播专享价",
    flashSale: "秒杀",
    text500MlPortable316StainlessSteelInsulatedBottle: "316 不锈钢便携保温杯 500ml 长效保温",
    wirelessAncHeadphonesWith30HourBatteryLife: "主动降噪无线蓝牙耳机 30h 续航",
    limited: "限量",
    desktopRgbSmartAmbientLightWithAppControls: "桌面 RGB 智能氛围灯 APP 调色",
    fourPieceAntibacterialCottonBeddingSetForA18MBed: "纯棉抗菌四件套 裸睡级亲肤 1.8m 床",
    flickerFreeAaRatedDeskLampWithThreeColorTemperatures: "护眼台灯 国 AA 级 无频闪 三色温",
    thisStyleComesInSizesSXxlOpenProduct1ForTheSizeChartAndChooseYourUsualSize: "亲，这款有 S–XXL 全码段，1 号链接详情页有尺码表，按平时码拍就好~",
    product2Holds500MlUsesAFoodGrade316StainlessSteelLinerAndStaysAt58CAfterSixHours: "2 号保温杯净容量 500ml，316 食品级内胆，6 小时仍有 58℃ 哦。",
    product3LastsEightHoursPerChargeAnd30HoursWithTheCaseWithUpTo42DbOfActiveNoiseCancellation: "3 号耳机单次 8 小时、配充电仓共 30 小时，主动降噪 -42dB。",
    product4Supports16MillionAppControlledColorsAndMusicSyncOrderTonightToReceiveARemoteControl: "4 号氛围灯支持 APP 1600 万色 + 音乐律动，今晚下单送遥控。",
    ordersPlacedTonightShipWithin48HoursJiangsuZhejiangAndShanghaiReceiveNextDayDeliveryRemoteAreasM: "今晚下单 48 小时内发货，江浙沪次日达，偏远地区顺延~",
    everyItemIncludesSevenDayReturnsAndShippingInsuranceSoYouCanOrderWithConfidence: "全店支持七天无理由退换，运费险已赠，放心拍~",
    iSawYourQuestionTheHostWillAnswerItOnAirShortly: "这位宝宝的问题我看到啦，稍等主播口播解答一下哈~",
    viewershipIsRecoveringOfferAStackableLimitedTimeCouponForProduct1ToConvertTheNewTraffic: "在线人数回升，建议现在抛出 1 号外套的限时叠加券承接流量。",
    deliveryQuestionsAreIncreasingInChatStateTheShippingTimeframeOnAirToReduceUncertainty: "弹幕里「发货」提问变多，口播一次发货时效可降低疑虑。",
    product3HasStrongWatchTimeButLowConversionAddAQuickBatteryLifeComparisonWithCompetitors: "3 号耳机停留时长高但转化低，建议补一句续航对比竞品。",
    engagementIsFallingACommentToEnterGiveawayCouldImproveRetention: "互动率走低，发起一次「扣 1 抽免单」可拉回停留。",
    newViewersMakeUp41OfTheAudienceRepeatTheGiveawayRules: "新观众占比 41%，建议重复一次福袋玩法规则。",
    featureProduct1: "上架 1 号链接",
    theSherpaJacketIsNowFeaturedInTheAudienceShoppingPanel: "已把「羊羔绒外套」置为讲解中并弹出小黄车。",
    send70OffCoupons: "发放 3 折券",
    sent100LimitedTime70OffCouponsToViewersValidForTenMinutes: "已对在线观众发放 100 张 3 折秒杀券，有效期 10 分钟。",
    pinTopQuestion: "置顶高赞提问",
    pinnedThePlusSizeQuestionForTheHostToAnswerForEveryone: "已把「有大码吗」置顶到公屏，方便统一解答。",
    startGiveaway: "开启福袋",
    startedTheFollowToEnterFreeOrderGiveawayTheWinnerIsDrawnIn60Seconds: "已开启「关注抽免单」福袋，60 秒后开奖。",
  },
  en: {
    hanselectHostAnan: "HanSelect · Host Anan",
    text286kFollowers326Streams: "286K followers · 326 streams",
    theHostIsAmazing: "The host is amazing!",
    doesThisJacketComeInPlusSizes: "Does this jacket come in plus sizes?",
    pleaseShareProduct3: "Please share product 3",
    canThePriceGoAnyLower: "Can the price go any lower?",
    orderedWaitingForDelivery: "Ordered! Waiting for delivery.",
    isTheFabricPureCotton: "Is the fabric pure cotton?",
    firstTimeInTheStream: "First time in the stream",
    fanBadgeSupport: "Fan badge support 🔆",
    frontrowviewer: "FrontRowViewer",
    theHostSoundsGreat: "The host sounds great",
    thisIsAGreatDeal: "This is a great deal",
    waitingToSeeTheFit: "Waiting to see the fit",
    isShippingFree: "Is shipping free?",
    iBoughtThisBeforeGreatQuality: "I bought this before. Great quality.",
    whenWillItShip: "When will it ship?",
    howManyColorsAreThere: "How many colors are there?",
    likedFollowedAndShared: "Liked, followed, and shared ❤️",
    canIGetACoupon: "Can I get a coupon?",
    tellUsAboutTheInsulatedBottle: "Tell us about the insulated bottle",
    justOrdered: "Just ordered!",
    isThisAvailableInXl: "Is this available in XL?",
    howManyMillilitersDoesTheBottleHold: "How many milliliters does the bottle hold?",
    howLongDoTheHeadphonesLast: "How long do the headphones last?",
    canTheAmbientLightChangeColors: "Can the ambient light change colors?",
    doesTheJacketShed: "Does the jacket shed?",
    whenWillItShip2: "When will it ship?",
    doYouOfferSevenDayReturns: "Do you offer seven-day returns?",
    abai: "Abai",
    nightvoyager: "NightVoyager",
    deer: "Deer",
    doudoudragon: "DoudouDragon",
    titmouse: "Titmouse",
    seabreeze: "SeaBreeze",
    ananfan: "AnanFan",
    colanoice: "ColaNoIce",
    eveningbreeze: "EveningBreeze",
    sunflower: "Sunflower",
    returningcustomerzhang: "ReturningCustomerZhang",
    techfan: "TechFan",
    savvyshopper: "SavvyShopper",
    xixi: "Xixi",
    bigspender: "BigSpender",
    icecream: "IceCream",
    chestnut: "Chestnut",
    azhou: "Azhou",
    heart: "Heart",
    lollipop: "Lollipop",
    rocket: "Rocket",
    sportsCar: "Sports car",
    castle: "Castle",
    unisexHeavyweightWinterSherpaJacketLiveExclusivePrice: "Unisex heavyweight winter sherpa jacket · Live-exclusive price",
    flashSale: "Flash sale",
    text500MlPortable316StainlessSteelInsulatedBottle: "500 ml portable 316 stainless-steel insulated bottle",
    wirelessAncHeadphonesWith30HourBatteryLife: "Wireless ANC headphones with 30-hour battery life",
    limited: "Limited",
    desktopRgbSmartAmbientLightWithAppControls: "Desktop RGB smart ambient light with app controls",
    fourPieceAntibacterialCottonBeddingSetForA18MBed: "Four-piece antibacterial cotton bedding set for a 1.8 m bed",
    flickerFreeAaRatedDeskLampWithThreeColorTemperatures: "Flicker-free AA-rated desk lamp with three color temperatures",
    thisStyleComesInSizesSXxlOpenProduct1ForTheSizeChartAndChooseYourUsualSize: "This style comes in sizes S–XXL. Open product 1 for the size chart and choose your usual size.",
    product2Holds500MlUsesAFoodGrade316StainlessSteelLinerAndStaysAt58CAfterSixHours: "Product 2 holds 500 ml, uses a food-grade 316 stainless-steel liner, and stays at 58°C after six hours.",
    product3LastsEightHoursPerChargeAnd30HoursWithTheCaseWithUpTo42DbOfActiveNoiseCancellation: "Product 3 lasts eight hours per charge and 30 hours with the case, with up to 42 dB of active noise cancellation.",
    product4Supports16MillionAppControlledColorsAndMusicSyncOrderTonightToReceiveARemoteControl: "Product 4 supports 16 million app-controlled colors and music sync. Order tonight to receive a remote control.",
    ordersPlacedTonightShipWithin48HoursJiangsuZhejiangAndShanghaiReceiveNextDayDeliveryRemoteAreasM: "Orders placed tonight ship within 48 hours. Jiangsu, Zhejiang, and Shanghai receive next-day delivery; remote areas may take longer.",
    everyItemIncludesSevenDayReturnsAndShippingInsuranceSoYouCanOrderWithConfidence: "Every item includes seven-day returns and shipping insurance, so you can order with confidence.",
    iSawYourQuestionTheHostWillAnswerItOnAirShortly: "I saw your question. The host will answer it on air shortly.",
    viewershipIsRecoveringOfferAStackableLimitedTimeCouponForProduct1ToConvertTheNewTraffic: "Viewership is recovering. Offer a stackable limited-time coupon for product 1 to convert the new traffic.",
    deliveryQuestionsAreIncreasingInChatStateTheShippingTimeframeOnAirToReduceUncertainty: "Delivery questions are increasing in chat. State the shipping timeframe on air to reduce uncertainty.",
    product3HasStrongWatchTimeButLowConversionAddAQuickBatteryLifeComparisonWithCompetitors: "Product 3 has strong watch time but low conversion. Add a quick battery-life comparison with competitors.",
    engagementIsFallingACommentToEnterGiveawayCouldImproveRetention: "Engagement is falling. A comment-to-enter giveaway could improve retention.",
    newViewersMakeUp41OfTheAudienceRepeatTheGiveawayRules: "New viewers make up 41% of the audience. Repeat the giveaway rules.",
    featureProduct1: "Feature product 1",
    theSherpaJacketIsNowFeaturedInTheAudienceShoppingPanel: "The sherpa jacket is now featured in the audience shopping panel.",
    send70OffCoupons: "Send 70%-off coupons",
    sent100LimitedTime70OffCouponsToViewersValidForTenMinutes: "Sent 100 limited-time 70%-off coupons to viewers, valid for ten minutes.",
    pinTopQuestion: "Pin top question",
    pinnedThePlusSizeQuestionForTheHostToAnswerForEveryone: "Pinned the plus-size question for the host to answer for everyone.",
    startGiveaway: "Start giveaway",
    startedTheFollowToEnterFreeOrderGiveawayTheWinnerIsDrawnIn60Seconds: "Started the follow-to-enter free-order giveaway. The winner is drawn in 60 seconds.",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>(
    (text, value, index) => text.replaceAll(`{${index}}`, String(value)),
    content[DOCS_LOCALE][key],
  );
}

const dictionary: Dictionary = {
  key: "demo-live-data-content",
  content: t(content),
};

export default dictionary;
