import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "closingParenthesis": "）",
    "taxFree": "免税",
    "hulianConstructionEngineeringGroupCoLtd": "瑚琏建工集团有限公司",
    "noJiangnanAvenueBinjiangDistrictHangzhou": "杭州市滨江区江南大道 1788 号",
    "industrialAndCommercialBankOfChinaHangzhou": "工商银行杭州滨江支行 1202 0000 1234 5678",
    "chenGong": "陈工 · 0571-8888 6666",
    "theQuotationDoesNotExist": "报价单不存在",
    "theQuotationMayHaveBeenDeletedDemo": "该报价单可能已被删除（demo 内存态，刷新还原）。",
    "returnToQuoteList": "返回报价列表",
    "projectName": "项目名称",
    "specificationsModels": "规格 / 型号",
    "unit": "单位",
    "quantity": "数量",
    "quantity2": "数量",
    "unitPrice": "单价",
    "unitPrice2": "单价",
    "subtotal": "小计",
    "deleteThisLine": "删除此行？",
    "thisDetailRowCannotBeRestoredAfter": "该明细行删除后无法还原。",
    "delete": "删除",
    "detailRowDeleted": "已删除明细行",
    "delete2": "删除",
    "deleteRow": "删除行",
    "draftSaved": "草稿已保存",
    "quotationHasBeenGenerated": "报价单已生成",
    "valueHasBeenSavedAsTheOfficial": "{0} 已保存为正式版",
    "edit": "编辑",
    "previewPrint": "预览 / 打印",
    "return": "返回",
    "returnToQuoteList2": "返回报价列表",
    "saveDraft": "保存草稿",
    "generateDocuments": "生成单据",
    "partyARaisesItsHead": "甲方抬头",
    "relatedProjects": "关联项目",
    "validUntil": "有效期至",
    "taxRate": "税率",
    "remarks": "备注",
    "newItem": "新分项",
    "item": "项",
    "totalExcludingTax": "合计（不含税）",
    "taxAmount": "税额（",
    "totalPriceAndTax": "价税合计",
    "totalPriceAndTaxInCapitalLetters": "价税合计大写：",
    "projectQuotationQuotation": "工程报价单 · QUOTATION",
    "orderMakingDate": "制单日期：",
    "validUntil2": "有效期至：",
    "customerInformation": "客户信息",
    "partyA": "甲方：",
    "project": "项目：",
    "orderMaker": "制单人：",
    "quotationDetails": "报价明细",
    "serialNumber": "序号",
    "projectName2": "项目名称",
    "specifications": "规格",
    "unit2": "单位",
    "quantity3": "数量",
    "unitPrice3": "单价",
    "subtotal2": "小计",
    "totalExcludingTax2": "合计（不含税）",
    "taxAmount2": "税额（",
    "totalPriceAndTax2": "价税合计",
    "uppercase": "大写：",
    "remarks2": "备注",
    "accountOpeningBank": "开户行：",
    "taxIdNumber": "税号：",
    "address": "地址：",
    "contactPerson": "联系人：",
    "sellerSSignature": "销售方签章",
  },
  en: {
    "closingParenthesis": ")",
    "taxFree": "Tax free",
    "hulianConstructionEngineeringGroupCoLtd": "Hulian Construction Engineering Group Co., Ltd.",
    "noJiangnanAvenueBinjiangDistrictHangzhou": "No. 1788 Jiangnan Avenue, Binjiang District, Hangzhou",
    "industrialAndCommercialBankOfChinaHangzhou": "Industrial and Commercial Bank of China Hangzhou Binjiang Branch 1202 0000 1234 5678",
    "chenGong": "Chen Gong · 0571-8888 6666",
    "theQuotationDoesNotExist": "The quote does not exist",
    "theQuotationMayHaveBeenDeletedDemo": "The quote may have been deleted (stored in memory for this demo; reload to restore).",
    "returnToQuoteList": "Return to quote list",
    "projectName": "Project name",
    "specificationsModels": "Specifications/Models",
    "unit": "unit",
    "quantity": "Quantity",
    "quantity2": "Quantity",
    "unitPrice": "unit price",
    "unitPrice2": "unit price",
    "subtotal": "Subtotal",
    "deleteThisLine": "Delete this line?",
    "thisDetailRowCannotBeRestoredAfter": "This detail row cannot be restored after being deleted.",
    "delete": "Delete",
    "detailRowDeleted": "Detail row deleted",
    "delete2": "Delete",
    "deleteRow": "Delete row",
    "draftSaved": "Draft saved",
    "quotationHasBeenGenerated": "Quote has been generated",
    "valueHasBeenSavedAsTheOfficial": "{0} has been saved as the official version",
    "edit": "Edit",
    "previewPrint": "Preview/Print",
    "return": "Return",
    "returnToQuoteList2": "Return to quote list",
    "saveDraft": "save draft",
    "generateDocuments": "Generate quote",
    "partyARaisesItsHead": "Bill to",
    "relatedProjects": "Related projects",
    "validUntil": "Valid until",
    "taxRate": "tax rate",
    "remarks": "Remarks",
    "newItem": "New item",
    "item": "item",
    "totalExcludingTax": "Total (excluding tax)",
    "taxAmount": "tax amount (",
    "totalPriceAndTax": "Total incl. tax",
    "totalPriceAndTaxInCapitalLetters": "Amount in words:",
    "projectQuotationQuotation": "Project quote · QUOTATION",
    "orderMakingDate": "Order making date:",
    "validUntil2": "Valid until:",
    "customerInformation": "Customer information",
    "partyA": "Client:",
    "project": "Project:",
    "orderMaker": "Prepared by:",
    "quotationDetails": "Quote details",
    "serialNumber": "serial number",
    "projectName2": "Project name",
    "specifications": "Specifications",
    "unit2": "unit",
    "quantity3": "Quantity",
    "unitPrice3": "unit price",
    "subtotal2": "Subtotal",
    "totalExcludingTax2": "Total (excluding tax)",
    "taxAmount2": "tax amount (",
    "totalPriceAndTax2": "Total incl. tax",
    "uppercase": "Amount in words:",
    "remarks2": "Remarks",
    "accountOpeningBank": "Account opening bank:",
    "taxIdNumber": "Tax ID number:",
    "address": "Address:",
    "contactPerson": "Contact person:",
    "sellerSSignature": "Seller's signature",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-projects-components-quote-editor",
  content: t(content),
};

export default dictionary;
