import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "closingParenthesis": "）",
    "all": "全部",
    "applyForInvoicing": "申请开票",
    "projectSubmission": "项目提交",
    "financialReview": "财务审核",
    "amountReview": "金额复核",
    "issueAnInvoice": "开具发票",
    "taxControlIssuance": "税控开具",
    "deliveredByMail": "邮寄送达",
    "sendToPartyA": "寄送甲方",
    "hulianConstructionEngineeringGroupCoLtd": "瑚琏建工集团有限公司",
    "noJiangnanAvenueBinjiangDistrictHangzhou": "杭州市滨江区江南大道 1788 号 · 0571-8888 6666",
    "industrialAndCommercialBankOfChinaHangzhou": "工商银行杭州滨江支行 1202 0000 1234 5678",
    "invoiced": "已开票",
    "valueIssuanceSuccessful": "{0} 开具成功",
    "voided": "已作废",
    "valueHasBeenInvalidatedAndCanBe": "{0} 已作废，可重新开具",
    "invoice": "发票",
    "buyerSHead": "购方抬头",
    "type": "类型",
    "invoiceAmount": "开票金额",
    "balanceReceivable": "应收余额",
    "invoicingStatus": "开票状态",
    "refund": "回款",
    "operation": "操作",
    "view": "查看",
    "invoicing": "开票",
    "areYouSureYouWantToVoid": "确认作废此发票？",
    "afterBeingInvalidatedTheStatusWillReturn": "作废后状态将退回「待开」，不可恢复。",
    "confirmedToBeInvalid": "确认作废",
    "void": "作废",
    "total": "共",
    "zhangHasSentAnInvoiceWithAn": "张已寄送发票存在逾期应收余额，请跟进回款。",
    "invoicedAmount": "已开票金额",
    "accumulatedRepayments": "累计回款",
    "balanceToBeRepaid": "待回款余额",
    "invoicingAndPaymentCollection": "开票与回款",
    "keywords": "关键词",
    "invoiceNumberItemPurchaser": "发票号 / 项目 / 购方",
    "invoicingStatus2": "开票状态",
    "paymentStatus": "回款状态",
    "valueInvoiceDetails": "{0} · 发票详情",
    "invoiceAmount2": "开票金额",
    "refunded": "已回款",
    "balanceReceivable2": "应收余额",
    "theInvoiceHasBeenSentButExists": "该发票已寄送但存在",
    "forTheBalanceReceivablePleaseContactParty": "应收余额，请联系甲方跟进回款。",
    "invoicingAndCirculation": "开票流转",
    "invoiceDateValue": "开票日期：{0}",
    "notYetIssued": "尚未开具",
    "print": "打印",
    "printInvoice": "打印发票",
    "purchaseAndSaleInformation": "购销信息",
    "purchaser": "购买方：",
    "taxNumber": "（税号",
    "seller": "销售方：",
    "taxNumber2": "（税号",
    "relatedProjects": "关联项目：",
    "amount": "金额",
    "amountExcludingTax": "金额（不含税）",
    "taxAmount": "税额（",
    "totalPriceAndTax": "价税合计",
    "uppercase": "大写：",
    "accountOpeningBank": "开户行：",
    "address": "· 地址：",
    "invoiceNow": "立即开票",
    "areYouSureYouWantToVoid2": "确认作废此发票？",
    "afterBeingInvalidatedTheStatusWillReturn2": "作废后状态将退回「待开」，不可恢复。",
    "confirmedToBeInvalid2": "确认作废",
    "voidInvoice": "作废发票",
    "paymentRecord": "回款记录",
    "total2": "共",
    "noRecordOfPaymentYet": "暂无回款记录",
  },
  en: {
    "closingParenthesis": ")",
    "all": "All",
    "applyForInvoicing": "Apply for invoicing",
    "projectSubmission": "Project handoff",
    "financialReview": "financial review",
    "amountReview": "Amount review",
    "issueAnInvoice": "Issue an invoice",
    "taxControlIssuance": "Tax control issuance",
    "deliveredByMail": "Delivered by mail",
    "sendToPartyA": "Send to client",
    "hulianConstructionEngineeringGroupCoLtd": "Hulian Construction Engineering Group Co., Ltd.",
    "noJiangnanAvenueBinjiangDistrictHangzhou": "No. 1788 Jiangnan Avenue, Binjiang District, Hangzhou · 0571-8888 6666",
    "industrialAndCommercialBankOfChinaHangzhou": "Industrial and Commercial Bank of China Hangzhou Binjiang Branch 1202 0000 1234 5678",
    "invoiced": "Invoiced",
    "valueIssuanceSuccessful": "{0} issuance successful",
    "voided": "voided",
    "valueHasBeenInvalidatedAndCanBe": "{0} was voided and can be reissued",
    "invoice": "Invoice",
    "buyerSHead": "Client",
    "type": "Type",
    "invoiceAmount": "Invoice amount",
    "balanceReceivable": "Balance receivable",
    "invoicingStatus": "Invoicing status",
    "refund": "Payment status",
    "operation": "Operation",
    "view": "View",
    "invoicing": "Invoicing",
    "areYouSureYouWantToVoid": "Are you sure you want to void this invoice?",
    "afterBeingInvalidatedTheStatusWillReturn": "Voiding this invoice returns it to Pending issue. This action cannot be undone.",
    "confirmedToBeInvalid": "Void invoice",
    "void": "Void",
    "total": "There are ",
    "zhangHasSentAnInvoiceWithAn": " sent invoices with overdue balances. Follow up on payment.",
    "invoicedAmount": "Invoiced amount",
    "accumulatedRepayments": "Payments received",
    "balanceToBeRepaid": "Outstanding receivables",
    "invoicingAndPaymentCollection": "Invoices and payments",
    "keywords": "Keywords",
    "invoiceNumberItemPurchaser": "Invoice ID / project / client",
    "invoicingStatus2": "Invoicing status",
    "paymentStatus": "Payment status",
    "valueInvoiceDetails": "{0} · Invoice details",
    "invoiceAmount2": "Invoice amount",
    "refunded": "Paid",
    "balanceReceivable2": "Balance receivable",
    "theInvoiceHasBeenSentButExists": "This invoice was sent and has an outstanding balance of ",
    "forTheBalanceReceivablePleaseContactParty": ". Follow up with the client.",
    "invoicingAndCirculation": "Invoice workflow",
    "invoiceDateValue": "Invoice date: {0}",
    "notYetIssued": "Not yet issued",
    "print": "Print",
    "printInvoice": "Print invoice",
    "purchaseAndSaleInformation": "Purchase and sale information",
    "purchaser": "Purchaser:",
    "taxNumber": "(tax number",
    "seller": "Seller:",
    "taxNumber2": "(tax number",
    "relatedProjects": "Related projects:",
    "amount": "Amount",
    "amountExcludingTax": "Amount (excluding tax)",
    "taxAmount": "tax amount (",
    "totalPriceAndTax": "Total incl. tax",
    "uppercase": "Amount in words:",
    "accountOpeningBank": "Account opening bank:",
    "address": "· Address:",
    "invoiceNow": "Invoice now",
    "areYouSureYouWantToVoid2": "Are you sure you want to void this invoice?",
    "afterBeingInvalidatedTheStatusWillReturn2": "Voiding this invoice returns it to Pending issue. This action cannot be undone.",
    "confirmedToBeInvalid2": "Void invoice",
    "voidInvoice": "Void invoice",
    "paymentRecord": "Payment record",
    "total2": "Total ",
    "noRecordOfPaymentYet": "No record of payment yet",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-projects-app-invoices-page",
  content: t(content),
};

export default dictionary;
