// 瑚琏文档站 IA 元数据 —— 纯数据 SSOT，零 @hulianui/ui import，server / client 皆可安全读。
//
// 分区原则（2026-06 重构）：按「组件本质 / 你拿它干什么」分两级（大类 category → 小类 group），
// 而非按「会不会动」这种技术属性分。"动效" 不再是一个货架位置，而是横切标签 tags:["animated"]——
// AuroraText 本质是文字 → 归排版；ShimmerButton 本质是按钮 → 归表单；想"搞点炫的"用 animated 过滤。
// 只有没有功能本体、纯装饰的（光束/背景/放大镜）才进 decoration。

export type CategoryKey =
  | "layout"
  | "typography"
  | "forms"
  | "data-display"
  | "navigation"
  | "feedback"
  | "ai"
  | "decoration"
  | "mockups"
  | "mobile";

/** 横切属性标签：不决定组件归属，仅供侧栏过滤芯片跨分组筛选。 */
export type ComponentTag = "animated" | "webgl";

export interface CategoryGroup {
  key: string;
  label: string;
}

export interface Category {
  key: CategoryKey;
  label: string;
  groups: CategoryGroup[];
}

export interface ComponentMeta {
  slug: string;
  name: string;
  description: string;
  category: CategoryKey;
  /** 小类 key，须存在于其 category 的 groups 中（manifest.test 校验）。 */
  group: string;
  tags?: ComponentTag[];
  status: "stable" | "new";
}

export const CATEGORIES: Category[] = [
  {
    key: "layout",
    label: "布局",
    groups: [
      { key: "container", label: "容器" },
      { key: "arrange", label: "排布" },
    ],
  },
  {
    key: "typography",
    label: "排版",
    groups: [
      { key: "text", label: "文本" },
      { key: "code", label: "代码" },
    ],
  },
  {
    key: "forms",
    label: "表单",
    groups: [
      { key: "button", label: "按钮" },
      { key: "basic", label: "基础录入" },
      { key: "advanced", label: "高级录入" },
      { key: "datetime", label: "日期时间" },
      { key: "framework", label: "表单框架" },
    ],
  },
  {
    key: "data-display",
    label: "数据展示",
    groups: [
      { key: "collection", label: "集合" },
      { key: "info", label: "信息标记" },
      { key: "stat", label: "统计度量" },
      { key: "placeholder", label: "占位" },
    ],
  },
  {
    key: "navigation",
    label: "导航",
    groups: [
      { key: "global", label: "全局导航" },
      { key: "inpage", label: "页内导航" },
      { key: "action", label: "触发与工具" },
    ],
  },
  {
    key: "feedback",
    label: "反馈",
    groups: [
      { key: "overlay", label: "浮层" },
      { key: "message", label: "提示" },
      { key: "loading", label: "加载与进度" },
      { key: "guide", label: "引导" },
    ],
  },
  {
    key: "ai",
    label: "AI 智能体",
    groups: [
      { key: "conversation", label: "对话" },
      { key: "agent", label: "推理与工具" },
      { key: "assist", label: "辅助" },
    ],
  },
  {
    key: "decoration",
    label: "装饰",
    groups: [
      { key: "backdrop", label: "背景" },
      { key: "overlay-fx", label: "覆盖特效" },
    ],
  },
  {
    key: "mockups",
    label: "设备外壳",
    groups: [
      { key: "window", label: "窗口" },
      { key: "device", label: "设备" },
    ],
  },
  {
    key: "mobile",
    label: "移动端",
    groups: [
      { key: "nav", label: "导航" },
      { key: "overlay", label: "浮层" },
      { key: "input", label: "录入" },
      { key: "gesture", label: "手势交互" },
      { key: "layout", label: "布局" },
    ],
  },
];

export const manifest: ComponentMeta[] = [
  // ── 布局 layout ──────────────────────────────────────────────
  { slug: "layout", name: "Layout", description: "整页布局 · 复合 Header/Sider/Content/Footer + Sider 可折叠(受控/断点/trigger) + 宽度过渡(零依赖·尽量 RSC·复用 ScrollArea)", category: "layout", group: "container", status: "new" },
  { slug: "admin-layout", name: "AdminLayout", description: "中后台骨架 · 侧栏(品牌+NavMenu可折叠) + 顶栏(折叠/面包屑/扩展区) + 多页签导航(内嵌 RouteTabs·右键关闭其他/左右/全部/刷新·受控接路由或菜单点击自动维护) + 内容区(复用 NavMenu/ScrollArea·企业应用外壳)", category: "layout", group: "container", status: "new" },
  { slug: "route-tabs", name: "RouteTabs", description: "路由页签条 · 中后台多标签工作区(右键关闭其他/左侧/右侧/全部/刷新 + 固定页签 + 拖拽调序 + 激活项滚入视口 + 溢出滚动) · 完全受控", category: "navigation", group: "inpage", status: "new" },
  { slug: "scroll-area", name: "ScrollArea", description: "滚动区 · Base UI 自定义细滚动条 + 竖/横/双向", category: "layout", group: "container", status: "new" },
  { slug: "viewport", name: "Viewport", description: "响应式容器 · container-type 容器查询上下文 + web/平板/手机 预设宽度(可 width 覆盖) + 可选设备切换器(dogfood Segmented) · 内部组件用 @md/@5xl 等容器变体按【容器宽度】自适应而非页面视口(跨设备同套布局自动重排)", category: "layout", group: "container", status: "new" },
  { slug: "resizable", name: "Resizable", description: "拖拽分栏 · 复合 PanelGroup/Panel/Handle + 横竖向 + min/max + 键盘微调(零依赖·role=separator)", category: "layout", group: "container", status: "new" },
  { slug: "aspect-ratio", name: "AspectRatio", description: "比例容器 · CSS aspect-ratio 锁宽高比 + 图片/视频自动铺满(零依赖·RSC)", category: "layout", group: "container", status: "new" },
  { slug: "fit-screen", name: "FitScreen", description: "大屏适配 · 固定设计尺寸(默认 1920×1080)等比缩放铺满父容器并居中 + fit/cover/stretch 三模式(纯函数 computeFit 可测·ResizeObserver 监听·SSR 安全·数据可视化大屏刚需)", category: "layout", group: "container", status: "new" },
  { slug: "masonry", name: "Masonry", description: "瀑布流布局 · 确定性 round-robin 分列(item[i]→第 i%列·SSR 安全·顺序稳定·非 CSS columns 抖动) + 响应式列数(base/sm/md/lg·首帧 base 防 hydration mismatch·挂载后 matchMedia 调整) + 列内外统一 gap(泛型·token 主题)", category: "layout", group: "container", status: "new" },
  { slug: "stack", name: "Stack", description: "弹性布局 · flex 原语 direction/gap/align/justify/wrap + as 多态(零依赖·RSC)", category: "layout", group: "arrange", status: "new" },
  { slug: "container", name: "Container", description: "内容容器 · 限制最大宽度(sm/md/lg/xl/full) + 居中 + 左右安全内距 + as 多态(收口全站 mx-auto max-w-Nxl px-6 样板·零依赖·RSC)", category: "layout", group: "container", status: "new" },
  { slug: "grid", name: "Grid", description: "栅格布局 · grid 原语 cols/gap + GridItem 跨列跨行(零依赖·RSC)", category: "layout", group: "arrange", status: "new" },
  { slug: "spacer", name: "Spacer", description: "间距 · x/y × 0.25rem 布局留白 + aria-hidden + RSC", category: "layout", group: "arrange", status: "new" },
  { slug: "divider", name: "Divider", description: "带文字分隔 · orientation 左/中/右 + dashed/plain + 行内垂直(纯皮肤·零依赖·RSC·与 Separator 互补)", category: "layout", group: "arrange", status: "new" },
  { slug: "separator", name: "Separator", description: "分隔线 · Base UI role=separator + 横/竖几何", category: "layout", group: "arrange", status: "new" },

  // ── 排版 typography ──────────────────────────────────────────
  { slug: "text", name: "Text", description: "文本 · size/tone(6 语义色含 success/warning)/weight + 单行省略/多行截断 + as 多态(纯皮肤·零依赖·RSC)", category: "typography", group: "text", status: "new" },
  { slug: "heading", name: "Heading", description: "标题 · 1-6 级语义标签 + size/weight + as 多态(纯皮肤·零依赖·RSC)", category: "typography", group: "text", status: "new" },
  { slug: "prose", name: "Prose", description: "排版容器 · 富文本/markdown 后代选择器统一吃语义 token(纯皮肤·零依赖·RSC)", category: "typography", group: "text", status: "new" },
  { slug: "markdown", name: "Markdown", description: "Markdown 渲染 · 只读，零依赖块级解析(标题/代码块/列表/引用/行内粗斜码链) · 套 Prose 排版 + 围栏代码块委托 CodeBlock · 区别 MarkdownEditor 可编辑 · RSC 安全", category: "typography", group: "text", status: "new" },
  { slug: "question-card", name: "QuestionCard", description: "题目卡片 · 教辅题库标准展示件(题号/题型/分层/题干/选项/小问/附图/章节/出处) · 题干选项走 MathText 真数学版式 · 待复核题亮左警示边条不混进正常题 · dogfood Card/Tag/Chip/Image", category: "data-display", group: "collection", status: "new" },
  { slug: "math-text", name: "MathText", description: "行内数学排版 · 零依赖解析 LaTeX 子集(分数/根号/上下标/填空槽)并渲染成真数学版式 · 分数用 inline-flex 竖排不撑乱中文行高 · 可检索朴素文本走 mathToPlain · RSC 安全", category: "typography", group: "text", status: "new" },
  { slug: "aurora-text", name: "AuroraText", description: "极光文字 · bg-clip 流动渐变 + chart token + RSC", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "animated-shiny-text", name: "AnimatedShinyText", description: "高光文字 · 横扫高光 + 徽标气质 + RSC", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "animated-gradient-text", name: "AnimatedGradientText", description: "渐变文字 · 行内 chart 渐变流动 + RSC", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "word-rotate", name: "WordRotate", description: "轮换词 · motion 进出场 + reduced-motion", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "typing-animation", name: "TypingAnimation", description: "打字机 · 逐字 + 闪烁光标 + 进入视口触发", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "sparkles-text", name: "SparklesText", description: "星闪文字 · 随机小星脉冲(客户端生成) + token", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "split-text", name: "SplitText", description: "切字进场 · 文本切字/词 + 滚入视口逐段错峰位移淡入(motion · useInView 触发一次 · aria-label 整段读屏友好 · reduced-motion 直呈终态)", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "blur-text", name: "BlurText", description: "模糊解析 · 各词从模糊+位移解析到清晰 + 滚入视口触发(motion · top/bottom 方向 · aria-label 整段 · reduced-motion 直呈清晰)", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "decrypted-text", name: "DecryptedText", description: "乱码解码 · 字符翻滚后逐位解码到明文 + view/hover 触发(随机仅客户端 effect 避 hydration mismatch · 等宽 tabular-nums 防抖 · aria-label 明文)", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "glitch-text", name: "GlitchText", description: "故障撕裂 · 双伪元素 RGB 错位 + clip-path 切片抖动(纯 CSS 零依赖 RSC · 撕裂色吃 chart token · enableOnHover 门控 · motion-reduce 退普通文本)", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "circular-text", name: "CircularText", description: "环形文字 · 每字按等分角排到圆周 + 整体匀速自转 + 悬停调速(加速/减速/暂停/抓狂 · 颜色继承 currentColor · reduced-motion 静态)", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "scroll-reveal", name: "ScrollReveal", description: "滚动显影 · 整段随容器滚过视口逐词 opacity+blur 解析(motion useScroll/useTransform · 每词独立进度区间 · reduced-motion 直呈可读)", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "true-focus", name: "TrueFocus", description: "真实焦点 · 句中一词清晰余词模糊 + 焦点循环移动 + 四角框跟随(测量 rect 定位 · 角框吃 chart token · manualMode 悬停聚焦 · reduced-motion 全清晰)", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "code", name: "Code", description: "行内代码 · <code> 等宽皮肤 + tone(default/primary/danger) + RSC", category: "typography", group: "code", status: "new" },
  { slug: "code-block", name: "CodeBlock", description: "代码块 · 多行 <pre> + 一键复制(剪贴板+反馈) + 可选语言标签", category: "typography", group: "code", status: "new" },
  { slug: "snippet", name: "Snippet", description: "代码片段 · 命令提示符 + 一键复制(剪贴板+反馈)", category: "typography", group: "code", status: "new" },
  { slug: "code-diff", name: "CodeDiff", description: "代码对比 · 零依赖行级 LCS diff(纯函数 diffLines 可测) + unified 单栏/split 双栏 + 增绿删红行底色 + 双行号槽 + filename 头条与 +/− 摘要 · agent 改动/PR 评审", category: "typography", group: "code", status: "new" },
  { slug: "kbd", name: "Kbd", description: "按键 · <kbd> 等宽皮肤 + 组合键并排 + RSC", category: "typography", group: "code", status: "new" },

  // ── 表单 forms ───────────────────────────────────────────────
  { slug: "button", name: "Button", description: "按钮 · CVA 变体 + press 动效", category: "forms", group: "button", status: "stable" },
  { slug: "shimmer-button", name: "ShimmerButton", description: "微光按钮 · 边缘游走火花(conic) + token + RSC", category: "forms", group: "button", tags: ["animated"], status: "new" },
  { slug: "rainbow-button", name: "RainbowButton", description: "彩虹按钮 · chart 流光底 + 模糊光晕 + RSC", category: "forms", group: "button", tags: ["animated"], status: "new" },
  { slug: "pulsating-button", name: "PulsatingButton", description: "脉冲按钮 · 外扩光环(box-shadow) + RSC", category: "forms", group: "button", tags: ["animated"], status: "new" },
  { slug: "ripple-button", name: "RippleButton", description: "波纹按钮 · 点击落点扩散(Material) + reduced-motion", category: "forms", group: "button", tags: ["animated"], status: "new" },
  { slug: "button-group", name: "ButtonGroup", description: "按钮组 · 把若干 Button 连排成一体(抹内侧圆角/合并相邻边框/hover 项抬层) 或分离编组 + 横竖向 · 工具栏分段/拆分按钮/步进器(纯布局壳·不接管子按钮变体)", category: "forms", group: "button", status: "new" },
  { slug: "social-button", name: "SocialButton", description: "第三方登录按钮 · 微信/支付宝/QQ/微博 + GitHub/Google/Apple/X 品牌 logo(内联 simple-icons·零依赖) + outline/solid 变体 + 纯 logo 方钮 + loading · 黑白系品牌 solid 随主题前景避暗色不可见", category: "forms", group: "button", status: "new" },
  { slug: "input", name: "Input", description: "输入框 · Base UI Field + 前后缀 + invalid", category: "forms", group: "basic", status: "new" },
  { slug: "textarea", name: "Textarea", description: "多行输入 · 自适应高度", category: "forms", group: "basic", status: "new" },
  { slug: "select", name: "Select", description: "下拉选择 · Base UI overlay 单选/多选(multiple·string[] 受控·Trigger 平铺 label 超出 +N) + items 自动 label", category: "forms", group: "basic", status: "new" },
  { slug: "checkbox", name: "Checkbox", description: "复选框 · 三态(含半选) + Base UI", category: "forms", group: "basic", status: "new" },
  { slug: "checkbox-group", name: "CheckboxGroup", description: "复选组 · Base UI 值数组协调 + 复用瑚琏 Checkbox", category: "forms", group: "basic", status: "new" },
  { slug: "radio", name: "Radio", description: "单选 · RadioGroup 单选组 + 键盘方向键", category: "forms", group: "basic", status: "new" },
  { slug: "switch", name: "Switch", description: "开关 · Base UI 受控 + ARIA", category: "forms", group: "basic", status: "stable" },
  { slug: "toggle", name: "Toggle", description: "切换按钮 · Base UI pressed 态 + ToggleGroup 单/多选", category: "forms", group: "basic", status: "new" },
  { slug: "segmented", name: "Segmented", description: "分段控制器 · 自研 radio 语义(方向键漫游) + active-tab CSS 变量滑块(零依赖)", category: "forms", group: "basic", status: "new" },
  { slug: "slider", name: "Slider", description: "滑块 · Base UI 单值/range + 键盘步进", category: "forms", group: "basic", status: "new" },
  { slug: "number-field", name: "NumberField", description: "数字步进 · Base UI ±按钮 + 键盘步进 + min/max", category: "forms", group: "basic", status: "new" },
  { slug: "secret-field", name: "SecretField", description: "密钥掩码字段 · sk-abc…wxyz 掩码(full/prefix-suffix) + 眼睛 toggle 显形 + 一键复制原值(同 Snippet idiom·1.5s 反馈) + 尾部动作槽(重置/吊销) + 受控 revealed(API key 管理刚需·复用 _icons Eye/Copy)", category: "forms", group: "advanced", status: "new" },
  { slug: "password-generator", name: "PasswordGenerator", description: "密码生成器 · Bitwarden 式双模面板(字符密码 + 密码短语·内置 1747 词表) + 熵值实时评级四档强度条 + 参数即改即重算 + 逐字符着色(数字蓝符号红·手抄可辨) + 复制/重生成 + i18n · 随机源 crypto.getRandomValues 拒绝采样消模偏(拒绝 Math.random) + 生成算法作纯函数导出可服务端复用 + SSR 首帧占位不水合失配", category: "forms", group: "advanced", status: "new" },
  { slug: "combobox", name: "Combobox", description: "自动补全 · 触发按钮 + 弹层内搜索(图4 范式)，亦支持内联输入；浮层锚到字段等宽", category: "forms", group: "advanced", status: "new" },
  { slug: "remote-select", name: "RemoteSelect", description: "远程搜索选择器 · 防抖搜索 + AbortSignal 取消 + 滚到底分页 + resolveValue 初值回显，支持多选 chips", category: "forms", group: "advanced", status: "new" },
  { slug: "listbox", name: "Listbox", description: "可选列表 · WAI-ARIA roving tabindex + 单/多/纯动作 + typeahead(零依赖)", category: "forms", group: "advanced", status: "new" },
  { slug: "mentions", name: "Mentions", description: "@提及输入 · 复用 Textarea 皮肤 + 触发符唤起候选(镜像 div 测光标像素坐标) + aria-activedescendant 虚拟焦点(零依赖)", category: "forms", group: "advanced", status: "new" },
  { slug: "input-otp", name: "InputOTP", description: "验证码输入 · 分段自动跳格/退格回退/整段粘贴(零依赖)", category: "forms", group: "advanced", status: "new" },
  { slug: "rating", name: "Rating", description: "评分 · 零依赖受控星级(radio 语义) + 自定义图标 + hover 预览 + token 星色", category: "forms", group: "advanced", status: "new" },
  { slug: "upload", name: "Upload", description: "文件上传 · 拖拽落区/按钮形态 + accept/maxSize/limit 校验 + 受控列表(缩略图/进度/拖拽调序)，传输层拆成 useUpload(request 由消费者提供·并发+取消)", category: "forms", group: "advanced", status: "new" },
  { slug: "region-select", name: "RegionSelect", description: "图上框选回坐标 · 拖框拿回原图像素 [x1,y1,x2,y2](区别 ImageCropper 出 Blob) · 反向拖规范化 + minSide 滤误点 + aspect 固定比例(撞边界整体缩不破比例) + boxes 只读其它框带标注 + maxHeight 内滚 · SVG viewBox 打底画框零换算，指针→图像素折算是纯函数可测 · 自然尺寸自量、量到前不画框 · touch-none + setPointerCapture 后置 try/catch + 描边按图宽 · 题库配图/文档标注/OCR 纠错/热区/打码", category: "forms", group: "advanced", status: "new" },
  { slug: "image-cropper", name: "ImageCropper", description: "图片裁剪 · 固定比例框(默认证件照 5:7) + 触屏双指捏合/拖拽对位 + 缩放滑杆 + canvas 出 Blob(尺寸/质量/字节上限可配·react-easy-crop MIT)", category: "forms", group: "advanced", status: "new" },
  { slug: "scope-matrix", name: "ScopeMatrix", description: "范围矩阵 · 允许/禁止两个语义对立的模式桶 + 底部「有效范围小结」写成人话(这类配置最易想错的正是「禁止优先」与「允许为空≠全部禁止」) + suggestions 候选点选填入 + 只读/受控双态 · 权限白名单/同步范围/CI 触发路径 · 不内置 glob 校验(各家方言差异大·猜错比不猜更糟)", category: "forms", group: "advanced", status: "new" },
  { slug: "transfer", name: "Transfer", description: "穿梭框 · 左右双 listbox 面板 + 移动按钮(选中/全部) + 可选搜索 + 空态(零依赖·复用 Listbox/Empty)", category: "forms", group: "advanced", status: "new" },
  { slug: "cascader", name: "Cascader", description: "级联选择 · 触发器 + Popover 横向逐级面板列 + 路径数组受控 + click/hover 展开 + changeOnSelect · 复用树引擎核", category: "forms", group: "advanced", status: "new" },
  { slug: "tree-select", name: "TreeSelect", description: "树选择器 · 触发器 + Popover 浮层内嵌 Tree + 单选/多选(checkable)对称 + 树内搜索 + clearable 清除回未选态(与 Select 对称) · 复用树引擎核", category: "forms", group: "advanced", status: "new" },
  { slug: "region-cascader", name: "RegionCascader", description: "中国省市区级联 · 内置全量行政区划(国家统计局口径·3级) + 浮层搜索直达 + onChange 同回码与名 · dogfood Cascader", category: "forms", group: "advanced", status: "new" },
  { slug: "country-select", name: "CountrySelect", description: "国家/地区选择 · 内置 250 国(旗+中英文名+区号) + 单/多选 chips + 中英文/码/区号搜索 · dogfood Combobox(新增多选)", category: "forms", group: "advanced", status: "new" },
  { slug: "markdown-editor", name: "MarkdownEditor", description: "Markdown 编辑器 · WYSIWYG 罩 TipTap + 值进出 markdown 字符串 + 隐藏 input 桥 Field + 标准集工具栏", category: "forms", group: "advanced", status: "new" },
  { slug: "colorpicker", name: "ColorPicker", description: "颜色选择 · react-colorful 内核 + HEX/RGB/HSL 多格式输出与切换器(零依赖派生) + 瑚琏 token 皮肤", category: "forms", group: "advanced", status: "new" },
  { slug: "color-field", name: "ColorField", description: "颜色输入框 · 紧凑单行:色块(调起系统取色器) + 十六进制文本输入 + 短写自动展开(#abc→#aabbcc) + 草稿态支持手输", category: "forms", group: "advanced", status: "new" },
  { slug: "color-swatch-picker", name: "ColorSwatchPicker", description: "预设色块单选 · base-ui RadioGroup 换皮(方向键 a11y) + 选中 ring + mix-blend 勾(零依赖)", category: "forms", group: "advanced", status: "new" },
  { slug: "choicebox", name: "Choicebox", description: "卡片选择 · 复合 ChoiceboxGroup/Choicebox(标题/描述/图标卡片) · 单选(radio)/多选(checkbox)对称 + 受控非受控 + 网格列数 · 隐藏原生 input 承载键盘与 a11y(单选方向键漫游/多选空格切换) · 套餐/支付方式/订阅档位", category: "forms", group: "advanced", status: "new" },
  { slug: "emoji-picker", name: "EmojiPicker", description: "表情选择器 · 内联 emoji 数据集(7 分类·中英关键词) + 关键词搜索 + 分类页签 + 最近使用(受控/内部) · 搜索框 dogfood Input · onSelect 回传 emoji(零依赖·聊天/评论)", category: "forms", group: "advanced", status: "new" },
  { slug: "voice-record", name: "VoiceRecord", description: "语音录制 · 圆形录音按钮(光环脉动+波形动画) · idle/recording/processing/disabled 四态 + 按住说话(默认·pointercancel 兜底防 iOS 死锁)/点击切换双模式 + levels 波形驱动 + sm/md/lg 三档 · 纯 Pointer Events 零依赖", category: "forms", group: "advanced", status: "new" },
  { slug: "calendar", name: "Calendar", description: "日历面板 · 自研零依赖(日/月/年三层下钻·常驻不带浮层) + min-max/disabledDate/今天快捷 · 定宽字符串受控", category: "forms", group: "datetime", status: "new" },
  { slug: "date-picker", name: "DatePicker", description: "单日期选择 · 自研零依赖(触发器 + Popover 罩 Calendar 面板·日/月/年三粒度) + min-max/disabledDate/清除 · 定宽 YYYY-MM-DD 受控", category: "forms", group: "datetime", status: "new" },
  { slug: "date-time-picker", name: "DateTimePicker", description: "日期时间选择 · 自研零依赖(左日历 + 右时/分/秒列一体弹层) + 步进/秒/此刻 · 边界只在压着 min-max 那天生效 · 定宽 YYYY-MM-DD HH:mm 受控", category: "forms", group: "datetime", status: "new" },
  { slug: "date-range-picker", name: "DateRangePicker", description: "日期区间 · 自研零依赖双月范围日历 + Popover 引擎 + 快捷预设/min-max/disabledDate · ISO 数组受控", category: "forms", group: "datetime", status: "new" },
  { slug: "icon-picker", name: "IconPicker", description: "图标选择 · 分类页签 + 跨类搜索(名字/中文别名) + 网格 + 最近使用 · 图标集由消费方经 renderIcon 注入(库不打包图标集)", category: "forms", group: "advanced", status: "new" },
  { slug: "time-picker", name: "TimePicker", description: "时间选择 · 自研零依赖(时/分/秒三列浮层) + 步进/minTime-maxTime 逐列禁用 · 定宽 HH:mm[:ss] 受控", category: "forms", group: "datetime", status: "new" },
  { slug: "time-field", name: "TimeField", description: "时间分段输入 · 自研零依赖(时/分/秒各一段 spinbutton·↑↓ 调值/←→ 切段/数字键两位覆写) + min-max 钳制 · 定宽 HH:mm[:ss] 受控", category: "forms", group: "datetime", status: "new" },
  { slug: "form", name: "Form", description: "表单容器 · Base UI 结构化提交 + errors 按 name + 与 Field 协同", category: "forms", group: "framework", status: "new" },
  { slug: "form-dialog", name: "ModalForm / DrawerForm", description: "弹窗/抽屉表单 · 列表页新增/编辑编排件(复用 Dialog/Drawer + useForm + Button footer) · 提交前自动 validate · async onFinish 成功关闭/失败保持 · 文案接 i18n", category: "forms", group: "framework", status: "new" },
  { slug: "pro-form", name: "ProForm", description: "内联表单编排 · useForm + 自动 footer(提交/重置) + async onFinish loading + 自定义 footer(ModalForm 的内联姊妹件·文案接 i18n)", category: "forms", group: "framework", status: "new" },
  { slug: "steps-form", name: "StepsForm", description: "分步表单 · 复用 Steps 指示器 + 上一步/下一步/提交导航 + onStepValidate 逐步校验 + 跨步保值(消费者 useForm 持有·文案接 i18n)", category: "forms", group: "framework", status: "new" },
  { slug: "login-form", name: "LoginForm", description: "登录模板 · 自管 useForm(账号/密码必填+记住我) + rules 字段校验 + values 受控逃生口 + beforeSubmit 异步拦截 + extra/logo/footer 插槽(复用 Field/Input/Checkbox/Button·文案接 i18n)", category: "forms", group: "framework", status: "new" },
  { slug: "click-captcha", name: "ClickCaptcha", description: "点选人机验证 · 采集点击序列回传相对坐标(0~1) + 序号标记/撤销/换一张 + 键盘准星可达 + 失败抖动清空(零协议·不碰网络)", category: "forms", group: "framework", status: "new" },
  { slug: "field", name: "Field", description: "字段包装 · label/help/error a11y 串联", category: "forms", group: "framework", status: "new" },
  { slug: "search-form", name: "SearchForm", description: "查询筛选表单 · 中后台列表页顶部条件区 · fields 配置 + 固定列栅格 + 一行折叠 + 查询/重置(dogfood Grid/Field/Input/Select/Button·零依赖)", category: "forms", group: "framework", status: "new" },

  // ── 数据展示 data-display ────────────────────────────────────
  { slug: "table", name: "Table", description: "表格 · TanStack headless + 列排序 + 行点击/整行导航(onRowClick/rowHref·冒泡隔离) + 空态", category: "data-display", group: "collection", status: "new" },
  { slug: "book-3d", name: "Book3D", description: "3D 立体书 · CSS 3D transform 透视书体(前封/书脊/页块/后封) + 渐变或图封面 + 封面标题副标 + 角标缎带 + hover 翻正(纯 transform·GPU 合成·reduced-motion 降级) · 作品集书架/封面墙", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "pro-table", name: "ProTable", description: "高级表格 · 列表页编排层(复用 Table/SearchForm/Pagination) · 查询区 + 工具栏(密度/列设置/刷新/全屏) + 行选择 + 集成分页(企业中后台列表页旗舰)", category: "data-display", group: "collection", status: "new" },
  { slug: "pricing-table", name: "PricingTable", description: "定价对比矩阵 · 行列转置(列=被比项/模型·行=属性/价目) + 列高亮描边 + 角标(推荐/最佳性价比) + 表头吸顶 + 窄屏横滚(复用 ScrollArea·区别 Table 行=记录·模型市场定价对照刚需)", category: "data-display", group: "collection", status: "new" },
  { slug: "json-viewer", name: "JsonViewer", description: "只读 JSON 树 · 折叠 JSON 树(只读) · 递归零依赖 + 语法着色(key/string/number/bool/null) + 行级展开折叠 + 折叠态 {…} N keys/[…] N items + depth<阈值初始展开/大对象懒展开 + hover 复制节点值与 JSON path(网关请求/响应日志检查器刚需·导出 valueType/jsonPath 纯函数)", category: "data-display", group: "collection", status: "new" },
  { slug: "editable-table", name: "EditableTable", description: "行内编辑表格 · 行级编辑(草稿副本/保存校验/取消还原) + 自定义编辑器(editor 逃生舱) + 增删行 + 列对齐/宽度(企业录入场景·文案接 i18n)", category: "data-display", group: "collection", status: "new" },
  { slug: "list", name: "List", description: "数据列表 · 复合 List/ListItem/ListItem.Meta + actions/size/bordered/split/grid + 空态/分页/加载更多(零依赖·复用 Empty/Pagination/Avatar/User)", category: "data-display", group: "collection", status: "new" },
  { slug: "descriptions", name: "Descriptions", description: "描述列表 · 详情页键值对 + horizontal/vertical + bordered + span 跨列(纯皮肤·RSC)", category: "data-display", group: "collection", status: "new" },
  { slug: "tree", name: "Tree", description: "递归树 · 自研零依赖引擎 + WAI-ARIA tree(roving/方向键/typeahead) + checkable 父子级联半选 + 连接线 + 树内搜索 + grid-rows 高度过渡", category: "data-display", group: "collection", status: "new" },
  { slug: "card", name: "Card", description: "卡片 · Header/Body/Footer 插槽", category: "data-display", group: "collection", status: "new" },
  { slug: "carousel", name: "Carousel", description: "轮播 · 自研零依赖 scroll-snap + 箭头/圆点/autoplay/loop + 拖拽/键盘(reduced-motion)", category: "data-display", group: "collection", status: "new" },
  { slug: "video", name: "Video", description: "视频播放器 · Vidstack 引擎 + 瑚琏 token 自搓皮肤(播放/进度/音量/倍速/PiP/全屏) + 文件/HLS + 章节标记/续播/结束屏", category: "data-display", group: "collection", status: "new" },
  { slug: "bento-grid", name: "BentoGrid", description: "错落栅格 · BentoGrid/BentoCard 复合 + 跨列跨行 + hover CTA(纯 CSS·RSC)", category: "data-display", group: "collection", status: "new" },
  { slug: "image", name: "Image", description: "图片 · 加载淡入 + 失败回退/占位 + isZoomed hover 放大 + radius", category: "data-display", group: "collection", status: "new" },
  { slug: "magic-card", name: "MagicCard", description: "魔法卡片 · 鼠标跟随径向高光(motion) + surface token", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "animated-list", name: "AnimatedList", description: "动效列表 · 子项逐个淡入上移入场(motion + 进入视口)", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "marquee", name: "Marquee", description: "跑马灯 · 纯 CSS 无缝循环 + hover 暂停 + 方向", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "sortable", name: "Sortable", description: "拖拽排序 · @dnd-kit headless + 键盘可拖(Space 抓起/方向键移动) + 手柄/整项两式 + 横竖向 · 行内交互元素(输入框/按钮)指针与键盘双路守卫内置·默认即安全 + renderItem 给 index(序号/唯一 aria-label) · 受控 onChange(arrayMove)", category: "data-display", group: "collection", status: "new" },
  { slug: "kanban", name: "Kanban", description: "看板 · @dnd-kit headless 多容器 + 跨列/列内拖拽 + 键盘可拖 + 列头统计槽 + 空列占位 · 受控 onMove(消费者改业务字段) · 商机看板/任务流转旗舰", category: "data-display", group: "collection", status: "new" },
  { slug: "flow", name: "Flow", description: "节点画布编排器 · 零依赖原生 Pointer Events + SVG 贝塞尔连线 · 拖节点/拖桩连线/平移缩放/适配视图 + 受控 nodes/edges(onNodesChange/onConnect/删点删线) + renderNode 自定义节点内容 · 几何抽纯函数带单测 · AI 工作流/流程编排旗舰", category: "data-display", group: "collection", status: "new" },
  { slug: "sankey", name: "Sankey", description: "桑基图 · (库内首个) · 多层流向/分配比例 · 零依赖 SVG ribbon · 拓扑自动分层(未给 layer 按 links 推) + 节点高度/流宽按 value 占比 + 跨层一致比例尺(值域守恒) · hover 高亮关联链路 tooltip + 点击节点/连线下钻 · 调度流向/流量来源/预算分配/转化路径旗舰", category: "data-display", group: "collection", status: "new" },
  { slug: "sparkline", name: "Sparkline", description: "内联趋势迷你图 · 无轴无网格的极简趋势 · line/area/bar 三态 + highlightLast 末点圆点 + 原生 SVG <title> tooltip(RSC 安全零 JS) · 几何抽纯函数(归一化/path/柱矩形)带单测 · 表格内联/KPI 卡/负载趋势(零依赖)", category: "data-display", group: "info", status: "new" },
  { slug: "funnel", name: "Funnel", description: "漏斗图 · 阶段宽度按 value 比例 + 级间转化率徽标(本级/上一级) · 纵/横双向 + per-stage tone + renderStage 自定义 · computeFunnel 纯函数(不除零)带单测 · 任务漏斗/转化漏斗/留存(零依赖)", category: "data-display", group: "collection", status: "new" },
  { slug: "event-stream", name: "EventStream", description: "事件流 · 高频机器事件的连续时间线(审计流/CI 阶段/告警流) · 语义色承载「哪些不对劲」 + detail 折叠 + meta 右对齐 + overridden 单独成行标记「曾被拦但已放行」 + live 新条目淡入一次(首帧不闪·不做循环动效) + maxHeight 内滚 · 时间不做格式化(时区精度属调用方领域知识) · 区别 Timeline(稀疏人工编排)/ThreadList(可进入会话)/QueueLane(积压非时序)", category: "data-display", group: "collection", status: "new" },
  { slug: "queue-lane", name: "QueueLane", description: "优先级队列板 · 优先级泳道队列板 · 横向泳道 + 道头聚合队列指标(深度/平均等待/吞吐) · 只读队列监视器(区别 Kanban 拖拽工作流·FIFO+aging) + maxVisible 折叠「还有 N 条」 + onItemClick · groupByLane 保序分组纯函数带单测 · 任务总线/优先级队列(零依赖)", category: "data-display", group: "collection", status: "new" },
  { slug: "document-sheet", name: "DocumentSheet", description: "单据纸张 · A4 居中纸面(白底/暗色近黑纸·shadow·210mm 宽) + 打印态隔离(工具栏/阴影/外边距 print:hidden·data-document-sheet 钩子) + 内置打印按钮(onPrint ?? window.print) + 子件 Header(左右抬头)/Section(带小标题段)/Footer(签章位) · 报价单/发票等单据容器", category: "data-display", group: "collection", status: "new" },
  { slug: "gantt", name: "Gantt", description: "甘特图(只读) · 项目排期可视化 · 左固定列(按 group 分组小标题) + 右时间轴(day/week/month 刻度) · CSS grid + 百分比定位条形 + progress 深色填充层 + today 竖线 · 自带 UTC 日期数学(零依赖) · 横向滚动", category: "data-display", group: "collection", status: "new" },
  { slug: "scheduler", name: "Scheduler", description: "事件日历/排班 · 库首个事件日历件 · 月/周/日/资源四视图(横轴资源·纵轴时间) + 时间轴网格事件块 + 重叠并排 + 当前时间红线 · 零依赖原生 PointerEvents 拖空白建预约/拖事件改期/拖下缘改时长(全 snap 到 slot) · 受控 events/view/date(onEventsChange/onSlotDragCreate/onEventClick) + 内置 toolbar(前/今/后 + Segmented 视图) + renderEvent 自定义事件块 · 几何抽纯函数带单测 · 预约/排班旗舰", category: "data-display", group: "collection", status: "new" },
  { slug: "image-viewer", name: "ImageViewer", description: "图片查看器 · 全屏 Lightbox(portal+锁滚复用 dialog) · 受控 index 翻页(箭头/← →/序号) + 滚轮指针锚定缩放/双击 1x↔2x/拖拽平移(切图重置) + 底部缩略图条 + role=dialog aria-modal/Esc 关闭(仅渲当前图·零依赖)", category: "data-display", group: "info", status: "new" },
  { slug: "danmaku", name: "Danmaku", description: "弹幕引擎 · 轨道分配防重叠(等速模型·第二条入场后发车永不追尾) · scroll 滚动/top 顶部/bottom 底部三模式 + 轨道数/速度/密度(low/normal/high)/占屏比/透明度/暂停 + pointer-events none 穿透到底层视频 · 几何抽纯函数(allocateTrack/scrollDuration/estimateWidth)带单测 · 直播旗舰", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "live-chat", name: "LiveChat", description: "直播公屏 · 高频自动滚消息流 + message/enter(进场)/gift(送礼)/follow(关注)/system(系统)五类型默认皮肤 + 等级牌/身份徽标 + 置顶区 + 上滚查看历史时浮出「N 条新消息」恢复钮(贴底判定) + maxItems 窗口限流 + renderItem 逃生舱 + overlay 浅色态(叠加深色视频上白字) · 区别 AI 轮次制 Conversation", category: "data-display", group: "collection", status: "new" },
  { slug: "live-player", name: "LivePlayer", description: "直播播放器壳 · 自带极简 muted/loop/autoPlay video(非 VOD scrubber chrome·与 Video 互补) 或 surface 自定义画面 + LIVE 呼吸徽标(ping 红点) + 在线人数(dogfood NumberTicker 跳数) + 清晰度切换菜单 + 主播条(头像/名/关注钮) + overlay 弹幕飘心层与 footer 互动栏插槽 + 竖/横屏(9:16 / 16:9)", category: "data-display", group: "collection", status: "new" },
  { slug: "live-product-card", name: "LiveProductCard", description: "小黄车讲解卡 · 序号链接角标 + 现价/划线原价 + 讲解中脉冲徽标 + 库存/已售 + 秒杀限量角标 + 抢购按钮插槽 + row 列表行/card 网格卡两布局(直播带货标配·只消费 token·区别通用 Card)", category: "data-display", group: "info", status: "new" },
  { slug: "log-viewer", name: "LogViewer", description: "日志查看器 · 数据驱动行 lines(level/message/timestamp/source) + info/warn/error/debug/success 级别着色(纯函数 levelClass 可测) + autoScroll 新行贴底(复用 Conversation 法) + showTimestamp + wrap 折行/横滚 · 区别 Terminal mockup·真·流式输出", category: "data-display", group: "collection", status: "new" },
  { slug: "file-tree", name: "FileTree", description: "文件树 · 递归 nodes(file/folder) + 文件夹展开折叠(defaultExpanded) + 改动状态角标 A/M/D/U/R 着色(纯函数 statusMeta 可测·git status 语义) + selectedPath 受控高亮 + onSelect 回传 node+path · 复用 _icons Folder/File(新补)·devtools 左栏", category: "data-display", group: "collection", status: "new" },
  { slug: "diff-stat", name: "DiffStat", description: "改动统计条 · +N −M 绿红格子条按比例填充(纯函数 splitBlocks 可测) + A/M/D/R 状态徽标 · 代码审查/PR 列表刚需·零依赖·RSC", category: "data-display", group: "info", status: "new" },
  { slug: "score-ring", name: "ScoreRing", description: "评分环 · 半径仪表盘 + A-F 等级带(value→grade tone 映射·纯函数 resolveGrade 可测) + 环心分值/等级 · 区别线性 Meter/Progress·SVG dasharray 非 transform·RSC", category: "data-display", group: "info", status: "new" },
  { slug: "heatmap", name: "Heatmap", description: "热力图 · 网格色阶映射(value→bucket→primary 透明度档·纯函数 buildMatrix/bucketize 可测) + emptyCellTone 区分「无数据」与「值为 0」 + 小数值域 domain/valueFormat 百分比 + 色阶图例 + 行列标签 + 原生 hover 提示 + 点击下钻 · 代码热点/贡献活动/覆盖率·库内首个热力图", category: "data-display", group: "collection", status: "new" },
  { slug: "code-review-thread", name: "CodeReviewThread", description: "代码评审线程 · 代码审查评论线程 · severity 左边色条(四级语气) + AI/人类作者 + 内嵌建议修改 diff 可采纳 + 回复/标记已解决·误报 + 折叠 · 嵌 code-diff annotations 槽或独立用·复用 Avatar/Tag/CodeDiff", category: "data-display", group: "collection", status: "new" },
  { slug: "virtual-list", name: "VirtualList", description: "虚拟滚动 · 包 @tanstack/react-virtual 仅渲染可见区 + 定高/变高(measureElement)双模 + initialRect 首帧可算 + 末行触发 onReachEnd(万行列表/长列表刚需)", category: "data-display", group: "collection", status: "new" },
  { slug: "infinite-scroll", name: "InfiniteScroll", description: "无限滚动 · IntersectionObserver 底部哨兵 + 自动定位可滚祖先作 root + 加载锁防重入 + hasMore 完结态(零依赖·分页加载)", category: "data-display", group: "collection", status: "new" },
  { slug: "badge", name: "Badge", description: "计数角标 · count/max 溢出 + dot + 自定义内容 + 包裹叠加(四角/offset)", category: "data-display", group: "info", status: "new" },
  { slug: "dot", name: "Dot", description: "状态圆点 · 5 语气状态色 + sm/md/lg + 呼吸 pulse(在线/进行中) + a11y label(role=status)(Tag/Chip 内嵌点的独立原语·纯CSS·RSC)", category: "data-display", group: "info", status: "new" },
  { slug: "status-dot", name: "StatusDot", description: "健康状态点 · 在线/降级/离线/维护四语义态(→success/warning/danger/neutral 映射) + 默认仅在线脉冲 + 状态文字 + 尾部数值槽(延迟/成功率)(封装 Dot·网关渠道健康墙刚需·纯CSS·RSC)", category: "data-display", group: "info", status: "new" },
  { slug: "chip", name: "Chip", description: "标签 · 可移除(onClose×) + dot + tone×variant(区别 Badge 计数)", category: "data-display", group: "info", status: "new" },
  { slug: "coupon", name: "Coupon", description: "优惠券 · 撕票造型(中缝虚线+上下半圆穿孔·纯CSS) + 满减/折扣/包邮三类 + 可领/已领/已用/过期四态 + 选券高亮(电商标配·只消费 token)", category: "data-display", group: "info", status: "new" },
  { slug: "tag", name: "Tag", description: "状态标签 · 5 语气状态色 + 状态圆点/呼吸进行态(pulse) + 图标 + 可关闭(企业状态标记·区别 Chip 令牌)", category: "data-display", group: "info", status: "new" },
  { slug: "annotation", name: "Annotation", description: "手写风格标注 · 荧光笔底色 + 手绘箭头 + 手写旁注就地讲解行内内容(文档/演示/组件解剖图) · 八方位(标签在哪，箭头自动指回) + 6 语气(含彩虹) + 只圈不注 · 标签是真节点故可放 ReactNode 且读屏可读(区别 Callout 块级提示框·零依赖)", category: "data-display", group: "info", status: "new" },
  { slug: "avatar", name: "Avatar", description: "头像 · Base UI 图片+fallback", category: "data-display", group: "info", status: "new" },
  { slug: "avatar-circles", name: "AvatarCircles", description: "堆叠头像组 · 重叠 + ring + +N 计数(扩 Avatar·RSC)", category: "data-display", group: "info", status: "new" },
  { slug: "user", name: "User", description: "用户卡 · Avatar + 名称/描述组合(复用瑚琏 Avatar) + RSC", category: "data-display", group: "info", status: "new" },
  { slug: "qrcode", name: "QRCode", description: "二维码 · qrcode-generator 内核 + 自渲 SVG(暗块合 path·crispEdges) + currentColor 吃主题(区别 qrcode.react 写死黑白) + UTF-8 中文 + minVersion 钉密度/boostLevel 不升版本白拿纠错 + 中心 logo(excavate 抠空开关·opacity 水印) + qrCodeSvgString/qrCodeToPngDataUrl 导出(按 DPR 放大·默认白底·可 RSC)", category: "data-display", group: "info", status: "new" },
  { slug: "comment", name: "Comment", description: "评论 · 嵌套回复缩进 + 可选连接线 + 操作区 + comment/log 类型(复用 Avatar/Link·RSC)", category: "data-display", group: "info", status: "new" },
  { slug: "relative-time", name: "RelativeTime", description: "相对时间 · 时间戳→「3分钟前/昨天/2个月后」+ 自动 tick 刷新(可设间隔/受控基准) + 中英 locale · 纯函数 formatRelative/formatAbsolute 可测 · <time> 语义 + title 绝对时间 + SSR 安全(suppressHydrationWarning)", category: "data-display", group: "info", status: "new" },
  { slug: "git-commit", name: "GitCommit", description: "git 提交引用 · 分支 chip(GitBranch) + 短哈希等宽(纯函数 shortSha 可测·可定制位数/href 跳链) + 提交信息单行截断 + 作者头像槽 · inline 单行/stacked 两行(表格单元格) · 部署列表/PR 列表/活动流「Source」列刚需(零依赖·RSC)", category: "data-display", group: "info", status: "new" },
  { slug: "deploy-status", name: "DeployStatus", description: "部署状态 · 部署/构建生命周期态 · 排队/构建中(转圈)/已上线/失败/已取消/已跳过 六态(→success/danger/primary/neutral 软填充) · badge 徽标/dot 圆点(building 脉冲)/icon 紧凑三形态 · 区别健康态 StatusDot 语义 · CI/CD/Pages/流水线刚需(纯CSS·RSC)", category: "data-display", group: "info", status: "new" },
  { slug: "contribution-graph", name: "ContributionGraph", description: "贡献活动墙 · 日期驱动格子图(GitHub 绿墙) · calendar 周列×星期行 / strip 单行最近 N 天(卡片活动条) · 补齐区间每一天 + 月份标签落列 + 周起始可切 · 色阶复用 Heatmap bucketize + tone 换色系 + 少→多图例 · 无点击整块 role=img 播报总数·onDayClick 后格子成按钮 · 日期算术纯函数 buildContributionCalendar 可测(零新依赖·RSC)", category: "data-display", group: "collection", status: "new" },
  { slug: "legend", name: "Legend", description: "独立图例 · 彩标记 + 系列名 + 可选数值 · dot/square/line 三标记 × row 横排换行/column 竖排 · 缺省色按序取 chart-1..6(与 Chart 同套 token) · onItemClick 后条目成按钮(aria-pressed)·显隐受控 · 给自绘图形(Sparkline/Heatmap/贡献墙/地图)配图例(零依赖·RSC)", category: "data-display", group: "stat", status: "new" },
  { slug: "shield-badge", name: "ShieldBadge", description: "README 徽章 · shields.io 风格「左灰标签 + 右彩数值」双段贴纸(版本/许可证/下载量/CI/星标) · 5 语气 + color 逃生舱 · solid/soft/outline 三皮肤 × rounded/square/pill 三外形 · icon 品牌 mark 槽 + href 整枚可点 · 配 ShieldBadgeGroup 排一行自动换行 + 纯函数 compactCount(1.5k/3.4M) · 纯 CSS 吃主题不联网(零依赖·RSC)", category: "data-display", group: "info", status: "new" },
  { slug: "award-badge", name: "AwardBadge", description: "桂冠奖章 · 左桂冠圈名次 + 右「前缀小字 + 粗体主标题」· 对标 GitHub Trending「#1 Repository Of The Day」/ Product Hunt 荣誉牌 · outline/solid/soft 三皮肤 × 5 语气 + color 逃生舱 × sm/md/lg · emblem 换徽记·wreath 可关 · 桂冠由纯函数 laurelLeaves 算出(吃 currentColor·缩放不糊·零图片)", category: "data-display", group: "info", status: "new" },
  { slug: "credit-card", name: "CreditCard", description: "银行卡展示 · 卡号前缀识别品牌(visa/mastercard/amex/银联/jcb/discover) + 分组格式化/打码(纯函数可测) + token 渐变卡面 + 芯片/品牌字标 + 正反面(磁条/CVC) · 结算确认/钱包(纯展示·RSC)", category: "data-display", group: "info", status: "new" },
  { slug: "stat", name: "Stat", description: "指标卡 · KPI 数值/标签/升降趋势(无图表库) + hint 与趋势无关的注脚槽", category: "data-display", group: "stat", status: "new" },
  { slug: "statistic", name: "Statistic", description: "统计数值 · 千分位/precision/前后缀/valueStyle + 可选 NumberTicker 入场滚动 + Statistic.Countdown 倒计时(SSR 安全·零依赖·与 Stat 互补)", category: "data-display", group: "stat", status: "new" },
  { slug: "chart", name: "Chart", description: "图表 · recharts 直裹 + chart token 皮肤(Area/Bar) + horizontal 类目轴 CJK 自适应宽(yAxisWidth 逃生舱)", category: "data-display", group: "stat", status: "new" },
  { slug: "meter", name: "Meter", description: "度量条 · Base UI role=meter(静态量占比，区别 Progress)", category: "data-display", group: "stat", status: "new" },
  { slug: "timeline", name: "Timeline", description: "时间线 · 复合 Timeline/Item + items 数组 + 彩色节点/自定义 dot + left/right/alternate + pending 加载态(纯皮肤·零依赖·RSC)", category: "data-display", group: "stat", status: "new" },
  { slug: "number-ticker", name: "NumberTicker", description: "数字滚动 · 进入视口 tween 到目标值 + reduced-motion", category: "data-display", group: "stat", tags: ["animated"], status: "new" },
  { slug: "world-map", name: "WorldMap", description: "点阵世界地图 · 预烘点阵(零依赖·吃主题) + 经纬度动画弧线(pathLength 画入 + 端点脉冲) + 独立节点 points(value 分大小/可选标签) + onPointClick 可点击键盘下钻(交互态放开 aria-hidden) + flyingMarker 沿飞线移动标记(✈️飞机/光点彗尾/箭头·offset-path 动效自动转向)", category: "data-display", group: "stat", tags: ["animated"], status: "new" },
  { slug: "empty", name: "Empty", description: "空状态 · 图标+标题+描述+操作槽 + 内置空箱图标 + sm/md(零依赖·RSC)", category: "data-display", group: "placeholder", status: "new" },
  { slug: "skeleton", name: "Skeleton", description: "骨架屏 · shimmer 高光占位(text/circle/rect) + 无边框组合预设 CardSkeleton/ListSkeleton/TableSkeleton", category: "data-display", group: "placeholder", status: "new" },
  { slug: "watermark", name: "Watermark", description: "水印 · 自研 canvas 平铺 + MutationObserver 防篡改 + 高清 DPR(零依赖·防截图泄密)", category: "data-display", group: "placeholder", status: "new" },

  // ── 导航 navigation ──────────────────────────────────────────
  { slug: "navbar", name: "Navbar", description: "导航栏 · 复合 Brand/Content/Item/MenuToggle + sticky + 移动端切换", category: "navigation", group: "global", status: "new" },
  { slug: "beian-footer", name: "BeianFooter", description: "备案页脚 · ICP 备案号(可多个·默认链 miit) + 公网安备(警徽 icon·默认链 mps) + 版权行 · 中国大陆合规底栏(发丝边卡片·语义 token·外链新窗·RSC)", category: "navigation", group: "global", status: "new" },
  { slug: "brand", name: "Brand", description: "品牌标识 · 方角徽章 + 站点名(+ 副标题) · mark 缺省自动取品牌名首字(中文一字/英文首字母) · 三档尺寸(sm 导航栏/md 侧栏/lg 登录页) + color 换徽章底色 · 省略 name 即收起态只出徽章 · href 普通链接 / render 接框架路由件回首页 · 区别 Avatar(圆的·套它得改形状=业务侧打补丁)", category: "navigation", group: "global", status: "new" },
  { slug: "app-launcher", name: "AppLauncher", description: "应用启动台 · 毛玻璃面板 + 搜索(标题即 placeholder) + 分类胶囊 + 图标网格(macOS Launchpad/工作台首页) · 搜索与分类各自可受控 · keywords 拼音别名参与匹配·中文按子串命中 · 连续同 section 归组自动分隔线 · 方向键网格漫游焦点 · badge/href/disabled/右上操作槽 · glass vs solid · 筛选分节纯函数可测(零依赖)", category: "navigation", group: "global", status: "new" },
  { slug: "nav-menu", name: "NavMenu", description: "侧边导航菜单 · 自研零依赖 · inline 手风琴/collapsed 图标飞出 + 树形 items + 选中/展开受控 + 纯 CSS grid 高度过渡 + WAI-ARIA tree 键盘漫游", category: "navigation", group: "global", status: "new" },
  { slug: "navigation-menu", name: "NavigationMenu", description: "导航菜单 · Base UI navigation-menu 薄包(mega 面板/共享 Viewport 尺寸形变) + 触发器/内容/链接 + chevron 旋转", category: "navigation", group: "global", status: "new" },
  { slug: "menu", name: "Menu", description: "下拉菜单 · Base UI 命令式 + Item/分隔/分组 + danger", category: "navigation", group: "global", status: "new" },
  { slug: "menubar", name: "Menubar", description: "菜单条 · Base UI menubar 薄包(File/Edit/View 顶层项+下拉) + dogfood Menu 皮肤 + 键盘切换/方向键漫游", category: "navigation", group: "global", status: "new" },
  { slug: "dock", name: "Dock", description: "放大坞 · macOS 式按鼠标距离放大图标(motion 弹簧 + context 下发 mouseX)", category: "navigation", group: "global", status: "new" },
  { slug: "tabs", name: "Tabs", description: "选项卡 · Base UI 无浮层 + underline/solid 滑块", category: "navigation", group: "inpage", status: "new" },
  { slug: "breadcrumb", name: "Breadcrumb", description: "面包屑 · 纯皮肤静态 + aria-current 当前页语义", category: "navigation", group: "inpage", status: "new" },
  { slug: "pagination", name: "Pagination", description: "分页器 · 纯皮肤受控 + 页码区间算法(省略号)", category: "navigation", group: "inpage", status: "new" },
  { slug: "anchor", name: "Anchor", description: "锚点导航 · 自研零依赖 scrollspy(IntersectionObserver) + 平滑滚动 + active CSS 变量滑动指示条 + offsetTop/二级项", category: "navigation", group: "inpage", status: "new" },
  { slug: "affix", name: "Affix", description: "固钉 · 自研零依赖滚动吸附 + offsetTop/offsetBottom + 占位防跳动 + 自定义容器", category: "navigation", group: "inpage", status: "new" },
  { slug: "back-top", name: "BackTop", description: "回顶 · 监听滚动容器超 visibilityHeight 淡入 + scrollTo smooth + prefers-reduced-motion 降级 auto(零依赖)", category: "navigation", group: "inpage", status: "new" },
  { slug: "stepper", name: "Stepper", description: "步骤条 · 零依赖 flex 布局 + 自绘完成对勾 + 连接线随进度点亮 + aria-current", category: "navigation", group: "inpage", status: "new" },
  { slug: "steps", name: "Steps", description: "步骤条(原生) · 零依赖数据驱动 items + 水平/垂直 + wait/process/finish/error 状态派生 + 可点击受控(分步表单/审批流)", category: "navigation", group: "inpage", status: "new" },
  { slug: "page-header", name: "PageHeader", description: "页头骨架 · 返回/面包屑/标题/标签/操作区/Tabs 页脚(dogfood 复用·零依赖·可 RSC)", category: "navigation", group: "inpage", status: "new" },
  { slug: "command", name: "Command", description: "命令面板 · ⌘K 模态(复用 Dialog 引擎) + 实时过滤 + 分组 + 键盘漫游(零依赖)", category: "navigation", group: "action", status: "new" },
  { slug: "context-menu", name: "ContextMenu", description: "右键菜单 · Base UI context-menu 原语薄包(锚到光标) + 复用 Menu 皮肤/data-highlighted + danger", category: "navigation", group: "action", status: "new" },
  { slug: "toolbar", name: "Toolbar", description: "工具栏 · Base UI role=toolbar + 键盘漫游 + Button/Group/Separator", category: "navigation", group: "action", status: "new" },
  { slug: "accordion", name: "Accordion", description: "手风琴 · Base UI 单/多开 + 高度过渡", category: "navigation", group: "action", status: "new" },
  { slug: "collapsible", name: "Collapsible", description: "折叠区 · Base UI collapsible 薄包 + 高度过渡(复用 Accordion --collapsible-panel-height)", category: "navigation", group: "action", status: "new" },
  { slug: "link", name: "Link", description: "链接 · tone×underline + external 自动 target/rel/图标 + RSC", category: "navigation", group: "action", status: "new" },
  { slug: "animated-theme-toggler", name: "AnimatedThemeToggler", description: "主题切换 · View Transitions 圆形揭示明暗(复用瑚琏 useTheme + 降级)", category: "navigation", group: "action", tags: ["animated"], status: "new" },

  // ── 反馈 feedback ────────────────────────────────────────────
  { slug: "dialog", name: "Dialog", description: "对话框 · Base UI Portal + focus trap", category: "feedback", group: "overlay", status: "stable" },
  { slug: "modal", name: "Modal", description: "命令式对话框 · confirm/info/success/error/warning 函数式 API + Dialog 引擎", category: "feedback", group: "overlay", status: "new" },
  { slug: "alert-dialog", name: "AlertDialog", description: "确认对话框 · Base UI 强制决策(不点遮罩/Esc 关) + Dialog 引擎", category: "feedback", group: "overlay", status: "new" },
  { slug: "drawer", name: "Drawer", description: "抽屉 · Base UI Dialog 引擎 + 四向侧滑", category: "feedback", group: "overlay", status: "new" },
  { slug: "popover", name: "Popover", description: "气泡卡片 · click 触发 + 标题/描述/Close", category: "feedback", group: "overlay", status: "new" },
  { slug: "tooltip", name: "Tooltip", description: "提示浮层 · Base UI Positioner + 箭头 + hover 触发", category: "feedback", group: "overlay", status: "new" },
  { slug: "hover-card", name: "HoverCard", description: "悬停卡片 · Popover 引擎自研 hover 开/移出延迟关(复刻 Tooltip delay 范式) + 富内容", category: "feedback", group: "overlay", status: "new" },
  { slug: "glimpse", name: "Glimpse", description: "链接预览 · dogfood HoverCard 引擎换皮成「封面图+标题+描述+域名」预览卡(维基式 hover preview) · 触发器随 href 渲染外链 a 或纯 span 保持行内排版 · 描述多行截断", category: "feedback", group: "overlay", status: "new" },
  { slug: "hero-video-dialog", name: "HeroVideoDialog", description: "视频弹层 · 缩略图+播放钮→Portal 模态(Esc/遮罩关 + 锁滚)", category: "feedback", group: "overlay", status: "new" },
  { slug: "alert", name: "Alert", description: "提示条 · tone×variant 皮肤 + a11y role", category: "feedback", group: "message", status: "new" },
  { slug: "intercept-card", name: "InterceptCard", description: "拦截卡 · 「某个动作被规则挡下了」的完整交代：规则/出处/违反点/改法/要不要放行 · block-confirm-notice 三档强度(左缘色条是唯一锚点·不整卡染色免成列糊成色块) + 溯源槽 + 放行理由强制必填(为空则按钮禁用·onOverride 根本不被调用) + 已放行态展示既有理由 · 区别 Alert(单纯通知)", category: "feedback", group: "message", status: "new" },
  { slug: "callout", name: "Callout", description: "文档提示框 · 长文内联 admonition(坑/正解/Tip) · 左 accent 竖边 + 极浅 tone 底·仅标题/图标着色·正文保持 foreground 可读 · 区别 Alert(整块染色通知横幅) · tip/info/warning/success/danger 五语气·纯皮肤RSC", category: "feedback", group: "message", status: "new" },
  { slug: "banner", name: "Banner", description: "公告条 · 横贯容器顶部全宽 bar(站点维护/促销/版本更新) · 6 语气×soft/solid + 前导图标/操作区/可关闭 + 居中或左对齐 + 长文案 dogfood Marquee 单行无缝滚动 · 区别 Alert(局部卡片)/Notification(命令式四角)", category: "feedback", group: "message", status: "new" },
  { slug: "toast", name: "Toast", description: "命令式轻提示 · 自动消失 + 队列堆叠 + 手动关闭", category: "feedback", group: "message", status: "new" },
  { slug: "notification", name: "Notification", description: "通知 · 四角堆叠卡片 + 图标/操作区/位置 + 命令式 API(比 Toast 重)", category: "feedback", group: "message", status: "new" },
  { slug: "service-message", name: "ServiceMessage", description: "服务通知卡片 · 复刻微信「服务通知」会话内消息卡(模板/订阅消息) · 头部(头像+来源+⋯)/正文(标题+键值字段或自定义 children)/底部(引导文字+小程序入口) · 数据驱动 fields + onMore/onAction 交互 + footer/action 可定制 · 区别 Notification(命令式四角 toast) · 复用 Avatar/_icons·全吃 token 明暗自适配", category: "feedback", group: "message", status: "new" },
  { slug: "result", name: "Result", description: "结果页 · 7 状态(success/error/info/warning/403/404/500)内置图标+语义色 + 标题/副标题/详情/操作槽(零依赖·RSC)", category: "feedback", group: "message", status: "new" },
  { slug: "gift-feed", name: "GiftFeed", description: "礼物连击 · 受控礼物事件流 + 同 id 连击合并 combo ×N 滚动弹跳计数(纯函数 applyGiftEvent 可测) + 横幅左滑入/自动消散计时(每连击重置) + max 同屏上限挤旧 + dogfood Avatar · 直播打赏特效(pointer-events none)", category: "feedback", group: "message", tags: ["animated"], status: "new" },
  { slug: "floating-reactions", name: "FloatingReactions", description: "飘心点赞 · 命令式 ref.emit(content,{count}) 从底部喷射上浮表情 + 随机起点/横向漂移/缩放/时长扰动 + 上浮渐隐(keyframe)动画结束自移除 + palette 随机池 + rise/drift/duration 可调(forwardRef+useImperativeHandle·pointer-events none·可复用于任意点赞钮)", category: "feedback", group: "message", tags: ["animated"], status: "new" },
  { slug: "popconfirm", name: "Popconfirm", description: "气泡确认 · dogfood Popover 引擎 + 危险操作就地确认(标题/图标/确认取消) + async onConfirm loading + 受控开合", category: "feedback", group: "message", status: "new" },
  { slug: "spin", name: "Spin", description: "加载遮罩 · 覆盖内容区 + tip + delay 防闪 + fullscreen", category: "feedback", group: "loading", status: "new" },
  { slug: "spinner", name: "Spinner", description: "加载旋转器 · 纯 CSS animate-spin SVG 环 + role=status + RSC", category: "feedback", group: "loading", status: "new" },
  { slug: "progress", name: "Progress", description: "进度条 · linear/circular + 不定态 · 几何自有(reduced-motion)", category: "feedback", group: "loading", status: "new" },
  { slug: "tour", name: "Tour", description: "漫游引导 · 自研零依赖 SVG mask 镂空高亮 + 自定位气泡卡(标题/描述/上一步/下一步/跳过/进度) + resize/scroll 重算", category: "feedback", group: "guide", status: "new" },

  // ── AI 智能体 ai ─────────────────────────────────────────────
  { slug: "conversation", name: "Conversation", description: "消息流容器 · 纵向堆叠 ChatMessage + 内容增长自动贴底(新消息/流式 token)·消费侧给高度获独立滚动区", category: "ai", group: "conversation", status: "new" },
  { slug: "chat-message", name: "ChatMessage", description: "对话气泡 · user右(primary)/assistant左(surface)/system居中 + 头像(复用Avatar)/名称/时间 + loading态(TypingDots) + 操作槽·纯皮肤RSC", category: "ai", group: "conversation", status: "new" },
  { slug: "prompt-input", name: "PromptInput", description: "提示输入 · 自增高Textarea + 发送/停止键 + Enter提交/Shift+Enter换行/IME合成保护 + 受控非受控两用 + 左侧操作槽", category: "ai", group: "conversation", status: "new" },
  { slug: "typing-dots", name: "TypingDots", description: "打字指示 · 三点交错弹跳(纯CSS·RSC) + reduced-motion停 + role=status·配 ChatMessage loading", category: "ai", group: "conversation", tags: ["animated"], status: "new" },
  { slug: "thinking-block", name: "ThinkingBlock", description: "思考折叠块 · dogfood Collapsible(自带chevron+平滑高度) + thinking态(转圈+AnimatedShinyText高光+默认展开) + 耗时标记·收起隐藏 chain-of-thought", category: "ai", group: "agent", tags: ["animated"], status: "new" },
  { slug: "tool-call", name: "ToolCall", description: "工具调用卡 · dogfood Collapsible + Dot状态色 + Spinner(运行中) · pending/running/success/error 四态 + 参数/结果折叠面板 + 工具图标", category: "ai", group: "agent", status: "new" },
  { slug: "agent-plan", name: "AgentPlan", description: "执行计划 · 数据驱动任务清单 + 状态图标(空心环待办/Spinner进行·行高亮/Check完成删除线/X失败) + 每步右侧 meta 槽(耗时) + bare 内嵌 · 复用 Spinner·纯皮肤RSC", category: "ai", group: "agent", status: "new" },
  { slug: "dossier", name: "Dossier", description: "案卷面板 · 智能体槽位填充进度可视化：分域清单 + 三态(空心环/半填充/Check) + 当前采集域高亮 + 域内容摘要 + 自动进度(已归档 n/m·可选域不计分母) + bare 内嵌 · 纯皮肤RSC", category: "ai", group: "agent", status: "new" },
  { slug: "artifact", name: "Artifact", description: "工件卡 · 智能体产出物(文档/简历/代码)对话内承载：头部(图标+标题+版本Chip+操作槽) + 折叠限高+底部渐隐遮罩 + 展开/收起(受控/非受控) · dogfood Chip", category: "ai", group: "agent", status: "new" },
  { slug: "confirm-card", name: "ConfirmCard", description: "确认卡 · human-in-the-loop 标准件：结构化字段摘要(dl) + 确认/修正双动作 + acted 锁定态(已确认/修改中) · dogfood Button", category: "ai", group: "agent", status: "new" },
  { slug: "thread-list", name: "ThreadList", description: "会话历史列表 · ChatGPT 式智能体侧栏：标题+meta 双行条目 + active 高亮 + 删除按钮(stopPropagation 不触发选中) + 头部动作槽(新对话) + 空态占位 + bare 内嵌", category: "ai", group: "agent", status: "new" },
  { slug: "task-runner", name: "TaskRunner", description: "任务运行卡 · dogfood AgentPlan(bare)步骤列表 + Progress顶部进度 + Tag标签 + Dot状态徽标 · idle/running/success/error四态派生 + 每步耗时(meta)/running行高亮/pending空心环 + progress省略按完成比派生 + 累计耗时footer + headerExtra/footerExtra送掣 · 纯展示RSC(计时驱动留消费侧)", category: "ai", group: "agent", status: "new" },
  { slug: "streaming-text", name: "StreamingText", description: "流式文本 · 渲染父级累积 text(随token增长) + 流式中尾随闪烁光标(hulian-blink) · 区别 TypingAnimation 自驱定时 · 纯皮肤RSC", category: "ai", group: "assist", tags: ["animated"], status: "new" },
  { slug: "prompt-suggestions", name: "PromptSuggestions", description: "建议提示 · 可点击 pill 列表 + string/{label,value} 两式 + onSelect 回传 value 填充输入或发起对话", category: "ai", group: "assist", status: "new" },
  { slug: "message-actions", name: "MessageActions", description: "消息操作条 · 复制(剪贴板+Check反馈)/重新生成/赞/踩 · 各键按需渲染 · 复用内联图标 · 挂 ChatMessage actions 槽", category: "ai", group: "assist", status: "new" },
  { slug: "citation", name: "Citation", description: "引用来源 · 序号角标 + 标题/来源 + href 新标签页外链 · 内联标注 agent 回答信息出处 · 纯皮肤RSC", category: "ai", group: "assist", status: "new" },

  // ── 装饰 decoration（纯视觉、无功能本体）────────────────────────
  { slug: "dot-pattern", name: "DotPattern", description: "点阵背景 · 纯 SVG pattern + currentColor token + RSC", category: "decoration", group: "backdrop", status: "new" },
  { slug: "grid-pattern", name: "GridPattern", description: "网格背景 · 纯 SVG 线 + 虚线可配 + currentColor", category: "decoration", group: "backdrop", status: "new" },
  { slug: "striped-pattern", name: "StripedPattern", description: "斜条纹背景 · 纯 CSS 渐变 + currentColor", category: "decoration", group: "backdrop", status: "new" },
  { slug: "spotlight", name: "Spotlight", description: "径向辉光背景 · token 驱动 radial-gradient + 明暗自适应 + RSC", category: "decoration", group: "backdrop", status: "new" },
  { slug: "retro-grid", name: "RetroGrid", description: "复古透视网格 · CSS 滚动 + reduced-motion", category: "decoration", group: "backdrop", tags: ["animated"], status: "new" },
  { slug: "ripple", name: "Ripple", description: "同心脉冲圆环 · CSS 逐圈延迟 + reduced-motion", category: "decoration", group: "backdrop", tags: ["animated"], status: "new" },
  { slug: "meteors", name: "Meteors", description: "流星雨 · 随机斜落拖尾(客户端生成) + currentColor", category: "decoration", group: "backdrop", tags: ["animated"], status: "new" },
  // 设计感背景批（复刻 react-bits/Aceternity·canvas 零依赖 + WebGL/ogl 懒加载·全吃 chart token·reduced-motion 降级）
  { slug: "aurora", name: "Aurora", description: "极光渐变背景 · 双层 repeating-linear-gradient 横移干涉 + 径向 mask 聚焦 + chart token(纯 CSS·RSC)", category: "decoration", group: "backdrop", tags: ["animated"], status: "new" },
  { slug: "particles", name: "Particles", description: "交互粒子场 · canvas 星尘漂浮 + 鼠标排斥位移 + DPR 自适应 + 颜色吃主题前景 token(明暗跟随)", category: "decoration", group: "backdrop", tags: ["animated"], status: "new" },
  { slug: "flickering-grid", name: "FlickeringGrid", description: "闪烁网格 · canvas 像素方格随机明灭 + ResizeObserver 自适应 + 颜色吃主题 token(逐帧现取)", category: "decoration", group: "backdrop", tags: ["animated"], status: "new" },
  { slug: "wavy-background", name: "WavyBackground", description: "噪声波浪 · canvas 多彩波浪带叠加 + 内联零依赖 value noise + chart token + reduced-motion 静态", category: "decoration", group: "backdrop", tags: ["animated"], status: "new" },
  { slug: "silk", name: "Silk", description: "丝绸流动背景 · WebGL/ogl 懒加载 shader(复刻 react-bits) + chart token 主色 + reduced-motion 渐变兜底", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "iridescence", name: "Iridescence", description: "虹彩光泽背景 · WebGL/ogl shader 连续光谱干涉 + 鼠标光流扰动 + chart token + 静态 fallback", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "threads", name: "Threads", description: "流动丝线背景 · WebGL/ogl Perlin 波动线随鼠标摆动 + 透明底叠加 + chart token + 静态 fallback", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "orb", name: "Orb", description: "指针交互光球 · WebGL/ogl 发光能量球 + hover 增亮/旋转 + hue 色相 + reduced-motion 径向渐变球", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "liquid-chrome", name: "LiquidChrome", description: "液态铬背景 · WebGL/ogl 金属流动反光 + 鼠标涟漪 + chart token 基色 + 静态金属渐变 fallback", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "border-beam", name: "BorderBeam", description: "边框光束 · motion offsetPath 绕边 + mask 只露边框", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "shine-border", name: "ShineBorder", description: "流光边框 · 渐变 mask 只留边框区 + chart token + RSC", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "glare-hover", name: "GlareHover", description: "反光悬停 · hover 斜向扫光 + reduced-motion + RSC", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "lens", name: "Lens", description: "放大镜 · 悬停光标处圆形放大任意 children(零依赖 mask+scale)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "animated-beam", name: "AnimatedBeam", description: "动效光束 · 连接两元素的流光曲线(motion 渐变 + SVG + ResizeObserver)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "orbiting-circles", name: "OrbitingCircles", description: "轨道环绕 · 子元素沿圆周匀速公转 + 自身反旋正立(纯 CSS·RSC)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "progressive-blur", name: "ProgressiveBlur", description: "渐进模糊 · 分层 backdrop-blur + mask 渐变(纯 CSS·RSC)", category: "decoration", group: "overlay-fx", status: "new" },
  { slug: "card-spotlight", name: "CardSpotlight", description: "聚光卡片 · 鼠标跟随径向高光(纯 CSS 变量 + radial-gradient) + color-mix 高光色 + surface token(零依赖)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },

  // ── 设备外壳 mockups ─────────────────────────────────────────
  { slug: "safari", name: "Safari", description: "浏览器外壳 · 顶栏红绿灯+地址栏包裹截图 + RSC", category: "mockups", group: "window", status: "new" },
  { slug: "chrome", name: "Chrome", description: "浏览器外壳 · 标签页+工具栏(前进/后退/刷新+地址栏)包裹截图 + RSC", category: "mockups", group: "window", status: "new" },
  { slug: "terminal", name: "Terminal", description: "终端框 · mac 窗口外壳 + 命令行逐行揭示(motion + tone) + 语法着色(命令名/flag/URL/数字)", category: "mockups", group: "window", tags: ["animated"], status: "new" },
  { slug: "iphone", name: "iPhone", description: "手机外壳 · 灵动岛机身包裹屏幕(token themeable) + RSC", category: "mockups", group: "device", status: "new" },
  { slug: "android", name: "Android", description: "安卓外壳 · 打孔摄像头机身包裹屏幕 + RSC", category: "mockups", group: "device", status: "new" },
  { slug: "tablet", name: "Tablet", description: "平板外壳 · iPad 系机身(model 预设尺寸/比例·token themeable) + RSC", category: "mockups", group: "device", status: "new" },
  { slug: "watch", name: "Watch", description: "手表外壳 · Apple Watch 系 squircle 表壳+数码表冠(model 预设尺寸) + RSC", category: "mockups", group: "device", status: "new" },

  // ── 移动端 mobile ──────────────────────────────────────────────
  { slug: "tab-bar", name: "TabBar", description: "底部导航栏 · items 驱动受控/非受控 + 激活 text-primary/aria-current + 角标/红点 + 吃底部安全区(零依赖·H5 主导航)", category: "mobile", group: "nav", status: "new" },
  { slug: "fab", name: "Fab", description: "悬浮操作钮 · fixed 贴边 + speed-dial 子动作错峰展开/主钮旋 45°(零依赖·reduced-motion)", category: "mobile", group: "nav", status: "new" },
  { slug: "action-sheet", name: "ActionSheet", description: "动作面板 · 建在 Base UI Dialog 底滑(同 Drawer 范式·motion token CSS 镜像) + 动作即 Close + 危险态 + 独立取消块 + 安全区", category: "mobile", group: "overlay", status: "new" },
  { slug: "picker", name: "Picker", description: "滚轮选择器 · 多列 CSS scroll-snap 吸附 + 即时高亮居中项 + 停稳防抖 emit + 受控滚定位(零依赖·H5 选时间/地区)", category: "mobile", group: "input", status: "new" },
  { slug: "swipe-action", name: "SwipeAction", description: "列表项滑动操作 · 内容层 translateX 跟手 + 左/右动作面板 + 过半吸附全开/回弹 + 主轴判定放行纵向滚动(零依赖·Pointer Events)", category: "mobile", group: "gesture", status: "new" },
  { slug: "pull-to-refresh", name: "PullToRefresh", description: "下拉刷新 · 置顶下拉带阻尼 + 过阈进 armed + 松手触发并保持刷新态至 Promise 结束回弹(零依赖·Pointer Events)", category: "mobile", group: "gesture", status: "new" },
  { slug: "safe-area", name: "SafeArea", description: "安全区适配 · env(safe-area-inset-*) 作 padding/margin 应用到指定边 + min 兜底 + as 多态(零依赖·RSC·刘海/底部横条)", category: "mobile", group: "layout", status: "new" },
  // —— react-bits 移植批 ——
  { slug: "ascii-text", name: "ASCIIText", description: "ASCII 字符画 · 把文字渲染成 ASCII 字符画 · canvas2d 逐像素亮度采样映射字符 + 正弦波动位移 + 鼠标驱动 hue-rotate 色相（零依赖去 three.js·token·reduced-motion）", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "curved-loop", name: "CurvedLoop", description: "弧形跑马灯 · 沿二次贝塞尔曲线无缝循环滚动的弧形跑马灯文字 · SVG textPath + rAF 续滚 + 可拖拽拨动(零依赖·token/currentColor·reduced-motion)", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "falling-text", name: "FallingText", description: "文字散落 · 文字按词散落物理特效 · 触发后逐词受重力下落/撞墙反弹堆叠 + 指针拖拽抛掷(零依赖 RAF 自写二维刚体·token·reduced-motion)", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "fuzzy-text", name: "FuzzyText", description: "噪点模糊标题 · 信号噪点模糊标题 · canvas2d 逐行/逐列随机错位扫描 + 悬停增强抖动(零依赖·token·reduced-motion 退静态帧)", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "scrambled-text", name: "ScrambledText", description: "乱码悬停文字 · 指针靠近文字逐字翻滚乱码再收敛的悬停文字特效 · 半径内越近翻滚越久 + 可自定字符集/速度（零依赖 RAF·reduced-motion）", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "reveal", name: "Reveal", description: "逐级揭示 · 通用「逐级揭示」块级动效原语 · Reveal 包裹元素进入视口时从位移/透明/缩放过渡到正常 + Stagger/StaggerItem 让子项按序错峰入场（非文字动画 · 作用于任意块级内容 · motion 运行时 · 吃 token · reduced-motion 直出终态）", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "scroll-float", name: "ScrollFloat", description: "滚动浮现标题 · ：随容器滚过视口逐字符从「下沉 + 纵向拉伸横向压扁 + 透明」拔起到正常 · useScroll 绑进度 + 每字符 useTransform 派生 opacity/y/scaleX/scaleY（去 gsap·吃 text-foreground token·reduced-motion 直出清晰标题）", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "scroll-velocity", name: "ScrollVelocity", description: "滚动跑马灯 · 滚动速度跑马灯文字 · 多行交替方向视差 + 随页面滚动加速/变向、静止匀速漂移(motion 速度值驱动·零额外依赖·reduced-motion 冻结自走帧保留 DOM)", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "shuffle", name: "Shuffle", description: "洗牌解密文字 · 逐字「洗牌解密」文本动画 · 字位先滚乱码再按方向顺序锁定真字 + 视口/悬停/循环触发(零依赖 rAF·reduced-motion 直落终态·token 着色)", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "text-cursor", name: "TextCursor", description: "光标拖尾文字 · 特效组件 · 在容器内移动光标时沿轨迹按间距落下一串字形并随机微浮动淡出回收（沿方向旋转 / emoji / 自定义间距上限）(零依赖·motion 运行时·reduced-motion 去浮动)", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "text-pressure", name: "TextPressure", description: "逐字符\"压感\"标题 · 字形随鼠标距离实时插值字重/宽度/倾斜 + 透明度(零依赖 RAF·token 配色·reduced-motion·系统字体兜底)", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "variable-proximity", name: "VariableProximity", description: "邻近可变字体 · 鼠标邻近驱动的逐字可变字体文本 · 按距离插值 font-variation-settings（wght/opsz 等轴）+ linear/exponential/gaussian 三档衰减（零依赖 RAF · reduced-motion 定格 from · sr-only 完整朗读）", category: "typography", group: "text", tags: ["animated"], status: "new" },
  { slug: "antigravity", name: "Antigravity", description: "反重力粒子 · 吸附背景 · 光标靠近把漂浮粒子吸入环绕轨道(波动+脉冲+取向)，离开缓回原位 · 磁吸半径/环半径/形状/自动巡游可调(canvas2d 零依赖·token 配色·reduced-motion 静态点阵)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "blob-cursor", name: "BlobCursor", description: "果冻光标 · 拖尾组件 · 领头跟手 + 多滴弹性拖尾经 SVG gooey 滤镜融成液态水银(去 gsap·motion useSpring·token·reduced-motion)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "click-spark", name: "ClickSpark", description: "点击火花 · 点击迸发火花的交互背景包裹器 · 点击点放射一圈短线段沿角度缓动飞散 + 数量/半径/长度/时长/缓动全可调（canvas2d+RAF 零依赖·token 取色·reduced-motion 静默·RSC 安全·jsdom 安全）", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "crosshair", name: "Crosshair", description: "准星十字线 · 鼠标跟随的容器内准星十字线 · lerp 平滑拖尾 + 进入抖动脉冲 + token 配色(零依赖·reduced-motion)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "electric-border", name: "ElectricBorder", description: "通电边框 · 通电跳动的边框装饰 · SVG 湍流位移描边 + 多层模糊光晕模拟放电辉光(零依赖·token·reduced-motion)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "ghost-cursor", name: "GhostCursor", description: "幽灵拖尾光标 · 跟随指针的幽灵烟雾拖尾 · fbm 噪声烟团 + 环形帧缓冲历史尾迹 + 惯性滑行渐隐（ogl WebGL·去 three.js·reduced-motion 降级）", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "gradual-blur", name: "GradualBlur", description: "渐进贴边模糊 · 沿容器某一边叠加多层 backdrop-filter 的渐进式模糊贴边 · 八方向/曲线/指数递增 + 悬停增强 + 进场淡入(零依赖·tokens·reduced-motion)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "image-trail", name: "ImageTrail", description: "光标图片拖尾 · 光标拖尾图片组件 · 移动光标沿轨迹依次甩出图片淡入跟随、缩小淡出(零依赖 RAF+lerp·token·reduced-motion)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "laser-flow", name: "LaserFlow", description: "激光束 · 自顶向下倾泻的体积激光束 WebGL 背景 · 极坐标光束几何 + fbm 噪声雾 + 行进微流光 + 指针牵引倾斜(ogl 去 three·主题感知·reduced-motion 降级)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "magic-rings", name: "MagicRings", description: "魔法光环 · 同心魔法光环装饰背景 · GLSL 循环扩张/淡入淡出双色波纹 + 噪点颗粒 + 鼠标视差/悬停缩放/点击爆发（ogl·token 双色·reduced-motion 静态同心环降级）", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "magnet", name: "Magnet", description: "指针磁吸 · 交互组件 · 内容按「到中心距离/强度」牵引跟随指针、离开平滑归位(零依赖·reduced-motion 钳位)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "magnet-lines", name: "MagnetLines", description: "磁力线网格 · 指针驱动的磁力线网格 · rows×columns 细线段实时朝向鼠标(acos 反三角求角) + token 线色(零依赖·reduced-motion 静止)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "meta-balls", name: "MetaBalls", description: "黏液融球 · 一组黏液球（metaball）公转游走、距离平方反比势场叠加 smoothstep 等值面产生融合/分裂的有机黏连背景 · 主体球与跟随鼠标的光标球交界处混色 + 自动巡游兜底(ogl·token 配色·reduced-motion 静态渐变球团 fallback)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "metallic-paint", name: "MetallicPaint", description: "液态金属漆面 · WebGL 装饰背景 · fbm 液态扰动 + RGB 折射色散 + 多段金属条纹梯度(ogl·token·reduced-motion 降级)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "orbit-images", name: "OrbitImages", description: "轨道环绕 · 沿轨道环绕流转的子项编排组件 · 9 种形状预设(椭圆/圆/方/三角/星/心/无穷/波浪+custom path)+等距铺满/鱼贯出发+可倾斜+中心叠层(纯 CSS offset-path·零依赖·RSC 安全·reduced-motion)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "pixel-trail", name: "PixelTrail", description: "像素余晖拖尾 · 鼠标划过点亮背后的像素网格、拖尾随时间淡灭的颗粒余晖背景 · 自维护 CPU 拖尾缓冲 + ogl data texture 着色 + 可选 gooey 液态融合(ogl·token·reduced-motion)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "pixel-transition", name: "PixelTransition", description: "像素转场卡 · 像素马赛克转场卡片：双层内容叠放，悬停/聚焦/点击触发一幕随机散入再散出的像素幕布完成切换 · 自定网格密度/过场时长/只进不退 + token 像素色（去 gsap·motion 减包驱动·reduced-motion 直切）", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "ribbons", name: "Ribbons", description: "飘带跟随 · 弹簧追随鼠标的飘带 WebGL 效果 · ogl Polyline 多条折线弹性拖尾 + 可选沿带渐隐/正弦波动(ogl·token·reduced-motion)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "shape-blur", name: "ShapeBlur", description: "模糊形状高光 · 鼠标揭示的模糊形状高光 WebGL 件 · 圆角矩形/圆/圆环/三角四形态 + 阻尼跟随柔光圆擦亮边缘(ogl·token·reduced-motion 降级静态光晕)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "splash-cursor", name: "SplashCursor", description: "流体溅射光标 · 指针流体溅射光标特效 · 移动溅彩+点击爆斑+拖尾消散 · 彩虹色相轮/固定 chart token 双模(canvas2d 零依赖·reduced-motion·RSC 安全)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "star-border", name: "StarBorder", description: "流星描边按钮 · 上下两道 radial-gradient 光带沿边沿来回扫过(纯 CSS·零依赖·RSC 安全)，光带色走 token、内壳 bg-surface/border-border，多态 as + reduced-motion 自动停。", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "sticker-peel", name: "StickerPeel", description: "可拖拽贴纸 · hover/按住顶部卷边揭起 + 落地投影 + 鼠标跟随高光（零依赖·PointerEvents 拖拽·reduced-motion）", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "target-cursor", name: "TargetCursor", description: "准星光标 · 跟随鼠标的准星自定义光标 · 中心圆点 + 四角括号空闲自转、悬停命中元素时展开包裹其包围盒(去 gsap·裸 rAF lerp·token 着色·reduced-motion)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "cubes", name: "Cubes", description: "立方体阵列 · 3D 立方体阵列交互背景 · 指针靠近按距离衰减倾斜 + 空闲自动游走 + 点击环形涟漪高亮（零依赖去 gsap·token 配色·reduced-motion）", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "logo-loop", name: "LogoLoop", description: "logo 跑马灯 · 无缝无限滚动的 logo 跑马灯 · RAF 速度低通平滑 + 序列复制无缝回卷 · 横纵四向/悬停变速暂停/单项放大/两端渐隐(零依赖·token·reduced-motion)", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "bubble-menu", name: "BubbleMenu", description: "气泡导航菜单 · logo 气泡 + 汉堡切换钮，点开整屏铺一组错落旋转胶囊导航 · 胶囊弹性 scale 入场 + 标签上滑淡入按序错峰(motion·零 gsap·reduced-motion)", category: "navigation", group: "global", tags: ["animated"], status: "new" },
  { slug: "card-nav", name: "CardNav", description: "卡片导航 · ：胶囊顶栏汉堡点击后整条高度展开，内部卡片逐张错峰 y 位移淡入 · 受控/非受控开合 + token 卡片色(motion 去 gsap·reduced-motion)", category: "navigation", group: "global", tags: ["animated"], status: "new" },
  { slug: "flowing-menu", name: "FlowingMenu", description: "竖排流动菜单 · 指针近边缘判进/离向揭幕 + 循环跑马灯(文字/图片)(零依赖去 gsap·CSS keyframes + transition·token·reduced-motion)", category: "navigation", group: "global", tags: ["animated"], status: "new" },
  { slug: "gooey-nav", name: "GooeyNav", description: "胶质导航条 · 切换时白色药丸 motion 弹簧滑到目标 + 迸射一圈彩色粒子经 blur/contrast 熔成黏稠液滴(零依赖 CSS 关键帧·token 取色·受控/非受控·reduced-motion)", category: "navigation", group: "global", tags: ["animated"], status: "new" },
  { slug: "pill-nav", name: "PillNav", description: "胶囊导航条 · 悬停底部圆涨满 + 文案翻转反相 + 激活指示圆点(纯 CSS·零依赖·RSC 安全·reduced-motion)", category: "navigation", group: "global", tags: ["animated"], status: "new" },
  { slug: "staggered-menu", name: "StaggeredMenu", description: "侧滑分层菜单 · 侧滑分层导航菜单 · 触发按钮（菜单↔关闭文字滚动 + 加号旋转 225°）唤起面板 · 多层色层错峰滑入做叠纸质感 + 主条目自下而上带旋转依次入场 + 序号/社交链接尾随淡入（motion 去 gsap·token·reduced-motion）", category: "navigation", group: "global", tags: ["animated"], status: "new" },
  { slug: "bounce-cards", name: "BounceCards", description: "扇形弹跳卡 · 一叠卡片扇形铺开的入场弹跳组件 · 逐张 scale 0 弹性弹入 + hover 推挤让位（零依赖去 gsap·motion 弹簧·reduced-motion）", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "card-swap", name: "CardSwap", description: "卡片洗牌 · 3D 透视卡片自动洗牌组件 · 最前卡下坠 → 其余递进 → 绕回队尾循环 + 复合 CardSwap.Card 默认皮肤（去 gsap·motion useAnimate·reduced-motion）", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "chroma-grid", name: "ChromaGrid", description: "聚光卡片墙 · 光标聚光揭示的卡片墙 · 整片灰度暗化、光标圈内透出全彩 + 单卡 hover 径向高光（弹性跟随·reduced-motion）", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "circular-gallery", name: "CircularGallery", description: "弧形图片画廊 · ogl 弧形图片画廊 · 卡片沿圆弧弯曲倾斜排开 + 滚轮/拖拽惯性平移首尾无缝循环(ogl·圆角SDF·token化标题·reduced-motion 降级静态轨道)", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "dome-gallery", name: "DomeGallery", description: "球面图库 · ：图片瓦片贴在 CSS 3D 半球内壁，拖拽旋转浏览、点击放大查看 · 原生 PointerEvents 自搓拖拽+RAF 惯性 + motion 灯箱(零依赖·token·reduced-motion)", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "flying-posters", name: "FlyingPosters", description: "WebGL 海报飞行长廊 · 一列海报随滚轮/拖拽无限循环上下飞过，顶点着色器按 distortion 翻折\"飞起\"·离屏循环复用 + 透视相机景深(ogl·懒加载·StrictMode 安全·reduced-motion 静态海报网格 fallback·去 gsap 改 RAF lerp)", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "infinite-menu", name: "InfiniteMenu", description: "球面菜单 · 可拖拽旋转的菜单球，菜单项围绕球面分布、正对镜头者贴靠为激活项并显覆盖层标题/描述+动作箭头 · 松手惯性衰减 + 自动自旋（零依赖 CSS-3D/RAF·reduced-motion）", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "magic-bento", name: "MagicBento", description: "便当卡片网格 · 魔法便当卡片网格 · 光标跟随径向聚光 + 描边光呼吸 + 可选 3D 倾斜(零依赖·token·reduced-motion)", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "scroll-stack", name: "ScrollStack", description: "滚动堆叠卡 · 滚动驱动的卡片堆叠组件 · 逐张钉住 + 缩放递进 + 可选旋转/景深模糊(零依赖原生滚动+RAF·token 皮肤·reduced-motion 静态平铺)", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "profile-card", name: "ProfileCard", description: "全息名片卡 · 指针倾斜 + 全息炫彩名片卡 · RAF 阻尼弹簧驱动 3D 旋转/光晕（零依赖）+ chart token 全息渐变 + 无头像落首字母占位（reduced-motion 静态降级）", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "tilt", name: "Tilt", description: "视差倾斜包裹器 · 裹住任意 children 做 3D 倾斜(区别 TiltedCard 的固定卡片结构) · 指针/陀螺仪/手动角度三种驱动 + 全窗跟踪 + 单轴限制 + 反向 + 静息角 + 悬停放大 · glare 跟随指针的反光高光 · onTiltMove 每帧回传角度与反光可驱动多层视差 · 角度/反光是纯函数可测 · 吃瑚琏动效曲线·默认尊重 reduced-motion(零依赖·对标 react-parallax-tilt)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "tilted-card", name: "TiltedCard", description: "倾斜卡片 · 指针驱动的 3D 倾斜卡片 · perspective + rotateX/Y 弹簧倾斜 + 悬停放大 + 跟随指针的浮动提示气泡（motion 弹簧·零新依赖·reduced-motion）", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "pixel-card", name: "PixelCard", description: "像素卡片 · canvas2d 像素卡片 · 悬停/聚焦时像素自中心波纹生长+闪烁、离开收缩消散 · 4 变体/可定制 gap·speed·colors(零依赖 RAF·token 配色·reduced-motion 静止)", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "decay-card", name: "DecayCard", description: "湍流溶解卡 · 鼠标驱动的「湍流溶解」图片卡 · SVG feTurbulence+feDisplacementMap 随鼠标速度融化图像 + 带阻尼的视差倾斜平移（零依赖去 gsap·RAF 缓动·reduced-motion）", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "reflective-card", name: "ReflectiveCard", description: "金属反光证件卡 · 对角高光横扫 + 磨砂噪点 + 渐变发丝边框(纯 CSS 零依赖·token·RSC 安全·reduced-motion)，内容可插槽化", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "folder", name: "Folder", description: "3D 文件夹 · 点击展开的 3D 文件夹 · 三层纸张扇形铺开 + 展开后磁吸跟随鼠标(零依赖纯 CSS transform·token 派生·reduced-motion)", category: "data-display", group: "collection", tags: ["animated"], status: "new" },
  { slug: "border-glow", name: "BorderGlow", description: "发光边框卡 · 指针感应发光边框卡片 · 沿光锥点亮彩色网格边框 + 外层霓虹光晕(随边缘贴近度渐变) + 可选挂载自动扫光(零依赖·token·reduced-motion)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "glass-icons", name: "GlassIcons", description: "玻璃图标网格 · 玻璃拟态图标按钮网格 · 背面 3D 旋转彩色发光板 + 前面磨砂玻璃片（backdrop-blur·inset 高光边），hover/focus 彩板抬升旋转、玻璃前推、标签滑出（纯 CSS 零依赖·token 配色·RSC 安全·reduced-motion）", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "glass-surface", name: "GlassSurface", description: "液态玻璃折射面 · SVG feDisplacementMap 三通道色散 + RGB 色差边缘(零依赖·token 磨砂底/发丝边/焦点环·RSC client·非 SVG 浏览器回落 backdrop-blur·reduced-motion 关过渡)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "lanyard", name: "Lanyard", description: "挂绳工牌 · 可拖拽的挂绳工牌 · 单摆+阻尼弹簧物理回弹(原生 PointerEvents+RAF·零三方依赖) + SVG 二次贝塞尔挂绳随摆角实时弯折 + token 配色(挂绳 primary·工牌 surface/border)·reduced-motion 松手即静止归位", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "model-viewer", name: "ModelViewer", description: "3D 模型舞台 · 交互式 3D 模型查看舞台 · 拖拽旋转(惯性) + 鼠标视差 + 悬停倾斜 + 自动旋转 + 接触阴影(零依赖 CSS 3D · RAF · reduced-motion)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "fluid-glass", name: "FluidGlass", description: "流体玻璃 · 跟随指针的流体玻璃折射背景 · 程序化流动渐变底图 + 圆形玻璃透镜实时折射/放大/边缘色散/菲涅尔高光(ogl 单 shader·零 3D 依赖·reduced-motion)", category: "decoration", group: "overlay-fx", tags: ["animated"], status: "new" },
  { slug: "elastic-slider", name: "ElasticSlider", description: "橡皮筋音量滑块 · 拖到两端轨道横拉纵压 + 图标回弹位移 + hover 整体放大、松手 spring 弹回(motion·零新依赖·reduced-motion)", category: "forms", group: "basic", tags: ["animated"], status: "new" },
  { slug: "balatro", name: "Balatro", description: "螺旋油彩 · WebGL 背景 · 像素旋涡 + 5 次正弦迭代油画混色 + 可选鼠标交互/自转(ogl·三色吃 chart token·reduced-motion conic 兜底)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "ballpit", name: "Ballpit", description: "彩球球池 · 一坑彩色小球的可交互物理球池 · 重力下落+墙壁回弹+球球弹性碰撞+光标排斥(零依赖 canvas2d·chart token·reduced-motion)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "beams", name: "Beams", description: "流动光柱 · 流动体积光柱 WebGL 背景 · perlin 噪声扰动起伏 + 方向光受光梯度 + 倾斜光幕 + 胶片颗粒(ogl·token·reduced-motion 降级静态渐变)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "color-bends", name: "ColorBends", description: "多色流场 · WebGL 背景组件 · 正弦折叠噪声场按软阈值带宽采样叠加生成相互弯折的有机色带 + 指针视差/牵引/自动旋转(ogl·主题感知·reduced-motion 降级)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "dark-veil", name: "DarkVeil", description: "暗色帷幕 · CPPN 神经场暗色流动帷幕 WebGL 背景 · 色相旋转/扫描线/颗粒/空间扭曲(ogl·懒加载·reduced-motion 降级静态渐变)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "dither", name: "Dither", description: "抖动波纹 · 复古有序抖动波纹 WebGL 背景 · Perlin/fbm 波纹场 + 8×8 Bayer 抖动 + 色阶量化/像素马赛克(ogl 单遍 shader·token·reduced-motion 降级)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "dot-field", name: "DotField", description: "交互式点阵背景 · 光标推挤点阵鼓胀 + 移动泛起径向辉光，可选波浪起伏/星点闪烁（canvas2d 零依赖·token 配色·reduced-motion 静态降级）", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "evil-eye", name: "EvilEye", description: "火焰邪眼 · WebGL 背景 · 极坐标多层程序化噪声画出翻腾火焰瞳孔 + 瞳孔惯性跟随光标 + 外圈弥散辉光（ogl·token 自适应·reduced-motion 静态降级）", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "faulty-terminal", name: "FaultyTerminal", description: "故障终端雨 · 出故障的 CRT 终端字符雨 WebGL 背景 · fbm 噪声点阵 + 横向撕裂/扫描线/闪烁/桶形畸变/色散 + 鼠标涟漪(ogl·token 着色·reduced-motion 兜底)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "ferrofluid", name: "Ferrofluid", description: "铁磁流体 · 液态金属铁磁流体 WebGL 背景组件 · value-noise 峰脊 + smin 软融合 + rim 亮带流动 + 鼠标下凹交互(ogl·主题 chart token·reduced-motion 径向渐变兜底)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "floating-lines", name: "FloatingLines", description: "漂浮线束 · WebGL 背景 · 三组正弦波线束随时间漂浮 + log 半径扭曲旋转 + 渐变色带插值 + 可选指针径向弯曲(ogl 零新依赖·token 吃 chart·reduced-motion 降级静态渐变)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "galaxy", name: "Galaxy", description: "视差星河 · 程序化生成的多层视差星河 WebGL 背景 · Hash 铺点+十字辉光+HSV 调色+三角波闪烁+自转/鼠标斥力，4 层尺度叠加深空纵深(ogl·懒加载·StrictMode 安全·reduced-motion 降级 chart token 径向渐变)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "gradient-blinds", name: "GradientBlinds", description: "渐变百叶窗 · WebGL 背景 · 多色站水平渐变 + 竖条百叶明暗调制 + 跟随鼠标聚光灯 + 颗粒噪声(可旋转/镜像/扭曲) · 默认吃 chart token(ogl·reduced-motion 静态百叶降级)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "grainient", name: "Grainient", description: "颗粒渐变 · 三色域扭曲 + 胶片颗粒的 WebGL 渐变背景 · 噪声驱动旋转 + 实时 grain/对比度后期(ogl·reduced-motion 降级静态渐变)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "grid-distortion", name: "GridDistortion", description: "网格扭曲 · 鼠标拖拽的液态网格扭曲 WebGL 背景 · 数据纹理位移场 + 鼠标速度涟漪/弛豫回弹(ogl·零外部资源默认程序化网格底纹·token 着色·reduced-motion 降级)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "grid-motion", name: "GridMotion", description: "倾斜网格视差 · 背景 · 鼠标横移每行奇偶反向弹性追随 + 中心径向光晕(零依赖 motion useSpring·token·reduced-motion)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "grid-scan", name: "GridScan", description: "扫描网格 · 透视扫描网格 WebGL 背景 · 射线投射无限网格(实线/虚线/点线)+纵深推进的发光扫描脉冲+鼠标视差偏摆(ogl·token·reduced-motion 降级静态网格)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "hyperspeed", name: "Hyperspeed", description: "跃迁隧道 · 超空间跃迁 warp 隧道背景 · 从消失点放射的双色车灯光带向观察者冲来 + 湍流扭曲 + 程序化辉光(ogl 单 shader·零新依赖·token·reduced-motion 静态降级)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "letter-glitch", name: "LetterGlitch", description: "字符故障雨 · 终端字符故障雨背景 · canvas 等宽字符矩阵按节拍随机翻字翻色 + 颜色逐帧插值平滑 + 内/外缘暗角(零依赖 canvas2d·token 调色板·reduced-motion)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "lightfall", name: "Lightfall", description: "光束坠落 · 隧道光束坠落 WebGL 背景 · 多色光束按高度循环取色 + 中心辉光 + 闪烁/拖尾 + 鼠标牵引(ogl·token·reduced-motion 降级)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "lightning", name: "Lightning", description: "电弧极光 · fbm 噪声电弧/极光柱 WebGL 背景 · 距离场反比辉光 + hash 随机闪烁(ogl·token 取色·reduced-motion 静态降级)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "light-pillar", name: "LightPillar", description: "体积光柱 · WebGL 背景 · 沿 y 轴 raymarch 累积辉光 + 多层波动噪声 + 顶底双色纵向渐变(ogl·token 自适应·reduced-motion 降级)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "light-rays", name: "LightRays", description: "光束放射 · 体积光束放射 WebGL 背景 · 八向原点 + 双层正弦扰动/扩散衰减/脉动/噪点/扭曲 + 鼠标方向跟随(ogl·token 着色·reduced-motion 静态渐变兜底)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "line-waves", name: "LineWaves", description: "波纹线阵 · 流动波纹线阵 WebGL 背景 · 双正弦位移场 + 噪声脊线 + 三通道色相循环 + 鼠标局部隆起(ogl·chart token 配色·reduced-motion 静态线纹降级)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "liquid-ether", name: "LiquidEther", description: "液态色域 · 鼠标驱动的液态色域 WebGL 背景 · 域扭曲+metaball 翻涌 + 指针搅动/自动巡游(ogl·token·reduced-motion 降级)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "pixel-blast", name: "PixelBlast", description: "点阵翻涌 · 抖动点阵翻涌的 WebGL 背景 · FBM 噪声 + 8×8 Bayer 有序抖动量化成方块/圆/三角/菱形像素 + 四周渐隐（ogl·token·reduced-motion 降级静态点阵）", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "pixel-snow", name: "PixelSnow", description: "像素雪场 · 像素化体素雪场 WebGL 背景 · 光线步进逐格哈希生雪 + 景深淡出 · 方块/圆点/六臂雪花三变体（ogl 去 three.js·token 着色·reduced-motion 静态点阵降级）", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "plasma", name: "Plasma", description: "等离子流动 · WebGL 背景 · 60 步光线步进 shader + 鼠标扰动 + forward/reverse/pingpong 三向(ogl·token 染色·reduced-motion 降级)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "plasma-wave", name: "PlasmaWave", description: "等离子波 · WebGL 背景 · raymarch 双丝带交织流动 + 双色权重混合(ogl·主题感知 chart token·reduced-motion 静态渐变降级)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "prism", name: "Prism", description: "棱镜分光 · WebGL 背景 · ray-march 八面体 SDF 折射出彩虹体积光 + rotate/3drotate/hover 三姿态(ogl·主题色相自适应·reduced-motion 降级)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "prismatic-burst", name: "PrismaticBurst", description: "棱镜光爆 · WebGL 背景 · 从中心放射的体积步进光谱射线(可弯曲扭曲/N 瓣梳理/三维翻滚/hover 跟随) · 默认色带吃 --color-chart-1..5 token(明暗自适应) + 懒加载 ogl 复用 useGlCanvas(StrictMode 安全·reduced-motion 降级静态径向光爆)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "radar", name: "Radar", description: "雷达扫描 · WebGL 背景 · 同心环波纹 + 径向辐条 + 旋转扫描臂 + 边缘衰减 + 鼠标视差(ogl·主色吃 chart token·reduced-motion 降级静态盘)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "ripple-grid", name: "RippleGrid", description: "涟漪网格 · WebGL 背景 · 同心 sin 波推挤网格 + 暗角/辉光/彩虹配色 + 指针局部涟漪(ogl·chart token·reduced-motion 降级静态网格)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "shape-grid", name: "ShapeGrid", description: "几何网格 · 无限滚动几何网格背景 · canvas2d 绘制方/圆/三角/六边形四形，沿任意方向匀速平移环绕 + 鼠标悬停缓动填充与渐隐拖尾（零依赖·token 配色·reduced-motion 静止·jsdom 安全）", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "side-rays", name: "SideRays", description: "侧光束 · 从屏幕一角发散的动态侧光束 WebGL 背景 · 双束角度正弦摆动+平方反比衰减+饱和度/混色调节(ogl·token 双色·reduced-motion 静态兜底)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
  { slug: "soft-aurora", name: "SoftAurora", description: "柔和极光 · WebGL 柔和极光背景 · 3D Perlin 噪声 + cosine 渐变双层叠加 · 鼠标视差(ogl·token 着色·reduced-motion 降级)", category: "decoration", group: "backdrop", tags: ["animated", "webgl"], status: "new" },
];
