"use client";
import type { ShowcaseSpec } from "@hulian/ui";
import {
  buttonShowcase,
  switchShowcase,
  dialogShowcase,
  badgeShowcase,
  cardShowcase,
  skeletonShowcase,
  avatarShowcase,
  inputShowcase,
  textareaShowcase,
  fieldShowcase,
  checkboxShowcase,
  radioShowcase,
  alertShowcase,
  sliderShowcase,
  tabsShowcase,
  tooltipShowcase,
  popoverShowcase,
  accordionShowcase,
  breadcrumbShowcase,
  paginationShowcase,
  tableShowcase,
  carouselShowcase,
  numberTickerShowcase,
  marqueeShowcase,
  drawerShowcase,
  menuShowcase,
  toastShowcase,
  statShowcase,
  chartShowcase,
  selectShowcase,
  comboboxShowcase,
  progressShowcase,
  ratingShowcase,
  stepperShowcase,
  dotPatternShowcase,
  gridPatternShowcase,
  retroGridShowcase,
  rippleShowcase,
  stripedPatternShowcase,
  separatorShowcase,
  numberFieldShowcase,
  alertDialogShowcase,
  toggleShowcase,
  toolbarShowcase,
  meterShowcase,
  formShowcase,
  scrollAreaShowcase,
  checkboxGroupShowcase,
  auroraTextShowcase,
  animatedShinyTextShowcase,
  animatedGradientTextShowcase,
  wordRotateShowcase,
  typingAnimationShowcase,
  sparklesTextShowcase,
  shimmerButtonShowcase,
  rainbowButtonShowcase,
  pulsatingButtonShowcase,
  rippleButtonShowcase,
  borderBeamShowcase,
  shineBorderShowcase,
  meteorsShowcase,
  magicCardShowcase,
  glareHoverShowcase,
  safariShowcase,
  chromeShowcase,
  iphoneShowcase,
  androidShowcase,
  tabletShowcase,
  watchShowcase,
  spinnerShowcase,
  chipShowcase,
  linkShowcase,
  kbdShowcase,
  codeShowcase,
  codeBlockShowcase,
  snippetShowcase,
  spacerShowcase,
  userShowcase,
  imageShowcase,
  navbarShowcase,
  inputOtpShowcase,
  listboxShowcase,
  commandShowcase,
  calendarShowcase,
  datePickerShowcase,
  dateTimePickerShowcase,
  timeFieldShowcase,
  colorPickerShowcase,
  colorSwatchPickerShowcase,
  avatarCirclesShowcase,
  orbitingCirclesShowcase,
  animatedListShowcase,
  progressiveBlurShowcase,
  dockShowcase,
  lensShowcase,
  terminalShowcase,
  bentoGridShowcase,
  animatedThemeTogglerShowcase,
  animatedBeamShowcase,
  heroVideoDialogShowcase,
  worldMapShowcase,
  stackShowcase,
  gridShowcase,
  aspectRatioShowcase,
  emptyShowcase,
  uploadShowcase,
  transferShowcase,
  contextMenuShowcase,
  hoverCardShowcase,
} from "@hulian/ui";

// 唯一 import @hulian/ui 渲染 spec 的地方；只被 ComponentDoc client 岛 import。
export const specBySlug: Record<string, ShowcaseSpec> = {
  button: buttonShowcase,
  switch: switchShowcase,
  dialog: dialogShowcase,
  badge: badgeShowcase,
  card: cardShowcase,
  skeleton: skeletonShowcase,
  avatar: avatarShowcase,
  input: inputShowcase,
  textarea: textareaShowcase,
  field: fieldShowcase,
  checkbox: checkboxShowcase,
  radio: radioShowcase,
  alert: alertShowcase,
  slider: sliderShowcase,
  tabs: tabsShowcase,
  tooltip: tooltipShowcase,
  popover: popoverShowcase,
  accordion: accordionShowcase,
  breadcrumb: breadcrumbShowcase,
  pagination: paginationShowcase,
  table: tableShowcase,
  carousel: carouselShowcase,
  "number-ticker": numberTickerShowcase,
  marquee: marqueeShowcase,
  drawer: drawerShowcase,
  menu: menuShowcase,
  toast: toastShowcase,
  stat: statShowcase,
  chart: chartShowcase,
  select: selectShowcase,
  combobox: comboboxShowcase,
  progress: progressShowcase,
  rating: ratingShowcase,
  stepper: stepperShowcase,
  "dot-pattern": dotPatternShowcase,
  "grid-pattern": gridPatternShowcase,
  "retro-grid": retroGridShowcase,
  ripple: rippleShowcase,
  "striped-pattern": stripedPatternShowcase,
  separator: separatorShowcase,
  "number-field": numberFieldShowcase,
  "alert-dialog": alertDialogShowcase,
  toggle: toggleShowcase,
  toolbar: toolbarShowcase,
  meter: meterShowcase,
  form: formShowcase,
  "scroll-area": scrollAreaShowcase,
  "checkbox-group": checkboxGroupShowcase,
  "aurora-text": auroraTextShowcase,
  "animated-shiny-text": animatedShinyTextShowcase,
  "animated-gradient-text": animatedGradientTextShowcase,
  "word-rotate": wordRotateShowcase,
  "typing-animation": typingAnimationShowcase,
  "sparkles-text": sparklesTextShowcase,
  "shimmer-button": shimmerButtonShowcase,
  "rainbow-button": rainbowButtonShowcase,
  "pulsating-button": pulsatingButtonShowcase,
  "ripple-button": rippleButtonShowcase,
  "border-beam": borderBeamShowcase,
  "shine-border": shineBorderShowcase,
  meteors: meteorsShowcase,
  "magic-card": magicCardShowcase,
  "glare-hover": glareHoverShowcase,
  safari: safariShowcase,
  chrome: chromeShowcase,
  iphone: iphoneShowcase,
  android: androidShowcase,
  tablet: tabletShowcase,
  watch: watchShowcase,
  spinner: spinnerShowcase,
  chip: chipShowcase,
  link: linkShowcase,
  kbd: kbdShowcase,
  code: codeShowcase,
  "code-block": codeBlockShowcase,
  snippet: snippetShowcase,
  spacer: spacerShowcase,
  user: userShowcase,
  image: imageShowcase,
  navbar: navbarShowcase,
  "input-otp": inputOtpShowcase,
  listbox: listboxShowcase,
  command: commandShowcase,
  calendar: calendarShowcase,
  "date-picker": datePickerShowcase,
  "date-time-picker": dateTimePickerShowcase,
  "time-field": timeFieldShowcase,
  colorpicker: colorPickerShowcase,
  "color-swatch-picker": colorSwatchPickerShowcase,
  "avatar-circles": avatarCirclesShowcase,
  "orbiting-circles": orbitingCirclesShowcase,
  "animated-list": animatedListShowcase,
  "progressive-blur": progressiveBlurShowcase,
  dock: dockShowcase,
  lens: lensShowcase,
  terminal: terminalShowcase,
  "bento-grid": bentoGridShowcase,
  "animated-theme-toggler": animatedThemeTogglerShowcase,
  "animated-beam": animatedBeamShowcase,
  "hero-video-dialog": heroVideoDialogShowcase,
  "world-map": worldMapShowcase,
  stack: stackShowcase,
  grid: gridShowcase,
  "aspect-ratio": aspectRatioShowcase,
  empty: emptyShowcase,
  upload: uploadShowcase,
  transfer: transferShowcase,
  "context-menu": contextMenuShowcase,
  "hover-card": hoverCardShowcase,
};
