"use client";
import type { ShowcaseSpec } from "@hulian/ui";
import {
  buttonShowcase,
  switchShowcase,
  dialogShowcase,
  badgeShowcase,
  cardShowcase,
  skeletonShowcase,
  avatarShowcase,
  inputShowcase,
  textareaShowcase,
  fieldShowcase,
  checkboxShowcase,
  radioShowcase,
  alertShowcase,
  sliderShowcase,
  tabsShowcase,
  tooltipShowcase,
  popoverShowcase,
  accordionShowcase,
  breadcrumbShowcase,
  paginationShowcase,
  tableShowcase,
  numberTickerShowcase,
  drawerShowcase,
  menuShowcase,
  toastShowcase,
  statShowcase,
  chartShowcase,
  selectShowcase,
  comboboxShowcase,
} from "@hulian/ui";

// 唯一 import @hulian/ui 渲染 spec 的地方；只被 ComponentDoc client 岛 import。
export const specBySlug: Record<string, ShowcaseSpec> = {
  button: buttonShowcase,
  switch: switchShowcase,
  dialog: dialogShowcase,
  badge: badgeShowcase,
  card: cardShowcase,
  skeleton: skeletonShowcase,
  avatar: avatarShowcase,
  input: inputShowcase,
  textarea: textareaShowcase,
  field: fieldShowcase,
  checkbox: checkboxShowcase,
  radio: radioShowcase,
  alert: alertShowcase,
  slider: sliderShowcase,
  tabs: tabsShowcase,
  tooltip: tooltipShowcase,
  popover: popoverShowcase,
  accordion: accordionShowcase,
  breadcrumb: breadcrumbShowcase,
  pagination: paginationShowcase,
  table: tableShowcase,
  "number-ticker": numberTickerShowcase,
  drawer: drawerShowcase,
  menu: menuShowcase,
  toast: toastShowcase,
  stat: statShowcase,
  chart: chartShowcase,
  select: selectShowcase,
  combobox: comboboxShowcase,
};
