"use client";
import type { ShowcaseSpec } from "@hulianui/ui";
import {
  buttonShowcase,
  switchShowcase,
  dialogShowcase,
  annotationShowcase,
  badgeShowcase,
  dotShowcase,
  statusDotShowcase,
  beianFooterShowcase,
  book3dShowcase,
  calloutShowcase,
  cardShowcase,
  skeletonShowcase,
  avatarShowcase,
  inputShowcase,
  textareaShowcase,
  fieldShowcase,
  secretFieldShowcase,
  passwordGeneratorShowcase,
  eventStreamShowcase,
  interceptCardShowcase,
  scopeMatrixShowcase,
  checkboxShowcase,
  radioShowcase,
  alertShowcase,
  sliderShowcase,
  tabsShowcase,
  tagShowcase,
  stepsShowcase,
  tooltipShowcase,
  popoverShowcase,
  accordionShowcase,
  collapsibleShowcase,
  segmentedShowcase,
  breadcrumbShowcase,
  anchorShowcase,
  descriptionsShowcase,
  pageHeaderShowcase,
  paginationShowcase,
  tableShowcase,
  pricingTableShowcase,
  jsonViewerShowcase,
  proTableShowcase,
  editableTableShowcase,
  watermarkShowcase,
  carouselShowcase,
  videoShowcase,
  voiceRecordShowcase,
  resizableShowcase,
  affixShowcase,
  timelineShowcase,
  numberTickerShowcase,
  marqueeShowcase,
  drawerShowcase,
  menuShowcase,
  toastShowcase,
  modalShowcase,
  notificationShowcase,
  serviceMessageShowcase,
  spinShowcase,
  statShowcase,
  chartShowcase,
  selectShowcase,
  comboboxShowcase,
  remoteSelectShowcase,
  progressShowcase,
  ratingShowcase,
  stepperShowcase,
  dotPatternShowcase,
  gridPatternShowcase,
  retroGridShowcase,
  rippleShowcase,
  stripedPatternShowcase,
  spotlightShowcase,
  separatorShowcase,
  numberFieldShowcase,
  alertDialogShowcase,
  toggleShowcase,
  toolbarShowcase,
  meterShowcase,
  formShowcase,
  formDialogShowcase,
  proFormShowcase,
  loginFormShowcase,
  authPanelShowcase,
  clickCaptchaShowcase,
  stepsFormShowcase,
  scrollAreaShowcase,
  checkboxGroupShowcase,
  auroraTextShowcase,
  animatedShinyTextShowcase,
  animatedGradientTextShowcase,
  wordRotateShowcase,
  typingAnimationShowcase,
  sparklesTextShowcase,
  splitTextShowcase,
  blurTextShowcase,
  decryptedTextShowcase,
  glitchTextShowcase,
  circularTextShowcase,
  scrollRevealShowcase,
  trueFocusShowcase,
  shimmerButtonShowcase,
  rainbowButtonShowcase,
  pulsatingButtonShowcase,
  rippleButtonShowcase,
  borderBeamShowcase,
  shineBorderShowcase,
  meteorsShowcase,
  magicCardShowcase,
  glareHoverShowcase,
  auroraShowcase,
  particlesShowcase,
  flickeringGridShowcase,
  wavyBackgroundShowcase,
  cardSpotlightShowcase,
  silkShowcase,
  iridescenceShowcase,
  threadsShowcase,
  orbShowcase,
  liquidChromeShowcase,
  safariShowcase,
  chromeShowcase,
  iphoneShowcase,
  androidShowcase,
  tabletShowcase,
  watchShowcase,
  spinnerShowcase,
  chipShowcase,
  couponShowcase,
  linkShowcase,
  kbdShowcase,
  codeShowcase,
  codeBlockShowcase,
  snippetShowcase,
  spacerShowcase,
  userShowcase,
  commentShowcase,
  imageShowcase,
  navbarShowcase,
  navMenuShowcase,
  treeShowcase,
  treeSelectShowcase,
  cascaderShowcase,
  regionCascaderShowcase,
  countrySelectShowcase,
  markdownEditorShowcase,
  markdownShowcase,
  mathShowcase,
  questionCardShowcase,
  inputOtpShowcase,
  listboxShowcase,
  mentionsShowcase,
  commandShowcase,
  colorPickerShowcase,
  colorFieldShowcase,
  colorSwatchPickerShowcase,
  avatarCirclesShowcase,
  orbitingCirclesShowcase,
  animatedListShowcase,
  progressiveBlurShowcase,
  dockShowcase,
  lensShowcase,
  terminalShowcase,
  bentoGridShowcase,
  animatedThemeTogglerShowcase,
  animatedBeamShowcase,
  heroVideoDialogShowcase,
  tourShowcase,
  worldMapShowcase,
  stackShowcase,
  containerShowcase,
  gridShowcase,
  aspectRatioShowcase,
  fitScreenShowcase,
  emptyShowcase,
  listShowcase,
  resultShowcase,
  uploadShowcase,
  imageCropperShowcase,
  transferShowcase,
  contextMenuShowcase,
  hoverCardShowcase,
  searchFormShowcase,
  headingShowcase,
  textShowcase,
  proseShowcase,
  layoutShowcase,
  adminLayoutShowcase,
  popconfirmShowcase,
  menubarShowcase,
  navigationMenuShowcase,
  dateRangePickerShowcase,
  timePickerShowcase,
  iconPickerShowcase,
  routeTabsShowcase,
  dividerShowcase,
  backTopShowcase,
  statisticShowcase,
  sortableShowcase,
  kanbanShowcase,
  flowShowcase,
  sankeyShowcase,
  sparklineShowcase,
  funnelShowcase,
  queueLaneShowcase,
  typingDotsShowcase,
  chatMessageShowcase,
  conversationShowcase,
  promptInputShowcase,
  thinkingBlockShowcase,
  toolCallShowcase,
  agentPlanShowcase,
  dossierShowcase,
  artifactShowcase,
  confirmCardShowcase,
  threadListShowcase,
  taskRunnerShowcase,
  promptSuggestionsShowcase,
  messageActionsShowcase,
  citationShowcase,
  streamingTextShowcase,
  safeAreaShowcase,
  fabShowcase,
  tabBarShowcase,
  actionSheetShowcase,
  swipeActionShowcase,
  pullToRefreshShowcase,
  pickerShowcase,
  virtualListShowcase,
  infiniteScrollShowcase,
  qrcodeShowcase,
  viewportShowcase,
  masonryShowcase,
  documentSheetShowcase,
  ganttShowcase,
  schedulerShowcase,
  imageViewerShowcase,
  danmakuShowcase,
  liveChatShowcase,
  giftFeedShowcase,
  floatingReactionsShowcase,
  livePlayerShowcase,
  liveProductCardShowcase,
  logViewerShowcase,
  codeDiffShowcase,
  diffStatShowcase,
  scoreRingShowcase,
  heatmapShowcase,
  codeReviewThreadShowcase,
  fileTreeShowcase,
  buttonGroupShowcase,
  socialButtonShowcase,
  bannerShowcase,
  relativeTimeShowcase,
  choiceboxShowcase,
  creditCardShowcase,
  emojiPickerShowcase,
  glimpseShowcase,
  gitCommitShowcase,
  deployStatusShowcase,
  shieldBadgeShowcase,
  awardBadgeShowcase,
  contributionGraphShowcase,
  legendShowcase,
  appLauncherShowcase,
  regionSelectShowcase,
  tiltShowcase,
  brandShowcase,
  // —— react-bits 移植批 ——
  asciiTextShowcase,
  curvedLoopShowcase,
  fallingTextShowcase,
  fuzzyTextShowcase,
  scrambledTextShowcase,
  revealShowcase,
  scrollFloatShowcase,
  scrollVelocityShowcase,
  shuffleShowcase,
  textCursorShowcase,
  textPressureShowcase,
  variableProximityShowcase,
  antigravityShowcase,
  blobCursorShowcase,
  clickSparkShowcase,
  crosshairShowcase,
  electricBorderShowcase,
  ghostCursorShowcase,
  gradualBlurShowcase,
  imageTrailShowcase,
  laserFlowShowcase,
  magicRingsShowcase,
  magnetShowcase,
  magnetLinesShowcase,
  metaBallsShowcase,
  metallicPaintShowcase,
  orbitImagesShowcase,
  pixelTrailShowcase,
  pixelTransitionShowcase,
  ribbonsShowcase,
  shapeBlurShowcase,
  splashCursorShowcase,
  starBorderShowcase,
  stickerPeelShowcase,
  targetCursorShowcase,
  cubesShowcase,
  logoLoopShowcase,
  bubbleMenuShowcase,
  cardNavShowcase,
  flowingMenuShowcase,
  gooeyNavShowcase,
  pillNavShowcase,
  staggeredMenuShowcase,
  bounceCardsShowcase,
  cardSwapShowcase,
  chromaGridShowcase,
  circularGalleryShowcase,
  domeGalleryShowcase,
  flyingPostersShowcase,
  infiniteMenuShowcase,
  magicBentoShowcase,
  scrollStackShowcase,
  profileCardShowcase,
  tiltedCardShowcase,
  pixelCardShowcase,
  decayCardShowcase,
  reflectiveCardShowcase,
  folderShowcase,
  borderGlowShowcase,
  glassIconsShowcase,
  glassSurfaceShowcase,
  lanyardShowcase,
  modelViewerShowcase,
  fluidGlassShowcase,
  elasticSliderShowcase,
  balatroShowcase,
  ballpitShowcase,
  beamsShowcase,
  colorBendsShowcase,
  darkVeilShowcase,
  ditherShowcase,
  dotFieldShowcase,
  evilEyeShowcase,
  faultyTerminalShowcase,
  ferrofluidShowcase,
  floatingLinesShowcase,
  galaxyShowcase,
  gradientBlindsShowcase,
  grainientShowcase,
  gridDistortionShowcase,
  gridMotionShowcase,
  gridScanShowcase,
  hyperspeedShowcase,
  letterGlitchShowcase,
  lightfallShowcase,
  lightningShowcase,
  lightPillarShowcase,
  lightRaysShowcase,
  lineWavesShowcase,
  liquidEtherShowcase,
  pixelBlastShowcase,
  pixelSnowShowcase,
  plasmaShowcase,
  plasmaWaveShowcase,
  prismShowcase,
  prismaticBurstShowcase,
  radarShowcase,
  rippleGridShowcase,
  shapeGridShowcase,
  sideRaysShowcase,
  softAuroraShowcase,
  calendarShowcase,
  datePickerShowcase,
  dateTimePickerShowcase,
  timeFieldShowcase,
} from "@hulian-docs/showcase";

// 唯一 import @hulianui/ui 渲染 spec 的地方；只被 ComponentDoc client 岛 import。
export const specBySlug: Record<string, ShowcaseSpec> = {
  "date-range-picker": dateRangePickerShowcase,
  "time-picker": timePickerShowcase,
  "icon-picker": iconPickerShowcase,
  "route-tabs": routeTabsShowcase,
  button: buttonShowcase,
  switch: switchShowcase,
  dialog: dialogShowcase,
  annotation: annotationShowcase,
  badge: badgeShowcase,
  dot: dotShowcase,
  "status-dot": statusDotShowcase,
  "beian-footer": beianFooterShowcase,
  "book-3d": book3dShowcase,
  callout: calloutShowcase,
  card: cardShowcase,
  skeleton: skeletonShowcase,
  avatar: avatarShowcase,
  input: inputShowcase,
  textarea: textareaShowcase,
  field: fieldShowcase,
  "secret-field": secretFieldShowcase,
  "password-generator": passwordGeneratorShowcase,
  "event-stream": eventStreamShowcase,
  "intercept-card": interceptCardShowcase,
  "scope-matrix": scopeMatrixShowcase,
  checkbox: checkboxShowcase,
  radio: radioShowcase,
  alert: alertShowcase,
  slider: sliderShowcase,
  tabs: tabsShowcase,
  tag: tagShowcase,
  steps: stepsShowcase,
  tooltip: tooltipShowcase,
  popover: popoverShowcase,
  accordion: accordionShowcase,
  collapsible: collapsibleShowcase,
  segmented: segmentedShowcase,
  breadcrumb: breadcrumbShowcase,
  anchor: anchorShowcase,
  descriptions: descriptionsShowcase,
  "page-header": pageHeaderShowcase,
  pagination: paginationShowcase,
  table: tableShowcase,
  "pricing-table": pricingTableShowcase,
  "json-viewer": jsonViewerShowcase,
  "pro-table": proTableShowcase,
  "editable-table": editableTableShowcase,
  carousel: carouselShowcase,
  video: videoShowcase,
  "voice-record": voiceRecordShowcase,
  resizable: resizableShowcase,
  affix: affixShowcase,
  timeline: timelineShowcase,
  "number-ticker": numberTickerShowcase,
  marquee: marqueeShowcase,
  drawer: drawerShowcase,
  menu: menuShowcase,
  toast: toastShowcase,
  modal: modalShowcase,
  notification: notificationShowcase,
  "service-message": serviceMessageShowcase,
  spin: spinShowcase,
  stat: statShowcase,
  chart: chartShowcase,
  select: selectShowcase,
  combobox: comboboxShowcase,
  "remote-select": remoteSelectShowcase,
  progress: progressShowcase,
  rating: ratingShowcase,
  stepper: stepperShowcase,
  "dot-pattern": dotPatternShowcase,
  "grid-pattern": gridPatternShowcase,
  "retro-grid": retroGridShowcase,
  ripple: rippleShowcase,
  "striped-pattern": stripedPatternShowcase,
  spotlight: spotlightShowcase,
  separator: separatorShowcase,
  "number-field": numberFieldShowcase,
  "alert-dialog": alertDialogShowcase,
  toggle: toggleShowcase,
  toolbar: toolbarShowcase,
  meter: meterShowcase,
  form: formShowcase,
  "form-dialog": formDialogShowcase,
  "pro-form": proFormShowcase,
  "login-form": loginFormShowcase,
  "auth-panel": authPanelShowcase,
  "click-captcha": clickCaptchaShowcase,
  "steps-form": stepsFormShowcase,
  "scroll-area": scrollAreaShowcase,
  "checkbox-group": checkboxGroupShowcase,
  "aurora-text": auroraTextShowcase,
  "animated-shiny-text": animatedShinyTextShowcase,
  "animated-gradient-text": animatedGradientTextShowcase,
  "word-rotate": wordRotateShowcase,
  "typing-animation": typingAnimationShowcase,
  "sparkles-text": sparklesTextShowcase,
  "split-text": splitTextShowcase,
  "blur-text": blurTextShowcase,
  "decrypted-text": decryptedTextShowcase,
  "glitch-text": glitchTextShowcase,
  "circular-text": circularTextShowcase,
  "scroll-reveal": scrollRevealShowcase,
  "true-focus": trueFocusShowcase,
  "shimmer-button": shimmerButtonShowcase,
  "rainbow-button": rainbowButtonShowcase,
  "pulsating-button": pulsatingButtonShowcase,
  "ripple-button": rippleButtonShowcase,
  "border-beam": borderBeamShowcase,
  "shine-border": shineBorderShowcase,
  meteors: meteorsShowcase,
  "magic-card": magicCardShowcase,
  "glare-hover": glareHoverShowcase,
  aurora: auroraShowcase,
  particles: particlesShowcase,
  "flickering-grid": flickeringGridShowcase,
  "wavy-background": wavyBackgroundShowcase,
  "card-spotlight": cardSpotlightShowcase,
  silk: silkShowcase,
  iridescence: iridescenceShowcase,
  threads: threadsShowcase,
  orb: orbShowcase,
  "liquid-chrome": liquidChromeShowcase,
  safari: safariShowcase,
  chrome: chromeShowcase,
  iphone: iphoneShowcase,
  android: androidShowcase,
  tablet: tabletShowcase,
  watch: watchShowcase,
  spinner: spinnerShowcase,
  chip: chipShowcase,
  coupon: couponShowcase,
  link: linkShowcase,
  kbd: kbdShowcase,
  code: codeShowcase,
  "code-block": codeBlockShowcase,
  snippet: snippetShowcase,
  spacer: spacerShowcase,
  user: userShowcase,
  comment: commentShowcase,
  image: imageShowcase,
  navbar: navbarShowcase,
  "input-otp": inputOtpShowcase,
  listbox: listboxShowcase,
  mentions: mentionsShowcase,
  command: commandShowcase,
  calendar: calendarShowcase,
  "date-picker": datePickerShowcase,
  "date-time-picker": dateTimePickerShowcase,
  "time-field": timeFieldShowcase,
  colorpicker: colorPickerShowcase,
  "color-field": colorFieldShowcase,
  "color-swatch-picker": colorSwatchPickerShowcase,
  "avatar-circles": avatarCirclesShowcase,
  "orbiting-circles": orbitingCirclesShowcase,
  "animated-list": animatedListShowcase,
  "progressive-blur": progressiveBlurShowcase,
  dock: dockShowcase,
  lens: lensShowcase,
  terminal: terminalShowcase,
  "bento-grid": bentoGridShowcase,
  "animated-theme-toggler": animatedThemeTogglerShowcase,
  "animated-beam": animatedBeamShowcase,
  "hero-video-dialog": heroVideoDialogShowcase,
  tour: tourShowcase,
  "world-map": worldMapShowcase,
  stack: stackShowcase,
  container: containerShowcase,
  grid: gridShowcase,
  "aspect-ratio": aspectRatioShowcase,
  "fit-screen": fitScreenShowcase,
  empty: emptyShowcase,
  list: listShowcase,
  result: resultShowcase,
  upload: uploadShowcase,
  "image-cropper": imageCropperShowcase,
  transfer: transferShowcase,
  "context-menu": contextMenuShowcase,
  "hover-card": hoverCardShowcase,
  "search-form": searchFormShowcase,
  heading: headingShowcase,
  text: textShowcase,
  prose: proseShowcase,
  watermark: watermarkShowcase,
  layout: layoutShowcase,
  "admin-layout": adminLayoutShowcase,
  popconfirm: popconfirmShowcase,
  menubar: menubarShowcase,
  "navigation-menu": navigationMenuShowcase,
  "nav-menu": navMenuShowcase,
  "tree": treeShowcase,
  "tree-select": treeSelectShowcase,
  "cascader": cascaderShowcase,
  "region-cascader": regionCascaderShowcase,
  "country-select": countrySelectShowcase,
  "markdown-editor": markdownEditorShowcase,
  markdown: markdownShowcase,
  math: mathShowcase,
  "question-card": questionCardShowcase,
  divider: dividerShowcase,
  "back-top": backTopShowcase,
  statistic: statisticShowcase,
  sortable: sortableShowcase,
  kanban: kanbanShowcase,
  flow: flowShowcase,
  sankey: sankeyShowcase,
  sparkline: sparklineShowcase,
  funnel: funnelShowcase,
  "queue-lane": queueLaneShowcase,
  "typing-dots": typingDotsShowcase,
  "chat-message": chatMessageShowcase,
  conversation: conversationShowcase,
  "prompt-input": promptInputShowcase,
  "thinking-block": thinkingBlockShowcase,
  "tool-call": toolCallShowcase,
  "agent-plan": agentPlanShowcase,
  dossier: dossierShowcase,
  artifact: artifactShowcase,
  "confirm-card": confirmCardShowcase,
  "thread-list": threadListShowcase,
  "task-runner": taskRunnerShowcase,
  "prompt-suggestions": promptSuggestionsShowcase,
  "message-actions": messageActionsShowcase,
  citation: citationShowcase,
  "streaming-text": streamingTextShowcase,
  "safe-area": safeAreaShowcase,
  fab: fabShowcase,
  "tab-bar": tabBarShowcase,
  "action-sheet": actionSheetShowcase,
  "swipe-action": swipeActionShowcase,
  "pull-to-refresh": pullToRefreshShowcase,
  picker: pickerShowcase,
  "virtual-list": virtualListShowcase,
  "infinite-scroll": infiniteScrollShowcase,
  qrcode: qrcodeShowcase,
  viewport: viewportShowcase,
  masonry: masonryShowcase,
  "document-sheet": documentSheetShowcase,
  gantt: ganttShowcase,
  scheduler: schedulerShowcase,
  "image-viewer": imageViewerShowcase,
  danmaku: danmakuShowcase,
  "live-chat": liveChatShowcase,
  "gift-feed": giftFeedShowcase,
  "floating-reactions": floatingReactionsShowcase,
  "live-player": livePlayerShowcase,
  "live-product-card": liveProductCardShowcase,
  "log-viewer": logViewerShowcase,
  "code-diff": codeDiffShowcase,
  "diff-stat": diffStatShowcase,
  "score-ring": scoreRingShowcase,
  heatmap: heatmapShowcase,
  "code-review-thread": codeReviewThreadShowcase,
  "file-tree": fileTreeShowcase,
  "button-group": buttonGroupShowcase,
  "social-button": socialButtonShowcase,
  banner: bannerShowcase,
  "relative-time": relativeTimeShowcase,
  choicebox: choiceboxShowcase,
  "credit-card": creditCardShowcase,
  "emoji-picker": emojiPickerShowcase,
  glimpse: glimpseShowcase,
  "git-commit": gitCommitShowcase,
  "deploy-status": deployStatusShowcase,
  "shield-badge": shieldBadgeShowcase,
  "award-badge": awardBadgeShowcase,
  "contribution-graph": contributionGraphShowcase,
  legend: legendShowcase,
  "app-launcher": appLauncherShowcase,
  "region-select": regionSelectShowcase,
  tilt: tiltShowcase,
  brand: brandShowcase,
  // —— react-bits 移植批 ——
  "ascii-text": asciiTextShowcase,
  "curved-loop": curvedLoopShowcase,
  "falling-text": fallingTextShowcase,
  "fuzzy-text": fuzzyTextShowcase,
  "scrambled-text": scrambledTextShowcase,
  "reveal": revealShowcase,
  "scroll-float": scrollFloatShowcase,
  "scroll-velocity": scrollVelocityShowcase,
  "shuffle": shuffleShowcase,
  "text-cursor": textCursorShowcase,
  "text-pressure": textPressureShowcase,
  "variable-proximity": variableProximityShowcase,
  "antigravity": antigravityShowcase,
  "blob-cursor": blobCursorShowcase,
  "click-spark": clickSparkShowcase,
  "crosshair": crosshairShowcase,
  "electric-border": electricBorderShowcase,
  "ghost-cursor": ghostCursorShowcase,
  "gradual-blur": gradualBlurShowcase,
  "image-trail": imageTrailShowcase,
  "laser-flow": laserFlowShowcase,
  "magic-rings": magicRingsShowcase,
  "magnet": magnetShowcase,
  "magnet-lines": magnetLinesShowcase,
  "meta-balls": metaBallsShowcase,
  "metallic-paint": metallicPaintShowcase,
  "orbit-images": orbitImagesShowcase,
  "pixel-trail": pixelTrailShowcase,
  "pixel-transition": pixelTransitionShowcase,
  "ribbons": ribbonsShowcase,
  "shape-blur": shapeBlurShowcase,
  "splash-cursor": splashCursorShowcase,
  "star-border": starBorderShowcase,
  "sticker-peel": stickerPeelShowcase,
  "target-cursor": targetCursorShowcase,
  "cubes": cubesShowcase,
  "logo-loop": logoLoopShowcase,
  "bubble-menu": bubbleMenuShowcase,
  "card-nav": cardNavShowcase,
  "flowing-menu": flowingMenuShowcase,
  "gooey-nav": gooeyNavShowcase,
  "pill-nav": pillNavShowcase,
  "staggered-menu": staggeredMenuShowcase,
  "bounce-cards": bounceCardsShowcase,
  "card-swap": cardSwapShowcase,
  "chroma-grid": chromaGridShowcase,
  "circular-gallery": circularGalleryShowcase,
  "dome-gallery": domeGalleryShowcase,
  "flying-posters": flyingPostersShowcase,
  "infinite-menu": infiniteMenuShowcase,
  "magic-bento": magicBentoShowcase,
  "scroll-stack": scrollStackShowcase,
  "profile-card": profileCardShowcase,
  "tilted-card": tiltedCardShowcase,
  "pixel-card": pixelCardShowcase,
  "decay-card": decayCardShowcase,
  "reflective-card": reflectiveCardShowcase,
  "folder": folderShowcase,
  "border-glow": borderGlowShowcase,
  "glass-icons": glassIconsShowcase,
  "glass-surface": glassSurfaceShowcase,
  "lanyard": lanyardShowcase,
  "model-viewer": modelViewerShowcase,
  "fluid-glass": fluidGlassShowcase,
  "elastic-slider": elasticSliderShowcase,
  "balatro": balatroShowcase,
  "ballpit": ballpitShowcase,
  "beams": beamsShowcase,
  "color-bends": colorBendsShowcase,
  "dark-veil": darkVeilShowcase,
  "dither": ditherShowcase,
  "dot-field": dotFieldShowcase,
  "evil-eye": evilEyeShowcase,
  "faulty-terminal": faultyTerminalShowcase,
  "ferrofluid": ferrofluidShowcase,
  "floating-lines": floatingLinesShowcase,
  "galaxy": galaxyShowcase,
  "gradient-blinds": gradientBlindsShowcase,
  "grainient": grainientShowcase,
  "grid-distortion": gridDistortionShowcase,
  "grid-motion": gridMotionShowcase,
  "grid-scan": gridScanShowcase,
  "hyperspeed": hyperspeedShowcase,
  "letter-glitch": letterGlitchShowcase,
  "lightfall": lightfallShowcase,
  "lightning": lightningShowcase,
  "light-pillar": lightPillarShowcase,
  "light-rays": lightRaysShowcase,
  "line-waves": lineWavesShowcase,
  "liquid-ether": liquidEtherShowcase,
  "pixel-blast": pixelBlastShowcase,
  "pixel-snow": pixelSnowShowcase,
  "plasma": plasmaShowcase,
  "plasma-wave": plasmaWaveShowcase,
  "prism": prismShowcase,
  "prismatic-burst": prismaticBurstShowcase,
  "radar": radarShowcase,
  "ripple-grid": rippleGridShowcase,
  "shape-grid": shapeGridShowcase,
  "side-rays": sideRaysShowcase,
  "soft-aurora": softAuroraShowcase,
};
