import { copy } from "./alerts.content";
// 告警规则 + 告警事件流（mock）。

import type { AlertEvent, AlertRule } from "./types";

export const ALERT_RULES: AlertRule[] = [
  {
    id: "alert-p95",
    name: copy("p95LatencyExceedsThreshold"),
    metric: "p95",
    op: ">",
    threshold: 2500,
    unit: "ms",
    severity: "warning",
    enabled: true,
    channel: copy("wechatWorkDutyGroup"),
  },
  {
    id: "alert-queue",
    name: copy("queueDepthBacklog"),
    metric: "queue",
    op: ">",
    threshold: 100,
    unit: copy("article"),
    severity: "warning",
    enabled: true,
    channel: copy("wechatWorkDutyGroup2"),
  },
  {
    id: "alert-sla-violate",
    name: copy("p0TaskSlaDefault"),
    metric: "sla_violation",
    op: ">=",
    threshold: 1,
    unit: copy("times"),
    severity: "critical",
    enabled: true,
    channel: copy("smsPhoneDutySupervisor"),
  },
  {
    id: "alert-cost",
    name: copy("hourlyCostExceedsBudget"),
    metric: "cost",
    op: ">",
    threshold: 140,
    unit: "¥/h",
    severity: "warning",
    enabled: true,
    channel: copy("emailCostCenter"),
  },
  {
    id: "alert-executor-degrade",
    name: copy("actuatorHealthDegradation"),
    metric: "executor_health",
    op: "<=",
    threshold: 1,
    unit: copy("level"),
    severity: "critical",
    enabled: true,
    channel: copy("wechatWorkSms"),
  },
  {
    id: "alert-budget-fail",
    name: copy("missionOverBudgetFailure"),
    metric: "budget_fail",
    op: ">=",
    threshold: 1,
    unit: copy("times2"),
    severity: "info",
    enabled: false,
    channel: copy("emailSubmitter"),
  },
];

export const ALERT_EVENTS: AlertEvent[] = [
  {
    id: "ev-1",
    ruleId: "alert-p95",
    title: copy("p95HasLatencyOfMsExceedingThe"),
    severity: "warning",
    value: 2980,
    unit: "ms",
    at: copy("todayAt"),
    status: "firing",
    detail: copy("duringTheMorningPeakOpusWasLoaded"),
  },
  {
    id: "ev-2",
    ruleId: "alert-queue",
    title: copy("queueDepthReachesItemsExceedingTheThreshold"),
    severity: "warning",
    value: 108,
    unit: copy("article2"),
    at: copy("todayAt2"),
    status: "acked",
    detail: copy("theBacklogOfP3BatchTasksHas"),
  },
  {
    id: "ev-3",
    ruleId: "alert-executor-degrade",
    title: copy("deepseekV4HealthHasBeenDowngradedTo"),
    severity: "critical",
    value: 1,
    unit: copy("level2"),
    at: copy("todayAt3"),
    status: "firing",
    detail: copy("deepseekV4ExtractionTasksTimedOutAnd"),
  },
  {
    id: "ev-4",
    ruleId: "alert-sla-violate",
    title: copy("communityUgcReviewTaskSlaNearExpiration"),
    severity: "critical",
    value: 26500,
    unit: "ms",
    at: copy("todayAt4"),
    status: "firing",
    detail: copy("p0RealTimeReviewWaitIsSeconds"),
  },
  {
    id: "ev-5",
    ruleId: "alert-budget-fail",
    title: copy("failureToArrangeCompetitorResearchTasksBeyond"),
    severity: "info",
    value: 7.8,
    unit: "¥",
    at: copy("todayAt5"),
    status: "resolved",
    detail: copy("externalSearchSourceTrafficRestrictionsCausedRetrys"),
  },
  {
    id: "ev-6",
    ruleId: "alert-cost",
    title: copy("timeSlotCostHExceedingThreshold"),
    severity: "warning",
    value: 146,
    unit: "¥/h",
    at: copy("todayAt6"),
    status: "acked",
    detail: copy("duringPeakPeriodsTheProportionOfOpus"),
  },
];
