// 告警规则 + 告警事件流（mock）。

import type { AlertEvent, AlertRule } from "./types";

export const ALERT_RULES: AlertRule[] = [
  {
    id: "alert-p95",
    name: "P95 延迟超阈",
    metric: "p95",
    op: ">",
    threshold: 2500,
    unit: "ms",
    severity: "warning",
    enabled: true,
    channel: "企业微信 · 值班群",
  },
  {
    id: "alert-queue",
    name: "队列深度积压",
    metric: "queue",
    op: ">",
    threshold: 100,
    unit: "条",
    severity: "warning",
    enabled: true,
    channel: "企业微信 · 值班群",
  },
  {
    id: "alert-sla-violate",
    name: "P0 任务 SLA 违约",
    metric: "sla_violation",
    op: ">=",
    threshold: 1,
    unit: "次",
    severity: "critical",
    enabled: true,
    channel: "短信 + 电话 · 值班负责人",
  },
  {
    id: "alert-cost",
    name: "单小时成本超预算",
    metric: "cost",
    op: ">",
    threshold: 140,
    unit: "¥/h",
    severity: "warning",
    enabled: true,
    channel: "邮件 · 成本中心",
  },
  {
    id: "alert-executor-degrade",
    name: "执行器健康降级",
    metric: "executor_health",
    op: "<=",
    threshold: 1,
    unit: "级",
    severity: "critical",
    enabled: true,
    channel: "企业微信 + 短信",
  },
  {
    id: "alert-budget-fail",
    name: "任务超预算失败",
    metric: "budget_fail",
    op: ">=",
    threshold: 1,
    unit: "次",
    severity: "info",
    enabled: false,
    channel: "邮件 · 提交人",
  },
];

export const ALERT_EVENTS: AlertEvent[] = [
  {
    id: "ev-1",
    ruleId: "alert-p95",
    title: "P95 延迟达 2980ms，超阈值 2500ms",
    severity: "warning",
    value: 2980,
    unit: "ms",
    at: "今天 10:00",
    status: "firing",
    detail: "早高峰 Opus 4.7 负载 71%，拖尾延迟上升，建议临时上调 Sonnet 分流权重。",
  },
  {
    id: "ev-2",
    ruleId: "alert-queue",
    title: "队列深度达 108 条，超阈值 100 条",
    severity: "warning",
    value: 108,
    unit: "条",
    at: "今天 10:00",
    status: "acked",
    detail: "P3 批量任务积压，已自动调度至 DeepSeek V4 低成本池消化。",
  },
  {
    id: "ev-3",
    ruleId: "alert-executor-degrade",
    title: "DeepSeek V4 健康度降级为 degraded",
    severity: "critical",
    value: 1,
    unit: "级",
    at: "今天 09:42",
    status: "firing",
    detail: "DeepSeek V4 抽取任务出现超时，已对其新流量启用降级链（Haiku 4.5 / Sonnet 4.6）。",
  },
  {
    id: "ev-4",
    ruleId: "alert-sla-violate",
    title: "社区 UGC 审核任务 SLA 临期（已用 88%）",
    severity: "critical",
    value: 26500,
    unit: "ms",
    at: "今天 09:58",
    status: "firing",
    detail: "P0 实时审核等待 26.5s，SLA 30s，建议抢占审核 Agent 并发或提级至 Opus。",
  },
  {
    id: "ev-5",
    ruleId: "alert-budget-fail",
    title: "竞品调研编排任务超预算失败",
    severity: "info",
    value: 7.8,
    unit: "¥",
    at: "今天 09:21",
    status: "resolved",
    detail: "外部检索源限流导致重试，花费 ¥7.8 触顶预算 ¥8.0 后中止，已通知提交人。",
  },
  {
    id: "ev-6",
    ruleId: "alert-cost",
    title: "10:00 时段成本达 ¥146/h，超阈值 ¥140",
    severity: "warning",
    value: 146,
    unit: "¥/h",
    at: "今天 10:00",
    status: "acked",
    detail: "高峰期 Opus/Flux 占比上升，已开启批量任务成本权重上调策略。",
  },
];
