import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "intelligentReviewOfCrossBorderProcurementContracts": "跨境采购合同智能审阅",
    "contractReview": "合同审阅",
    "legalAffairsZhouLan": "法务 · 周澜",
    "retrieveTheInternalContractClauseDatabase": "检索内部合同条款库",
    "theEnglishClausesAreTranslatedIntoChinese": "翻译英文条款为中文",
    "riskClauseComplianceReview": "风险条款合规审核",
    "summarizeAndReviewTheOpinionReport": "汇总审阅意见报告",
    "missionEntersTheBusHitsTheRule": "任务进入总线，命中规则「P0 安全敏感 → 旗舰」",
    "ifTheContractContainsCrossBorderClauses": "合同含跨境条款，需先建立条款上下文再翻译，避免术语漂移。",
    "callRetrievalEnhancementAgentRecallSimilarClauses": "调用 检索增强 Agent · 向量召回 24 条相似条款，重排取 Top 8。",
    "threeKeyClausesForceMajeureJurisdictionOf": "已抽取「不可抗力」「争议管辖」「付款节点」三类关键条款…",
    "callHaikuBatchTranslateEnglishTerms": "调用 Haiku 4.5 · 批量翻译 8 条英文条款。",
    "liquidatedDamagesIsADirectTranslationOf": "「liquidated damages」直译为「违约金」存歧义，标注为「约定损害赔偿金」。",
    "callContentReviewAgentCompareComplianceBaselines": "调用 内容审核 Agent · 比对合规基线，标记 2 处高风险。",
    "afterTheReviewIsCompletedTheOrchestration": "等待审核完成后由 编排 Agent 汇总最终报告。",
    "abilityNotSatisfiedOrchestrate": "能力不满足: orchestrate",
    "abilityNotSatisfiedTranslateModerateOrchestrate": "能力不满足: translate/moderate/orchestrate",
    "p0MultiAgentOrchestrationWithOrchestratedAnd": "P0 + 多 agent 编排，编排调度 Agent 综合分最高（0.685），由其拉起 RAG/翻译/审核子链。",
    "structuredExtractionOfListedCompanyFinancialReports": "上市公司财报结构化抽取",
    "dataExtraction": "数据抽取",
    "investmentResearchLinAn": "投研 · 林岸",
    "analyzePdfFinancialReportPages": "解析 PDF 财报分页",
    "extractThreeMajorReportFields": "抽取三大报表字段",
    "extractThreeMajorReportFieldsDowngradeAnd": "抽取三大报表字段（降级重试）",
    "verifyAndVerifyTheRelationshipsBetweenThe": "校验勾稽关系",
    "exportingStructuredJson": "导出结构化 JSON",
    "theTaskEntersTheBusHittingThe": "任务进入总线，命中规则「批量低优 → 低成本池」，初选 DeepSeek V4。",
    "callStructuredExtractAgentParseAnPage": "调用 结构化抽取 Agent · 解析 86 页财报，分离报表区块。",
    "callDeepseekV4ExtractBalanceSheetFields": "调用 DeepSeek V4 · 抽取资产负债表字段…",
    "deepseekV4ReturnsATimeoutHealthDegraded": "⚠ DeepSeek V4 返回超时（健康度 degraded），触发降级。",
    "degradationChainHaikuSonnetHaikuHealthyWith": "降级链 [haiku-4-5, sonnet-4-6]，Haiku healthy 且具备 extract，切换。",
    "callHaikuTryAgainToExtractThe": "调用 Haiku 4.5 · 重试抽取三大报表字段，成功。",
    "crossCheckingVerificationAssetsLiabilitiesEquityRevenue": "勾稽校验：资产=负债+权益 ✓，营收-成本=毛利 ✓…",
    "exportingJsonCompletesEndToEndIn": "导出 JSON 完成，端到端 38.4s，花费 ¥0.61，SLA 余量充足。",
    "p1BatchExtractionDeepseekV4HadThe": "P1 批量抽取，DeepSeek V4 极低成本综合分最高（0.735）；运行中超时降级至 Haiku 4.5。",
    "deepseekV4DegradedAndSwitchedToHaiku": "DeepSeek V4 抽取超时（degraded），按降级链切换至 Haiku 4.5",
    "mainMarketingVisualMaterialGeneration": "618 营销主视觉素材生成",
    "materialGeneration": "素材生成",
    "marketSuWan": "市场 · 苏晚",
    "generateSetsOfCopywritingVisualPrompts": "生成 5 组文案 + 视觉提示词",
    "textToTextImageMainVisual": "文生图 · 主视觉 1024×1024",
    "materialComplianceReviewAdvertisingLaw": "素材合规审核（广告法）",
    "theTaskEntersTheBusAndHits": "任务进入总线，命中规则「图像任务 → 视觉模型」。",
    "callSonnetGenerateSetsOfCopyAnd": "调用 Sonnet 4.6 · 生成 5 组文案与配套视觉提示词。",
    "newSummerStoresEnjoyGoodItemsAt": "「盛夏开新场，好物半价享」「囤货季 · 一键凑单更划算」…",
    "callingHulianScrollFluxRenderTheMain": "调用 瑚琏绘卷 Flux · 渲染主视觉，1024×1024，CFG 7。",
    "afterImageRenderingIsCompletedItMust": "等待图像渲染完成后，须过广告法合规审核再发布。",
    "abilityNotSatisfiedImage": "能力不满足: image",
    "withImageCapabilitiesHulianScrollFluxIs": "含 image 能力，瑚琏绘卷 Flux 为唯一具备 image 的执行器，文/审环节由 Sonnet/审核 Agent 协作。",
    "multilingualTranslationOfProductManuals": "产品手册多语翻译",
    "translation": "翻译",
    "localizationGaoHeng": "本地化 · 高珩",
    "p2TranslationHaikuIsOptimalForLow": "P2 翻译，Haiku 4.5 低成本 + 低延迟综合最优。",
    "prCodeSecurityReview": "PR 代码安全审查",
    "codeReview": "代码审查",
    "researchAndDevelopmentChenZhao": "研发 · 陈昭",
    "p1CodingTaskSonnetBalancingCapabilityAmple": "P1 代码任务，Sonnet 4.6 均衡能力 + SLA 余量充足。",
    "customerServiceKnowledgeBaseIntelligentQA": "客服知识库智能问答",
    "ragQA": "RAG 问答",
    "customerServiceShenZhi": "客服 · 沈知",
    "hitTheRetrievalEnhancementRagAgentRag": "命中「检索增强 → RAG Agent」，RAG Agent 承接。",
    "realTimeCommunityUgcReview": "社区 UGC 实时审核",
    "contentReview": "内容审核",
    "riskControlHanChe": "风控 · 韩澈",
    "p0AuditReviewAgentAcceptanceCurrentWaiting": "P0 审核，审核 Agent 承接；当前等待已达 SLA 88%，临期告警。",
    "industryPublicOpinionDailySummary": "行业舆情日报摘要",
    "textSummary": "文本摘要",
    "operationsYeHe": "运营 · 叶禾",
    "p3BatchLowQualityQueueingWaitingFor": "P3 批量低优排队中，待低成本池（DeepSeek/Haiku）释放并发。",
    "naturalLanguageToSql": "自然语言转 SQL",
    "codeGeneration": "代码生成",
    "dataLuoYan": "数据 · 罗砚",
    "p2CodeGenerationDeepseekV4UltraLow": "P2 代码生成，DeepSeek V4 超低成本综合最优。",
    "quickReleaseOfHolidayPosterImages": "节日海报快速出图",
    "imageGeneration": "图像生成",
    "designQiuBai": "设计 · 邱白",
    "theUniqueImageActuatorFluxConcurrentlyOccupies": "唯一 image 执行器 Flux 并发占满，排队等待空槽。",
    "extractionOfVatInvoiceFields": "增值税发票字段抽取",
    "dataExtraction2": "数据抽取",
    "financeTangNing": "财务 · 唐宁",
    "p2ExtractionStructuredExtractionAgentSpecializedCapability": "P2 抽取，结构化抽取 Agent 专项能力 + SLA 充足。",
    "multilingualHandlingOfOverseasWorkOrders": "海外工单多语应答",
    "translation2": "翻译",
    "customerServiceGuTang": "客服 · 顾棠",
    "p1TranslationHaikuLowLatencyWithReal": "P1 翻译，Haiku 4.5 低延迟保实时性。",
    "compilationOfCompetitorResearchFromMultipleSources": "竞品调研多源汇编",
    "multiAgentOrchestration": "多 agent 编排",
    "strategyJiangyu": "战略 · 江屿",
    "p1OrchestrationOrchestratedByAgentAcceptanceDue": "P1 编排，编排 Agent 承接；因外部检索源限流，子链超预算失败。",
    "aMassiveNumberOfCommentsAndEmotional": "海量评论情感分类",
    "textClassification": "文本分类",
    "operationsShaoQing": "运营 · 邵青",
    "p3BatchHitTheBatchLowQuality": "P3 批量，命中「批量低优 → 低成本池」，排队等 DeepSeek 释放。",
  },
  en: {
    "intelligentReviewOfCrossBorderProcurementContracts": "Intelligent review of cross-border procurement contracts",
    "contractReview": "Contract review",
    "legalAffairsZhouLan": "Legal Affairs · Zhou Lan",
    "retrieveTheInternalContractClauseDatabase": "Retrieve the internal contract clause database",
    "theEnglishClausesAreTranslatedIntoChinese": "The English clauses are translated into Chinese",
    "riskClauseComplianceReview": "Risk clause compliance review",
    "summarizeAndReviewTheOpinionReport": "Summarize and review the opinion report",
    "missionEntersTheBusHitsTheRule": "Task enters the bus, hits the rule \"P0 Security-Sensitive → Flagship\"",
    "ifTheContractContainsCrossBorderClauses": "If the contract contains cross-border clauses, the context of the terms must be established before translation to avoid terminology drift.",
    "callRetrievalEnhancementAgentRecallSimilarClauses": "Call Retrieval Enhancement Agent · Recall 24 similar clauses and rearrange the Top 8.",
    "threeKeyClausesForceMajeureJurisdictionOf": "Three key clauses: \"Force Majeure,\" \"Jurisdiction of Disputes,\" and \"Payment Nodes\" have been extracted...",
    "callHaikuBatchTranslateEnglishTerms": "Call Haiku 4.5 · Batch translate 8 English terms.",
    "liquidatedDamagesIsADirectTranslationOf": "\"liquidated damages\" is a direct translation of \"liquidated damages\" (breach of contract), which is ambiguous and is labeled as \"agreed damages compensation.\"",
    "callContentReviewAgentCompareComplianceBaselines": "Call Content Review Agent · Compare compliance baselines and mark 2 high-risk locations.",
    "afterTheReviewIsCompletedTheOrchestration": "After the review is completed, the orchestration agent compiles the final report.",
    "abilityNotSatisfiedOrchestrate": "Ability not satisfied: orchestrate",
    "abilityNotSatisfiedTranslateModerateOrchestrate": "Ability not satisfied: translate/moderate/orchestrate",
    "p0MultiAgentOrchestrationWithOrchestratedAnd": "P0 + multi-agent orchestration, with orchestrated and scheduling agents achieving the highest overall score (0.685), which leads to the RAG/translation/audit subchain.",
    "structuredExtractionOfListedCompanyFinancialReports": "Structured extraction of listed company financial reports",
    "dataExtraction": "Data extraction",
    "investmentResearchLinAn": "Investment Research · Lin An",
    "analyzePdfFinancialReportPages": "Analyze PDF financial report pages",
    "extractThreeMajorReportFields": "Extract three major report fields",
    "extractThreeMajorReportFieldsDowngradeAnd": "Extract three major report fields (downgrade and retry)",
    "verifyAndVerifyTheRelationshipsBetweenThe": "Verify and verify the relationships between the accounts",
    "exportingStructuredJson": "Exporting structured JSON",
    "theTaskEntersTheBusHittingThe": "The task enters the bus, hitting the rule \"batch low-quality → low-cost pool,\" preliminarily selecting DeepSeek V4.",
    "callStructuredExtractAgentParseAnPage": "Call Structured Extract Agent · Parse an 86-page financial report and separate report blocks.",
    "callDeepseekV4ExtractBalanceSheetFields": "Call DeepSeek V4 · Extract balance sheet fields...",
    "deepseekV4ReturnsATimeoutHealthDegraded": "⚠ DeepSeek V4 returns a timeout (health degraded), triggering a downgrade.",
    "degradationChainHaikuSonnetHaikuHealthyWith": "Degradation chain [haiku-4-5, sonnet-4-6], Haiku healthy with extract and switching.",
    "callHaikuTryAgainToExtractThe": "Call Haiku 4.5 · Try again to extract the three major report fields, successful.",
    "crossCheckingVerificationAssetsLiabilitiesEquityRevenue": "Cross-checking verification: Assets = Liabilities + Equity ✓, Revenue - Cost = Gross Profit ✓...",
    "exportingJsonCompletesEndToEndIn": "Exporting JSON completes end-to-end in 38.4 seconds, costing ¥0.61, with ample SLA margin.",
    "p1BatchExtractionDeepseekV4HadThe": "P1 batch extraction, DeepSeek V4 had the highest overall score at extremely low cost (0.735); during operation, it was downgraded to Haiku 4.5 due to overtime.",
    "deepseekV4DegradedAndSwitchedToHaiku": "DeepSeek V4 degraded and switched to Haiku 4.5 by downgrading chain",
    "mainMarketingVisualMaterialGeneration": "618 Main Marketing Visual Material Generation",
    "materialGeneration": "Material generation",
    "marketSuWan": "Market · Su Wan",
    "generateSetsOfCopywritingVisualPrompts": "Generate 5 sets of copywriting + visual prompts",
    "textToTextImageMainVisual": "Text-to-Text Image · Main Visual 1024×1024",
    "materialComplianceReviewAdvertisingLaw": "Material compliance review (Advertising Law)",
    "theTaskEntersTheBusAndHits": "The task enters the bus and hits the rule \"Image Task → Visual Model.\"",
    "callSonnetGenerateSetsOfCopyAnd": "Call Sonnet 4.6 · Generate 5 sets of copy and accompanying visual prompts.",
    "newSummerStoresEnjoyGoodItemsAt": "\"New Summer Stores, Enjoy Good Items at Half Price\" \"Stocking Season · One-Click Bundle for a Better Deal\"...",
    "callingHulianScrollFluxRenderTheMain": "Calling Hulian Scroll Flux · Render the main visual, 1024×1024, CFG 7.",
    "afterImageRenderingIsCompletedItMust": "After image rendering is completed, it must pass the Advertising Law compliance review before publishing.",
    "abilityNotSatisfiedImage": "Ability not satisfied: image",
    "withImageCapabilitiesHulianScrollFluxIs": "With image capabilities, Hulian Scroll Flux is the only executor with images, and the document review process is handled by Sonnet/review agents.",
    "multilingualTranslationOfProductManuals": "Multilingual translation of product manuals",
    "translation": "Translation",
    "localizationGaoHeng": "Localization · Gao Heng",
    "p2TranslationHaikuIsOptimalForLow": "P2 translation, Haiku 4.5 is optimal for low cost + low latency.",
    "prCodeSecurityReview": "PR Code Security Review",
    "codeReview": "Code review",
    "researchAndDevelopmentChenZhao": "Research and Development · Chen Zhao",
    "p1CodingTaskSonnetBalancingCapabilityAmple": "P1 coding task, Sonnet 4.6 balancing capability + ample SLA margin.",
    "customerServiceKnowledgeBaseIntelligentQA": "Customer service knowledge base intelligent Q&A",
    "ragQA": "RAG Q&A",
    "customerServiceShenZhi": "Customer Service · Shen Zhi",
    "hitTheRetrievalEnhancementRagAgentRag": "Hit the \"Retrieval Enhancement → RAG Agent,\" RAG Agent takes over.",
    "realTimeCommunityUgcReview": "Real-time community UGC review",
    "contentReview": "Content review",
    "riskControlHanChe": "Risk Control · Han Che",
    "p0AuditReviewAgentAcceptanceCurrentWaiting": "P0 moderation task routed to the Review Agent. Queue time has consumed 88% of the SLA, so an expiry warning is active.",
    "industryPublicOpinionDailySummary": "Industry Public Opinion Daily Summary",
    "textSummary": "Text summary",
    "operationsYeHe": "Operations · Ye He",
    "p3BatchLowQualityQueueingWaitingFor": "P3 batch low-quality queueing, waiting for low-cost pools (DeepSeek/Haiku) to release concurrency.",
    "naturalLanguageToSql": "Natural language to SQL",
    "codeGeneration": "Code generation",
    "dataLuoYan": "Data · Luo Yan",
    "p2CodeGenerationDeepseekV4UltraLow": "P2 code generation, DeepSeek V4 ultra-low cost for optimal overall optimization.",
    "quickReleaseOfHolidayPosterImages": "Quick release of holiday poster images",
    "imageGeneration": "Image generation",
    "designQiuBai": "Design · Qiu Bai",
    "theUniqueImageActuatorFluxConcurrentlyOccupies": "Flux is the only image-capable executor and is at full concurrency, so the task is waiting for a slot.",
    "extractionOfVatInvoiceFields": "Extraction of VAT invoice fields",
    "dataExtraction2": "Data extraction",
    "financeTangNing": "Finance · Tang Ning",
    "p2ExtractionStructuredExtractionAgentSpecializedCapability": "P2 extraction, structured extraction agent specialized capability + sufficient SLA.",
    "multilingualHandlingOfOverseasWorkOrders": "Multilingual handling of overseas work orders",
    "translation2": "Translation",
    "customerServiceGuTang": "Customer Service · Gu Tang",
    "p1TranslationHaikuLowLatencyWithReal": "P1 translation, Haiku 4.5 low-latency with real-time performance.",
    "compilationOfCompetitorResearchFromMultipleSources": "Compilation of competitor research from multiple sources",
    "multiAgentOrchestration": "Multi-agent orchestration",
    "strategyJiangyu": "Strategy · Jiangyu",
    "p1OrchestrationOrchestratedByAgentAcceptanceDue": "P1 orchestration was assigned to the Orchestration Agent. External source rate limits caused retries and pushed the subtask chain over budget.",
    "aMassiveNumberOfCommentsAndEmotional": "A massive number of comments and emotional categories",
    "textClassification": "Text classification",
    "operationsShaoQing": "Operations · Shao Qing",
    "p3BatchHitTheBatchLowQuality": "P3 batch hit the \"batch low-quality → low-cost pool,\" queued for DeepSeek release.",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanhelm-data-tasks",
  content: t(content),
};

export default dictionary;
