import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "intelligentReviewOfCrossBorderProcurementContracts": "跨境采购合同智能审阅",
    "contractReview": "合同审阅",
    "legalAffairsZhouLan": "法务 · 周澜",
    "retrieveTheInternalContractClauseDatabase": "检索内部合同条款库",
    "theEnglishClausesAreTranslatedIntoChinese": "翻译英文条款为中文",
    "riskClauseComplianceReview": "风险条款合规审核",
    "summarizeAndReviewTheOpinionReport": "汇总审阅意见报告",
    "missionEntersTheBusHitsTheRule": "任务进入总线，命中规则「P0 安全敏感 → 旗舰」",
    "ifTheContractContainsCrossBorderClauses": "合同含跨境条款，需先建立条款上下文再翻译，避免术语漂移。",
    "callRetrievalEnhancementAgentRecallSimilarClauses": "调用 检索增强 Agent · 向量召回 24 条相似条款，重排取 Top 8。",
    "threeKeyClausesForceMajeureJurisdictionOf": "已抽取「不可抗力」「争议管辖」「付款节点」三类关键条款…",
    "callHaikuBatchTranslateEnglishTerms": "调用 Haiku 4.5 · 批量翻译 8 条英文条款。",
    "liquidatedDamagesIsADirectTranslationOf": "「liquidated damages」直译为「违约金」存歧义，标注为「约定损害赔偿金」。",
    "callContentReviewAgentCompareComplianceBaselines": "调用 内容审核 Agent · 比对合规基线，标记 2 处高风险。",
    "afterTheReviewIsCompletedTheOrchestration": "等待审核完成后由 编排 Agent 汇总最终报告。",
    "abilityNotSatisfiedOrchestrate": "能力不满足: orchestrate",
    "abilityNotSatisfiedTranslateModerateOrchestrate": "能力不满足: translate/moderate/orchestrate",
    "p0MultiAgentOrchestrationWithOrchestratedAnd": "P0 + 多 agent 编排，编排调度 Agent 综合分最高（0.685），由其拉起 RAG/翻译/审核子链。",
    "structuredExtractionOfListedCompanyFinancialReports": "上市公司财报结构化抽取",
    "dataExtraction": "数据抽取",
    "investmentResearchLinAn": "投研 · 林岸",
    "analyzePdfFinancialReportPages": "解析 PDF 财报分页",
    "extractThreeMajorReportFields": "抽取三大报表字段",
    "extractThreeMajorReportFieldsDowngradeAnd": "抽取三大报表字段（降级重试）",
    "verifyAndVerifyTheRelationshipsBetweenThe": "校验勾稽关系",
    "exportingStructuredJson": "导出结构化 JSON",
    "theTaskEntersTheBusHittingThe": "任务进入总线，命中规则「批量低优 → 低成本池」，初选 DeepSeek V4。",
    "callStructuredExtractAgentParseAnPage": "调用 结构化抽取 Agent · 解析 86 页财报，分离报表区块。",
    "callDeepseekV4ExtractBalanceSheetFields": "调用 DeepSeek V4 · 抽取资产负债表字段…",
    "deepseekV4ReturnsATimeoutHealthDegraded": "⚠ DeepSeek V4 返回超时（健康度 degraded），触发降级。",
    "degradationChainHaikuSonnetHaikuHealthyWith": "降级链 [haiku-4-5, sonnet-4-6]，Haiku healthy 且具备 extract，切换。",
    "callHaikuTryAgainToExtractThe": "调用 Haiku 4.5 · 重试抽取三大报表字段，成功。",
    "crossCheckingVerificationAssetsLiabilitiesEquityRevenue": "勾稽校验：资产=负债+权益 ✓，营收-成本=毛利 ✓…",
    "exportingJsonCompletesEndToEndIn": "导出 JSON 完成，端到端 38.4s，花费 ¥0.61，SLA 余量充足。",
    "p1BatchExtractionDeepseekV4HadThe": "P1 批量抽取，DeepSeek V4 极低成本综合分最高（0.735）；运行中超时降级至 Haiku 4.5。",
    "deepseekV4DegradedAndSwitchedToHaiku": "DeepSeek V4 抽取超时（degraded），按降级链切换至 Haiku 4.5",
    "mainMarketingVisualMaterialGeneration": "618 营销主视觉素材生成",
    "materialGeneration": "素材生成",
    "marketSuWan": "市场 · 苏晚",
    "generateSetsOfCopywritingVisualPrompts": "生成 5 组文案 + 视觉提示词",
    "textToTextImageMainVisual": "文生图 · 主视觉 1024×1024",
    "materialComplianceReviewAdvertisingLaw": "素材合规审核（广告法）",
    "theTaskEntersTheBusAndHits": "任务进入总线，命中规则「图像任务 → 视觉模型」。",
    "callSonnetGenerateSetsOfCopyAnd": "调用 Sonnet 4.6 · 生成 5 组文案与配套视觉提示词。",
    "newSummerStoresEnjoyGoodItemsAt": "「盛夏开新场，好物半价享」「囤货季 · 一键凑单更划算」…",
    "callingHulianScrollFluxRenderTheMain": "调用 瑚琏绘卷 Flux · 渲染主视觉，1024×1024，CFG 7。",
    "afterImageRenderingIsCompletedItMust": "等待图像渲染完成后，须过广告法合规审核再发布。",
    "abilityNotSatisfiedImage": "能力不满足: image",
    "withImageCapabilitiesHulianScrollFluxIs": "含 image 能力，瑚琏绘卷 Flux 为唯一具备 image 的执行器，文/审环节由 Sonnet/审核 Agent 协作。",
    "multilingualTranslationOfProductManuals": "产品手册多语翻译",
    "translation": "翻译",
    "localizationGaoHeng": "本地化 · 高珩",
    "p2TranslationHaikuIsOptimalForLow": "P2 翻译，Haiku 4.5 低成本 + 低延迟综合最优。",
    "prCodeSecurityReview": "PR 代码安全审查",
    "codeReview": "代码审查",
    "researchAndDevelopmentChenZhao": "研发 · 陈昭",
    "p1CodingTaskSonnetBalancingCapabilityAmple": "P1 代码任务，Sonnet 4.6 均衡能力 + SLA 余量充足。",
    "customerServiceKnowledgeBaseIntelligentQA": "客服知识库智能问答",
    "ragQA": "RAG 问答",
    "customerServiceShenZhi": "客服 · 沈知",
    "hitTheRetrievalEnhancementRagAgentRag": "命中「检索增强 → RAG Agent」，RAG Agent 承接。",
    "realTimeCommunityUgcReview": "社区 UGC 实时审核",
    "contentReview": "内容审核",
    "riskControlHanChe": "风控 · 韩澈",
    "p0AuditReviewAgentAcceptanceCurrentWaiting": "P0 审核，审核 Agent 承接；当前等待已达 SLA 88%，临期告警。",
    "industryPublicOpinionDailySummary": "行业舆情日报摘要",
    "textSummary": "文本摘要",
    "operationsYeHe": "运营 · 叶禾",
    "p3BatchLowQualityQueueingWaitingFor": "P3 批量低优排队中，待低成本池（DeepSeek/Haiku）释放并发。",
    "naturalLanguageToSql": "自然语言转 SQL",
    "codeGeneration": "代码生成",
    "dataLuoYan": "数据 · 罗砚",
    "p2CodeGenerationDeepseekV4UltraLow": "P2 代码生成，DeepSeek V4 超低成本综合最优。",
    "quickReleaseOfHolidayPosterImages": "节日海报快速出图",
    "imageGeneration": "图像生成",
    "designQiuBai": "设计 · 邱白",
    "theUniqueImageActuatorFluxConcurrentlyOccupies": "唯一 image 执行器 Flux 并发占满，排队等待空槽。",
    "extractionOfVatInvoiceFields": "增值税发票字段抽取",
    "dataExtraction2": "数据抽取",
    "financeTangNing": "财务 · 唐宁",
    "p2ExtractionStructuredExtractionAgentSpecializedCapability": "P2 抽取，结构化抽取 Agent 专项能力 + SLA 充足。",
    "multilingualHandlingOfOverseasWorkOrders": "海外工单多语应答",
    "translation2": "翻译",
    "customerServiceGuTang": "客服 · 顾棠",
    "p1TranslationHaikuLowLatencyWithReal": "P1 翻译，Haiku 4.5 低延迟保实时性。",
    "compilationOfCompetitorResearchFromMultipleSources": "竞品调研多源汇编",
    "multiAgentOrchestration": "多 agent 编排",
    "strategyJiangyu": "战略 · 江屿",
    "p1OrchestrationOrchestratedByAgentAcceptanceDue": "P1 编排，编排 Agent 承接；因外部检索源限流，子链超预算失败。",
    "aMassiveNumberOfCommentsAndEmotional": "海量评论情感分类",
    "textClassification": "文本分类",
    "operationsShaoQing": "运营 · 邵青",
    "p3BatchHitTheBatchLowQuality": "P3 批量，命中「批量低优 → 低成本池」，排队等 DeepSeek 释放。",
  },
  en: {
    "intelligentReviewOfCrossBorderProcurementContracts": "Review a cross-border procurement contract",
    "contractReview": "Contract review",
    "legalAffairsZhouLan": "Legal Affairs · Zhou Lan",
    "retrieveTheInternalContractClauseDatabase": "Retrieve the internal contract clause database",
    "theEnglishClausesAreTranslatedIntoChinese": "Translate the English clauses into Chinese",
    "riskClauseComplianceReview": "Risk clause compliance review",
    "summarizeAndReviewTheOpinionReport": "Compile the review report",
    "missionEntersTheBusHitsTheRule": "Task submitted · Matched rule: \"P0 security-sensitive → flagship\"",
    "ifTheContractContainsCrossBorderClauses": "If the contract contains cross-border clauses, the context of the terms must be established before translation to avoid terminology drift.",
    "callRetrievalEnhancementAgentRecallSimilarClauses": "Retrieval Agent · Found 24 similar clauses and reranked the top 8.",
    "threeKeyClausesForceMajeureJurisdictionOf": "Extracted three key clauses: force majeure, dispute jurisdiction, and payment milestones.",
    "callHaikuBatchTranslateEnglishTerms": "Haiku 4.5 · Translated 8 English terms in one batch.",
    "liquidatedDamagesIsADirectTranslationOf": "The draft translates \"liquidated damages\" too broadly as \"breach penalty.\" Use the contract-specific term \"agreed damages\" and flag it for legal review.",
    "callContentReviewAgentCompareComplianceBaselines": "Content Review Agent · Compared compliance baselines and flagged 2 high-risk clauses.",
    "afterTheReviewIsCompletedTheOrchestration": "The Orchestration Agent compiled the final report after all reviews completed.",
    "abilityNotSatisfiedOrchestrate": "Missing capability: orchestration",
    "abilityNotSatisfiedTranslateModerateOrchestrate": "Missing capabilities: translation, moderation, and orchestration",
    "p0MultiAgentOrchestrationWithOrchestratedAnd": "For this P0 multi-agent task, the Orchestration Agent had the highest overall score (0.685) and launched the retrieval, translation, and review subtask chain.",
    "structuredExtractionOfListedCompanyFinancialReports": "Structured extraction of listed company financial reports",
    "dataExtraction": "Data extraction",
    "investmentResearchLinAn": "Investment Research · Lin An",
    "analyzePdfFinancialReportPages": "Analyze PDF financial report pages",
    "extractThreeMajorReportFields": "Extract three major report fields",
    "extractThreeMajorReportFieldsDowngradeAnd": "Extract three financial statements (fallback retry)",
    "verifyAndVerifyTheRelationshipsBetweenThe": "Validate cross-statement relationships",
    "exportingStructuredJson": "Export structured JSON",
    "theTaskEntersTheBusHittingThe": "Task submitted · Matched rule: \"Batch work → Low-cost pool\" · Initial executor: DeepSeek V4.",
    "callStructuredExtractAgentParseAnPage": "Structured Extraction Agent · Parsed an 86-page financial report and separated the statement blocks.",
    "callDeepseekV4ExtractBalanceSheetFields": "DeepSeek V4 · Extracting balance-sheet fields...",
    "deepseekV4ReturnsATimeoutHealthDegraded": "⚠ DeepSeek V4 timed out and its health changed to degraded. Starting fallback.",
    "degradationChainHaikuSonnetHaikuHealthyWith": "Fallback chain: Haiku 4.5 → Sonnet 4.6. Haiku is healthy and supports extraction, so traffic switches to Haiku.",
    "callHaikuTryAgainToExtractThe": "Haiku 4.5 · Retried and extracted all three statements successfully.",
    "crossCheckingVerificationAssetsLiabilitiesEquityRevenue": "Cross-checks passed: Assets = Liabilities + Equity; Revenue − Cost = Gross profit.",
    "exportingJsonCompletesEndToEndIn": "JSON export completed in 38.4 seconds at a cost of ¥0.61, with ample SLA margin.",
    "p1BatchExtractionDeepseekV4HadThe": "DeepSeek V4 had the highest score (0.735) for this P1 batch extraction because of its low cost. It timed out during execution, so the fallback chain moved the task to Haiku 4.5.",
    "deepseekV4DegradedAndSwitchedToHaiku": "DeepSeek V4 degraded; fallback switched execution to Haiku 4.5",
    "mainMarketingVisualMaterialGeneration": "Generate campaign hero artwork",
    "materialGeneration": "Material generation",
    "marketSuWan": "Market · Su Wan",
    "generateSetsOfCopywritingVisualPrompts": "Generate 5 copy and visual-prompt concepts",
    "textToTextImageMainVisual": "Generate main visual · 1024×1024",
    "materialComplianceReviewAdvertisingLaw": "Material compliance review (Advertising Law)",
    "theTaskEntersTheBusAndHits": "Task submitted · Matched rule: \"Image task → Image model.\"",
    "callSonnetGenerateSetsOfCopyAnd": "Sonnet 4.6 · Generated 5 copy concepts with matching visual prompts.",
    "newSummerStoresEnjoyGoodItemsAt": "\"Fresh summer arrivals at half price\" · \"Stock-up season: bundle and save\"",
    "callingHulianScrollFluxRenderTheMain": "Hulian Image Flux · Rendering the 1024×1024 main visual with CFG 7.",
    "afterImageRenderingIsCompletedItMust": "The rendered image must pass advertising-compliance review before publication.",
    "abilityNotSatisfiedImage": "Missing capability: image generation",
    "withImageCapabilitiesHulianScrollFluxIs": "Hulian Image Flux is the only image-capable executor. Sonnet and the Content Review Agent handle the copy and compliance steps.",
    "multilingualTranslationOfProductManuals": "Multilingual translation of product manuals",
    "translation": "Translation",
    "localizationGaoHeng": "Localization · Gao Heng",
    "p2TranslationHaikuIsOptimalForLow": "Haiku 4.5 offers the best cost and latency for this P2 translation task.",
    "prCodeSecurityReview": "Review pull request security",
    "codeReview": "Code review",
    "researchAndDevelopmentChenZhao": "Research and Development · Chen Zhao",
    "p1CodingTaskSonnetBalancingCapabilityAmple": "Sonnet 4.6 balances coding capability and SLA margin for this P1 task.",
    "customerServiceKnowledgeBaseIntelligentQA": "Answer questions from the customer-support knowledge base",
    "ragQA": "RAG Q&A",
    "customerServiceShenZhi": "Customer Service · Shen Zhi",
    "hitTheRetrievalEnhancementRagAgentRag": "Matched rule: \"Retrieval-augmented task → RAG Agent.\"",
    "realTimeCommunityUgcReview": "Real-time community UGC review",
    "contentReview": "Content review",
    "riskControlHanChe": "Risk Control · Han Che",
    "p0AuditReviewAgentAcceptanceCurrentWaiting": "P0 moderation task routed to the Review Agent. Queue time has consumed 88% of the SLA, so an expiry warning is active.",
    "industryPublicOpinionDailySummary": "Daily industry sentiment summary",
    "textSummary": "Text summary",
    "operationsYeHe": "Operations · Ye He",
    "p3BatchLowQualityQueueingWaitingFor": "This P3 batch task is queued until the low-cost DeepSeek or Haiku pool has capacity.",
    "naturalLanguageToSql": "Natural language to SQL",
    "codeGeneration": "Code generation",
    "dataLuoYan": "Data · Luo Yan",
    "p2CodeGenerationDeepseekV4UltraLow": "DeepSeek V4 offers the best overall score for this P2 code-generation task at very low cost.",
    "quickReleaseOfHolidayPosterImages": "Generate a holiday poster",
    "imageGeneration": "Image generation",
    "designQiuBai": "Design · Qiu Bai",
    "theUniqueImageActuatorFluxConcurrentlyOccupies": "Flux is the only image-capable executor and is at full concurrency, so the task is waiting for a slot.",
    "extractionOfVatInvoiceFields": "Extraction of VAT invoice fields",
    "dataExtraction2": "Data extraction",
    "financeTangNing": "Finance · Tang Ning",
    "p2ExtractionStructuredExtractionAgentSpecializedCapability": "The Structured Extraction Agent provides the required specialization with sufficient SLA margin for this P2 task.",
    "multilingualHandlingOfOverseasWorkOrders": "Translate international support tickets",
    "translation2": "Translation",
    "customerServiceGuTang": "Customer Service · Gu Tang",
    "p1TranslationHaikuLowLatencyWithReal": "Haiku 4.5 provides the low latency required for this P1 translation task.",
    "compilationOfCompetitorResearchFromMultipleSources": "Compile multi-source competitor research",
    "multiAgentOrchestration": "Multi-agent orchestration",
    "strategyJiangyu": "Strategy · Jiangyu",
    "p1OrchestrationOrchestratedByAgentAcceptanceDue": "P1 orchestration was assigned to the Orchestration Agent. External source rate limits caused retries and pushed the subtask chain over budget.",
    "aMassiveNumberOfCommentsAndEmotional": "Classify sentiment across a large comment set",
    "textClassification": "Text classification",
    "operationsShaoQing": "Operations · Shao Qing",
    "p3BatchHitTheBatchLowQuality": "Matched rule: \"Batch work → Low-cost pool.\" The task is queued until DeepSeek has capacity.",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanhelm-data-tasks",
  content: t(content),
};

export default dictionary;
