// 内联 emoji 数据集（零依赖）。每项 e=emoji，k=搜索关键词（中英混合，空格分隔）。
// 精选高频 emoji，覆盖聊天/评论常用面，刻意不求全（求全应换 emoji-mart 等专用库）。
export interface EmojiItem {
  e: string;
  k: string;
}
export interface EmojiCategory {
  key: string;
  label: string;
  /** 分类页签上展示的代表 emoji。 */
  icon: string;
  items: EmojiItem[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    key: "smileys",
    label: "笑脸",
    icon: "😀",
    items: [
      { e: "😀", k: "grin smile 笑 开心" },
      { e: "😃", k: "smile happy 笑 高兴" },
      { e: "😄", k: "laugh 大笑 开心" },
      { e: "😁", k: "beam grin 露齿笑" },
      { e: "😆", k: "laugh xd 哈哈" },
      { e: "😅", k: "sweat 苦笑 尴尬" },
      { e: "🤣", k: "rofl 笑哭 滚地" },
      { e: "😂", k: "joy tears 笑哭 喜极而泣" },
      { e: "🙂", k: "slight smile 微笑" },
      { e: "🙃", k: "upside 倒脸 调皮" },
      { e: "😉", k: "wink 眨眼 暗示" },
      { e: "😊", k: "blush 害羞 微笑" },
      { e: "😇", k: "angel innocent 天使" },
      { e: "🥰", k: "love hearts 爱 喜欢" },
      { e: "😍", k: "heart eyes 爱慕 花痴" },
      { e: "🤩", k: "star struck 崇拜 星星眼" },
      { e: "😘", k: "kiss 飞吻 么么" },
      { e: "😋", k: "yum 美味 馋" },
      { e: "😜", k: "tongue wink 鬼脸" },
      { e: "🤪", k: "zany crazy 疯" },
      { e: "😎", k: "cool sunglasses 酷 墨镜" },
      { e: "🥳", k: "party 庆祝 派对" },
      { e: "😏", k: "smirk 得意 坏笑" },
      { e: "😢", k: "cry sad 哭 难过" },
      { e: "😭", k: "sob cry 大哭" },
      { e: "😤", k: "huff 生气 哼" },
      { e: "😡", k: "angry rage 愤怒" },
      { e: "🥺", k: "pleading 可怜 请求" },
      { e: "😴", k: "sleep 睡觉 困" },
      { e: "🤔", k: "thinking 思考 想" },
      { e: "😱", k: "scream shock 惊吓" },
      { e: "🤮", k: "vomit sick 吐 恶心" },
    ],
  },
  {
    key: "gestures",
    label: "手势",
    icon: "👍",
    items: [
      { e: "👍", k: "thumbs up 赞 好" },
      { e: "👎", k: "thumbs down 踩 差" },
      { e: "👌", k: "ok perfect 没问题" },
      { e: "✌️", k: "victory peace 胜利 耶" },
      { e: "🤞", k: "fingers crossed 祈求 好运" },
      { e: "🤟", k: "love you 我爱你 手势" },
      { e: "🤘", k: "rock 摇滚" },
      { e: "👏", k: "clap 鼓掌 棒" },
      { e: "🙌", k: "raise hands 欢呼 万岁" },
      { e: "👐", k: "open hands 张开双手" },
      { e: "🤝", k: "handshake 握手 合作" },
      { e: "🙏", k: "pray thanks 拜托 感谢 祈祷" },
      { e: "💪", k: "muscle strong 加油 强壮" },
      { e: "👋", k: "wave hello bye 招手 你好 再见" },
      { e: "🤙", k: "call me 打电话" },
      { e: "☝️", k: "point up 指上" },
      { e: "✋", k: "raise hand 举手 停" },
      { e: "🖐️", k: "hand five 五指" },
      { e: "👈", k: "point left 指左" },
      { e: "👉", k: "point right 指右" },
      { e: "👇", k: "point down 指下" },
      { e: "✊", k: "fist 拳头 加油" },
      { e: "👊", k: "punch 出拳 碰拳" },
      { e: "🤛", k: "fist left 左拳" },
    ],
  },
  {
    key: "animals",
    label: "动物",
    icon: "🐶",
    items: [
      { e: "🐶", k: "dog 狗 狗狗" },
      { e: "🐱", k: "cat 猫 猫咪" },
      { e: "🐭", k: "mouse 老鼠 鼠" },
      { e: "🐹", k: "hamster 仓鼠" },
      { e: "🐰", k: "rabbit 兔 兔子" },
      { e: "🦊", k: "fox 狐狸" },
      { e: "🐻", k: "bear 熊" },
      { e: "🐼", k: "panda 熊猫" },
      { e: "🐨", k: "koala 考拉" },
      { e: "🐯", k: "tiger 老虎 虎" },
      { e: "🦁", k: "lion 狮子" },
      { e: "🐮", k: "cow 牛" },
      { e: "🐷", k: "pig 猪" },
      { e: "🐵", k: "monkey 猴 猴子" },
      { e: "🐔", k: "chicken 鸡" },
      { e: "🐧", k: "penguin 企鹅" },
      { e: "🐦", k: "bird 鸟" },
      { e: "🦄", k: "unicorn 独角兽" },
      { e: "🐝", k: "bee 蜜蜂" },
      { e: "🦋", k: "butterfly 蝴蝶" },
      { e: "🐢", k: "turtle 乌龟 龟" },
      { e: "🐙", k: "octopus 章鱼" },
      { e: "🐳", k: "whale 鲸鱼" },
      { e: "🐬", k: "dolphin 海豚" },
    ],
  },
  {
    key: "food",
    label: "食物",
    icon: "🍔",
    items: [
      { e: "🍎", k: "apple 苹果" },
      { e: "🍊", k: "orange 橙子" },
      { e: "🍋", k: "lemon 柠檬" },
      { e: "🍌", k: "banana 香蕉" },
      { e: "🍉", k: "watermelon 西瓜" },
      { e: "🍇", k: "grapes 葡萄" },
      { e: "🍓", k: "strawberry 草莓" },
      { e: "🍑", k: "peach 桃子" },
      { e: "🥭", k: "mango 芒果" },
      { e: "🍍", k: "pineapple 菠萝" },
      { e: "🥝", k: "kiwi 猕猴桃" },
      { e: "🍅", k: "tomato 番茄 西红柿" },
      { e: "🥑", k: "avocado 牛油果" },
      { e: "🌽", k: "corn 玉米" },
      { e: "🥕", k: "carrot 胡萝卜" },
      { e: "🍔", k: "burger 汉堡" },
      { e: "🍟", k: "fries 薯条" },
      { e: "🍕", k: "pizza 披萨" },
      { e: "🌭", k: "hotdog 热狗" },
      { e: "🍜", k: "noodles ramen 面 拉面" },
      { e: "🍣", k: "sushi 寿司" },
      { e: "🍦", k: "ice cream 冰淇淋" },
      { e: "☕", k: "coffee 咖啡" },
      { e: "🍺", k: "beer 啤酒" },
    ],
  },
  {
    key: "activity",
    label: "活动",
    icon: "⚽",
    items: [
      { e: "⚽", k: "soccer football 足球" },
      { e: "🏀", k: "basketball 篮球" },
      { e: "🏈", k: "football 橄榄球" },
      { e: "⚾", k: "baseball 棒球" },
      { e: "🎾", k: "tennis 网球" },
      { e: "🏐", k: "volleyball 排球" },
      { e: "🏓", k: "ping pong 乒乓" },
      { e: "🎱", k: "pool 8 ball 台球" },
      { e: "🎯", k: "dart target 飞镖 目标" },
      { e: "🎮", k: "game 游戏 手柄" },
      { e: "🎲", k: "dice 骰子" },
      { e: "🎸", k: "guitar 吉他" },
      { e: "🎺", k: "trumpet 小号" },
      { e: "🎨", k: "art paint 画 艺术" },
      { e: "🎬", k: "movie clapper 电影" },
      { e: "🏆", k: "trophy 奖杯 冠军" },
      { e: "🥇", k: "gold medal 金牌 第一" },
      { e: "🎉", k: "party tada 庆祝 撒花" },
      { e: "🎁", k: "gift 礼物" },
      { e: "🎈", k: "balloon 气球" },
    ],
  },
  {
    key: "objects",
    label: "物品",
    icon: "💡",
    items: [
      { e: "⌚", k: "watch 手表" },
      { e: "📱", k: "phone 手机" },
      { e: "💻", k: "laptop 电脑 笔记本" },
      { e: "🖥️", k: "desktop 台式 显示器" },
      { e: "⌨️", k: "keyboard 键盘" },
      { e: "📷", k: "camera 相机" },
      { e: "🎥", k: "video camera 摄像机" },
      { e: "📺", k: "tv 电视" },
      { e: "🔋", k: "battery 电池" },
      { e: "💡", k: "bulb idea 灯泡 点子" },
      { e: "🔦", k: "flashlight 手电" },
      { e: "📕", k: "book 书" },
      { e: "📦", k: "package box 包裹 盒子" },
      { e: "✏️", k: "pencil 铅笔" },
      { e: "📌", k: "pin 图钉" },
      { e: "📎", k: "clip 回形针" },
      { e: "🔒", k: "lock 锁" },
      { e: "🔑", k: "key 钥匙" },
      { e: "💰", k: "money bag 钱袋" },
      { e: "💳", k: "card 银行卡 信用卡" },
    ],
  },
  {
    key: "symbols",
    label: "符号",
    icon: "❤️",
    items: [
      { e: "❤️", k: "heart red love 爱 红心" },
      { e: "🧡", k: "orange heart 橙心" },
      { e: "💛", k: "yellow heart 黄心" },
      { e: "💚", k: "green heart 绿心" },
      { e: "💙", k: "blue heart 蓝心" },
      { e: "💜", k: "purple heart 紫心" },
      { e: "🖤", k: "black heart 黑心" },
      { e: "🤍", k: "white heart 白心" },
      { e: "💔", k: "broken heart 心碎" },
      { e: "💯", k: "hundred 满分 100" },
      { e: "✅", k: "check 对 完成" },
      { e: "❌", k: "cross wrong 错 叉" },
      { e: "⭕", k: "circle 圈 对" },
      { e: "❗", k: "exclamation 感叹号" },
      { e: "❓", k: "question 问号" },
      { e: "💢", k: "anger 怒 青筋" },
      { e: "💤", k: "zzz sleep 睡" },
      { e: "⚡", k: "lightning 闪电" },
      { e: "🔥", k: "fire hot 火 热门" },
      { e: "⭐", k: "star 星星" },
    ],
  },
];

/** 扁平化全部 emoji（搜索用）。 */
export const ALL_EMOJI: EmojiItem[] = EMOJI_CATEGORIES.flatMap((c) => c.items);
