import { copy } from "./artifacts.content";
import type { Artifact } from "./types";

// mock 历史产物（产物画廊）。图用程序化渐变 seed，视频复用 public/demo 下的样例资源。
export const ARTIFACTS: Artifact[] = [
  {
    id: "a1",
    type: "image",
    title: copy("neonMechanicalCat"),
    seed: 480231,
    model: "flux-hl",
    ratio: "1:1",
    workflow: copy("vincentHighDefinitionEnlargement"),
    createdAt: copy("minutesAgo"),
    prompt: copy("aMechanicalCatSittingInANeonAlleyRainyNight"),
  },
  {
    id: "a2",
    type: "image",
    title: copy("morningFogMountainLake"),
    seed: 240118,
    model: "huapro-xl",
    ratio: "16:9",
    workflow: copy("vincentMapsFoundation"),
    createdAt: copy("minutesAgoAlternate"),
    prompt: copy("mountainLakesInTheMorningMistRealisticScenerySoftMorning"),
  },
  {
    id: "a3",
    type: "video",
    title: copy("starryWhale"),
    videoUrl: "/demo/sample-video.mp4",
    poster: "/demo/sample-poster.jpg",
    model: "huapro-xl",
    ratio: "16:9",
    workflow: copy("vincentVideo"),
    createdAt: copy("minutesAgoSecondary"),
    prompt: copy("whalesRoamingTheStarsDreamySlowShot"),
  },
  {
    id: "a4",
    type: "image",
    title: copy("futureSkyline"),
    seed: 771203,
    model: "flux-hl",
    ratio: "16:9",
    workflow: copy("vincentHighDefinitionEnlargement"),
    createdAt: copy("minutesAgoTertiary"),
    prompt: copy("futureCitySkylineDuskUltraWideAnglePoster"),
  },
  {
    id: "a5",
    type: "image",
    title: copy("watercolorGirl"),
    seed: 558014,
    model: "yunhui-anime3",
    ratio: "1:1",
    workflow: copy("tuscanyStyleRedraw"),
    createdAt: copy("minutesAgoQuaternary"),
    prompt: copy("retainCompositionAndTurnToWatercolorIllustrationStyle"),
  },
  {
    id: "a6",
    type: "image",
    title: copy("nationalStyleCourtyard"),
    seed: 661820,
    model: "huapro-xl",
    ratio: "4:3",
    workflow: copy("vincentMapsFoundation"),
    createdAt: copy("hourAgo"),
    prompt: copy("gangnamCourtyardInkCountryStyleFlyingCorner"),
  },
  {
    id: "a7",
    type: "image",
    title: copy("cyberStreetMarket"),
    seed: 119537,
    model: "flux-hl",
    ratio: "9:16",
    workflow: copy("vincentMapsFoundation"),
    createdAt: copy("hourAgo"),
    prompt: copy("cyberpunkNightMarketRainNeonSignsVerticalComposition"),
  },
  {
    id: "a8",
    type: "video",
    title: copy("mobileGalaxy"),
    videoUrl: "/demo/sample-video.mp4",
    poster: "/demo/sample-poster.jpg",
    model: "huapro-xl",
    ratio: "16:9",
    workflow: copy("tucsonVideo"),
    createdAt: copy("hoursAgo"),
    prompt: copy("uploadAPictureToGetItUpAndRunning"),
  },
  {
    id: "a9",
    type: "image",
    title: copy("minimalistProductDiagram"),
    seed: 903412,
    model: "realvis-5",
    ratio: "1:1",
    workflow: copy("vincentMapsFoundation"),
    createdAt: copy("hoursAgoAlternate"),
    prompt: copy("minimalistWhiteProductPhotographySoftLightHighTexture"),
  },
  {
    id: "a10",
    type: "image",
    title: copy("filmPortrait"),
    seed: 330921,
    model: "realvis-5",
    ratio: "4:3",
    workflow: copy("tuscanyStyleRedraw"),
    createdAt: copy("yesterday"),
    prompt: copy("filmGrainPortraitWarmthShallowDepthOfField"),
  },
  {
    id: "a11",
    type: "image",
    title: copy("threeDimensionalCartoonHouse"),
    seed: 207744,
    model: "yunhui-anime3",
    ratio: "1:1",
    workflow: copy("vincentMapsFoundation"),
    createdAt: copy("yesterday"),
    prompt: copy("threeDimensionalCartoonCabinPrompt"),
  },
  {
    id: "a12",
    type: "image",
    title: copy("neonWhaleFalls"),
    seed: 902335,
    model: "huapro-xl",
    ratio: "16:9",
    workflow: copy("vincentVideo"),
    createdAt: copy("yesterday"),
    prompt: copy("whalesRoamingTheStarsDreamySlowShot"),
  },
];
