import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "online": "在线",
    "downgrade": "降级",
    "offline": "离线",
    "maintenance": "维护",
    "channel": "渠道",
    "status": "状态",
    "successRate": "成功率",
    "weight": "权重",
    "priority": "优先级",
    "speedLimitMargin": "限速余量",
    "healthDetectionCenter": "健康探测中心",
    "upstreamChannelPingSpeedMeasurementWeightedRouting": "上游渠道 ping / 测速 · 加权路由 · 被动失败转移 · 阈值熔断",
    "speedMeasurementInProgress": "测速中…",
    "oneClickSpeedMeasurement": "一键测速",
    "currentlyThereAre": "当前有",
    "channelIsUnavailableAndTrafficHasBeen": "个渠道不可用，流量已自动转移至健康渠道，请关注降级影响。",
    "upstreamChannels": "上游渠道",
    "total": "共",
    "articleWeightedRoutingByPriorityWeight": "条 · 按优先级 + 权重加权路由",
    "detectingEachUpstreamDelayAndSuccessRate": "正在探测各上游延迟与成功率…",
    "channelModelMapping": "渠道 → 模型映射",
    "weight2": "权重",
    "circuitBreakerRules": "熔断规则",
    "continuousFailureThreshold": "连续失败阈值",
    "afterReachingTheNumberOfTimesThe": "达到次数后触发熔断转移",
    "continuousFailureThreshold2": "连续失败阈值",
    "automaticallyDisableChannels": "自动禁用渠道",
    "automaticallyOfflineAfterTheFuseIsBroken": "熔断后自动下线，恢复后自动接回",
    "automaticallyDisableChannels2": "自动禁用渠道",
    "downgradeTransfer": "降级转移",
    "thoseThatHitTheThresholdAreRemoved": "命中阈值即从加权池摘除，按优先级转移到次级渠道",
    "halfOpenDetection": "半开探测",
    "oneTrialRequestIsReleasedEveryS": "每 60s 放行 1 次试探请求，连续 3 次成功即恢复路由",
    "diggingStrategy": "兜底策略",
    "whenAllAreUnavailableReturnAndTrigger": "全部不可用时返回 503 并触发告警",
    "maintainTheOriginalChannelUntilManualIntervention": "保持原渠道直至人工介入",
    "detectionHistory": "探测历史",
    "probeLogCopied": "已复制探测日志",
    "exportLog": "导出日志",
  },
  en: {
    "online": "online",
    "downgrade": "Downgrade",
    "offline": "Offline",
    "maintenance": "maintenance",
    "channel": "channel",
    "status": "Status",
    "successRate": "success rate",
    "weight": "weight",
    "priority": "priority",
    "speedLimitMargin": "Speed limit margin",
    "healthDetectionCenter": "Health Detection Center",
    "upstreamChannelPingSpeedMeasurementWeightedRouting": "Upstream channel ping/speed measurement · Weighted routing · Passive failover · Threshold circuit breaker",
    "speedMeasurementInProgress": "Speed measurement in progress...",
    "oneClickSpeedMeasurement": "One-click speed measurement",
    "currentlyThereAre": "Currently there are",
    "channelIsUnavailableAndTrafficHasBeen": "channel is unavailable and traffic has been automatically transferred to healthy channels. Please pay attention to the impact of downgrade.",
    "upstreamChannels": "upstream channels",
    "total": "total",
    "articleWeightedRoutingByPriorityWeight": "Article · Weighted routing by priority + weight",
    "detectingEachUpstreamDelayAndSuccessRate": "Detecting each upstream delay and success rate...",
    "channelModelMapping": "Channel → Model Mapping",
    "weight2": "weight",
    "circuitBreakerRules": "circuit breaker rules",
    "continuousFailureThreshold": "Continuous failure threshold",
    "afterReachingTheNumberOfTimesThe": "After reaching the number of times, the fuse transfer is triggered.",
    "continuousFailureThreshold2": "Continuous failure threshold",
    "automaticallyDisableChannels": "Automatically disable channels",
    "automaticallyOfflineAfterTheFuseIsBroken": "Automatically offline after the fuse is broken, and automatically connected after recovery",
    "automaticallyDisableChannels2": "Automatically disable channels",
    "downgradeTransfer": "downgrade transfer",
    "thoseThatHitTheThresholdAreRemoved": "Those that hit the threshold are removed from the weighted pool and transferred to secondary channels according to priority.",
    "halfOpenDetection": "half-open detection",
    "oneTrialRequestIsReleasedEveryS": "One trial request is released every 60s, and routing is restored after three consecutive attempts.",
    "diggingStrategy": "Digging strategy",
    "whenAllAreUnavailableReturnAndTrigger": "When all are unavailable, return 503 and trigger an alarm.",
    "maintainTheOriginalChannelUntilManualIntervention": "Maintain the original channel until manual intervention",
    "detectionHistory": "Detection history",
    "probeLogCopied": "Probe log copied",
    "exportLog": "Export log",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanhub-app-health-page",
  content: t(content),
};

export default dictionary;
