import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "connectedToTheWarehouse": "接入仓库",
    "configureWebhooksPrCommitEventsTriggerAutomatic": "配置 Webhook，PR/提交事件触发自动审查",
    "theWebhookKeyHasBeenCopied": "Webhook 密钥已复制",
    "theWebhookKeyHasBeenReset": "已重置 Webhook 密钥",
    "reset": "重置",
    "connected": "已接入",
    "defaultBranchValue": "默认分支 {0}",
    "openTheAccessWizard": "打开接入向导",
    "connectingToTheNewWarehouse": "接入新仓库",
    "teamMembers": "团队成员",
    "whoCanViewAndHandleTheReview": "谁可以查看与处理审查",
    "notification": "通知",
    "howTheReviewResultsRemindedTheTeam": "审查结果如何提醒团队",
    "theGateWasBlockedAndBlocked": "门禁阻断",
    "prNotifiesTheAuthorWhenTheQuality": "PR 被质量门禁阻断时通知作者",
    "aSeriousProblem": "严重问题",
    "criticalIssuesAreDetectedImmediately": "发现 critical 级问题立即通知",
    "dailyQualitySummary": "每日质量摘要",
    "summarizeChangesInQualityScoresFromEach": "每天汇总各仓库质量分变化",
    "notificationChannels": "通知渠道",
    "sendingAFlyingLetter": "飞书",
    "notificationChannels2": "通知渠道",
    "sendingAFlyingLetter2": "飞书",
    "sendingAFlyingLetter3": "飞书",
    "swarmOfRobots": "群机器人",
    "email": "邮件",
    "email2": "邮件",
    "pushNotificationsAccordingToThePerson": "按人推送",
    "customCallbacks": "自定义回调",
    "aiBudget": "AI 预算",
    "controlTheSpendingOfMonthlyModelCalls": "控制每月审查的模型调用花费",
    "monthlyBudget": "月度预算（¥）",
    "monthlyBudget2": "月度预算",
    "thisMonthISpent": "本月已消耗 ¥1,284",
    "excessStrategy": "超额策略",
    "excessStrategy2": "超额策略",
    "downgradedToAnEconomicModel": "降级到经济模型",
    "afterOverBudgetingSwitchToHaikuDeepseek": "超预算后改用 Haiku/DeepSeek 继续审查",
    "suspensionOfReview": "暂停审查",
    "afterExceedingTheBudgetTheQueueIs": "超预算后队列挂起，等待下月或追加预算",
  },
  en: {
    "connectedToTheWarehouse": "Connected repositories",
    "configureWebhooksPrCommitEventsTriggerAutomatic": "Configure webhooks to start reviews automatically on pull request and commit events",
    "theWebhookKeyHasBeenCopied": "The webhook key has been copied",
    "theWebhookKeyHasBeenReset": "The webhook key has been reset",
    "reset": "Reset",
    "connected": "Connected",
    "defaultBranchValue": "Default branch {0}",
    "openTheAccessWizard": "Open connection wizard",
    "connectingToTheNewWarehouse": "Connect a repository",
    "teamMembers": "Team members",
    "whoCanViewAndHandleTheReview": "Who can view and manage reviews",
    "notification": "Notification",
    "howTheReviewResultsRemindedTheTeam": "Choose how review results are sent to the team",
    "theGateWasBlockedAndBlocked": "Quality gate blocks a review",
    "prNotifiesTheAuthorWhenTheQuality": "Notify the PR author when the quality gate blocks a review",
    "aSeriousProblem": "Critical finding detected",
    "criticalIssuesAreDetectedImmediately": "Notify the team immediately when a critical finding is detected",
    "dailyQualitySummary": "Daily quality summary",
    "summarizeChangesInQualityScoresFromEach": "Summarize daily quality-score changes for each repository",
    "notificationChannels": "Notification channels",
    "sendingAFlyingLetter": "Feishu",
    "notificationChannels2": "Notification channels",
    "sendingAFlyingLetter2": "Feishu",
    "sendingAFlyingLetter3": "Feishu",
    "swarmOfRobots": "Bot webhook",
    "email": "Email",
    "email2": "Email",
    "pushNotificationsAccordingToThePerson": "Send notifications to the assigned reviewer",
    "customCallbacks": "Custom callbacks",
    "aiBudget": "AI budget",
    "controlTheSpendingOfMonthlyModelCalls": "Set a monthly budget for model usage",
    "monthlyBudget": "Monthly budget (¥)",
    "monthlyBudget2": "Monthly budget",
    "thisMonthISpent": "¥1,284 spent this month",
    "excessStrategy": "Over-budget behavior",
    "excessStrategy2": "Over-budget behavior",
    "downgradedToAnEconomicModel": "Switch to a lower-cost model",
    "afterOverBudgetingSwitchToHaikuDeepseek": "After the budget is exceeded, route reviews to Haiku or DeepSeek",
    "suspensionOfReview": "Pause reviews",
    "afterExceedingTheBudgetTheQueueIs": "After the budget is exceeded, pause the queue until next month or until more budget is added",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanreview-app-settings-page",
  content: t(content),
};

export default dictionary;
