import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "allEnvironments": "全部环境",
    "produce": "生产",
    "preview": "预览",
    "allStatus": "全部状态",
    "alreadyOnline": "已上线",
    "underConstruction": "构建中",
    "failed": "失败",
    "canceled": "已取消",
    "queue": "排队",
    "skipped": "已跳过",
    "pleaseSelectAnItem": "请选择项目",
    "pleaseEnterBranch": "请输入分支",
    "project": "项目",
    "environment": "环境",
    "produce2": "生产",
    "preview2": "预览",
    "deploymentAddress": "部署地址",
    "status": "状态",
    "create": "创建",
    "operation": "操作",
    "view": "查看",
    "manualDeploymentBranchValue": "手动部署（分支 {0}）",
    "hulian": "瑚琏",
    "coral": "瑚",
    "deploymentTriggered": "已触发部署",
    "valueValueIsUnderConstruction": "{0} · {1} 正在构建中。",
    "deploymentHistory": "部署历史",
    "deploymentRecordsAcrossAllProjectsClickOn": "跨所有项目的部署记录 · 点开任一条查看构建步骤与日志",
    "failedToLoadDeploymentList": "加载部署列表失败",
    "tryAgain": "重试",
    "deployAll": "全部部署",
    "manualDeployment": "手动部署",
    "keywords": "关键词",
    "commitInformationShaBranchProjectName": "提交信息 / SHA / 分支 / 项目名",
    "environment2": "环境",
    "status2": "状态",
    "manualDeployment2": "手动部署",
    "triggerDeployment": "触发部署",
    "project2": "项目",
    "branch": "分支",
    "theLatestCommitOfThisBranchWill": "将以预览环境部署该分支的最新提交",
  },
  en: {
    "allEnvironments": "All environments",
    "produce": "produce",
    "preview": "Preview",
    "allStatus": "All status",
    "alreadyOnline": "Already online",
    "underConstruction": "Under construction",
    "failed": "failed",
    "canceled": "Canceled",
    "queue": "queue",
    "skipped": "skipped",
    "pleaseSelectAnItem": "Please select an item",
    "pleaseEnterBranch": "Please enter branch",
    "project": "Project",
    "environment": "environment",
    "produce2": "produce",
    "preview2": "Preview",
    "deploymentAddress": "Deployment address",
    "status": "Status",
    "create": "create",
    "operation": "Operation",
    "view": "View",
    "manualDeploymentBranchValue": "Manual deployment (branch {0})",
    "hulian": "Hulian",
    "coral": "coral",
    "deploymentTriggered": "Deployment triggered",
    "valueValueIsUnderConstruction": "{0} · {1} is under construction.",
    "deploymentHistory": "Deployment history",
    "deploymentRecordsAcrossAllProjectsClickOn": "Deployment records across all projects · Click on any item to view build steps and logs",
    "failedToLoadDeploymentList": "Failed to load deployment list",
    "tryAgain": "Try again",
    "deployAll": "Deploy all",
    "manualDeployment": "Manual deployment",
    "keywords": "keywords",
    "commitInformationShaBranchProjectName": "Commit information / SHA / branch / project name",
    "environment2": "environment",
    "status2": "Status",
    "manualDeployment2": "Manual deployment",
    "triggerDeployment": "trigger deployment",
    "project2": "Project",
    "branch": "branch",
    "theLatestCommitOfThisBranchWill": "The latest commit of this branch will be deployed in a preview environment",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanship-app-deployments-page",
  content: t(content),
};

export default dictionary;
