import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    hanphoneProFlagshipCameraPhone: "瀚拍 Pro 影像旗舰手机",
    alpineBlue: "远峰蓝",
    weiZhang1388866: "张伟 138****8866",
    hanyunTower969WestWenyiRoadYuhangDistrictHangzhouZhejiang: "浙江省杭州市余杭区文一西路 969 号瀚云大厦",
    departedHangzhouTransitCenterNextStopHangzhouYuhangDistributionCenter: "【杭州转运中心】快件已发出，下一站【杭州余杭分拨中心】",
    arrivedAtHangzhouTransitCenter: "【杭州转运中心】快件已到达",
    itemLeftTheWarehouseAndIsAwaitingCarrierPickup: "商品已出库，等待揽收",
    orderSubmittedAwaitingPaymentConfirmation: "您的订单已提交，等待付款确认",
    hansoundAirActiveNoiseCancelingEarbuds: "瀚声 Air 主动降噪耳机",
    obsidianBlack: "曜石黑",
    noiseCancelingPro: "降噪 Pro 版",
    hanfieldInsulatedSportsBottle: "瀚野 保温运动水壶",
    mintGreen: "薄荷绿",
    naLi1592030: "李娜 159****2030",
    text2BoyunRoadZhangjiangHiTechParkPudongShanghai: "上海市浦东新区张江高科技园区博云路 2 号",
    paymentReceivedTheSellerIsPreparingYourOrder: "支付成功，商家正在备货",
    orderSubmitted: "订单提交成功",
    hanlabNiacinamideRepairSerum: "瀚研 烟酰胺修护精华",
    text30MlStandard: "30ml 标准",
    buyOneGetOneGiftSet: "买一送一礼盒",
    fangWang1375521: "王芳 137****5521",
    gaoxinSouth1stRoadNanshanDistrictShenzhenGuangdong: "广东省深圳市南山区科技园南区高新南一道",
    deliveredAndSignedForByRecipientWeLookForwardToYourReview: "已签收，签收人：本人。期待您的评价",
    outForDeliveryFromShenzhenNanshanDeliveryCenter: "【深圳南山派送中心】派送中",
    arrivedAtShenzhenTransitCenter: "【深圳转运中心】快件已到达",
    itemLeftTheWarehouse: "商品已出库",
    hanwear3In1WeatherproofJacket: "瀚衣 三防冲锋衣",
    armyGreen: "军绿",
    qiangZhao1889012: "赵强 188****9012",
    wangjingSohoT1ChaoyangDistrictBeijing: "北京市朝阳区望京 SOHO T1",
    orderSubmittedCompletePaymentWithin30Minutes: "订单提交成功，请在 30 分钟内完成支付",
    hanlabVelvetMatteLipstick: "瀚研 丝绒雾面口红",
    mapleBrown: "枫叶棕",
    standardSize: "标准装",
    liSun1357788: "孙丽 135****7788",
    text100NorthZhongshanRoadGulouDistrictNanjingJiangsu: "江苏省南京市鼓楼区中山北路 100 号",
    refundRequestedAwaitingSellerReview: "退款申请已提交，等待商家处理",
    delivered: "已签收",
    awaitingPayment: "待付款",
    preparingShipment: "待发货",
    inTransit: "待收货",
    completed: "已完成",
    refundInProgress: "退款中",
    closed: "已关闭",
  },
  en: {
    hanphoneProFlagshipCameraPhone: "HanPhone Pro Flagship Camera Phone",
    alpineBlue: "Alpine blue",
    weiZhang1388866: "Wei Zhang 138****8866",
    hanyunTower969WestWenyiRoadYuhangDistrictHangzhouZhejiang: "Hanyun Tower, 969 West Wenyi Road, Yuhang District, Hangzhou, Zhejiang",
    departedHangzhouTransitCenterNextStopHangzhouYuhangDistributionCenter: "Departed Hangzhou Transit Center; next stop: Hangzhou Yuhang Distribution Center",
    arrivedAtHangzhouTransitCenter: "Arrived at Hangzhou Transit Center",
    itemLeftTheWarehouseAndIsAwaitingCarrierPickup: "Item left the warehouse and is awaiting carrier pickup",
    orderSubmittedAwaitingPaymentConfirmation: "Order submitted; awaiting payment confirmation",
    hansoundAirActiveNoiseCancelingEarbuds: "HanSound Air Active Noise-Canceling Earbuds",
    obsidianBlack: "Obsidian black",
    noiseCancelingPro: "Noise Canceling Pro",
    hanfieldInsulatedSportsBottle: "HanField Insulated Sports Bottle",
    mintGreen: "Mint green",
    naLi1592030: "Na Li 159****2030",
    text2BoyunRoadZhangjiangHiTechParkPudongShanghai: "2 Boyun Road, Zhangjiang Hi-Tech Park, Pudong, Shanghai",
    paymentReceivedTheSellerIsPreparingYourOrder: "Payment received; the seller is preparing your order",
    orderSubmitted: "Order submitted",
    hanlabNiacinamideRepairSerum: "HanLab Niacinamide Repair Serum",
    text30MlStandard: "30 ml standard",
    buyOneGetOneGiftSet: "Buy-one-get-one gift set",
    fangWang1375521: "Fang Wang 137****5521",
    gaoxinSouth1stRoadNanshanDistrictShenzhenGuangdong: "Gaoxin South 1st Road, Nanshan District, Shenzhen, Guangdong",
    deliveredAndSignedForByRecipientWeLookForwardToYourReview: "Delivered and signed for by recipient. We look forward to your review.",
    outForDeliveryFromShenzhenNanshanDeliveryCenter: "Out for delivery from Shenzhen Nanshan Delivery Center",
    arrivedAtShenzhenTransitCenter: "Arrived at Shenzhen Transit Center",
    itemLeftTheWarehouse: "Item left the warehouse",
    hanwear3In1WeatherproofJacket: "HanWear 3-in-1 Weatherproof Jacket",
    armyGreen: "Army green",
    qiangZhao1889012: "Qiang Zhao 188****9012",
    wangjingSohoT1ChaoyangDistrictBeijing: "Wangjing SOHO T1, Chaoyang District, Beijing",
    orderSubmittedCompletePaymentWithin30Minutes: "Order submitted. Complete payment within 30 minutes.",
    hanlabVelvetMatteLipstick: "HanLab Velvet Matte Lipstick",
    mapleBrown: "Maple brown",
    standardSize: "Standard size",
    liSun1357788: "Li Sun 135****7788",
    text100NorthZhongshanRoadGulouDistrictNanjingJiangsu: "100 North Zhongshan Road, Gulou District, Nanjing, Jiangsu",
    refundRequestedAwaitingSellerReview: "Refund requested; awaiting seller review",
    delivered: "Delivered",
    awaitingPayment: "Awaiting payment",
    preparingShipment: "Preparing shipment",
    inTransit: "In transit",
    completed: "Completed",
    refundInProgress: "Refund in progress",
    closed: "Closed",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = { key: "demo-shop--data-orders", content: t(content) };
export default dictionary;
