import { HUE, productArt } from "./art";
import { categoryByKey } from "./categories";
import type { CategoryKey, Product } from "./types";

// 商品目录 mock。覆盖 6 大品类、多 SKU、现价/原价/评分/销量/库存。图片程序化生成。

const C = (n: string, h: string) => ({ name: n, hex: h });

export const products: Product[] = [
  // —— 数码 3C ——
  {
    id: "p-hs-air",
    name: "瀚声 Air 主动降噪耳机",
    category: "digital",
    subCategory: "影音耳机",
    brand: "瀚声 HanSound",
    price: 899,
    originalPrice: 1299,
    rating: 4.8,
    reviewCount: 2143,
    sales: 8600,
    stock: 124,
    colors: [C("曜石黑", "#1f2937"), C("云母白", "#f3f4f6"), C("雾霾蓝", "#93c5fd")],
    sizes: ["标准版", "降噪 Pro 版"],
    tags: ["主动降噪", "42h 续航", "无线充电"],
    tagline: "深度降噪 42dB · 双设备无缝切换",
    highlights: [
      "自适应主动降噪，深度可达 42dB，地铁/机舱通勤更安静",
      "单次 10 小时 + 充电盒共 42 小时续航，快充 10 分钟续航 4 小时",
      "支持双设备同时连接，手机来电与电脑会议自动切换",
    ],
    flashSale: true,
    isNew: true,
  },
  {
    id: "p-hb-x9",
    name: "瀚本 X9 轻薄笔记本",
    category: "digital",
    subCategory: "电脑办公",
    brand: "瀚本 HanBook",
    price: 5499,
    originalPrice: 6299,
    rating: 4.7,
    reviewCount: 1320,
    sales: 3200,
    stock: 58,
    colors: [C("深空灰", "#4b5563"), C("银河银", "#d1d5db")],
    sizes: ["16G+512G", "32G+1T"],
    tags: ["2.8K 屏", "1.1kg", "Evo 认证"],
    tagline: "1.1kg 全金属机身 · 2.8K 120Hz 触控屏",
    highlights: [
      "2.8K 120Hz 低蓝光护眼屏，100% sRGB 出厂校色",
      "1.1kg 航空铝合金机身，整机厚度 14.9mm",
      "70Wh 大电池本地视频续航 15 小时",
    ],
    isNew: true,
  },
  {
    id: "p-hw-fit",
    name: "瀚腕 Fit 运动手表",
    category: "digital",
    subCategory: "智能穿戴",
    brand: "瀚腕 HanWatch",
    price: 1099,
    originalPrice: 1399,
    rating: 4.6,
    reviewCount: 980,
    sales: 5400,
    stock: 210,
    colors: [C("熔岩橙", "#fb923c"), C("石墨黑", "#374151"), C("月光银", "#e5e7eb")],
    sizes: ["46mm", "42mm"],
    tags: ["双频 GPS", "血氧监测", "14 天续航"],
    tagline: "双频 GPS 精准定位 · 100+ 运动模式",
    highlights: ["双频五星 GPS，越野跑轨迹更精准", "全天血氧 + 心率 + 睡眠监测", "典型场景 14 天超长续航"],
    flashSale: true,
  },
  {
    id: "p-hp-pro",
    name: "瀚拍 Pro 影像旗舰手机",
    category: "digital",
    subCategory: "手机通讯",
    brand: "瀚拍 HanPhone",
    price: 4299,
    originalPrice: 4999,
    rating: 4.9,
    reviewCount: 5210,
    sales: 12000,
    stock: 33,
    colors: [C("远峰蓝", "#3b82f6"), C("暗夜黑", "#111827"), C("晨曦金", "#fcd34d")],
    sizes: ["12G+256G", "16G+512G", "16G+1T"],
    tags: ["1 英寸主摄", "潜望长焦", "钛金属"],
    tagline: "1 英寸大底主摄 · 5 倍潜望长焦",
    highlights: ["1 英寸大底主摄 + 5 倍潜望长焦三摄系统", "钛金属中框 + 第二代昆仑玻璃", "5400mAh 电池 + 100W 快充"],
    isNew: true,
  },
  // —— 家居生活 ——
  {
    id: "p-hl-pot",
    name: "瀚庐 自动炒菜料理机",
    category: "home",
    subCategory: "厨房料理",
    brand: "瀚庐 HanHome",
    price: 1599,
    originalPrice: 2199,
    rating: 4.5,
    reviewCount: 760,
    sales: 2100,
    stock: 88,
    colors: [C("奶油白", "#faf7f0"), C("复古绿", "#6b8e6b")],
    sizes: ["3L 单人", "5L 家庭"],
    tags: ["翻炒不糊", "200+ 菜谱", "自清洁"],
    tagline: "智能翻炒不糊锅 · 内置 200+ 云菜谱",
    highlights: ["行星式翻炒结构，受热均匀不糊锅", "App 内置 200+ 名厨菜谱一键烹饪", "不粘内胆可拆洗 + 自动清洁程序"],
    flashSale: true,
  },
  {
    id: "p-hl-lamp",
    name: "瀚庐 护眼立式落地灯",
    category: "home",
    subCategory: "灯具照明",
    brand: "瀚庐 HanHome",
    price: 599,
    originalPrice: 899,
    rating: 4.7,
    reviewCount: 1540,
    sales: 4300,
    stock: 156,
    colors: [C("原木色", "#c8a878"), C("磨砂黑", "#27272a")],
    sizes: ["标准款", "Pro 调光款"],
    tags: ["国 AA 级", "无频闪", "自然光谱"],
    tagline: "国 AA 级照度 · 类自然光全光谱",
    highlights: ["国家 AA 级读写照度，大范围均匀照明", "全光谱接近自然光，显色 Ra95+", "无可视频闪，长时间阅读更护眼"],
  },
  {
    id: "p-hl-quilt",
    name: "瀚庐 A 类抗菌四季被",
    category: "home",
    subCategory: "床品布艺",
    brand: "瀚庐 HanHome",
    price: 329,
    originalPrice: 559,
    rating: 4.6,
    reviewCount: 2200,
    sales: 6700,
    stock: 320,
    colors: [C("豆沙粉", "#e8b4b8"), C("雾蓝", "#a5b4cb"), C("米白", "#f5f1e8")],
    sizes: ["1.5m", "1.8m", "2.0m"],
    tags: ["A 类母婴", "抗菌防螨", "可机洗"],
    tagline: "A 类母婴级面料 · 抗菌防螨可机洗",
    highlights: ["A 类母婴级安全标准，宝宝可贴身", "银离子抗菌防螨，敏感肌友好", "子母扣组合，一被四季用"],
  },
  // —— 美妆个护 ——
  {
    id: "p-hy-serum",
    name: "瀚研 烟酰胺修护精华",
    category: "beauty",
    subCategory: "护肤",
    brand: "瀚研 HanLab",
    price: 268,
    originalPrice: 398,
    rating: 4.8,
    reviewCount: 8900,
    sales: 23000,
    stock: 540,
    colors: [C("30ml 标准", "#f9a8d4"), C("50ml 大瓶", "#ec4899")],
    sizes: ["单瓶", "买一送一礼盒"],
    tags: ["提亮", "5% 烟酰胺", "敏肌可用"],
    tagline: "5% 黄金浓度烟酰胺 · 提亮修护双效",
    highlights: ["5% 烟酰胺黄金浓度，温和不刺激", "复配神经酰胺强韧屏障", "28 天肤色提亮可见"],
    flashSale: true,
  },
  {
    id: "p-hy-lip",
    name: "瀚研 丝绒雾面口红",
    category: "beauty",
    subCategory: "彩妆",
    brand: "瀚研 HanLab",
    price: 159,
    originalPrice: 219,
    rating: 4.5,
    reviewCount: 4100,
    sales: 11000,
    stock: 0,
    colors: [C("枫叶棕", "#9a3b2e"), C("玫调豆沙", "#b56576"), C("正橘", "#e8633a"), C("浆果红", "#7f1d3a")],
    sizes: ["标准装"],
    tags: ["丝绒雾面", "持久不沾杯", "显白"],
    tagline: "丝绒雾面质地 · 持妆 8 小时不沾杯",
    highlights: ["丝绒雾面一抹显色，不拔干", "持妆 8 小时，喝水吃饭不沾杯", "4 色全显白，黄黑皮友好"],
  },
  // —— 运动户外 ——
  {
    id: "p-ho-tent",
    name: "瀚野 速开露营帐篷",
    category: "outdoor",
    subCategory: "露营徒步",
    brand: "瀚野 HanField",
    price: 459,
    originalPrice: 699,
    rating: 4.6,
    reviewCount: 1300,
    sales: 3900,
    stock: 72,
    colors: [C("沙漠卡其", "#c2a878"), C("森林绿", "#4a6741")],
    sizes: ["3-4 人", "5-6 人"],
    tags: ["秒开秒收", "防泼水", "防紫外线"],
    tagline: "10 秒速开 · UPF50+ 防晒涂层",
    highlights: ["液压秒开结构，10 秒搭建", "银胶 UPF50+ 防晒涂层", "防泼水面料 + 全网纱透气"],
    flashSale: true,
  },
  {
    id: "p-ho-shoe",
    name: "瀚野 全地形越野跑鞋",
    category: "outdoor",
    subCategory: "运动鞋",
    brand: "瀚野 HanField",
    price: 539,
    originalPrice: 799,
    rating: 4.7,
    reviewCount: 2600,
    sales: 7200,
    stock: 198,
    colors: [C("火山红", "#dc2626"), C("碳灰", "#52525b"), C("荧光黄", "#d9f99d")],
    sizes: ["39", "40", "41", "42", "43", "44"],
    tags: ["防滑大底", "回弹中底", "包裹支撑"],
    tagline: "5mm 深齿防滑 · 高回弹缓震中底",
    highlights: ["5mm 深齿橡胶大底，泥地碎石不打滑", "超临界发泡中底高回弹缓震", "TPU 支撑片包裹，长距离稳定"],
    isNew: true,
  },
  {
    id: "p-ho-bottle",
    name: "瀚野 保温运动水壶",
    category: "outdoor",
    subCategory: "健身训练",
    brand: "瀚野 HanField",
    price: 119,
    originalPrice: 189,
    rating: 4.8,
    reviewCount: 5600,
    sales: 18000,
    stock: 430,
    colors: [C("薄荷绿", "#6ee7b7"), C("樱花粉", "#fbcfe8"), C("星空黑", "#1e293b"), C("天际蓝", "#7dd3fc")],
    sizes: ["600ml", "900ml"],
    tags: ["24h 保温", "一键弹盖", "316 内胆"],
    tagline: "316 不锈钢内胆 · 24 小时长效保温",
    highlights: ["食品级 316 不锈钢内胆", "24h 保温 / 12h 保冷", "一键弹盖单手开合"],
  },
  // —— 食品生鲜 ——
  {
    id: "p-hw-nuts",
    name: "瀚味 每日坚果礼盒",
    category: "grocery",
    subCategory: "休闲零食",
    brand: "瀚味 HanTaste",
    price: 89,
    originalPrice: 139,
    rating: 4.7,
    reviewCount: 12000,
    sales: 34000,
    stock: 880,
    colors: [C("30 包装", "#a3a3a3"), C("礼盒装", "#facc15")],
    sizes: ["750g", "1050g"],
    tags: ["每日独立装", "无添加", "新货"],
    tagline: "7 种坚果每日独立装 · 当季新货",
    highlights: ["7 种坚果果干科学配比", "氮气锁鲜独立小包装", "0 香精 0 防腐当季新货"],
    flashSale: true,
  },
  {
    id: "p-hw-coffee",
    name: "瀚味 精品挂耳咖啡",
    category: "grocery",
    subCategory: "酒水饮料",
    brand: "瀚味 HanTaste",
    price: 69,
    originalPrice: 99,
    rating: 4.6,
    reviewCount: 6800,
    sales: 21000,
    stock: 560,
    colors: [C("均衡拼配", "#92400e"), C("花果日晒", "#b45309")],
    sizes: ["10 片装", "30 片装"],
    tags: ["新鲜烘焙", "SCA 80+", "挂耳便携"],
    tagline: "SCA 80+ 精品豆 · 接单新鲜烘焙",
    highlights: ["SCA 杯测 80+ 精品咖啡豆", "接单新鲜烘焙锁香", "黄金研磨度挂耳便携"],
  },
  // —— 服饰箱包 ——
  {
    id: "p-ha-jacket",
    name: "瀚衣 三防冲锋衣",
    category: "apparel",
    subCategory: "男装",
    brand: "瀚衣 HanWear",
    price: 699,
    originalPrice: 1099,
    rating: 4.7,
    reviewCount: 3400,
    sales: 9100,
    stock: 145,
    colors: [C("军绿", "#556b2f"), C("炭黑", "#1c1917"), C("航海蓝", "#1e3a5f")],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["防水防风", "可拆内胆", "三合一"],
    tagline: "万级防水透湿 · 三合一可拆内胆",
    highlights: ["10000mm 防水 + 8000g 透湿", "可拆抓绒内胆三合一", "立体剪裁不臃肿"],
    flashSale: true,
  },
  {
    id: "p-ha-bag",
    name: "瀚衣 通勤双肩背包",
    category: "apparel",
    subCategory: "箱包",
    brand: "瀚衣 HanWear",
    price: 359,
    originalPrice: 559,
    rating: 4.8,
    reviewCount: 4700,
    sales: 13000,
    stock: 260,
    colors: [C("商务黑", "#18181b"), C("燕麦灰", "#a8a29e"), C("墨绿", "#14532d")],
    sizes: ["18L 通勤", "25L 扩容"],
    tags: ["防泼水", "USB 充电", "护脊背板"],
    tagline: "护脊减负背板 · 16 寸笔记本仓",
    highlights: ["人体工学护脊减负背板", "独立 16 寸笔记本防震仓", "防泼水面料 + USB 充电口"],
    isNew: true,
  },
];

export const productById = Object.fromEntries(products.map((p) => [p.id, p]));

/** 商品主图（列表/卡片用第 0 变体）。 */
export function productImage(p: Product, variant = 0, w = 600, h = 600): string {
  const hue = categoryByKey[p.category]?.hue ?? HUE[p.category] ?? 210;
  return productArt({ name: p.name, hue, w, h, variant, label: p.brand });
}

/** 商品详情图廊（4 张变体）。 */
export function productGallery(p: Product, w = 600, h = 600): string[] {
  return [0, 1, 2, 3].map((v) => productImage(p, v, w, h));
}

export const formatPrice = (n: number) => `¥${n.toLocaleString("zh-CN")}`;
