import { copy } from "./products.content";
import { HUE, productArt } from "./art";
import { categoryByKey } from "./categories";
import type { CategoryKey, Product } from "./types";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

// 商品目录 mock。覆盖 6 大品类、多 SKU、现价/原价/评分/销量/库存。图片程序化生成。

const C = (n: string, h: string) => ({ name: n, hex: h });

export const products: Product[] = [
  // —— 数码 3C ——
  {
    id: "p-hs-air",
    name: copy("hansoundAirActiveNoiseCancelingEarbuds"),
    category: "digital",
    subCategory: copy("audioHeadphones"),
    brand: copy("hansound"),
    price: 899,
    originalPrice: 1299,
    rating: 4.8,
    reviewCount: 2143,
    sales: 8600,
    stock: 124,
    colors: [C(copy("obsidianBlack"), "#1f2937"), C(copy("micaWhite"), "#f3f4f6"), C(copy("hazeBlue"), "#93c5fd")],
    sizes: [copy("standard"), copy("noiseCancelingPro")],
    tags: [copy("activeNoiseCanceling"), copy("text42HourBattery"), copy("wirelessCharging")],
    tagline: copy("text42DbDeepNoiseReductionSeamlessTwoDeviceSwitching"),
    highlights: [
      copy("adaptiveActiveNoiseCancelingCutsUpTo42DbForQuieterTrainsAndFlights"),
      copy("upTo10HoursPerChargeAnd42HoursWithTheCaseA10MinuteChargeAdds4Hours"),
      copy("connectTwoDevicesAtOnceAndSwitchAutomaticallyBetweenPhoneCallsAndComputerMeetings"),
    ],
    flashSale: true,
    isNew: true,
  },
  {
    id: "p-hb-x9",
    name: copy("hanbookX9UltralightLaptop"),
    category: "digital",
    subCategory: copy("computersOffice"),
    brand: copy("hanbook"),
    price: 5499,
    originalPrice: 6299,
    rating: 4.7,
    reviewCount: 1320,
    sales: 3200,
    stock: 58,
    colors: [C(copy("spaceGray"), "#4b5563"), C(copy("galaxySilver"), "#d1d5db")],
    sizes: ["16G+512G", "32G+1T"],
    tags: [copy("text28kDisplay"), "1.1kg", copy("evoCertified")],
    tagline: copy("text11KgAllMetalBody28k120HzTouchscreen"),
    highlights: [
      copy("factoryCalibrated28k120HzLowBlueLightDisplayWith100SrgbCoverage"),
      copy("aerospaceGradeAluminumBodyWeighing11KgAndMeasuring149MmThin"),
      copy("text70WhBatteryDeliversUpTo15HoursOfLocalVideoPlayback"),
    ],
    isNew: true,
  },
  {
    id: "p-hw-fit",
    name: copy("hanwatchFitSportsWatch"),
    category: "digital",
    subCategory: copy("wearables"),
    brand: copy("hanwatch"),
    price: 1099,
    originalPrice: 1399,
    rating: 4.6,
    reviewCount: 980,
    sales: 5400,
    stock: 210,
    colors: [C(copy("lavaOrange"), "#fb923c"), C(copy("graphiteBlack"), "#374151"), C(copy("moonlightSilver"), "#e5e7eb")],
    sizes: ["46mm", "42mm"],
    tags: [copy("dualBandGps"), copy("bloodOxygenTracking"), copy("text14DayBattery")],
    tagline: copy("precisionDualBandGps100WorkoutModes"),
    highlights: [copy("dualBandFiveSystemGpsRecordsTrailRunsWithGreaterPrecision"), copy("allDayBloodOxygenHeartRateAndSleepTracking"), copy("upTo14DaysOfBatteryLifeWithTypicalUse")],
    flashSale: true,
  },
  {
    id: "p-hp-pro",
    name: copy("hanphoneProFlagshipCameraPhone"),
    category: "digital",
    subCategory: copy("phonesMobile"),
    brand: copy("hanphone"),
    price: 4299,
    originalPrice: 4999,
    rating: 4.9,
    reviewCount: 5210,
    sales: 12000,
    stock: 33,
    colors: [C(copy("alpineBlue"), "#3b82f6"), C(copy("midnightBlack"), "#111827"), C(copy("dawnGold"), "#fcd34d")],
    sizes: ["12G+256G", "16G+512G", "16G+1T"],
    tags: [copy("text1InchMainCamera"), copy("periscopeTelephoto"), copy("titanium")],
    tagline: copy("text1InchMainSensor5PeriscopeTelephoto"),
    highlights: [copy("tripleCameraSystemWithA1InchMainSensorAnd5PeriscopeTelephoto"), copy("titaniumFrameAndSecondGenerationKunlunGlass"), copy("text5400MahBatteryWith100WFastCharging")],
    isNew: true,
  },
  // —— 家居生活 ——
  {
    id: "p-hl-pot",
    name: copy("hanhomeAutomaticCookingMachine"),
    category: "home",
    subCategory: copy("kitchenAppliances"),
    brand: copy("hanhome"),
    price: 1599,
    originalPrice: 2199,
    rating: 4.5,
    reviewCount: 760,
    sales: 2100,
    stock: 88,
    colors: [C(copy("creamWhite"), "#faf7f0"), C(copy("vintageGreen"), "#6b8e6b")],
    sizes: [copy("text3LSingleServing"), copy("text5LFamilySize")],
    tags: [copy("evenStirFrying"), copy("text200Recipes"), copy("selfCleaning")],
    tagline: copy("smartEvenStirFrying200CloudRecipesBuiltIn"),
    highlights: [copy("planetaryStirringDistributesHeatEvenlyToPreventScorching"), copy("cook200ChefCreatedRecipesFromTheAppWithOneTap"), copy("removableNonstickBowlPlusAnAutomaticCleaningCycle")],
    flashSale: true,
  },
  {
    id: "p-hl-lamp",
    name: copy("hanhomeEyeCareFloorLamp"),
    category: "home",
    subCategory: copy("lighting"),
    brand: copy("hanhome"),
    price: 599,
    originalPrice: 899,
    rating: 4.7,
    reviewCount: 1540,
    sales: 4300,
    stock: 156,
    colors: [C(copy("naturalWood"), "#c8a878"), C(copy("matteBlack"), "#27272a")],
    sizes: [copy("standardLamp"), copy("proDimmable")],
    tags: [copy("chinaAaRated"), copy("flickerFree"), copy("naturalSpectrum")],
    tagline: copy("chinaAaIlluminanceFullSpectrumNaturalLight"),
    highlights: [copy("chinaAaReadingIlluminanceProvidesWideEvenCoverage"), copy("naturalFullSpectrumLightWithRa95ColorRendering"), copy("noVisibleFlickerForGreaterComfortDuringLongReadingSessions")],
  },
  {
    id: "p-hl-quilt",
    name: copy("hanhomeClassAAntibacterialAllSeasonQuilt"),
    category: "home",
    subCategory: copy("beddingTextiles"),
    brand: copy("hanhome"),
    price: 329,
    originalPrice: 559,
    rating: 4.6,
    reviewCount: 2200,
    sales: 6700,
    stock: 320,
    colors: [C(copy("dustyRose"), "#e8b4b8"), C(copy("mistBlue"), "#a5b4cb"), C(copy("ivory"), "#f5f1e8")],
    sizes: ["1.5m", "1.8m", "2.0m"],
    tags: [copy("classABabySafe"), copy("antibacterialMiteResistant"), copy("machineWashable")],
    tagline: copy("classABabySafeFabricAntibacterialMiteResistantAndMachineWashable"),
    highlights: [copy("classABabySafeFabricIsSuitableForDirectContactWithDelicateSkin"), copy("silverIonProtectionResistsBacteriaAndMitesAndIsGentleOnSensitiveSkin"), copy("snapTogetherLayersAdaptOneQuiltForEverySeason")],
  },
  // —— 美妆个护 ——
  {
    id: "p-hy-serum",
    name: copy("hanlabNiacinamideRepairSerum"),
    category: "beauty",
    subCategory: copy("skinCare"),
    brand: copy("hanlab"),
    price: 268,
    originalPrice: 398,
    rating: 4.8,
    reviewCount: 8900,
    sales: 23000,
    stock: 540,
    colors: [C(copy("text30MlStandard"), "#f9a8d4"), C(copy("text50MlLarge"), "#ec4899")],
    sizes: [copy("singleBottle"), copy("buyOneGetOneGiftSet")],
    tags: [copy("brightening"), copy("text5Niacinamide"), copy("sensitiveSkinFriendly")],
    tagline: copy("text5NiacinamideBrightensAndRepairs"),
    highlights: [copy("aGentleEffective5NiacinamideConcentration"), copy("ceramidesHelpStrengthenTheSkinBarrier"), copy("visibleBrighteningIn28Days")],
    flashSale: true,
  },
  {
    id: "p-hy-lip",
    name: copy("hanlabVelvetMatteLipstick"),
    category: "beauty",
    subCategory: copy("makeup"),
    brand: copy("hanlab"),
    price: 159,
    originalPrice: 219,
    rating: 4.5,
    reviewCount: 4100,
    sales: 11000,
    stock: 0,
    colors: [C(copy("mapleBrown"), "#9a3b2e"), C(copy("rosewood"), "#b56576"), C(copy("trueOrange"), "#e8633a"), C(copy("berryRed"), "#7f1d3a")],
    sizes: [copy("standardSize")],
    tags: [copy("velvetMatte"), copy("longLastingTransferResistance"), copy("complexionEnhancing")],
    tagline: copy("velvetMatteFinishUpTo8HoursOfTransferResistantWear"),
    highlights: [copy("richVelvetMatteColorInOneSwipeWithoutDryingLips"), copy("upTo8HoursOfWearWithMinimalTransferWhileEatingAndDrinking"), copy("fourComplexionFlatteringShadesDesignedForWarmAndDeepSkinTones")],
  },
  // —— 运动户外 ——
  {
    id: "p-ho-tent",
    name: copy("hanfieldInstantCampingTent"),
    category: "outdoor",
    subCategory: copy("campingHiking"),
    brand: copy("hanfield"),
    price: 459,
    originalPrice: 699,
    rating: 4.6,
    reviewCount: 1300,
    sales: 3900,
    stock: 72,
    colors: [C(copy("desertKhaki"), "#c2a878"), C(copy("forestGreen"), "#4a6741")],
    sizes: [copy("text34People"), copy("text56People")],
    tags: [copy("instantSetup"), copy("waterResistant"), copy("uvProtection")],
    tagline: copy("text10SecondSetupUpf50SunProtection"),
    highlights: [copy("hydraulicFrameSetsUpIn10Seconds"), copy("silverCoatedUpf50SunProtection"), copy("waterResistantFabricWithFullMeshVentilation")],
    flashSale: true,
  },
  {
    id: "p-ho-shoe",
    name: copy("hanfieldAllTerrainTrailRunningShoes"),
    category: "outdoor",
    subCategory: copy("athleticShoes"),
    brand: copy("hanfield"),
    price: 539,
    originalPrice: 799,
    rating: 4.7,
    reviewCount: 2600,
    sales: 7200,
    stock: 198,
    colors: [C(copy("volcanicRed"), "#dc2626"), C(copy("carbonGray"), "#52525b"), C(copy("neonYellow"), "#d9f99d")],
    sizes: ["39", "40", "41", "42", "43", "44"],
    tags: [copy("highGripOutsole"), copy("responsiveMidsole"), copy("secureSupport")],
    tagline: copy("text5MmTrailLugsResponsiveCushionedMidsole"),
    highlights: [copy("text5MmRubberLugsGripMudAndLooseRock"), copy("supercriticalFoamMidsoleDeliversResponsiveCushioning"), copy("tpuSupportPlateAddsStabilityOverLongDistances")],
    isNew: true,
  },
  {
    id: "p-ho-bottle",
    name: copy("hanfieldInsulatedSportsBottle"),
    category: "outdoor",
    subCategory: copy("fitness"),
    brand: copy("hanfield"),
    price: 119,
    originalPrice: 189,
    rating: 4.8,
    reviewCount: 5600,
    sales: 18000,
    stock: 430,
    colors: [C(copy("mintGreen"), "#6ee7b7"), C(copy("cherryBlossomPink"), "#fbcfe8"), C(copy("nightSkyBlack"), "#1e293b"), C(copy("skyBlue"), "#7dd3fc")],
    sizes: ["600ml", "900ml"],
    tags: [copy("text24HourHeatRetention"), copy("oneTouchLid"), copy("text316StainlessInterior")],
    tagline: copy("text316StainlessSteelInteriorKeepsDrinksHotFor24Hours"),
    highlights: [copy("foodGrade316StainlessSteelInterior"), copy("keepsDrinksHotFor24HoursOrColdFor12"), copy("oneTouchLidOpensAndClosesWithOneHand")],
  },
  // —— 食品生鲜 ——
  {
    id: "p-hw-nuts",
    name: copy("hantasteDailyNutGiftBox"),
    category: "grocery",
    subCategory: copy("snacks"),
    brand: copy("hantaste"),
    price: 89,
    originalPrice: 139,
    rating: 4.7,
    reviewCount: 12000,
    sales: 34000,
    stock: 880,
    colors: [C(copy("text30Packs"), "#a3a3a3"), C(copy("giftBox"), "#facc15")],
    sizes: ["750g", "1050g"],
    tags: [copy("dailyPacks"), copy("noAdditives"), copy("freshHarvest")],
    tagline: copy("sevenNutDailyPacksFreshSeasonalHarvest"),
    highlights: [copy("balancedBlendOfSevenNutsAndDriedFruits"), copy("nitrogenFlushedIndividualPacksPreserveFreshness"), copy("freshSeasonalIngredientsWithNoFlavoringOrPreservatives")],
    flashSale: true,
  },
  {
    id: "p-hw-coffee",
    name: copy("hantasteSpecialtyDripCoffee"),
    category: "grocery",
    subCategory: copy("drinks"),
    brand: copy("hantaste"),
    price: 69,
    originalPrice: 99,
    rating: 4.6,
    reviewCount: 6800,
    sales: 21000,
    stock: 560,
    colors: [C(copy("balancedBlend"), "#92400e"), C(copy("naturalFloralFruit"), "#b45309")],
    sizes: [copy("text10Bags"), copy("text30Bags")],
    tags: [copy("freshlyRoasted"), "SCA 80+", copy("portableDripBags")],
    tagline: copy("sca80SpecialtyBeansRoastedFreshToOrder"),
    highlights: [copy("specialtyCoffeeBeansScoring80OnTheScaScale"), copy("roastedFreshToOrderToPreserveAroma"), copy("optimizedGrindInConvenientSingleServeDripBags")],
  },
  // —— 服饰箱包 ——
  {
    id: "p-ha-jacket",
    name: copy("hanwear3In1WeatherproofJacket"),
    category: "apparel",
    subCategory: copy("menSClothing"),
    brand: copy("hanwear"),
    price: 699,
    originalPrice: 1099,
    rating: 4.7,
    reviewCount: 3400,
    sales: 9100,
    stock: 145,
    colors: [C(copy("armyGreen"), "#556b2f"), C(copy("charcoalBlack"), "#1c1917"), C(copy("nauticalBlue"), "#1e3a5f")],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: [copy("waterproofWindproof"), copy("removableLiner"), copy("text3In1")],
    tagline: copy("text10000MmWaterproofingRemovable3In1Liner"),
    highlights: [copy("text10000MmWaterproofRatingAnd8000GBreathability"), copy("removableFleeceLinerForThreeSeasonVersatility"), copy("contouredCutForWarmthWithoutBulk")],
    flashSale: true,
  },
  {
    id: "p-ha-bag",
    name: copy("hanwearCommuterBackpack"),
    category: "apparel",
    subCategory: copy("bags"),
    brand: copy("hanwear"),
    price: 359,
    originalPrice: 559,
    rating: 4.8,
    reviewCount: 4700,
    sales: 13000,
    stock: 260,
    colors: [C(copy("businessBlack"), "#18181b"), C(copy("oatGray"), "#a8a29e"), C(copy("deepGreen"), "#14532d")],
    sizes: [copy("text18LCommuter"), copy("text25LExpandable")],
    tags: [copy("waterResistant"), copy("usbCharging"), copy("ergonomicBackPanel")],
    tagline: copy("supportiveBackPanel16InchLaptopCompartment"),
    highlights: [copy("ergonomicBackPanelDistributesWeightComfortably"), copy("dedicatedPaddedCompartmentForA16InchLaptop"), copy("waterResistantFabricAndAnIntegratedUsbChargingPort")],
    isNew: true,
  },
];

export const productById = Object.fromEntries(products.map((p) => [p.id, p]));

/** 商品主图（列表/卡片用第 0 变体）。 */
export function productImage(p: Product, variant = 0, w = 600, h = 600): string {
  const hue = categoryByKey[p.category]?.hue ?? HUE[p.category] ?? 210;
  return productArt({ name: p.name, hue, w, h, variant, label: p.brand });
}

/** 商品详情图廊（4 张变体）。 */
export function productGallery(p: Product, w = 600, h = 600): string[] {
  return [0, 1, 2, 3].map((v) => productImage(p, v, w, h));
}

export const formatPrice = (n: number) => `¥${n.toLocaleString("zh-CN")}`;

export const formatCompactCount = (n: number) =>
  new Intl.NumberFormat(DOCS_LOCALE === "en" ? "en" : "zh-CN", {
    notation: "compact",
    maximumFractionDigits: 1,
  }).format(n);
