import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    hansoundAirActiveNoiseCancelingEarbuds: "瀚声 Air 主动降噪耳机",
    audioHeadphones: "影音耳机",
    hansound: "瀚声 HanSound",
    obsidianBlack: "曜石黑",
    micaWhite: "云母白",
    hazeBlue: "雾霾蓝",
    standard: "标准版",
    noiseCancelingPro: "降噪 Pro 版",
    activeNoiseCanceling: "主动降噪",
    text42HourBattery: "42h 续航",
    wirelessCharging: "无线充电",
    text42DbDeepNoiseReductionSeamlessTwoDeviceSwitching: "深度降噪 42dB · 双设备无缝切换",
    adaptiveActiveNoiseCancelingCutsUpTo42DbForQuieterTrainsAndFlights: "自适应主动降噪，深度可达 42dB，地铁/机舱通勤更安静",
    upTo10HoursPerChargeAnd42HoursWithTheCaseA10MinuteChargeAdds4Hours: "单次 10 小时 + 充电盒共 42 小时续航，快充 10 分钟续航 4 小时",
    connectTwoDevicesAtOnceAndSwitchAutomaticallyBetweenPhoneCallsAndComputerMeetings: "支持双设备同时连接，手机来电与电脑会议自动切换",
    hanbookX9UltralightLaptop: "瀚本 X9 轻薄笔记本",
    computersOffice: "电脑办公",
    hanbook: "瀚本 HanBook",
    spaceGray: "深空灰",
    galaxySilver: "银河银",
    text28kDisplay: "2.8K 屏",
    evoCertified: "Evo 认证",
    text11KgAllMetalBody28k120HzTouchscreen: "1.1kg 全金属机身 · 2.8K 120Hz 触控屏",
    factoryCalibrated28k120HzLowBlueLightDisplayWith100SrgbCoverage: "2.8K 120Hz 低蓝光护眼屏，100% sRGB 出厂校色",
    aerospaceGradeAluminumBodyWeighing11KgAndMeasuring149MmThin: "1.1kg 航空铝合金机身，整机厚度 14.9mm",
    text70WhBatteryDeliversUpTo15HoursOfLocalVideoPlayback: "70Wh 大电池本地视频续航 15 小时",
    hanwatchFitSportsWatch: "瀚腕 Fit 运动手表",
    wearables: "智能穿戴",
    hanwatch: "瀚腕 HanWatch",
    lavaOrange: "熔岩橙",
    graphiteBlack: "石墨黑",
    moonlightSilver: "月光银",
    dualBandGps: "双频 GPS",
    bloodOxygenTracking: "血氧监测",
    text14DayBattery: "14 天续航",
    precisionDualBandGps100WorkoutModes: "双频 GPS 精准定位 · 100+ 运动模式",
    dualBandFiveSystemGpsRecordsTrailRunsWithGreaterPrecision: "双频五星 GPS，越野跑轨迹更精准",
    allDayBloodOxygenHeartRateAndSleepTracking: "全天血氧 + 心率 + 睡眠监测",
    upTo14DaysOfBatteryLifeWithTypicalUse: "典型场景 14 天超长续航",
    hanphoneProFlagshipCameraPhone: "瀚拍 Pro 影像旗舰手机",
    phonesMobile: "手机通讯",
    hanphone: "瀚拍 HanPhone",
    alpineBlue: "远峰蓝",
    midnightBlack: "暗夜黑",
    dawnGold: "晨曦金",
    text1InchMainCamera: "1 英寸主摄",
    periscopeTelephoto: "潜望长焦",
    titanium: "钛金属",
    text1InchMainSensor5PeriscopeTelephoto: "1 英寸大底主摄 · 5 倍潜望长焦",
    tripleCameraSystemWithA1InchMainSensorAnd5PeriscopeTelephoto: "1 英寸大底主摄 + 5 倍潜望长焦三摄系统",
    titaniumFrameAndSecondGenerationKunlunGlass: "钛金属中框 + 第二代昆仑玻璃",
    text5400MahBatteryWith100WFastCharging: "5400mAh 电池 + 100W 快充",
    hanhomeAutomaticCookingMachine: "瀚庐 自动炒菜料理机",
    kitchenAppliances: "厨房料理",
    hanhome: "瀚庐 HanHome",
    creamWhite: "奶油白",
    vintageGreen: "复古绿",
    text3LSingleServing: "3L 单人",
    text5LFamilySize: "5L 家庭",
    evenStirFrying: "翻炒不糊",
    text200Recipes: "200+ 菜谱",
    selfCleaning: "自清洁",
    smartEvenStirFrying200CloudRecipesBuiltIn: "智能翻炒不糊锅 · 内置 200+ 云菜谱",
    planetaryStirringDistributesHeatEvenlyToPreventScorching: "行星式翻炒结构，受热均匀不糊锅",
    cook200ChefCreatedRecipesFromTheAppWithOneTap: "App 内置 200+ 名厨菜谱一键烹饪",
    removableNonstickBowlPlusAnAutomaticCleaningCycle: "不粘内胆可拆洗 + 自动清洁程序",
    hanhomeEyeCareFloorLamp: "瀚庐 护眼立式落地灯",
    lighting: "灯具照明",
    naturalWood: "原木色",
    matteBlack: "磨砂黑",
    standardLamp: "标准款",
    proDimmable: "Pro 调光款",
    chinaAaRated: "国 AA 级",
    flickerFree: "无频闪",
    naturalSpectrum: "自然光谱",
    chinaAaIlluminanceFullSpectrumNaturalLight: "国 AA 级照度 · 类自然光全光谱",
    chinaAaReadingIlluminanceProvidesWideEvenCoverage: "国家 AA 级读写照度，大范围均匀照明",
    naturalFullSpectrumLightWithRa95ColorRendering: "全光谱接近自然光，显色 Ra95+",
    noVisibleFlickerForGreaterComfortDuringLongReadingSessions: "无可视频闪，长时间阅读更护眼",
    hanhomeClassAAntibacterialAllSeasonQuilt: "瀚庐 A 类抗菌四季被",
    beddingTextiles: "床品布艺",
    dustyRose: "豆沙粉",
    mistBlue: "雾蓝",
    ivory: "米白",
    classABabySafe: "A 类母婴",
    antibacterialMiteResistant: "抗菌防螨",
    machineWashable: "可机洗",
    classABabySafeFabricAntibacterialMiteResistantAndMachineWashable: "A 类母婴级面料 · 抗菌防螨可机洗",
    classABabySafeFabricIsSuitableForDirectContactWithDelicateSkin: "A 类母婴级安全标准，宝宝可贴身",
    silverIonProtectionResistsBacteriaAndMitesAndIsGentleOnSensitiveSkin: "银离子抗菌防螨，敏感肌友好",
    snapTogetherLayersAdaptOneQuiltForEverySeason: "子母扣组合，一被四季用",
    hanlabNiacinamideRepairSerum: "瀚研 烟酰胺修护精华",
    skinCare: "护肤",
    hanlab: "瀚研 HanLab",
    text30MlStandard: "30ml 标准",
    text50MlLarge: "50ml 大瓶",
    singleBottle: "单瓶",
    buyOneGetOneGiftSet: "买一送一礼盒",
    brightening: "提亮",
    text5Niacinamide: "5% 烟酰胺",
    sensitiveSkinFriendly: "敏肌可用",
    text5NiacinamideBrightensAndRepairs: "5% 黄金浓度烟酰胺 · 提亮修护双效",
    aGentleEffective5NiacinamideConcentration: "5% 烟酰胺黄金浓度，温和不刺激",
    ceramidesHelpStrengthenTheSkinBarrier: "复配神经酰胺强韧屏障",
    visibleBrighteningIn28Days: "28 天肤色提亮可见",
    hanlabVelvetMatteLipstick: "瀚研 丝绒雾面口红",
    makeup: "彩妆",
    mapleBrown: "枫叶棕",
    rosewood: "玫调豆沙",
    trueOrange: "正橘",
    berryRed: "浆果红",
    standardSize: "标准装",
    velvetMatte: "丝绒雾面",
    longLastingTransferResistance: "持久不沾杯",
    complexionEnhancing: "显白",
    velvetMatteFinishUpTo8HoursOfTransferResistantWear: "丝绒雾面质地 · 持妆 8 小时不沾杯",
    richVelvetMatteColorInOneSwipeWithoutDryingLips: "丝绒雾面一抹显色，不拔干",
    upTo8HoursOfWearWithMinimalTransferWhileEatingAndDrinking: "持妆 8 小时，喝水吃饭不沾杯",
    fourComplexionFlatteringShadesDesignedForWarmAndDeepSkinTones: "4 色全显白，黄黑皮友好",
    hanfieldInstantCampingTent: "瀚野 速开露营帐篷",
    campingHiking: "露营徒步",
    hanfield: "瀚野 HanField",
    desertKhaki: "沙漠卡其",
    forestGreen: "森林绿",
    text34People: "3-4 人",
    text56People: "5-6 人",
    instantSetup: "秒开秒收",
    waterResistant: "防泼水",
    uvProtection: "防紫外线",
    text10SecondSetupUpf50SunProtection: "10 秒速开 · UPF50+ 防晒涂层",
    hydraulicFrameSetsUpIn10Seconds: "液压秒开结构，10 秒搭建",
    silverCoatedUpf50SunProtection: "银胶 UPF50+ 防晒涂层",
    waterResistantFabricWithFullMeshVentilation: "防泼水面料 + 全网纱透气",
    hanfieldAllTerrainTrailRunningShoes: "瀚野 全地形越野跑鞋",
    athleticShoes: "运动鞋",
    volcanicRed: "火山红",
    carbonGray: "碳灰",
    neonYellow: "荧光黄",
    highGripOutsole: "防滑大底",
    responsiveMidsole: "回弹中底",
    secureSupport: "包裹支撑",
    text5MmTrailLugsResponsiveCushionedMidsole: "5mm 深齿防滑 · 高回弹缓震中底",
    text5MmRubberLugsGripMudAndLooseRock: "5mm 深齿橡胶大底，泥地碎石不打滑",
    supercriticalFoamMidsoleDeliversResponsiveCushioning: "超临界发泡中底高回弹缓震",
    tpuSupportPlateAddsStabilityOverLongDistances: "TPU 支撑片包裹，长距离稳定",
    hanfieldInsulatedSportsBottle: "瀚野 保温运动水壶",
    fitness: "健身训练",
    mintGreen: "薄荷绿",
    cherryBlossomPink: "樱花粉",
    nightSkyBlack: "星空黑",
    skyBlue: "天际蓝",
    text24HourHeatRetention: "24h 保温",
    oneTouchLid: "一键弹盖",
    text316StainlessInterior: "316 内胆",
    text316StainlessSteelInteriorKeepsDrinksHotFor24Hours: "316 不锈钢内胆 · 24 小时长效保温",
    foodGrade316StainlessSteelInterior: "食品级 316 不锈钢内胆",
    keepsDrinksHotFor24HoursOrColdFor12: "24h 保温 / 12h 保冷",
    oneTouchLidOpensAndClosesWithOneHand: "一键弹盖单手开合",
    hantasteDailyNutGiftBox: "瀚味 每日坚果礼盒",
    snacks: "休闲零食",
    hantaste: "瀚味 HanTaste",
    text30Packs: "30 包装",
    giftBox: "礼盒装",
    dailyPacks: "每日独立装",
    noAdditives: "无添加",
    freshHarvest: "新货",
    sevenNutDailyPacksFreshSeasonalHarvest: "7 种坚果每日独立装 · 当季新货",
    balancedBlendOfSevenNutsAndDriedFruits: "7 种坚果果干科学配比",
    nitrogenFlushedIndividualPacksPreserveFreshness: "氮气锁鲜独立小包装",
    freshSeasonalIngredientsWithNoFlavoringOrPreservatives: "0 香精 0 防腐当季新货",
    hantasteSpecialtyDripCoffee: "瀚味 精品挂耳咖啡",
    drinks: "酒水饮料",
    balancedBlend: "均衡拼配",
    naturalFloralFruit: "花果日晒",
    text10Bags: "10 片装",
    text30Bags: "30 片装",
    freshlyRoasted: "新鲜烘焙",
    portableDripBags: "挂耳便携",
    sca80SpecialtyBeansRoastedFreshToOrder: "SCA 80+ 精品豆 · 接单新鲜烘焙",
    specialtyCoffeeBeansScoring80OnTheScaScale: "SCA 杯测 80+ 精品咖啡豆",
    roastedFreshToOrderToPreserveAroma: "接单新鲜烘焙锁香",
    optimizedGrindInConvenientSingleServeDripBags: "黄金研磨度挂耳便携",
    hanwear3In1WeatherproofJacket: "瀚衣 三防冲锋衣",
    menSClothing: "男装",
    hanwear: "瀚衣 HanWear",
    armyGreen: "军绿",
    charcoalBlack: "炭黑",
    nauticalBlue: "航海蓝",
    waterproofWindproof: "防水防风",
    removableLiner: "可拆内胆",
    text3In1: "三合一",
    text10000MmWaterproofingRemovable3In1Liner: "万级防水透湿 · 三合一可拆内胆",
    text10000MmWaterproofRatingAnd8000GBreathability: "10000mm 防水 + 8000g 透湿",
    removableFleeceLinerForThreeSeasonVersatility: "可拆抓绒内胆三合一",
    contouredCutForWarmthWithoutBulk: "立体剪裁不臃肿",
    hanwearCommuterBackpack: "瀚衣 通勤双肩背包",
    bags: "箱包",
    businessBlack: "商务黑",
    oatGray: "燕麦灰",
    deepGreen: "墨绿",
    text18LCommuter: "18L 通勤",
    text25LExpandable: "25L 扩容",
    usbCharging: "USB 充电",
    ergonomicBackPanel: "护脊背板",
    supportiveBackPanel16InchLaptopCompartment: "护脊减负背板 · 16 寸笔记本仓",
    ergonomicBackPanelDistributesWeightComfortably: "人体工学护脊减负背板",
    dedicatedPaddedCompartmentForA16InchLaptop: "独立 16 寸笔记本防震仓",
    waterResistantFabricAndAnIntegratedUsbChargingPort: "防泼水面料 + USB 充电口",
  },
  en: {
    hansoundAirActiveNoiseCancelingEarbuds: "HanSound Air Active Noise-Canceling Earbuds",
    audioHeadphones: "Audio & headphones",
    hansound: "HanSound",
    obsidianBlack: "Obsidian black",
    micaWhite: "Mica white",
    hazeBlue: "Haze blue",
    standard: "Standard",
    noiseCancelingPro: "Noise Canceling Pro",
    activeNoiseCanceling: "Active noise canceling",
    text42HourBattery: "42-hour battery",
    wirelessCharging: "Wireless charging",
    text42DbDeepNoiseReductionSeamlessTwoDeviceSwitching: "42 dB deep noise reduction · Seamless two-device switching",
    adaptiveActiveNoiseCancelingCutsUpTo42DbForQuieterTrainsAndFlights: "Adaptive active noise canceling cuts up to 42 dB for quieter trains and flights",
    upTo10HoursPerChargeAnd42HoursWithTheCaseA10MinuteChargeAdds4Hours: "Up to 10 hours per charge and 42 hours with the case; a 10-minute charge adds 4 hours",
    connectTwoDevicesAtOnceAndSwitchAutomaticallyBetweenPhoneCallsAndComputerMeetings: "Connect two devices at once and switch automatically between phone calls and computer meetings",
    hanbookX9UltralightLaptop: "HanBook X9 Ultralight Laptop",
    computersOffice: "Computers & office",
    hanbook: "HanBook",
    spaceGray: "Space gray",
    galaxySilver: "Galaxy silver",
    text28kDisplay: "2.8K display",
    evoCertified: "Evo certified",
    text11KgAllMetalBody28k120HzTouchscreen: "1.1 kg all-metal body · 2.8K 120 Hz touchscreen",
    factoryCalibrated28k120HzLowBlueLightDisplayWith100SrgbCoverage: "Factory-calibrated 2.8K 120 Hz low-blue-light display with 100% sRGB coverage",
    aerospaceGradeAluminumBodyWeighing11KgAndMeasuring149MmThin: "Aerospace-grade aluminum body weighing 1.1 kg and measuring 14.9 mm thin",
    text70WhBatteryDeliversUpTo15HoursOfLocalVideoPlayback: "70 Wh battery delivers up to 15 hours of local video playback",
    hanwatchFitSportsWatch: "HanWatch Fit Sports Watch",
    wearables: "Wearables",
    hanwatch: "HanWatch",
    lavaOrange: "Lava orange",
    graphiteBlack: "Graphite black",
    moonlightSilver: "Moonlight silver",
    dualBandGps: "Dual-band GPS",
    bloodOxygenTracking: "Blood oxygen tracking",
    text14DayBattery: "14-day battery",
    precisionDualBandGps100WorkoutModes: "Precision dual-band GPS · 100+ workout modes",
    dualBandFiveSystemGpsRecordsTrailRunsWithGreaterPrecision: "Dual-band, five-system GPS records trail runs with greater precision",
    allDayBloodOxygenHeartRateAndSleepTracking: "All-day blood oxygen, heart rate, and sleep tracking",
    upTo14DaysOfBatteryLifeWithTypicalUse: "Up to 14 days of battery life with typical use",
    hanphoneProFlagshipCameraPhone: "HanPhone Pro Flagship Camera Phone",
    phonesMobile: "Phones & mobile",
    hanphone: "HanPhone",
    alpineBlue: "Alpine blue",
    midnightBlack: "Midnight black",
    dawnGold: "Dawn gold",
    text1InchMainCamera: "1-inch main camera",
    periscopeTelephoto: "Periscope telephoto",
    titanium: "Titanium",
    text1InchMainSensor5PeriscopeTelephoto: "1-inch main sensor · 5× periscope telephoto",
    tripleCameraSystemWithA1InchMainSensorAnd5PeriscopeTelephoto: "Triple-camera system with a 1-inch main sensor and 5× periscope telephoto",
    titaniumFrameAndSecondGenerationKunlunGlass: "Titanium frame and second-generation Kunlun Glass",
    text5400MahBatteryWith100WFastCharging: "5,400 mAh battery with 100 W fast charging",
    hanhomeAutomaticCookingMachine: "HanHome Automatic Cooking Machine",
    kitchenAppliances: "Kitchen appliances",
    hanhome: "HanHome",
    creamWhite: "Cream white",
    vintageGreen: "Vintage green",
    text3LSingleServing: "3 L single-serving",
    text5LFamilySize: "5 L family size",
    evenStirFrying: "Even stir-frying",
    text200Recipes: "200+ recipes",
    selfCleaning: "Self-cleaning",
    smartEvenStirFrying200CloudRecipesBuiltIn: "Smart, even stir-frying · 200+ cloud recipes built in",
    planetaryStirringDistributesHeatEvenlyToPreventScorching: "Planetary stirring distributes heat evenly to prevent scorching",
    cook200ChefCreatedRecipesFromTheAppWithOneTap: "Cook 200+ chef-created recipes from the app with one tap",
    removableNonstickBowlPlusAnAutomaticCleaningCycle: "Removable nonstick bowl plus an automatic cleaning cycle",
    hanhomeEyeCareFloorLamp: "HanHome Eye-Care Floor Lamp",
    lighting: "Lighting",
    naturalWood: "Natural wood",
    matteBlack: "Matte black",
    standardLamp: "Standard",
    proDimmable: "Pro dimmable",
    chinaAaRated: "China AA rated",
    flickerFree: "Flicker-free",
    naturalSpectrum: "Natural spectrum",
    chinaAaIlluminanceFullSpectrumNaturalLight: "China AA illuminance · Full-spectrum natural light",
    chinaAaReadingIlluminanceProvidesWideEvenCoverage: "China AA reading illuminance provides wide, even coverage",
    naturalFullSpectrumLightWithRa95ColorRendering: "Natural full-spectrum light with Ra95+ color rendering",
    noVisibleFlickerForGreaterComfortDuringLongReadingSessions: "No visible flicker for greater comfort during long reading sessions",
    hanhomeClassAAntibacterialAllSeasonQuilt: "HanHome Class A Antibacterial All-Season Quilt",
    beddingTextiles: "Bedding & textiles",
    dustyRose: "Dusty rose",
    mistBlue: "Mist blue",
    ivory: "Ivory",
    classABabySafe: "Class A baby-safe",
    antibacterialMiteResistant: "Antibacterial & mite resistant",
    machineWashable: "Machine washable",
    classABabySafeFabricAntibacterialMiteResistantAndMachineWashable: "Class A baby-safe fabric · Antibacterial, mite resistant, and machine washable",
    classABabySafeFabricIsSuitableForDirectContactWithDelicateSkin: "Class A baby-safe fabric is suitable for direct contact with delicate skin",
    silverIonProtectionResistsBacteriaAndMitesAndIsGentleOnSensitiveSkin: "Silver-ion protection resists bacteria and mites and is gentle on sensitive skin",
    snapTogetherLayersAdaptOneQuiltForEverySeason: "Snap-together layers adapt one quilt for every season",
    hanlabNiacinamideRepairSerum: "HanLab Niacinamide Repair Serum",
    skinCare: "Skin care",
    hanlab: "HanLab",
    text30MlStandard: "30 ml standard",
    text50MlLarge: "50 ml large",
    singleBottle: "Single bottle",
    buyOneGetOneGiftSet: "Buy-one-get-one gift set",
    brightening: "Brightening",
    text5Niacinamide: "5% niacinamide",
    sensitiveSkinFriendly: "Sensitive-skin friendly",
    text5NiacinamideBrightensAndRepairs: "5% niacinamide · Brightens and repairs",
    aGentleEffective5NiacinamideConcentration: "A gentle, effective 5% niacinamide concentration",
    ceramidesHelpStrengthenTheSkinBarrier: "Ceramides help strengthen the skin barrier",
    visibleBrighteningIn28Days: "Visible brightening in 28 days",
    hanlabVelvetMatteLipstick: "HanLab Velvet Matte Lipstick",
    makeup: "Makeup",
    mapleBrown: "Maple brown",
    rosewood: "Rosewood",
    trueOrange: "True orange",
    berryRed: "Berry red",
    standardSize: "Standard size",
    velvetMatte: "Velvet matte",
    longLastingTransferResistance: "Long-lasting transfer resistance",
    complexionEnhancing: "Complexion enhancing",
    velvetMatteFinishUpTo8HoursOfTransferResistantWear: "Velvet-matte finish · Up to 8 hours of transfer-resistant wear",
    richVelvetMatteColorInOneSwipeWithoutDryingLips: "Rich velvet-matte color in one swipe without drying lips",
    upTo8HoursOfWearWithMinimalTransferWhileEatingAndDrinking: "Up to 8 hours of wear with minimal transfer while eating and drinking",
    fourComplexionFlatteringShadesDesignedForWarmAndDeepSkinTones: "Four complexion-flattering shades designed for warm and deep skin tones",
    hanfieldInstantCampingTent: "HanField Instant Camping Tent",
    campingHiking: "Camping & hiking",
    hanfield: "HanField",
    desertKhaki: "Desert khaki",
    forestGreen: "Forest green",
    text34People: "3–4 people",
    text56People: "5–6 people",
    instantSetup: "Instant setup",
    waterResistant: "Water resistant",
    uvProtection: "UV protection",
    text10SecondSetupUpf50SunProtection: "10-second setup · UPF 50+ sun protection",
    hydraulicFrameSetsUpIn10Seconds: "Hydraulic frame sets up in 10 seconds",
    silverCoatedUpf50SunProtection: "Silver-coated UPF 50+ sun protection",
    waterResistantFabricWithFullMeshVentilation: "Water-resistant fabric with full mesh ventilation",
    hanfieldAllTerrainTrailRunningShoes: "HanField All-Terrain Trail Running Shoes",
    athleticShoes: "Athletic shoes",
    volcanicRed: "Volcanic red",
    carbonGray: "Carbon gray",
    neonYellow: "Neon yellow",
    highGripOutsole: "High-grip outsole",
    responsiveMidsole: "Responsive midsole",
    secureSupport: "Secure support",
    text5MmTrailLugsResponsiveCushionedMidsole: "5 mm trail lugs · Responsive cushioned midsole",
    text5MmRubberLugsGripMudAndLooseRock: "5 mm rubber lugs grip mud and loose rock",
    supercriticalFoamMidsoleDeliversResponsiveCushioning: "Supercritical-foam midsole delivers responsive cushioning",
    tpuSupportPlateAddsStabilityOverLongDistances: "TPU support plate adds stability over long distances",
    hanfieldInsulatedSportsBottle: "HanField Insulated Sports Bottle",
    fitness: "Fitness",
    mintGreen: "Mint green",
    cherryBlossomPink: "Cherry blossom pink",
    nightSkyBlack: "Night-sky black",
    skyBlue: "Sky blue",
    text24HourHeatRetention: "24-hour heat retention",
    oneTouchLid: "One-touch lid",
    text316StainlessInterior: "316 stainless interior",
    text316StainlessSteelInteriorKeepsDrinksHotFor24Hours: "316 stainless-steel interior · Keeps drinks hot for 24 hours",
    foodGrade316StainlessSteelInterior: "Food-grade 316 stainless-steel interior",
    keepsDrinksHotFor24HoursOrColdFor12: "Keeps drinks hot for 24 hours or cold for 12",
    oneTouchLidOpensAndClosesWithOneHand: "One-touch lid opens and closes with one hand",
    hantasteDailyNutGiftBox: "HanTaste Daily Nut Gift Box",
    snacks: "Snacks",
    hantaste: "HanTaste",
    text30Packs: "30 packs",
    giftBox: "Gift box",
    dailyPacks: "Daily packs",
    noAdditives: "No additives",
    freshHarvest: "Fresh harvest",
    sevenNutDailyPacksFreshSeasonalHarvest: "Seven-nut daily packs · Fresh seasonal harvest",
    balancedBlendOfSevenNutsAndDriedFruits: "Balanced blend of seven nuts and dried fruits",
    nitrogenFlushedIndividualPacksPreserveFreshness: "Nitrogen-flushed individual packs preserve freshness",
    freshSeasonalIngredientsWithNoFlavoringOrPreservatives: "Fresh seasonal ingredients with no flavoring or preservatives",
    hantasteSpecialtyDripCoffee: "HanTaste Specialty Drip Coffee",
    drinks: "Drinks",
    balancedBlend: "Balanced blend",
    naturalFloralFruit: "Natural floral & fruit",
    text10Bags: "10 bags",
    text30Bags: "30 bags",
    freshlyRoasted: "Freshly roasted",
    portableDripBags: "Portable drip bags",
    sca80SpecialtyBeansRoastedFreshToOrder: "SCA 80+ specialty beans · Roasted fresh to order",
    specialtyCoffeeBeansScoring80OnTheScaScale: "Specialty coffee beans scoring 80+ on the SCA scale",
    roastedFreshToOrderToPreserveAroma: "Roasted fresh to order to preserve aroma",
    optimizedGrindInConvenientSingleServeDripBags: "Optimized grind in convenient single-serve drip bags",
    hanwear3In1WeatherproofJacket: "HanWear 3-in-1 Weatherproof Jacket",
    menSClothing: "Men's clothing",
    hanwear: "HanWear",
    armyGreen: "Army green",
    charcoalBlack: "Charcoal black",
    nauticalBlue: "Nautical blue",
    waterproofWindproof: "Waterproof & windproof",
    removableLiner: "Removable liner",
    text3In1: "3-in-1",
    text10000MmWaterproofingRemovable3In1Liner: "10,000 mm waterproofing · Removable 3-in-1 liner",
    text10000MmWaterproofRatingAnd8000GBreathability: "10,000 mm waterproof rating and 8,000 g breathability",
    removableFleeceLinerForThreeSeasonVersatility: "Removable fleece liner for three-season versatility",
    contouredCutForWarmthWithoutBulk: "Contoured cut for warmth without bulk",
    hanwearCommuterBackpack: "HanWear Commuter Backpack",
    bags: "Bags",
    businessBlack: "Business black",
    oatGray: "Oat gray",
    deepGreen: "Deep green",
    text18LCommuter: "18 L commuter",
    text25LExpandable: "25 L expandable",
    usbCharging: "USB charging",
    ergonomicBackPanel: "Ergonomic back panel",
    supportiveBackPanel16InchLaptopCompartment: "Supportive back panel · 16-inch laptop compartment",
    ergonomicBackPanelDistributesWeightComfortably: "Ergonomic back panel distributes weight comfortably",
    dedicatedPaddedCompartmentForA16InchLaptop: "Dedicated padded compartment for a 16-inch laptop",
    waterResistantFabricAndAnIntegratedUsbChargingPort: "Water-resistant fabric and an integrated USB charging port",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = { key: "demo-shop--data-products", content: t(content) };
export default dictionary;
