import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    windListener: "听风的人",
    obsidianBlackNoiseCancelingPro: "曜石黑 · 降噪 Pro 版",
    theNoiseCancelingIsExcellentICanBarelyHearTheTrainOnMyCommuteBatteryLifeIsJustAsGoodIOnlyChargeT: "降噪是真的强，地铁里几乎听不到环境音，通勤戴一路很安静。续航也顶，一周充一次。",
    micaWhiteStandard: "云母白 · 标准版",
    theWhiteFinishLooksCleanAndSwitchingBetweenTwoDevicesIsSeamlessForMeetingsAndMusic: "颜值在线，白色很干净。双设备切换很丝滑，开会和听歌无缝切。",
    techieZhang: "数码控老张",
    hazeBlueStandard: "雾霾蓝 · 标准版",
    overallIMHappyThoughTheFitFeltTightAfterLongSessionsSwitchingToTheSmallerEarTipsHelpedALot: "整体满意，就是入耳偏紧，戴久了耳朵会有点胀，换了小号耳塞好多了。",
    anonymousCustomer: "匿名用户",
    obsidianBlackStandard: "曜石黑 · 标准版",
    soundQualityIsNoticeablyBetterThanThePreviousGenerationEspeciallyTheBassSupportRespondedQuicklyT: "音质比上一代提升明显，低频更扎实。客服响应也快，好评。",
    s0: "山***0",
    noiseCancelingIsGoodButTheTouchControlsAreALittleTooSensitiveISometimesPausePlaybackWhileFixingM: "降噪不错但触控有点灵敏，整理头发容易误触暂停。希望固件能优化。",
    photoEnthusiast: "拍照爱好者",
    alpineBlue16Gb512Gb: "远峰蓝 · 16G+512G",
    the1InchSensorMakesARealDifferenceNightShotsAreCleanAndTheTelephotoCapturedSharpConcertPhotos: "一英寸大底确实不一样，夜景纯净度很高，长焦拍演唱会也很清楚。",
    midnightBlack12Gb256Gb: "暗夜黑 · 12G+256G",
    theTitaniumFrameFeelsPremiumAndLighterInHandThanExpectedThe100WChargerFillsTheBatteryInAboutHalf: "钛金属手感高级，握持比想象轻。100W 快充半小时满电。",
    happyBuyer: "果断剁手",
    dawnGold16Gb1Tb: "晨曦金 · 16G+1T",
    performanceAndCamerasAreExcellentItIsALittleHeavySoFansOfSlimPhonesMayNeedTimeToAdjust: "性能和影像都顶，唯一就是有点压手，喜欢轻薄的可能要适应。",
    sensitiveSkinJourney: "敏感肌自救",
    text30MlStandardSingleBottle: "30ml 标准 · 单瓶",
    afterAMonthMyBlemishMarksHaveFadedAndMySkinToneLooksMoreEvenBestOfAllItDoesnTIrritateMySensitive: "用了一个月，痘印淡了不少，肤色均匀了。关键是敏感肌也不刺激。",
    iS: "成***分",
    text50MlLargeBuyOneGetOneGiftSet: "50ml 大瓶 · 买一送一礼盒",
    aThoughtfulFormulaAtAnEffectiveConcentrationTheTextureIsLightAndAbsorbsQuicklyThisIsMyThirdBottl: "成分党认证，浓度够诚意，质地清爽好吸收，回购第三瓶了。",
    aCustomer: "路人甲",
    theGentleFormulaTakesConsistentUseSoItMayFeelSlowIfYouWantInstantResultsItHasBeenReliablyIrritat: "效果温和需要坚持用，急效党可能觉得慢，但贵在稳定不翻车。",
    trailVeteran: "越野老炮",
    volcanicRed42: "火山红 · 42",
    theDeepLugsGripWellEvenOnWetTrailsAndTheResponsiveMidsoleStaysComfortableOverLongDistances: "深齿大底抓地很强，下雨天爬野山也不打滑。中底回弹长距离不累。",
    rC: "跑***团",
    carbonGray41: "碳灰 · 41",
    secureFitThoughIRecommendGoingHalfASizeUpTheyLookGoodEnoughForEverydayCommutingToo: "包裹很好，建议拍大半码。颜值也高，平时通勤也能穿。",
    wellnessFan: "养生少女",
    giftBox1050G: "礼盒装 · 1050g",
    theDailyPacksAreConvenientTheNutsTasteFreshAndTheIngredientListIsSimpleIAlwaysKeepABoxAtTheOffic: "每日一包很方便，坚果很新鲜不哈喇，配料干净。办公室常备。",
    text30Packs750G: "30 包装 · 750g",
    goodValueAndTheIndividualPacksKeepMoistureOutTheBoxAlsoMakesAPresentableGift: "性价比高，独立包装不怕受潮。送长辈也体面。",
  },
  en: {
    windListener: "Wind Listener",
    obsidianBlackNoiseCancelingPro: "Obsidian black · Noise Canceling Pro",
    theNoiseCancelingIsExcellentICanBarelyHearTheTrainOnMyCommuteBatteryLifeIsJustAsGoodIOnlyChargeT: "The noise canceling is excellent—I can barely hear the train on my commute. Battery life is just as good; I only charge them once a week.",
    micaWhiteStandard: "Mica white · Standard",
    theWhiteFinishLooksCleanAndSwitchingBetweenTwoDevicesIsSeamlessForMeetingsAndMusic: "The white finish looks clean, and switching between two devices is seamless for meetings and music.",
    techieZhang: "Techie Zhang",
    hazeBlueStandard: "Haze blue · Standard",
    overallIMHappyThoughTheFitFeltTightAfterLongSessionsSwitchingToTheSmallerEarTipsHelpedALot: "Overall I'm happy, though the fit felt tight after long sessions. Switching to the smaller ear tips helped a lot.",
    anonymousCustomer: "Anonymous customer",
    obsidianBlackStandard: "Obsidian black · Standard",
    soundQualityIsNoticeablyBetterThanThePreviousGenerationEspeciallyTheBassSupportRespondedQuicklyT: "Sound quality is noticeably better than the previous generation, especially the bass. Support responded quickly too.",
    s0: "S***0",
    noiseCancelingIsGoodButTheTouchControlsAreALittleTooSensitiveISometimesPausePlaybackWhileFixingM: "Noise canceling is good, but the touch controls are a little too sensitive—I sometimes pause playback while fixing my hair. I hope a firmware update improves this.",
    photoEnthusiast: "Photo Enthusiast",
    alpineBlue16Gb512Gb: "Alpine blue · 16 GB + 512 GB",
    the1InchSensorMakesARealDifferenceNightShotsAreCleanAndTheTelephotoCapturedSharpConcertPhotos: "The 1-inch sensor makes a real difference: night shots are clean, and the telephoto captured sharp concert photos.",
    midnightBlack12Gb256Gb: "Midnight black · 12 GB + 256 GB",
    theTitaniumFrameFeelsPremiumAndLighterInHandThanExpectedThe100WChargerFillsTheBatteryInAboutHalf: "The titanium frame feels premium and lighter in hand than expected. The 100 W charger fills the battery in about half an hour.",
    happyBuyer: "Happy Buyer",
    dawnGold16Gb1Tb: "Dawn gold · 16 GB + 1 TB",
    performanceAndCamerasAreExcellentItIsALittleHeavySoFansOfSlimPhonesMayNeedTimeToAdjust: "Performance and cameras are excellent. It is a little heavy, so fans of slim phones may need time to adjust.",
    sensitiveSkinJourney: "Sensitive Skin Journey",
    text30MlStandardSingleBottle: "30 ml standard · Single bottle",
    afterAMonthMyBlemishMarksHaveFadedAndMySkinToneLooksMoreEvenBestOfAllItDoesnTIrritateMySensitive: "After a month, my blemish marks have faded and my skin tone looks more even. Best of all, it doesn't irritate my sensitive skin.",
    iS: "I***s",
    text50MlLargeBuyOneGetOneGiftSet: "50 ml large · Buy-one-get-one gift set",
    aThoughtfulFormulaAtAnEffectiveConcentrationTheTextureIsLightAndAbsorbsQuicklyThisIsMyThirdBottl: "A thoughtful formula at an effective concentration. The texture is light and absorbs quickly—this is my third bottle.",
    aCustomer: "A Customer",
    theGentleFormulaTakesConsistentUseSoItMayFeelSlowIfYouWantInstantResultsItHasBeenReliablyIrritat: "The gentle formula takes consistent use, so it may feel slow if you want instant results. It has been reliably irritation-free for me.",
    trailVeteran: "Trail Veteran",
    volcanicRed42: "Volcanic red · 42",
    theDeepLugsGripWellEvenOnWetTrailsAndTheResponsiveMidsoleStaysComfortableOverLongDistances: "The deep lugs grip well even on wet trails, and the responsive midsole stays comfortable over long distances.",
    rC: "R***C",
    carbonGray41: "Carbon gray · 41",
    secureFitThoughIRecommendGoingHalfASizeUpTheyLookGoodEnoughForEverydayCommutingToo: "Secure fit, though I recommend going half a size up. They look good enough for everyday commuting too.",
    wellnessFan: "Wellness Fan",
    giftBox1050G: "Gift box · 1,050 g",
    theDailyPacksAreConvenientTheNutsTasteFreshAndTheIngredientListIsSimpleIAlwaysKeepABoxAtTheOffic: "The daily packs are convenient, the nuts taste fresh, and the ingredient list is simple. I always keep a box at the office.",
    text30Packs750G: "30 packs · 750 g",
    goodValueAndTheIndividualPacksKeepMoistureOutTheBoxAlsoMakesAPresentableGift: "Good value, and the individual packs keep moisture out. The box also makes a presentable gift.",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = { key: "demo-shop-data-reviews", content: t(content) };
export default dictionary;
