import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "allPriceRanges": "全部价位",
    "messagesRoleUserContentHelloHanhub": "    \"messages\": [{ \"role\": \"user\", \"content\": \"你好，瀚枢！\" }]",
    "messagesRoleUserContentHelloHanhub2": "    messages=[{\"role\": \"user\", \"content\": \"你好，瀚枢！\"}],",
    "recommended": "推荐",
    "inputPriceM": "输入价 / 1M",
    "outputPriceM": "输出价 / 1M",
    "contextWindow": "上下文窗口",
    "maximumOutput": "最大输出",
    "speedLimitRpm": "限速 RPM",
    "baseScore": "基准分",
    "gatewayMagnification": "网关倍率",
    "support": "支持",
    "notSupported": "不支持",
    "modelMarket": "模型市场",
    "upstreamModelOneBaseUrlForAll": "款上游模型 · 一个 base_url 全部路由 · OpenAI 兼容协议",
    "manufacturer": "厂商",
    "all": "全部",
    "filterByManufacturer": "按厂商筛选",
    "price": "价位",
    "filterByPrice": "按价位筛选",
    "ability": "能力",
    "input": "输入",
    "output": "输出",
    "baseScore2": "基准分",
    "speedLimit": "· 限速",
    "addedToComparison": "已加入对比",
    "addToComparison": "加入对比",
    "details": "详情",
    "thereAreNoModelsThatMatchThe": "没有符合当前筛选的模型，试试放宽条件。",
    "pricingComparisonMatrix": "定价对比矩阵",
    "selected": "已选",
    "modelRecommendedTheBestValueForMoney": "款 · 「推荐」= 当前对比中性价比最优",
    "clickAddToCompareFromTheModel": "从上方模型卡点「加入对比」，在此横向对照定价与能力。",
    "valueAccessHttpsApiHanhubCnV1": "{0} · 接入 https://api.hanhub.cn/v1",
    "moveOutOfComparison": "移出对比",
    "addToComparison2": "加入对比",
    "close": "关闭",
    "context": "上下文",
    "maximumOutput2": "· 最大输出",
    "inputPriceM2": "输入价 / 1M",
    "outputPriceM2": "输出价 / 1M",
    "speedLimit2": "限速",
    "gatewayMagnificationBaseScore": "网关倍率 / 基准分",
    "ability2": "能力",
    "billingInstructionsPricingIsBasedOnToken": "计费说明：按 token 用量计价，最终费用 =（输入 token × 输入价 + 输出 token × 输出价）÷ 1M ×",
    "gatewayMagnification2": "网关倍率。",
    "accessExampleCurl": "接入示例 · cURL",
    "accessExamplePython": "接入示例 · Python",
  },
  en: {
    "allPriceRanges": "All price ranges",
    "messagesRoleUserContentHelloHanhub": "\"messages\": [{ \"role\": \"user\", \"content\": \"Hello, HanHub!\" }]",
    "messagesRoleUserContentHelloHanhub2": "messages=[{\"role\": \"user\", \"content\": \"Hello, HanHub!\"}],",
    "recommended": "Recommended",
    "inputPriceM": "Input price / 1M",
    "outputPriceM": "Output price / 1M",
    "contextWindow": "context window",
    "maximumOutput": "maximum output",
    "speedLimitRpm": "Speed limit RPM",
    "baseScore": "base score",
    "gatewayMagnification": "Gateway magnification",
    "support": "support",
    "notSupported": "Not supported",
    "modelMarket": "model market",
    "upstreamModelOneBaseUrlForAll": "Upstream model · One base_url for all routes · OpenAI compatible protocol",
    "manufacturer": "Manufacturer",
    "all": "All",
    "filterByManufacturer": "Filter by manufacturer",
    "price": "price",
    "filterByPrice": "Filter by price",
    "ability": "Ability",
    "input": "input",
    "output": "output",
    "baseScore2": "base score",
    "speedLimit": "· Speed limit",
    "addedToComparison": "Added to comparison",
    "addToComparison": "Add to comparison",
    "details": "Details",
    "thereAreNoModelsThatMatchThe": "There are no models that match the current filter, try relaxing the conditions.",
    "pricingComparisonMatrix": "Pricing comparison matrix",
    "selected": "Selected",
    "modelRecommendedTheBestValueForMoney": "Model · \"Recommended\" = The best value for money in the current comparison",
    "clickAddToCompareFromTheModel": "Click \"Add to Compare\" from the model card above to compare pricing and capabilities horizontally.",
    "valueAccessHttpsApiHanhubCnV1": "{0} · Access https://api.hanhub.cn/v1",
    "moveOutOfComparison": "Move out of comparison",
    "addToComparison2": "Add to comparison",
    "close": "close",
    "context": "context",
    "maximumOutput2": "· Maximum output",
    "inputPriceM2": "Input price / 1M",
    "outputPriceM2": "Output price / 1M",
    "speedLimit2": "speed limit",
    "gatewayMagnificationBaseScore": "Gateway magnification / base score",
    "ability2": "Ability",
    "billingInstructionsPricingIsBasedOnToken": "Billing instructions: Pricing is based on token usage, final cost = (input token × input price + output token × output price) ÷ 1M ×",
    "gatewayMagnification2": "Gateway magnification.",
    "accessExampleCurl": "Access example · cURL",
    "accessExamplePython": "Access example · Python",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanhub-app-models-page",
  content: t(content),
};

export default dictionary;
