import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    text618SaleTechDeals: "618 大促 · 数码狂欢",
    save120OnHeadphonesWatchesAndLaptopsOver599: "耳机·手表·笔记本，满 599 减 120",
    shopDeals: "立即抢购",
    beautyCareSpecialOffers: "美妆个护 · 惊喜折扣",
    text15OffSerumsLipstickAndSkinCareSets: "精华·口红·护肤套装 8.5 折",
    exploreOffers: "去看看",
    outdoorAdventureSummerStartsHere: "户外运动 · 夏日出发",
    specialPricesOnTentsTrailShoesAndInsulatedBottles: "帐篷·越野鞋·保温壶全场特惠",
    exploreOutdoors: "探索户外",
    homeLivingEditorSPicks: "家居生活 · 精选好物",
    limitedTimeOffersOnCookersFloorLampsAndAllSeasonQuilts: "料理机·护眼灯·四季被限时优惠",
    shopHome: "逛家居",
    hansound: "瀚声 HanSound",
    hanbook: "瀚本 HanBook",
    hanwatch: "瀚腕 HanWatch",
    hanphone: "瀚拍 HanPhone",
    hanhome: "瀚庐 HanHome",
    hanlab: "瀚研 HanLab",
    hanfield: "瀚野 HanField",
    hantaste: "瀚味 HanTaste",
    hanwear: "瀚衣 HanWear",
    tech: "数码 3C",
    homeEssentials: "家居好物",
    beautyCare: "美妆个护",
    outdoorGear: "户外装备",
    fineFoods: "精品食材",
    fashion: "时尚服饰",
    promotions: "营销横幅",
    promotionalCarousel: "营销横幅轮播",
    curated: "精选",
    andOther: "等",
    greatFinds: "好物",
    featuredBrands: "入驻品牌",
    shoppingPromises: "平台保障",
    authenticityGuaranteed: "正品保证",
    text100DirectFromBrands: "100% 品牌直供",
    fastDelivery: "极速配送",
    nextDayDeliveryFreeNationwideShipping: "次日达 · 全国包邮",
    easyReturns: "无忧退换",
    text15DayFreeReturns: "15 天无理由退货",
    memberBenefits: "会员权益",
    redeemPointsMemberOnlyOffers: "积分兑换 · 专属折扣",
  },
  en: {
    text618SaleTechDeals: "618 Sale · Tech deals",
    save120OnHeadphonesWatchesAndLaptopsOver599: "Save ¥120 on headphones, watches, and laptops over ¥599",
    shopDeals: "Shop deals",
    beautyCareSpecialOffers: "Beauty & care · Special offers",
    text15OffSerumsLipstickAndSkinCareSets: "15% off serums, lipstick, and skin-care sets",
    exploreOffers: "Explore offers",
    outdoorAdventureSummerStartsHere: "Outdoor adventure · Summer starts here",
    specialPricesOnTentsTrailShoesAndInsulatedBottles: "Special prices on tents, trail shoes, and insulated bottles",
    exploreOutdoors: "Explore outdoors",
    homeLivingEditorSPicks: "Home living · Editor's picks",
    limitedTimeOffersOnCookersFloorLampsAndAllSeasonQuilts: "Limited-time offers on cookers, floor lamps, and all-season quilts",
    shopHome: "Shop home",
    hansound: "HanSound",
    hanbook: "HanBook",
    hanwatch: "HanWatch",
    hanphone: "HanPhone",
    hanhome: "HanHome",
    hanlab: "HanLab",
    hanfield: "HanField",
    hantaste: "HanTaste",
    hanwear: "HanWear",
    tech: "Tech",
    homeEssentials: "Home essentials",
    beautyCare: "Beauty & care",
    outdoorGear: "Outdoor gear",
    fineFoods: "Fine foods",
    fashion: "Fashion",
    promotions: "Promotions",
    promotionalCarousel: "Promotional carousel",
    curated: "Curated",
    andOther: "and other",
    greatFinds: "great finds",
    featuredBrands: "Featured brands",
    shoppingPromises: "Shopping promises",
    authenticityGuaranteed: "Authenticity guaranteed",
    text100DirectFromBrands: "100% direct from brands",
    fastDelivery: "Fast delivery",
    nextDayDeliveryFreeNationwideShipping: "Next-day delivery · Free nationwide shipping",
    easyReturns: "Easy returns",
    text15DayFreeReturns: "15-day free returns",
    memberBenefits: "Member benefits",
    redeemPointsMemberOnlyOffers: "Redeem points · Member-only offers",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = { key: "demo-shop--shop-page", content: t(content) };
export default dictionary;
