import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "stringConcatenationIsProhibitedWhenConstructingSql": "禁止字符串拼接构造 SQL，必须参数化查询",
    "externalCallbackEntryMustBeIdempotentTo": "外部回调入口必须幂等，防止重放导致重复业务",
    "notificationSideEffectFailuresShouldNotBlock": "通知类副作用失败不应阻塞主流程，需兜底落日志",
    "ifValidationFailsAClearXxStatus": "校验失败应返回明确的 4xx 状态码",
    "ifVerifysignReqBodySignReturnOk": "if (!verifySign(req.body, sign)) {\n  return { ok: false, msg: \"签名校验失败\" };\n}",
    "hardcodeKeysCredentialsAreProhibitedInThe": "禁止在源码硬编码密钥 / 凭证",
    "constSecretSkLiveF3c2a9d4e1bTodoWas": "const SECRET = \"sk_live_8f3c2a9d4e1b\"; // TODO 上线前替换",
    "constSecretProcessEnvPaySecretIf": "const SECRET = process.env.PAY_SECRET;\nif (!SECRET) throw new Error(\"PAY_SECRET 未配置\");",
    "itIsForbiddenToUseMd5For": "禁止用 MD5 与宽松比较做签名校验",
    "avoidONNestedSearchesAndInstead": "避免 O(n²) 嵌套查找，改用 Map 索引",
    "forPotentiallyUndefinedValuesAccessingAttributesMust": "对可能为 undefined 的值访问属性需先判空",
    "refactoringMustNotSilentlyAlterTheOriginal": "重构不得静默改变原有行为（条目丢弃）",
    "pureDataConstructorsShouldNotBeInlined": "纯数据构建函数不应内联副作用",
    "asynchronousCallsRequireAwaitOrExplicitlyAnnotate": "异步调用需 await 或显式标注 fire-and-forget",
    "aesEcbIsProhibitedAuthenticationEncryptionWith": "禁止使用 AES-ECB，应使用带 IV 的认证加密（GCM）",
    "kdfSaltMustBeRandomlyGeneratedFor": "KDF 盐必须每条记录随机生成",
    "theNumberOfPbkdf2Sha256IterationsShould": "PBKDF2-SHA256 迭代次数不应低于 600000",
    "crossTenantResourceAccessMustVerifyAttribution": "跨租户资源访问必须校验归属（防 IDOR）",
    "commentsOnKnownUnsafeImplementationsShouldNot": "不应保留已知不安全实现的注释而不修复",
    "deriveTheMasterKeyUsingFixedSalt": "# 用固定盐 + 低迭代次数派生主密钥",
    "summingValuesThatMayBeUndefinedRequires": "对可能为 undefined 的数值求和需兜底",
    "styleValuesShouldBeDeductedAsDesign": "样式数值应抽成 design token",
    "itIsForbiddenToPrintUserIds": "禁止把用户标识直接 print 到标准输出",
    "theAuditSourceIpShouldNotBe": "审计来源 ip 不应为可选默认 None",
    "dependencyUpgradesRequireSynchronizingLockfileAndRunning": "依赖升级需同步 lockfile 并跑 audit",
    "theVirtualScrollingRowHeightEstimateShould": "虚拟滚动行高估计应贴近真实值",
    "containerDimensionsShouldAdaptToTheViewport": "容器尺寸应自适应视口",
    "ifTheFunctionExceedsLinesItIs": "函数超过 50 行，建议拆分",
    "missingCallbackReplayInjectionScenarioTestCases": "缺少回调重放 / 注入场景测试用例",
    "noPlaybackOrInjectionUseCaseOverlays": "// 无重放与注入用例覆盖",
    "lackOfUnauthorizedAccessAndGcmIntegrity": "缺少越权访问与 GCM 完整性测试",
    "batchProxyPaymentCycleFailsMidwayAnd": "批量代付循环中途失败缺少补偿 / 回滚",
    "thePaymentAmountOnBehalfOfOthers": "代付金额未做范围与符号校验",
    "couponStackingDoesNotConsiderTheCombination": "优惠券叠加未考虑互斥类型组合",
    "transitionShouldSpecifySpecificAttributesToAvoid": "transition 应指明具体属性避免重排开销",
    "itIsRecommendedToSupplementVirtualScrolling": "建议补充虚拟滚动的交互测试而非仅快照",
    "onlySnapshotTestsExistLackingScrollingBehavior": "// 仅有快照测试，缺少滚动行为断言",
    "theFieldListIsWrittenInBoth": "字段清单同时写在代码与配置，存在双源",
    "delayingResponseByCallingBackToThe": "回调主链路内同步等待通知拖慢响应",
    "eachBuildInTheHotPathIs": "热路径里每次构建都排序，建议缓存结果",
    "publicFunctionsSuggestCompletingTypeAnnotations": "公共函数建议补全类型注解",
    "afterTheUpgradeItIsNecessaryTo": "升级后需复核传递依赖的已知漏洞",
  },
  en: {
    "stringConcatenationIsProhibitedWhenConstructingSql": "String concatenation is prohibited when constructing SQL and must be parameterized",
    "externalCallbackEntryMustBeIdempotentTo": "External callback handlers must be idempotent to prevent duplicate processing on retries",
    "notificationSideEffectFailuresShouldNotBlock": "Notification failures must not block the main flow; catch and log them for retry",
    "ifValidationFailsAClearXxStatus": "If validation fails, a clear 4xx status code should be returned",
    "ifVerifysignReqBodySignReturnOk": "if (!verifySign(req.body, sign)) { \n return { ok: false, msg: \"Signature validation failed\" }; \n}",
    "hardcodeKeysCredentialsAreProhibitedInThe": "Do not hard-code keys or credentials in source code",
    "constSecretSkLiveF3c2a9d4e1bTodoWas": "const SECRET = \"sk_live_8f3c2a9d4e1b\"; // TODO: replace before production",
    "constSecretProcessEnvPaySecretIf": "const SECRET = process.env.PAY_SECRET; \nif (! SECRET) throw new Error(\"PAY_SECRET unconfigured\");",
    "itIsForbiddenToUseMd5For": "Do not use MD5 or loose equality for signature verification",
    "avoidONNestedSearchesAndInstead": "Avoid O(n²) nested searches and instead use the Map index",
    "forPotentiallyUndefinedValuesAccessingAttributesMust": "Guard potentially undefined values before accessing their properties",
    "refactoringMustNotSilentlyAlterTheOriginal": "Refactoring must not silently change existing behavior or drop records",
    "pureDataConstructorsShouldNotBeInlined": "Keep pure data-building functions free of side effects",
    "asynchronousCallsRequireAwaitOrExplicitlyAnnotate": "Asynchronous calls require await or explicitly annotate fire-and-forget",
    "aesEcbIsProhibitedAuthenticationEncryptionWith": "Do not use AES-ECB; use authenticated encryption with a unique nonce, such as AES-GCM.",
    "kdfSaltMustBeRandomlyGeneratedFor": "KDF salt must be randomly generated for each record",
    "theNumberOfPbkdf2Sha256IterationsShould": "The number of PBKDF2-SHA256 iterations should not be less than 600,000",
    "crossTenantResourceAccessMustVerifyAttribution": "Cross-tenant resource access must verify tenant ownership to prevent IDOR",
    "commentsOnKnownUnsafeImplementationsShouldNot": "Do not leave known unsafe implementations in place with only a warning comment",
    "deriveTheMasterKeyUsingFixedSalt": "# Derive the master key using fixed salt + low iterations",
    "summingValuesThatMayBeUndefinedRequires": "Guard against undefined values before summing",
    "styleValuesShouldBeDeductedAsDesign": "Extract repeated style values into design tokens",
    "itIsForbiddenToPrintUserIds": "Do not print user IDs directly to standard output",
    "theAuditSourceIpShouldNotBe": "Require the source IP for audit records instead of defaulting to None",
    "dependencyUpgradesRequireSynchronizingLockfileAndRunning": "Dependency upgrades require synchronizing lockfile and running audit",
    "theVirtualScrollingRowHeightEstimateShould": "The virtual scrolling row height estimate should be close to the true value",
    "containerDimensionsShouldAdaptToTheViewport": "Container dimensions should adapt to the viewport",
    "ifTheFunctionExceedsLinesItIs": "Split functions longer than 50 lines when it improves readability",
    "missingCallbackReplayInjectionScenarioTestCases": "Missing callback replay/injection scenario test cases",
    "noPlaybackOrInjectionUseCaseOverlays": "Missing test coverage for replay and injection scenarios",
    "lackOfUnauthorizedAccessAndGcmIntegrity": "Missing tests for unauthorized access and GCM integrity failures",
    "batchProxyPaymentCycleFailsMidwayAnd": "The batch payout flow lacks compensation or rollback for partial failures",
    "thePaymentAmountOnBehalfOfOthers": "The payout amount is not validated for range or sign",
    "couponStackingDoesNotConsiderTheCombination": "Coupon stacking does not consider the combination of exclusive types",
    "transitionShouldSpecifySpecificAttributesToAvoid": "List specific transition properties to avoid unnecessary layout work",
    "itIsRecommendedToSupplementVirtualScrolling": "Add interaction tests for virtual scrolling instead of relying only on snapshots",
    "onlySnapshotTestsExistLackingScrollingBehavior": "Only snapshot tests exist, lacking scrolling behavior assertions",
    "theFieldListIsWrittenInBoth": "The field list is duplicated in code and configuration, creating two sources of truth",
    "delayingResponseByCallingBackToThe": "Synchronous notification delivery delays the main callback response",
    "eachBuildInTheHotPathIs": "The hot path sorts on every build; cache the result when inputs are unchanged",
    "publicFunctionsSuggestCompletingTypeAnnotations": "Add complete type annotations to public functions",
    "afterTheUpgradeItIsNecessaryTo": "After upgrading, audit transitive dependencies for known vulnerabilities",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanreview-data-findings",
  content: t(content),
};

export default dictionary;
