import { copy } from "./findings.content";
import type { Finding } from "./types";

// 问题清单（部分由 reviews 的 annotations 派生，部分为独立历史问题）。
// reviewId ∈ REVIEWS、repoId ∈ REPOS，覆盖全部 severity / type / status。
export const FINDINGS: Finding[] = [
  // ── 派生自 rev-001（hanpay-api 退款回调）──
  {
    id: "f-001",
    reviewId: "rev-001",
    repoId: "hanpay-api",
    severity: "critical",
    type: "security",
    rule: "sql-injection",
    ruleDesc: copy("stringConcatenationIsProhibitedWhenConstructingSql"),
    file: "src/payment/refundCallback.ts",
    line: 11,
    status: "open",
    firstSeen: "2026-06-05 14:23",
    snippet:
      "await db.query(\n  'UPDATE orders SET status = \"refunded\", refund_amount = ' +\n    amount + ' WHERE id = ' + orderId\n);",
    suggestion: {
      oldText: "'UPDATE orders SET status = \"refunded\", refund_amount = ' + amount + ' WHERE id = ' + orderId",
      newText: "'UPDATE orders SET status = ?, refund_amount = ? WHERE id = ?', ['refunded', amount, orderId]",
    },
  },
  {
    id: "f-002",
    reviewId: "rev-001",
    repoId: "hanpay-api",
    severity: "critical",
    type: "bug",
    rule: "missing-idempotency",
    ruleDesc: copy("externalCallbackEntryMustBeIdempotentTo"),
    file: "src/payment/refundCallback.ts",
    line: 2,
    status: "open",
    firstSeen: "2026-06-05 14:23",
    snippet: "export async function handleRefundCallback(req: Request) {\n  const { orderId, amount, sign } = req.body;",
  },
  {
    id: "f-003",
    reviewId: "rev-001",
    repoId: "hanpay-api",
    severity: "major",
    type: "bug",
    rule: "unhandled-side-effect",
    ruleDesc: copy("notificationSideEffectFailuresShouldNotBlock"),
    file: "src/payment/refundCallback.ts",
    line: 15,
    status: "open",
    firstSeen: "2026-06-05 14:23",
    snippet: "await notifyUser(orderId);\nreturn { ok: true };",
  },
  {
    id: "f-004",
    reviewId: "rev-001",
    repoId: "hanpay-api",
    severity: "minor",
    type: "style",
    rule: "http-status-on-failure",
    ruleDesc: copy("ifValidationFailsAClearXxStatus"),
    file: "src/payment/refundCallback.ts",
    line: 6,
    status: "ignored",
    firstSeen: "2026-06-05 14:23",
    snippet: copy("ifVerifysignReqBodySignReturnOk"),
  },
  {
    id: "f-005",
    reviewId: "rev-001",
    repoId: "hanpay-api",
    severity: "critical",
    type: "security",
    rule: "hardcoded-secret",
    ruleDesc: copy("hardcodeKeysCredentialsAreProhibitedInThe"),
    file: "src/payment/sign.ts",
    line: 1,
    status: "open",
    firstSeen: "2026-06-05 14:23",
    snippet: copy("constSecretSkLiveF3c2a9d4e1bTodoWas"),
    suggestion: {
      oldText: 'const SECRET = "sk_live_8f3c2a9d4e1b";',
      newText: copy("constSecretProcessEnvPaySecretIf"),
    },
  },
  {
    id: "f-006",
    reviewId: "rev-001",
    repoId: "hanpay-api",
    severity: "major",
    type: "security",
    rule: "weak-crypto",
    ruleDesc: copy("itIsForbiddenToUseMd5For"),
    file: "src/payment/sign.ts",
    line: 13,
    status: "open",
    firstSeen: "2026-06-05 14:23",
    snippet: "const hash = md5(raw + SECRET);\nreturn hash == sign;",
  },

  // ── 派生自 rev-002（hancloud-web 列表）──
  {
    id: "f-007",
    reviewId: "rev-002",
    repoId: "hancloud-web",
    severity: "major",
    type: "perf",
    rule: "nested-loop-on2",
    ruleDesc: copy("avoidONNestedSearchesAndInstead"),
    file: "src/dashboard/resourceService.ts",
    line: 4,
    status: "open",
    firstSeen: "2026-06-05 11:08",
    snippet: "for (const it of items) {\n  for (const t of tags) {\n    if (t.id === it.tagId) { ... }\n  }\n}",
    suggestion: {
      oldText: "for (const it of items) { for (const t of tags) { ... } }",
      newText: "const tagMap = new Map(tags.map((t) => [t.id, t.name]));",
    },
  },
  {
    id: "f-008",
    reviewId: "rev-002",
    repoId: "hancloud-web",
    severity: "major",
    type: "bug",
    rule: "possible-null-deref",
    ruleDesc: copy("forPotentiallyUndefinedValuesAccessingAttributesMust"),
    file: "src/dashboard/resourceService.ts",
    line: 14,
    status: "open",
    firstSeen: "2026-06-05 11:08",
    snippet: "return result.sort((a, b) => a.tagName.length - b.tagName.length);",
  },
  {
    id: "f-009",
    reviewId: "rev-002",
    repoId: "hancloud-web",
    severity: "minor",
    type: "bug",
    rule: "behavior-regression",
    ruleDesc: copy("refactoringMustNotSilentlyAlterTheOriginal"),
    file: "src/dashboard/resourceService.ts",
    line: 9,
    status: "fixed",
    firstSeen: "2026-06-05 11:08",
    snippet: "result.push({ ...it, tagName: t.name });",
  },
  {
    id: "f-010",
    reviewId: "rev-002",
    repoId: "hancloud-web",
    severity: "info",
    type: "complexity",
    rule: "side-effect-in-pure-fn",
    ruleDesc: copy("pureDataConstructorsShouldNotBeInlined"),
    file: "src/dashboard/resourceService.ts",
    line: 12,
    status: "wontfix",
    firstSeen: "2026-06-05 11:08",
    snippet: "refreshCache(result);",
  },
  {
    id: "f-011",
    reviewId: "rev-002",
    repoId: "hancloud-web",
    severity: "minor",
    type: "bug",
    rule: "floating-promise",
    ruleDesc: copy("asynchronousCallsRequireAwaitOrExplicitlyAnnotate"),
    file: "src/dashboard/utils.ts",
    line: 3,
    status: "open",
    firstSeen: "2026-06-05 11:08",
    snippet: 'cache.set("dashboard:list", rows);',
    suggestion: {
      oldText: 'cache.set("dashboard:list", rows);',
      newText: 'await cache.set("dashboard:list", rows);',
    },
  },

  // ── 派生自 rev-003（hanvault-core 加密）──
  {
    id: "f-012",
    reviewId: "rev-003",
    repoId: "hanvault-core",
    severity: "critical",
    type: "security",
    rule: "insecure-cipher-mode",
    ruleDesc: copy("aesEcbIsProhibitedAuthenticationEncryptionWith"),
    file: "vault/crypto.py",
    line: 10,
    status: "open",
    firstSeen: "2026-06-05 09:41",
    snippet: "cipher = AES.new(key, AES.MODE_ECB)\npad = 16 - len(plain) % 16\nplain += bytes([pad]) * pad",
    suggestion: {
      oldText: "cipher = AES.new(key, AES.MODE_ECB)",
      newText: "cipher = AES.new(key, AES.MODE_GCM, nonce=os.urandom(12))",
    },
  },
  {
    id: "f-013",
    reviewId: "rev-003",
    repoId: "hanvault-core",
    severity: "major",
    type: "security",
    rule: "fixed-salt",
    ruleDesc: copy("kdfSaltMustBeRandomlyGeneratedFor"),
    file: "vault/crypto.py",
    line: 1,
    status: "open",
    firstSeen: "2026-06-05 09:41",
    snippet: 'def derive_key(password: str, salt: bytes = b"vault") -> bytes:',
  },
  {
    id: "f-014",
    reviewId: "rev-003",
    repoId: "hanvault-core",
    severity: "major",
    type: "security",
    rule: "weak-kdf-iterations",
    ruleDesc: copy("theNumberOfPbkdf2Sha256IterationsShould"),
    file: "vault/crypto.py",
    line: 4,
    status: "open",
    firstSeen: "2026-06-05 09:41",
    snippet: '"sha256", password.encode(), salt, 1000',
  },
  {
    id: "f-015",
    reviewId: "rev-003",
    repoId: "hanvault-core",
    severity: "major",
    type: "security",
    rule: "broken-access-control",
    ruleDesc: copy("crossTenantResourceAccessMustVerifyAttribution"),
    file: "vault/access.py",
    line: 3,
    status: "open",
    firstSeen: "2026-06-05 09:41",
    snippet: "# if secret.tenant_id != user.tenant_id:\n#     raise Forbidden()",
    suggestion: {
      oldText: "# if secret.tenant_id != user.tenant_id:\n#     raise Forbidden()",
      newText: "if secret.tenant_id != user.tenant_id:\n    raise Forbidden()",
    },
  },
  {
    id: "f-016",
    reviewId: "rev-003",
    repoId: "hanvault-core",
    severity: "minor",
    type: "style",
    rule: "todo-without-fix",
    ruleDesc: copy("commentsOnKnownUnsafeImplementationsShouldNot"),
    file: "vault/crypto.py",
    line: 2,
    status: "ignored",
    firstSeen: "2026-06-05 09:41",
    snippet: copy("deriveTheMasterKeyUsingFixedSalt"),
  },

  // ── 派生自 rev-004 / rev-005 ──
  {
    id: "f-017",
    reviewId: "rev-004",
    repoId: "hanshop-mobile",
    severity: "minor",
    type: "bug",
    rule: "undefined-arithmetic",
    ruleDesc: copy("summingValuesThatMayBeUndefinedRequires"),
    file: "src/cart/badge.ts",
    line: 3,
    status: "open",
    firstSeen: "2026-06-05 15:02",
    snippet: "return items.reduce((s, it) => s + it.qty, 0);",
    suggestion: { oldText: "s + it.qty", newText: "s + (it.qty ?? 0)" },
  },
  {
    id: "f-018",
    reviewId: "rev-005",
    repoId: "hancloud-web",
    severity: "info",
    type: "style",
    rule: "magic-value",
    ruleDesc: copy("styleValuesShouldBeDeductedAsDesign"),
    file: "src/components/Button.tsx",
    line: 1,
    status: "wontfix",
    firstSeen: "2026-06-04 17:36",
    snippet: '<button className="btn rounded-md transition-colors hover:bg-primary/90">',
  },

  // ── 派生自 rev-008 / rev-009 / rev-010 ──
  {
    id: "f-019",
    reviewId: "rev-008",
    repoId: "hanvault-core",
    severity: "major",
    type: "security",
    rule: "pii-in-stdout",
    ruleDesc: copy("itIsForbiddenToPrintUserIds"),
    file: "vault/audit.py",
    line: 8,
    status: "open",
    firstSeen: "2026-06-04 10:55",
    snippet: 'print("audit:", user_id, action)',
  },
  {
    id: "f-020",
    reviewId: "rev-008",
    repoId: "hanvault-core",
    severity: "minor",
    type: "bug",
    rule: "optional-required-field",
    ruleDesc: copy("theAuditSourceIpShouldNotBe"),
    file: "vault/audit.py",
    line: 1,
    status: "open",
    firstSeen: "2026-06-04 10:55",
    snippet: "def log(user_id, action, ip=None):",
  },
  {
    id: "f-021",
    reviewId: "rev-009",
    repoId: "hancloud-web",
    severity: "info",
    type: "security",
    rule: "lockfile-out-of-sync",
    ruleDesc: copy("dependencyUpgradesRequireSynchronizingLockfileAndRunning"),
    file: "package.json",
    line: 4,
    status: "fixed",
    firstSeen: "2026-06-04 09:12",
    snippet: '"vite": "5.4.11",\n"esbuild": "0.24.0"',
  },
  {
    id: "f-022",
    reviewId: "rev-010",
    repoId: "hanshop-mobile",
    severity: "minor",
    type: "perf",
    rule: "virtualizer-estimate-size",
    ruleDesc: copy("theVirtualScrollingRowHeightEstimateShould"),
    file: "src/product/ProductList.tsx",
    line: 3,
    status: "open",
    firstSeen: "2026-06-03 19:48",
    snippet: "useVirtualizer({ count: items.length, estimateSize: () => 96 })",
  },
  {
    id: "f-023",
    reviewId: "rev-010",
    repoId: "hanshop-mobile",
    severity: "minor",
    type: "style",
    rule: "hardcoded-dimension",
    ruleDesc: copy("containerDimensionsShouldAdaptToTheViewport"),
    file: "src/product/ProductList.tsx",
    line: 5,
    status: "open",
    firstSeen: "2026-06-03 19:48",
    snippet: 'style={{ overflow: "auto", height: 600 }}',
  },

  // ── 独立历史问题（仍引用真实 review/repo）──
  {
    id: "f-024",
    reviewId: "rev-002",
    repoId: "hancloud-web",
    severity: "minor",
    type: "complexity",
    rule: "function-too-long",
    ruleDesc: copy("ifTheFunctionExceedsLinesItIs"),
    file: "src/dashboard/resourceService.ts",
    line: 1,
    status: "wontfix",
    firstSeen: "2026-06-05 11:08",
    snippet: "export function buildList(items: Item[], tags: Tag[]) {",
  },
  {
    id: "f-025",
    reviewId: "rev-001",
    repoId: "hanpay-api",
    severity: "minor",
    type: "test",
    rule: "missing-edge-case-test",
    ruleDesc: copy("missingCallbackReplayInjectionScenarioTestCases"),
    file: "src/payment/refundCallback.ts",
    line: 1,
    status: "open",
    firstSeen: "2026-06-05 14:23",
    snippet: copy("noPlaybackOrInjectionUseCaseOverlays"),
  },
  {
    id: "f-026",
    reviewId: "rev-003",
    repoId: "hanvault-core",
    severity: "minor",
    type: "test",
    rule: "missing-security-test",
    ruleDesc: copy("lackOfUnauthorizedAccessAndGcmIntegrity"),
    file: "tests/test_crypto.py",
    line: 1,
    status: "open",
    firstSeen: "2026-06-05 09:41",
    snippet: "def test_derive_key_len():",
  },
  {
    id: "f-027",
    reviewId: "rev-006",
    repoId: "hanpay-api",
    severity: "major",
    type: "bug",
    rule: "partial-failure-no-rollback",
    ruleDesc: copy("batchProxyPaymentCycleFailsMidwayAnd"),
    file: "src/payout/batchJob.ts",
    line: 4,
    status: "open",
    firstSeen: "2026-06-04 16:10",
    snippet: "for (const it of items) {\n  await transfer(it.account, it.amount);\n}",
  },
  {
    id: "f-028",
    reviewId: "rev-006",
    repoId: "hanpay-api",
    severity: "major",
    type: "security",
    rule: "no-amount-validation",
    ruleDesc: copy("thePaymentAmountOnBehalfOfOthers"),
    file: "src/payout/batchJob.ts",
    line: 4,
    status: "open",
    firstSeen: "2026-06-04 16:10",
    snippet: "await transfer(it.account, it.amount);",
  },
  {
    id: "f-029",
    reviewId: "rev-007",
    repoId: "hanshop-mobile",
    severity: "minor",
    type: "complexity",
    rule: "missing-mutual-exclusion",
    ruleDesc: copy("couponStackingDoesNotConsiderTheCombination"),
    file: "src/coupon/stackRule.ts",
    line: 2,
    status: "open",
    firstSeen: "2026-06-05 15:20",
    snippet: "return a.stackable && b.stackable;",
  },
  {
    id: "f-030",
    reviewId: "rev-005",
    repoId: "hancloud-web",
    severity: "info",
    type: "style",
    rule: "transition-property-broad",
    ruleDesc: copy("transitionShouldSpecifySpecificAttributesToAvoid"),
    file: "src/components/Button.tsx",
    line: 1,
    status: "ignored",
    firstSeen: "2026-06-04 17:36",
    snippet: 'className="btn rounded-md transition-colors hover:bg-primary/90"',
  },
  {
    id: "f-031",
    reviewId: "rev-010",
    repoId: "hanshop-mobile",
    severity: "info",
    type: "test",
    rule: "snapshot-only-test",
    ruleDesc: copy("itIsRecommendedToSupplementVirtualScrolling"),
    file: "src/product/ProductList.tsx",
    line: 1,
    status: "open",
    firstSeen: "2026-06-03 19:48",
    snippet: copy("onlySnapshotTestsExistLackingScrollingBehavior"),
  },
  {
    id: "f-032",
    reviewId: "rev-008",
    repoId: "hanvault-core",
    severity: "info",
    type: "complexity",
    rule: "config-and-code-coupled",
    ruleDesc: copy("theFieldListIsWrittenInBoth"),
    file: "config/audit.yaml",
    line: 4,
    status: "wontfix",
    firstSeen: "2026-06-04 10:55",
    snippet: "fields: [u, a, ip, ts]",
  },
  {
    id: "f-033",
    reviewId: "rev-001",
    repoId: "hanpay-api",
    severity: "major",
    type: "perf",
    rule: "blocking-notify-in-callback",
    ruleDesc: copy("delayingResponseByCallingBackToThe"),
    file: "src/payment/refundCallback.ts",
    line: 15,
    status: "fixed",
    firstSeen: "2026-06-05 14:23",
    snippet: "await notifyUser(orderId);",
  },
  {
    id: "f-034",
    reviewId: "rev-002",
    repoId: "hancloud-web",
    severity: "minor",
    type: "perf",
    rule: "sort-in-hot-path",
    ruleDesc: copy("eachBuildInTheHotPathIs"),
    file: "src/dashboard/resourceService.ts",
    line: 14,
    status: "open",
    firstSeen: "2026-06-05 11:08",
    snippet: "return result.sort((a, b) => a.tagName.length - b.tagName.length);",
  },
  {
    id: "f-035",
    reviewId: "rev-003",
    repoId: "hanvault-core",
    severity: "info",
    type: "style",
    rule: "missing-type-hint",
    ruleDesc: copy("publicFunctionsSuggestCompletingTypeAnnotations"),
    file: "vault/access.py",
    line: 1,
    status: "wontfix",
    firstSeen: "2026-06-05 09:41",
    snippet: "def get_secret(user, secret_id):",
  },
  {
    id: "f-036",
    reviewId: "rev-009",
    repoId: "hancloud-web",
    severity: "minor",
    type: "security",
    rule: "transitive-dep-audit",
    ruleDesc: copy("afterTheUpgradeItIsNecessaryTo"),
    file: "package.json",
    line: 3,
    status: "fixed",
    firstSeen: "2026-06-04 09:12",
    snippet: '"vite": "5.4.11"',
  },
];
