import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "paymentRefundCallbackConnectsToThirdParty": "支付退款回调接入第三方网关",
    "zhouMubai": "周慕白",
    "seriousIssueExceedsTheUpperLimit": "严重问题 2 超过上限 0",
    "exportAsyncFunctionHandlerefundcallbackReqRequestConst": "export async function handleRefundCallback(req: Request) {\n  const { orderId, amount, sign } = req.body;\n  // 验签\n  if (!verifySign(req.body, sign)) {\n    return { ok: false, msg: \"签名校验失败\" };\n  }\n  // 直接拼接 orderId 进 SQL\n  await db.query(\n    'UPDATE orders SET status = \"refunded\", refund_amount = ' +\n      amount +\n      ' WHERE id = ' + orderId\n  );\n  await notifyUser(orderId);\n  return { ok: true };\n}",
    "aiCensor": "AI 审查官",
    "sqlInjectionOrderidAmountIsDirectlyConcatenated": "SQL 注入：orderId / amount 直接字符串拼接进 UPDATE 语句，攻击者可构造 `1; DROP TABLE orders` 篡改任意订单。必须用参数化查询。",
    "aiCensor2": "AI 审查官",
    "weakControlThirdPartyGatewayCallbacksWill": "缺幂等控制：第三方网关回调会重试，同一 orderId 可能多次进入此函数，导致重复退款 / 重复通知。需先查询订单当前状态或加唯一回调流水号。",
    "aiCensor3": "AI 审查官",
    "notifyuserDoesNotProvideAFailureSafety": "notifyUser 未 await 的副作用未做失败兜底；且通知失败不应阻塞回调成功响应，建议改为 fire-and-forget + 落日志。",
    "aiCensor4": "AI 审查官",
    "ifVerificationFailsTheXxStatusCode": "验签失败应返回 4xx 状态码并记录告警日志，当前仅返回业务体易被忽略。",
    "securitySensitivePathsTheStrongestModel": "安全敏感路径 → 最强模型",
    "constSecretSkLiveF3c2a9d4e1bTodoWas": "const SECRET = \"sk_live_8f3c2a9d4e1b\"; // TODO 上线前替换\n\nexport function verifySign(\n  body: Record<string, unknown>,\n  sign: string,\n): boolean {\n  const raw = Object.keys(body)\n    .sort()\n    .map((k) => k + \"=\" + body[k])\n    .join(\"&\");\n  const hash = md5(raw + SECRET);\n  return hash == sign;\n}",
    "aiCensor5": "AI 审查官",
    "hardcodeProductionKeysSkLiveTheReal": "硬编码生产密钥：sk_live_ 前缀的真实密钥写进源码会随仓库泄露。必须从环境变量 / 密钥管理服务读取，并立即轮换该密钥。",
    "constSecretSkLiveF3c2a9d4e1bTodoWas2": "const SECRET = \"sk_live_8f3c2a9d4e1b\"; // TODO 上线前替换",
    "constSecretProcessEnvPaySecretIf": "const SECRET = process.env.PAY_SECRET;\nif (!SECRET) throw new Error(\"PAY_SECRET 未配置\");",
    "aiCensor6": "AI 审查官",
    "md5IsNoLongerSecureAndUses": "MD5 已不安全且使用 == 宽松比较易受时序攻击。建议改用 HMAC-SHA256 + crypto.timingSafeEqual 常量时间比较。",
    "securitySensitivePathsTheStrongestModel2": "安全敏感路径 → 最强模型",
    "developAReviewPlan": "制定审查计划",
    "changesInvolvePaymentRefundCallbacksAndSignature": "改动涉及支付退款回调与验签，命中安全敏感路径，升级到 Opus 做深度安全审计：先静态扫描，再 grep 注入/密钥模式，最后跑测试。",
    "runEslintSecurityPlugin": "运行 ESLint + 安全插件",
    "runTheSemgrepSecurityRuleSet": "运行 Semgrep 安全规则集",
    "inferenceCallbackIdempotency": "推理回调幂等性",
    "thirdPartyPaymentGatewaysWillRetryExponentially": "第三方支付网关在未收到 2xx 时会按指数退避重试。当前实现无任何去重，重放同一 orderId 会触发重复 UPDATE 与重复 notifyUser。结合无参数化查询的 SQL，这是可被外部直接利用的高危链路，必须 block。",
    "runUnitTests": "运行单元测试",
    "testsPassedFailedButLacksReplayInjection": "Tests: 6 passed, 0 failed — 但缺少重放/注入场景用例",
    "reviewConclusions": "审查结论",
    "threeSeriousIssuesWereFoundSqlInjection": "发现 3 个严重问题（SQL 注入、缺幂等、硬编码密钥），门禁判定 block。建议补参数化查询、幂等流水号与密钥外置后重新提交。",
    "optimizationOfWorkbenchResourceListAggregationAnd": "工作台资源列表聚合与排序优化",
    "shenZhiwei": "沈知微",
    "exportFunctionBuildlistItemsItemTagsTag": "export function buildList(items: Item[], tags: Tag[]) {\n  const result: Enriched[] = [];\n  for (const it of items) {\n    // 每个 item 都全量扫一遍 tags\n    for (const t of tags) {\n      if (t.id === it.tagId) {\n        result.push({ ...it, tagName: t.name });\n      }\n    }\n  }\n  // 同步刷新缓存\n  refreshCache(result);\n  return result.sort((a, b) => a.tagName.length - b.tagName.length);\n}",
    "aiCensor7": "AI 审查官",
    "oNComplexityDualLoopOfItems": "O(n²) 复杂度：items × tags 双重循环。资源列表上千条时会明显卡顿。应先把 tags 建成 Map<id, name> 再 O(1) 查找。",
    "constResultEnrichedForConstItOf": "  const result: Enriched[] = [];\n  for (const it of items) {\n    // 每个 item 都全量扫一遍 tags\n    for (const t of tags) {\n      if (t.id === it.tagId) {\n        result.push({ ...it, tagName: t.name });\n      }\n    }\n  }",
    "aiCensor8": "AI 审查官",
    "nullPointerRiskTagnameMayBeUndefined": "空指针风险：tagName 可能 undefined（item 无匹配 tag），sort 里 a.tagName.length 会抛 TypeError。需提供默认值或过滤。",
    "aiCensor9": "AI 审查官",
    "inDoubleLayerLoopsItemsWithoutMatching": "双层循环里 item 无匹配 tag 时会被直接丢弃，与旧实现（保留 item、tagName 为 undefined）行为不一致，可能造成列表条目缺失。",
    "aiCensor10": "AI 审查官",
    "toSynchronizeSideEffectsRefreshcacheIsMixed": "refreshCache 为同步副作用混在纯数据构建函数里，建议拆分以保持 buildList 可测试、无副作用。",
    "defaultEqualizationModel": "默认 → 均衡模型",
    "exportFunctionRefreshcacheRowsEnrichedForgotAwait": "export function refreshCache(rows: Enriched[]) {\n  // 忘了 await，缓存写入与后续读取存在竞态\n  cache.set(\"dashboard:list\", rows);\n  log.info(\"cache refreshed: \" + rows.length);\n}",
    "aiCensor11": "AI 审查官",
    "asynchronousWritingWithoutAwaitCacheSetReturns": "未 await 的异步写入：cache.set 返回 Promise 但被丢弃，写入未完成就返回，调用方紧接着读缓存会拿到旧值。要么 await，要么显式标注 fire-and-forget。",
    "exportFunctionRefreshcacheRowsEnrichedForgotAwait2": "export function refreshCache(rows: Enriched[]) {\n  // 忘了 await，缓存写入与后续读取存在竞态\n  cache.set(\"dashboard:list\", rows);",
    "defaultEqualizationModel2": "默认 → 均衡模型",
    "testProfileEconomicModel": "测试/配置文件 → 经济模型",
    "developAReviewPlan2": "制定审查计划",
    "changedToFrontendWorkbenchListAggregationWith": "改动为前端工作台列表聚合，普通业务逻辑走 Sonnet；先性能静态分析，再核对边界与空值。",
    "runEslint": "运行 ESLint",
    "analyzeComplexityAndNullValues": "分析复杂度与空值",
    "theBuildlistInnerLayerTraversesTagsFor": "buildList 内层对每个 item 全量遍历 tags，时间复杂度 O(n·m)。当列表规模到千级时是可感知的卡顿。同时 tagName 可能 undefined，后续 sort 比较 .length 会运行时崩溃——这两点是本次主要风险。",
    "runUnitTests2": "运行单元测试",
    "reviewConclusions2": "审查结论",
    "noSeriousIssuesQualityScorePassingAccess": "无严重问题，质量分 71 通过门禁。建议把 tags 改 Map 查找、给 tagName 兜底，并修复未 await 的缓存写入。",
    "keyLibraryMasterKeyDerivationAndTenant": "密钥库主密钥派生与租户访问控制",
    "luHeng": "陆衡",
    "seriousIssueExceedingTheUpperLimitOf": "严重问题 1 超过上限 0",
    "defDeriveKeyPasswordStrSaltBytes": "def derive_key(password: str, salt: bytes = b\"vault\") -> bytes:\n    # 用固定盐 + 低迭代次数派生主密钥\n    return hashlib.pbkdf2_hmac(\n        \"sha256\", password.encode(), salt, 1000\n    )\n\n\ndef encrypt(plain: bytes, key: bytes) -> bytes:\n    cipher = AES.new(key, AES.MODE_ECB)\n    pad = 16 - len(plain) % 16\n    plain += bytes([pad]) * pad\n    return cipher.encrypt(plain)",
    "aiCensor12": "AI 审查官",
    "aesEcbModeIsInsecureIdenticalPlaintext": "AES-ECB 模式不安全：相同明文块产生相同密文块，会泄露数据模式。密钥库加密必须用带随机 IV 的 AES-GCM（兼具机密性与完整性）。",
    "aiCensor13": "AI 审查官",
    "fixedDefaultSaltBVaultSharingThe": "固定默认盐 b\"vault\"：所有租户共用同一盐会让彩虹表攻击可行，盐必须每条记录随机生成并与密文一同存储。",
    "aiCensor14": "AI 审查官",
    "pbkdf2IterationsHaveBeenReducedFromTo": "PBKDF2 迭代次数从 200000 降到 1000，大幅削弱抗暴力破解能力。OWASP 2026 建议 PBKDF2-SHA256 ≥ 600000 次。",
    "aiCensor15": "AI 审查官",
    "theNoteExplainsUnsafePracticesButDoes": "注释说明了不安全做法但未给出整改 TODO，建议直接修复而非保留弱实现。",
    "securitySensitivePathsTheStrongestModel3": "安全敏感路径 → 最强模型",
    "defGetSecretUserSecretIdSecret": "def get_secret(user, secret_id):\n    secret = db.find(secret_id)\n    # 跨租户校验被注释掉了\n    # if secret.tenant_id != user.tenant_id:\n    #     raise Forbidden()\n    audit.log(user.id, secret_id)\n    return secret",
    "aiCensor16": "AI 审查官",
    "overPermissionAccessIdorCrossTenantValidation": "越权访问（IDOR）：跨租户校验被注释掉，任意用户传入他人 secret_id 即可读取其密钥。必须恢复 tenant_id 校验。",
    "crossTenantValidationWasCommentedOutIf": "    # 跨租户校验被注释掉了\n    # if secret.tenant_id != user.tenant_id:\n    #     raise Forbidden()",
    "securitySensitivePathsTheStrongestModel4": "安全敏感路径 → 最强模型",
    "testProfileEconomicModel2": "测试/配置文件 → 经济模型",
    "developAReviewPlan3": "制定审查计划",
    "coreKeyLibraryEncryptionAccessControlAll": "密钥库核心加密 + 访问控制，全部命中安全敏感路径，升级 Opus。重点核对加密模式、KDF 强度与多租户隔离。",
    "runTheBanditSecurityScan": "运行 Bandit 安全扫描",
    "reasoningAboutMultipleTenantIsolation": "推理多租户隔离",
    "accessPyTenantIdChecksTheEntire": "access.py 把 tenant_id 校验整段注释，get_secret 仅凭 secret_id 取数。这是典型 IDOR：枚举 secret_id 即可跨租户读密钥。配合 crypto.py 的 ECB 模式，泄露风险叠加放大，必须 block。",
    "runPytest": "运行 pytest",
    "passedButLacksOverreachAndGcmIntegrity": "2 passed — 但缺少越权与 GCM 完整性用例",
    "reviewConclusions3": "审查结论",
    "criticalEcbEncryptionCriticalFixedSaltLow": "1 个严重（ECB 加密）+ 2 个重要（固定盐、低迭代、越权），门禁 block。恢复租户校验、改 AES-GCM、随机盐 + 高迭代后重审。",
    "theNumberOfCornerLabelsInThe": "购物车角标数量同步修复",
    "linXi": "林夕",
    "coverageIsBelow": "覆盖率 55% 低于 60%",
    "exportFunctionBadgecountItemsCartitemItShould": "export function badgeCount(items: CartItem[]) {\n  // 应按数量求和而非条目数\n  return items.reduce((s, it) => s + it.qty, 0);\n}",
    "aiCensor17": "AI 审查官",
    "theInitialValueOfReduceIsCorrect": "reduce 初始值正确，但 it.qty 可能为 undefined（脏数据），建议 + (it.qty ?? 0) 兜底。",
    "defaultEqualizationModel3": "默认 → 均衡模型",
    "developAReviewPlan4": "制定审查计划",
    "repairTheCartCornerCountInA": "小范围修复购物车角标计数，走 Sonnet。",
    "runEslint2": "运行 ESLint",
    "checkCountingSemantics": "核对计数语义",
    "theOldImplementationUsesItemsLengthTo": "旧实现用 items.length 把每个商品计 1，与实际购买数量不符。新实现 reduce 求和正确，仅需对 qty 做空值兜底。覆盖率偏低，正在补充用例…",
    "unifiedButtonRoundedCornersAndFloatingState": "统一按钮圆角与悬浮态",
    "shenZhiwei2": "沈知微",
    "aiCensor18": "AI 审查官",
    "itIsRecommendedToSubtractRoundedCorners": "建议把圆角值抽成 design token（如 radius-md），避免散落的 rounded-* 不一致。",
    "defaultEqualizationModel4": "默认 → 均衡模型",
    "developAReviewPlan5": "制定审查计划",
    "justAStyleChangeGoThroughIt": "纯样式改动，快速过一遍。",
    "runEslint3": "运行 ESLint",
    "reviewConclusions4": "审查结论",
    "qualityScoreForAccessControlOnlyTokenization": "质量分 99 通过门禁，仅 1 条 token 化建议。",
    "batchPaymentOnBehalfOfTaskScheduling": "批量代付任务调度",
    "zhouMubai2": "周慕白",
    "reviewExecutionFailureDependencyInstallationTimedOut": "审查执行失败：依赖安装超时，未产出结果",
    "securitySensitivePathsTheStrongestModel5": "安全敏感路径 → 最强模型",
    "developAReviewPlan6": "制定审查计划",
    "batchPaymentOnBehalfInvolvesFundsAnd": "代付批处理涉及资金，升级 Opus。",
    "installationDependency": "安装依赖",
    "etimedoutRegistryPullTimeoutReviewEnvironmentCannot": "ETIMEDOUT: registry 拉取超时，审查环境无法构建",
    "censorshipInterrupted": "审查中断",
    "dependencyInstallationFailedNoResultsWereProduced": "依赖安装失败，本次审查未产出结果，请重试。",
    "couponStackingRules": "优惠券叠加规则",
    "linXi2": "林夕",
    "inTheQueueTheReviewHasNot": "排队中，尚未开始审查",
    "defaultEqualizationModel5": "默认 → 均衡模型",
    "awaitingReview": "等待审查",
    "theTaskHasBeenQueuedAndIs": "任务已入队，等待审查 worker 空闲。",
    "fillInTheFieldsAndConfigurationOf": "审计日志补字段与配置",
    "luHeng2": "陆衡",
    "coverageRateIsBelow": "覆盖率 48% 低于 60%",
    "aiCensor19": "AI 审查官",
    "printingToStdoutInAuditLogsMay": "审计日志里 print 到 stdout 可能把用户标识打进容器日志，造成 PII 泄露，应移除或脱敏后走结构化日志。",
    "aiCensor20": "AI 审查官",
    "byDefaultIpNoneCausesALarge": "ip 默认 None 会让大量审计记录缺失来源，建议在调用层强制传入。",
    "defaultEqualizationModel6": "默认 → 均衡模型",
    "testProfileEconomicModel3": "测试/配置文件 → 经济模型",
    "developAReviewPlan7": "制定审查计划",
    "auditLogFieldExtensionNormalChangesRun": "审计日志字段扩展，普通改动走 Sonnet，配置文件走 Haiku。",
    "runRuff": "运行 ruff",
    "runPytest2": "运行 pytest",
    "testsPassedCoverage": "Tests: 3 passed — 覆盖率 48%",
    "reviewConclusions5": "审查结论",
    "qualityScoreButCoverageRateIsSubstandard": "质量分 86 但覆盖率 48% 不达标，门禁 block。补测试并移除 print 后通过。",
    "upgradeBuildDependenciesToTheLatestMinor": "升级构建依赖到最新小版本",
    "guYuanzhou": "顾远舟",
    "aiCensor21": "AI 审查官",
    "itIsRecommendedToUpdateTheLockfile": "建议同步更新 lockfile 并跑一次 audit，确认无新引入的高危传递依赖。",
    "testProfileEconomicModel4": "测试/配置文件 → 经济模型",
    "developAReviewPlan8": "制定审查计划",
    "dependsOnVersionUpgradesConfigurationFilesAre": "依赖版本提升，配置文件走 Haiku 快速核对。",
    "runNpmAudit": "运行 npm audit",
    "reviewConclusions6": "审查结论",
    "qualityScoreForPassingAccessControlOnly": "质量分 99 通过门禁，仅提醒同步 lockfile。",
    "virtualRollingRestructuringOfProductListings": "商品列表虚拟滚动重构",
    "linXi3": "林夕",
    "renderAllProductsAtOnceOldImplementation": "// 一次性渲染全部商品（旧实现，省略大段 JSX）\nexport function ProductList({ items }: { items: Product[] }) {\n  return <div>{items.map((it) => <Card key={it.id} item={it} />)}</div>;\n}",
    "introducesVirtualScrollingRenderingOnlyTheViewpoint": "// 引入虚拟滚动，仅渲染可视区（大文件，省略大段 JSX）\nexport function ProductList({ items }: { items: Product[] }) {\n  const v = useVirtualizer({ count: items.length, estimateSize: () => 96 });\n  return (\n    <div ref={parentRef} style={{ overflow: \"auto\", height: 600 }}>\n      {v.getVirtualItems().map((row) => (\n        <Card key={items[row.index].id} item={items[row.index]} />\n      ))}\n    </div>\n  );\n}",
    "aiCensor22": "AI 审查官",
    "estimatesizeFixedAtIfTheActualCard": "estimateSize 固定 96 与实际卡片高度不一致时会出现滚动抖动，建议测量真实高度或用动态测量。",
    "aiCensor23": "AI 审查官",
    "containerHeightIsSetToWhichWill": "容器 height 写死 600，小屏机型会露白，建议用百分比 / 视口高度自适应。",
    "largeFileBalancedModel": "大文件 → 均衡模型",
    "developAReviewPlan9": "制定审查计划",
    "largeFilesLinesAreVirtuallyRolledAnd": "大文件（>300 行）虚拟滚动重构，命中大文件分支走 Sonnet。",
    "runEslint4": "运行 ESLint",
    "checkTheAccuracyOfVirtualization": "核对虚拟化正确性",
    "theUsevirtualizerKeyIsBoundToThe": "useVirtualizer 的 key 绑定到真实 item.id 而非 row.index，避免复用错位，方向正确。主要风险是固定行高与固定容器高度的适配，列为 minor。",
    "runUnitTests3": "运行单元测试",
    "reviewConclusions7": "审查结论",
    "qualityScorePassesAccessControlWithAdaptive": "质量分 92 通过门禁，2 条尺寸自适应优化建议。",
  },
  en: {
    "paymentRefundCallbackConnectsToThirdParty": "Payment refund callback connects to third-party gateways",
    "zhouMubai": "Zhou Mubai",
    "seriousIssueExceedsTheUpperLimit": "Serious issue 2 exceeds the upper limit 0",
    "exportAsyncFunctionHandlerefundcallbackReqRequestConst": "export async function handleRefundCallback(req: Request) {\n  const { orderId, amount, sign } = req.body;\n  // Verify the signature\n  if (!verifySign(req.body, sign)) {\n    return { ok: false, msg: \"Signature validation failed\" };\n  }\n  // Vulnerable: directly concatenates orderId into SQL\n  await db.query(\n    'UPDATE orders SET status = \"refunded\", refund_amount = ' +\n      amount +\n      ' WHERE id = ' + orderId\n  );\n  await notifyUser(orderId);\n  return { ok: true };\n}",
    "aiCensor": "AI Censor",
    "sqlInjectionOrderidAmountIsDirectlyConcatenated": "SQL injection: orderId and amount are concatenated directly into an UPDATE statement, so an attacker could inject a payload such as '1; DROP TABLE orders'. Use parameterized queries.",
    "aiCensor2": "AI Censor",
    "weakControlThirdPartyGatewayCallbacksWill": "Weak Control: Third-party gateway callbacks will retry, and the same orderId may enter this function multiple times, resulting in repeated refunds or duplicate notifications. You need to first check the current order status or add a unique callback serial number.",
    "aiCensor3": "AI Censor",
    "notifyuserDoesNotProvideAFailureSafety": "notifyUser does not provide a failure safety net for the side effect of not waiting for it; Also, notification failures should not block callback success responses; it is recommended to change to fire-and-forget + log instead.",
    "aiCensor4": "AI Censor",
    "ifVerificationFailsTheXxStatusCode": "If verification fails, the 4xx status code should be returned and the alarm log recorded; currently, only the business entity is returned, which is easily ignored.",
    "securitySensitivePathsTheStrongestModel": "Security-sensitive paths → the strongest model",
    "constSecretSkLiveF3c2a9d4e1bTodoWas": "const SECRET = \"sk_live_8f3c2a9d4e1b\"; // TODO: replace before production\n\nexport function verifySign(\n  body: Record<string, unknown>,\n  sign: string,\n): boolean {\n  const raw = Object.keys(body).sort().map((k) => k + \"=\" + body[k]).join(\"&\");\n  const hash = md5(raw + SECRET);\n  return hash == sign;\n}",
    "aiCensor5": "AI Censor",
    "hardcodeProductionKeysSkLiveTheReal": "Hardcode production keys: sk_live_ The real key with the prefix is written into the source code and leaked with the repository. It must be read from the environment variable / key management service and immediately rotated the key.",
    "constSecretSkLiveF3c2a9d4e1bTodoWas2": "const SECRET = \"sk_live_8f3c2a9d4e1b\"; TODO was replaced before going live",
    "constSecretProcessEnvPaySecretIf": "const SECRET = process.env.PAY_SECRET; \nif (! SECRET) throw new Error(\"PAY_SECRET unconfigured\");",
    "aiCensor6": "AI Censor",
    "md5IsNoLongerSecureAndUses": "MD5 is no longer secure and uses == Lenient, making it more susceptible to timing attacks. It is recommended to switch to HMAC-SHA256 + crypto.timingSafeEqual for constant time comparison.",
    "securitySensitivePathsTheStrongestModel2": "Security-sensitive paths → the strongest model",
    "developAReviewPlan": "Develop a review plan",
    "changesInvolvePaymentRefundCallbacksAndSignature": "Changes involve payment refund callbacks and signature verification, hitting security-sensitive paths, and upgrading to Opus for deep security audits: first static scan, then grep injection/key mode, and finally testing.",
    "runEslintSecurityPlugin": "Run ESLint + Security Plugin",
    "runTheSemgrepSecurityRuleSet": "Run the Semgrep security rule set",
    "inferenceCallbackIdempotency": "Inference callback idempotency",
    "thirdPartyPaymentGatewaysWillRetryExponentially": "Third-party payment gateways will retry exponentially if 2xx is not received. Currently, there is no deduplication; replaying the same orderId will trigger repeated UPDATE and repeated notifyUser. Combined with SQL without parameterized queries, this is a high-risk link that can be directly exploited externally and must be blocked.",
    "runUnitTests": "Run unit tests",
    "testsPassedFailedButLacksReplayInjection": "Tests: 6 passed, 0 failed — but lacks replay/injection scenario use cases",
    "reviewConclusions": "Review conclusions",
    "threeSeriousIssuesWereFoundSqlInjection": "Three critical findings block the quality gate: SQL injection, missing idempotency protection, and a hard-coded signing secret. Use parameterized queries, add an idempotency key, move secrets to external configuration, and then resubmit the review.",
    "optimizationOfWorkbenchResourceListAggregationAnd": "Optimization of workbench resource list aggregation and sorting",
    "shenZhiwei": "Shen Zhiwei",
    "exportFunctionBuildlistItemsItemTagsTag": "export function buildList(items: Item[], tags: Tag[]) {\n  const result: Enriched[] = [];\n  for (const it of items) {\n    // Scans every tag for every item\n    for (const t of tags) {\n      if (t.id === it.tagId) {\n        result.push({ ...it, tagName: t.name });\n      }\n    }\n  }\n  // Refresh the cache synchronously\n  refreshCache(result);\n  return result.sort((a, b) => a.tagName.length - b.tagName.length);\n}",
    "aiCensor7": "AI Censor",
    "oNComplexityDualLoopOfItems": "O(n²) Complexity: Dual loop of items × tags. When the resource list has thousands of entries, it will noticeably lag. You should first create tags as Map<id, name> then use O(1) to search.",
    "constResultEnrichedForConstItOf": "const result: Enriched[] = [];\nfor (const it of items) {\n  // Scans every tag for every item\n  for (const t of tags) {\n    if (t.id === it.tagId) {\n      result.push({ ...it, tagName: t.name });\n    }\n  }\n}",
    "aiCensor8": "AI Censor",
    "nullPointerRiskTagnameMayBeUndefined": "Null pointer risk: tagName may be undefined (item has no matching tag), and a.tagName.length in sort will throw a TypeError. Default values or filters must be provided.",
    "aiCensor9": "AI Censor",
    "inDoubleLayerLoopsItemsWithoutMatching": "In double-layer loops, items without matching tags are directly discarded, which is inconsistent with the old implementation (keeping items and tagnames undefined), which may cause list entries to be missing.",
    "aiCensor10": "AI Censor",
    "toSynchronizeSideEffectsRefreshcacheIsMixed": "To synchronize side effects, refreshCache is mixed into a pure data build function. It is recommended to split it to keep buildList testable and free of side effects.",
    "defaultEqualizationModel": "Default → equalization model",
    "exportFunctionRefreshcacheRowsEnrichedForgotAwait": "export function refreshCache(rows: Enriched[]) {\n  // Missing await: subsequent reads can race the cache write\n  cache.set(\"dashboard:list\", rows);\n  log.info(\"cache refreshed: \" + rows.length);\n}",
    "aiCensor11": "AI Censor",
    "asynchronousWritingWithoutAwaitCacheSetReturns": "Asynchronous writing without await: cache.set returns a promise but is discarded; if the write is not completed, it returns, and the caller immediately reads the cache to get the old value. Either await or explicitly annotate fire-and-forget.",
    "exportFunctionRefreshcacheRowsEnrichedForgotAwait2": "export function refreshCache(rows: Enriched[]) {\n  // Missing await: subsequent reads can race the cache write\n  cache.set(\"dashboard:list\", rows);",
    "defaultEqualizationModel2": "Default → equalization model",
    "testProfileEconomicModel": "Test/profile → economic model",
    "developAReviewPlan2": "Develop a review plan",
    "changedToFrontendWorkbenchListAggregationWith": "Changed to frontend workbench list aggregation, with normal business logic running Sonnet; First, perform static performance analysis, then check boundaries and null values.",
    "runEslint": "Run ESLint",
    "analyzeComplexityAndNullValues": "Analyze complexity and null values",
    "theBuildlistInnerLayerTraversesTagsFor": "The buildList inner layer traverses tags for every item, with a time complexity of O(n · m). When the list size reaches thousands, it causes noticeable lag. At the same time, tagName may be undefined, and subsequent sort comparisons with.length may crash when running—these are the main risks this time.",
    "runUnitTests2": "Run unit tests",
    "reviewConclusions2": "Review conclusions",
    "noSeriousIssuesQualityScorePassingAccess": "No serious issues, quality score 71 passing the quality gate. Suggest changing tags to Map for lookup, adding tagName as a backup, and fixing cache writes without await.",
    "keyLibraryMasterKeyDerivationAndTenant": "Key library master key derivation and tenant access control",
    "luHeng": "Lu Heng",
    "seriousIssueExceedingTheUpperLimitOf": "Serious issue 1: Exceeding the upper limit of 0",
    "defDeriveKeyPasswordStrSaltBytes": "def derive_key(password: str, salt: bytes = b\"vault\") -> bytes: \n # Derive the master key using fixed salt + low iterations\n return hashlib.pbkdf2_hmac( \n \"sha256\", password.encode(), salt, 1000\n )\n\n\ndef encrypt(plain: bytes, key: bytes) -> bytes: \n cipher = AES.new(key, AES. MODE_ECB)\n pad = 16 - len(plain) % 16\n plain += bytes([pad]) * pad\n return cipher.encrypt(plain)",
    "aiCensor12": "AI Censor",
    "aesEcbModeIsInsecureIdenticalPlaintext": "AES-ECB mode is insecure: identical plaintext blocks produce identical ciphertext blocks, which can expose data patterns. Key library encryption must be done using AES-GCM with random IV (combining confidentiality and integrity).",
    "aiCensor13": "AI Censor",
    "fixedDefaultSaltBVaultSharingThe": "Fixed default salt b\"vault\": Sharing the same salt among all tenants makes rainbow table attacks possible; each salt must be randomly generated and stored together with ciphertext.",
    "aiCensor14": "AI Censor",
    "pbkdf2IterationsHaveBeenReducedFromTo": "PBKDF2 iterations have been reduced from 200,000 to 1,000, significantly weakening its resistance to brute-force attacks. OWASP 2026 recommends PBKDF2-SHA256 ≥ 600,000 iterations.",
    "aiCensor15": "AI Censor",
    "theNoteExplainsUnsafePracticesButDoes": "The note explains unsafe practices but does not provide corrective TODO; it is recommended to fix them directly rather than keep weak implementations.",
    "securitySensitivePathsTheStrongestModel3": "Security-sensitive paths → the strongest model",
    "defGetSecretUserSecretIdSecret": "def get_secret(user, secret_id): \n secret = db.find(secret_id)\n # Cross-tenant validation was commented out\n # if secret.tenant_id!= user.tenant_id: \n # raise Forbidden()\n audit.log(user.id, secret_id)\n return secret",
    "aiCensor16": "AI Censor",
    "overPermissionAccessIdorCrossTenantValidation": "Broken object-level authorization (IDOR): the tenant check is commented out, allowing a user to read another tenant's key by supplying its secret_id. Restore tenant_id validation.",
    "crossTenantValidationWasCommentedOutIf": "# Cross-tenant validation was commented out\n # if secret.tenant_id!= user.tenant_id: \n # raise Forbidden()",
    "securitySensitivePathsTheStrongestModel4": "Security-sensitive paths → the strongest model",
    "testProfileEconomicModel2": "Test/profile → economic model",
    "developAReviewPlan3": "Develop a review plan",
    "coreKeyLibraryEncryptionAccessControlAll": "Core key library encryption + access control, all hitting secure sensitive paths, Opus upgrades. Key verification of encryption modes, KDF strength, and multi-tenant isolation.",
    "runTheBanditSecurityScan": "Run the Bandit security scan",
    "reasoningAboutMultipleTenantIsolation": "Reasoning about multiple tenant isolation",
    "accessPyTenantIdChecksTheEntire": "access.py tenant_id checks the entire comment, get_secret only retrieves the secret_id. This is a typical IDOR: enumerate secret_id to read keys across tenants. Combined with crypto.py's ECB model, the risk of leakage is amplified and must be blocked.",
    "runPytest": "Run pytest",
    "passedButLacksOverreachAndGcmIntegrity": "2 passed — but lacks overreach and GCM integrity use cases",
    "reviewConclusions3": "Review conclusions",
    "criticalEcbEncryptionCriticalFixedSaltLow": "1 critical (ECB encryption) + 2 critical (fixed salt, low iteration, overreach), quality gate blocked the review. Restore tenant validation, change AES-GCM, random salt + high iteration post-re-review.",
    "theNumberOfCornerLabelsInThe": "The cart badge count in the shopping cart has been synchronized and fixed",
    "linXi": "Lin Xi",
    "coverageIsBelow": "Coverage is 55% below 60%",
    "exportFunctionBadgecountItemsCartitemItShould": "export function badgeCount(items: CartItem[]) {\n  // Sum quantities, not line items\n  return items.reduce((sum, item) => sum + item.qty, 0);\n}",
    "aiCensor17": "AI Censor",
    "theInitialValueOfReduceIsCorrect": "The initial value of reduce is correct, but it.qty may be undefined (dirty data). It is recommended to use + (it.qty?? 0) as a backup.",
    "defaultEqualizationModel3": "Default → equalization model",
    "developAReviewPlan4": "Develop a review plan",
    "repairTheCartCornerCountInA": "Repair the cart corner count in a small area, then go to Sonnet.",
    "runEslint2": "Run ESLint",
    "checkCountingSemantics": "Check counting semantics",
    "theOldImplementationUsesItemsLengthTo": "The old implementation uses items.length to count each product as 1, which does not match the actual purchase quantity. The new implementation reduces sum correctly; only the shorting value for qty is needed as a backup. Coverage is low, currently supplementing use cases...",
    "unifiedButtonRoundedCornersAndFloatingState": "Unified button rounded corners and floating state",
    "shenZhiwei2": "Shen Zhiwei",
    "aiCensor18": "AI Censor",
    "itIsRecommendedToSubtractRoundedCorners": "It is recommended to subtract rounded corners into design tokens (such as radius-md) to avoid scattered rounded-* inconsistencies.",
    "defaultEqualizationModel4": "Default → equalization model",
    "developAReviewPlan5": "Develop a review plan",
    "justAStyleChangeGoThroughIt": "Just a style change, go through it quickly.",
    "runEslint3": "Run ESLint",
    "reviewConclusions4": "Review conclusions",
    "qualityScoreForAccessControlOnlyTokenization": "Quality score 99 for access control, only 1 wording suggestion.",
    "batchPaymentOnBehalfOfTaskScheduling": "Batch payment on behalf of task scheduling",
    "zhouMubai2": "Zhou Mubai",
    "reviewExecutionFailureDependencyInstallationTimedOut": "Review execution failure: Dependency installation timed out, no results generated",
    "securitySensitivePathsTheStrongestModel5": "Security-sensitive paths → the strongest model",
    "developAReviewPlan6": "Develop a review plan",
    "batchPaymentOnBehalfInvolvesFundsAnd": "Batch payment on behalf involves funds and upgrades to Opus.",
    "installationDependency": "Installation dependency",
    "etimedoutRegistryPullTimeoutReviewEnvironmentCannot": "ETIMEDOUT: registry pull timeout, review environment cannot be built",
    "censorshipInterrupted": "Censorship interrupted",
    "dependencyInstallationFailedNoResultsWereProduced": "Dependency installation failed; no results were produced during this review. Please try again.",
    "couponStackingRules": "Coupon stacking rules",
    "linXi2": "Lin Xi",
    "inTheQueueTheReviewHasNot": "In the queue, the review has not yet begun",
    "defaultEqualizationModel5": "Default → equalization model",
    "awaitingReview": "Awaiting review",
    "theTaskHasBeenQueuedAndIs": "The task has been queued and is waiting to review worker availability.",
    "fillInTheFieldsAndConfigurationOf": "Fill in the fields and configuration of audit logs",
    "luHeng2": "Lu Heng",
    "coverageRateIsBelow": "Coverage rate is 48%, below 60%",
    "aiCensor19": "AI Censor",
    "printingToStdoutInAuditLogsMay": "Printing to stdout in audit logs may inscribe user identifiers into container logs, causing PII leaks; these should be removed or desensitized and then processed into structured logs.",
    "aiCensor20": "AI Censor",
    "byDefaultIpNoneCausesALarge": "By default, IP None causes a large number of audit records to miss sources, so it is recommended to force them at the call layer.",
    "defaultEqualizationModel6": "Default → equalization model",
    "testProfileEconomicModel3": "Test/profile → economic model",
    "developAReviewPlan7": "Develop a review plan",
    "auditLogFieldExtensionNormalChangesRun": "Audit log field extension: normal changes run Sonnet, configuration files use Haiku.",
    "runRuff": "Run ruff",
    "runPytest2": "Run pytest",
    "testsPassedCoverage": "Tests: 3 passed — Coverage 48%",
    "reviewConclusions5": "Review conclusions",
    "qualityScoreButCoverageRateIsSubstandard": "Quality score 86 but coverage rate 48% is substandard, quality gate blocked the review. Passed after retesting and removing print.",
    "upgradeBuildDependenciesToTheLatestMinor": "Upgrade build dependencies to the latest minor versions",
    "guYuanzhou": "Gu Yuanzhou",
    "aiCensor21": "AI Censor",
    "itIsRecommendedToUpdateTheLockfile": "It is recommended to update the lockfile simultaneously and run an audit to confirm there are no newly introduced high-risk pass-through dependencies.",
    "testProfileEconomicModel4": "Test/profile → economic model",
    "developAReviewPlan8": "Develop a review plan",
    "dependsOnVersionUpgradesConfigurationFilesAre": "Depends on version upgrades, configuration files are quickly verified by Haiku.",
    "runNpmAudit": "Run npm audit",
    "reviewConclusions6": "Review conclusions",
    "qualityScoreForPassingAccessControlOnly": "Quality score 99 for passing the quality gate, only reminding me to sync lockfile.",
    "virtualRollingRestructuringOfProductListings": "Virtual rolling restructuring of product listings",
    "linXi3": "Lin Xi",
    "renderAllProductsAtOnceOldImplementation": "Render all products at once (old implementation, omitted large JSX sections)\nexport function ProductList({ items }: { items: Product[] }) { \n return <div>{items.map((it) => <Card key={it.id} item={it} />)}</div>; \n}",
    "introducesVirtualScrollingRenderingOnlyTheViewpoint": "Introduces virtual scrolling, rendering only the viewpoint (large files, omitting large JSX sections)\nexport function ProductList({ items }: { items: Product[] }) { \n const v = useVirtualizer({ count: items.length, estimateSize: () => 96 }); \n return ( \n <div ref={parentRef} style={{ overflow: \"auto\", height: 600 }}>\n {v.getVirtualItems().map((row) => ( \n <Card key={items[row.index].id} item={items[row.index]} />\n ))}\n </div>\n ); \n}",
    "aiCensor22": "AI Censor",
    "estimatesizeFixedAtIfTheActualCard": "estimateSize fixed at 96 If the actual card height does not match, rolling shaking may occur. It is recommended to measure the actual height or use dynamic measurement.",
    "aiCensor23": "AI Censor",
    "containerHeightIsSetToWhichWill": "Container height is set to 600, which will show white on small-screen models. It's recommended to use percentage/viewport height for adaptation.",
    "largeFileBalancedModel": "Large file → balanced model",
    "developAReviewPlan9": "Develop a review plan",
    "largeFilesLinesAreVirtuallyRolledAnd": "Large files (>300 lines) are virtually rolled and reconstructed, and the branch of the large file goes through Sonnet.",
    "runEslint4": "Run ESLint",
    "checkTheAccuracyOfVirtualization": "Check the accuracy of virtualization",
    "theUsevirtualizerKeyIsBoundToThe": "The useVirtualizer key is bound to the real item.id instead of row.index, avoiding misalignment and correct direction. The main risk is the adaptation between fixed row heights and fixed container heights, listed as minor.",
    "runUnitTests3": "Run unit tests",
    "reviewConclusions7": "Review conclusions",
    "qualityScorePassesAccessControlWithAdaptive": "Quality score 92 passes the quality gate, with 2 adaptive size optimization suggestions.",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanreview-data-reviews",
  content: t(content),
};

export default dictionary;
