import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "xRecommended": "20.x (推荐)",
    "buildSettings": "构建设置",
    "project": "项目",
    "frameworkPresetsBuildCommandsAndGitIntegration": "的框架预设、构建命令与 Git 集成。",
    "frameworkAndBuild": "框架与构建",
    "framePresets": "框架预设",
    "switchingFrameworksWillAutomaticallyAdjustTheDefault": "切换框架会自动调整默认输出目录",
    "installationCommand": "安装命令",
    "buildCommand": "构建命令",
    "outputDirectory": "输出目录",
    "thePathOfTheBuildProductRelative": "构建产物相对仓库根目录的路径",
    "nodeVersion": "Node 版本",
    "buildSettingsSaved": "构建设置已保存",
    "save": "保存",
    "gitIntegration": "Git 集成",
    "warehouse": "仓库",
    "manageRepositoryConnectionsAtYourSourceCode": "在源代码托管商处管理仓库连接",
    "productionBranch": "生产分支",
    "pushingToThisBranchWillTriggerA": "推送到该分支将触发生产部署",
    "automaticDeployment": "自动部署",
    "automaticallyBuildAndDeployWhenBranchesHave": "分支有新提交时自动构建并部署",
    "automaticDeployment2": "自动部署",
    "prPreviewDeployment": "PR 预览部署",
    "generateIndependentPreviewAddressesForEachPull": "为每个 Pull Request 生成独立预览地址",
    "prPreviewDeployment2": "PR 预览部署",
    "gitIntegrationSettingsSaved": "Git 集成设置已保存",
    "save2": "保存",
    "dangerZone": "危险区",
    "pauseProject": "暂停项目",
    "afterTheSuspensionNewDeploymentsWillStop": "暂停后将停止接收新部署，已有部署继续在线。",
    "pauseProject2": "暂停项目",
    "pauseTheProject": "暂停该项目？",
    "automaticDeploymentWillStopAfterPausingAnd": "暂停后自动部署将停止，可随时恢复。",
    "cancel": "取消",
    "projectHasBeenSuspended": "项目已暂停",
    "confirmPause": "确认暂停",
    "deleteProject": "删除项目",
    "permanentlyDeleteTheProjectDeploymentRecordAnd": "永久删除项目、部署记录与域名绑定，此操作不可撤销。",
    "deleteProject2": "删除项目",
    "deleteThisProject": "删除该项目？",
    "valueAndAllItsDeploymentsAndDomain": "「{0}」及其全部部署、域名绑定将被永久删除，无法恢复。",
    "cancel2": "取消",
    "projectDeleted": "项目已删除",
    "deletePermanently": "永久删除",
    "staticSite": "静态站点",
  },
  en: {
    "xRecommended": "20.x (recommended)",
    "buildSettings": "Build settings",
    "project": "Project",
    "frameworkPresetsBuildCommandsAndGitIntegration": "Framework presets, build commands and Git integration.",
    "frameworkAndBuild": "Framework and Build",
    "framePresets": "Frame presets",
    "switchingFrameworksWillAutomaticallyAdjustTheDefault": "Switching frameworks will automatically adjust the default output directory",
    "installationCommand": "Installation command",
    "buildCommand": "Build command",
    "outputDirectory": "Output directory",
    "thePathOfTheBuildProductRelative": "The path of the build product relative to the root directory of the repository",
    "nodeVersion": "Node version",
    "buildSettingsSaved": "Build settings saved",
    "save": "save",
    "gitIntegration": "Git integration",
    "warehouse": "repository",
    "manageRepositoryConnectionsAtYourSourceCode": "Manage repository connections at your source code host",
    "productionBranch": "production branch",
    "pushingToThisBranchWillTriggerA": "Pushing to this branch will trigger a production deployment",
    "automaticDeployment": "Automatic deployment",
    "automaticallyBuildAndDeployWhenBranchesHave": "Automatically build and deploy when branches have new commits",
    "automaticDeployment2": "Automatic deployment",
    "prPreviewDeployment": "PR preview deployment",
    "generateIndependentPreviewAddressesForEachPull": "Generate independent preview addresses for each Pull Request",
    "prPreviewDeployment2": "PR preview deployment",
    "gitIntegrationSettingsSaved": "Git integration settings saved",
    "save2": "save",
    "dangerZone": "danger zone",
    "pauseProject": "Pause project",
    "afterTheSuspensionNewDeploymentsWillStop": "After the suspension, new deployments will stop being received, and existing deployments will continue to be online.",
    "pauseProject2": "Pause project",
    "pauseTheProject": "Pause the project?",
    "automaticDeploymentWillStopAfterPausingAnd": "Automatic deployment will stop after pausing and can be resumed at any time.",
    "cancel": "Cancel",
    "projectHasBeenSuspended": "Project has been suspended",
    "confirmPause": "Confirm pause",
    "deleteProject": "Delete project",
    "permanentlyDeleteTheProjectDeploymentRecordAnd": "Permanently delete the project, deployment record and domain name binding. This operation is irreversible.",
    "deleteProject2": "Delete project",
    "deleteThisProject": "Delete this project?",
    "valueAndAllItsDeploymentsAndDomain": "\"{0}\" and all its deployments and domain name bindings will be permanently deleted and cannot be restored.",
    "cancel2": "Cancel",
    "projectDeleted": "Project deleted",
    "deletePermanently": "Delete permanently",
    "staticSite": "Static site",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanship-app-settings-page",
  content: t(content),
};

export default dictionary;
