import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "produce": "生产",
    "preview": "预览",
    "all": "全部",
    "produce2": "生产",
    "preview2": "预览",
    "pleaseEnterVariableName": "请输入变量名",
    "pleaseEnterVariableValue": "请输入变量值",
    "chooseAtLeastOneEnvironment": "至少选择一个环境",
    "variableDeleted": "变量已删除",
    "key": "键",
    "value": "值",
    "copied": "已复制",
    "copied2": "已复制",
    "copyTheValueOfValue": "复制 {0} 的值",
    "environment": "环境",
    "update": "更新",
    "operation": "操作",
    "deleteThisVariable": "删除该变量？",
    "valueWillBeRemovedFromTheSelected": "{0} 将从所选环境中移除，下次部署生效。",
    "delete": "删除",
    "cancel": "取消",
    "delete2": "删除",
    "environmentVariables": "环境变量",
    "configureBuildRuntimeVariablesForProductionAnd": "为生产与预览环境配置构建期 / 运行期变量，密文值加密存储。",
    "addNewVariable": "新增变量",
    "variableList": "变量列表",
    "filterByEnvironment": "按环境筛选",
    "thereAreNoEnvironmentVariablesYet": "还没有环境变量",
    "thereAreNoVariablesInThisEnvironment": "该环境下没有变量",
    "afterAddingTheVariableItWillBe": "新增变量后将在下次部署注入构建。",
    "switchToAllToViewVariablesFrom": "切换到「全部」查看其他环境的变量。",
    "addNewVariable2": "新增变量",
    "viewAll": "查看全部",
    "addEnvironmentVariables": "新增环境变量",
    "save": "保存",
    "variableSaved": "变量已保存",
    "valueWillTakeEffectInTheNext": "{0} 将在下次部署生效",
    "variableName": "变量名",
    "suchAsDatabaseUrl": "如 DATABASE_URL",
    "variableValue": "变量值",
    "environment2": "环境",
    "variablesWillBeInjectedIntoTheSelected": "变量将注入所选环境",
    "targetEnvironment": "目标环境",
    "produce3": "生产",
    "preview3": "预览",
    "ciphertext": "密文",
    "whenTurnedOnTheValueWillBe": "开启后值将被加密，列表中以掩码展示",
    "markAsRedacted": "标记为密文",
  },
  en: {
    "produce": "produce",
    "preview": "Preview",
    "all": "All",
    "produce2": "produce",
    "preview2": "Preview",
    "pleaseEnterVariableName": "Please enter variable name",
    "pleaseEnterVariableValue": "Please enter variable value",
    "chooseAtLeastOneEnvironment": "Choose at least one environment",
    "variableDeleted": "Variable deleted",
    "key": "key",
    "value": "value",
    "copied": "Copied",
    "copied2": "Copied",
    "copyTheValueOfValue": "Copy the value of {0}",
    "environment": "environment",
    "update": "update",
    "operation": "Operation",
    "deleteThisVariable": "Delete this variable?",
    "valueWillBeRemovedFromTheSelected": "{0} will be removed from the selected environment and will take effect next time it is deployed.",
    "delete": "Delete",
    "cancel": "Cancel",
    "delete2": "Delete",
    "environmentVariables": "environment variables",
    "configureBuildRuntimeVariablesForProductionAnd": "Configure build/runtime variables for production and preview environments, and store ciphertext values encrypted.",
    "addNewVariable": "Add new variable",
    "variableList": "variable list",
    "filterByEnvironment": "Filter by environment",
    "thereAreNoEnvironmentVariablesYet": "There are no environment variables yet",
    "thereAreNoVariablesInThisEnvironment": "There are no variables in this environment",
    "afterAddingTheVariableItWillBe": "After adding the variable, it will be injected into the build during the next deployment.",
    "switchToAllToViewVariablesFrom": "Switch to \"All\" to view variables from other environments.",
    "addNewVariable2": "Add new variable",
    "viewAll": "View all",
    "addEnvironmentVariables": "Add environment variables",
    "save": "save",
    "variableSaved": "variable saved",
    "valueWillTakeEffectInTheNext": "{0} will take effect in the next deployment",
    "variableName": "variable name",
    "suchAsDatabaseUrl": "Such as DATABASE_URL",
    "variableValue": "variable value",
    "environment2": "environment",
    "variablesWillBeInjectedIntoTheSelected": "Variables will be injected into the selected environment",
    "targetEnvironment": "target environment",
    "produce3": "produce",
    "preview3": "Preview",
    "ciphertext": "ciphertext",
    "whenTurnedOnTheValueWillBe": "When turned on, the value will be encrypted and displayed as a mask in the list.",
    "markAsRedacted": "Mark as redacted",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanship-app-env-page",
  content: t(content),
};

export default dictionary;
