import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "curlValueChatCompletionsHAuthorizationBearer": "curl {0}/chat/completions \\\n  -H \"Authorization: Bearer $HANHUB_KEY\" \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\n    \"model\": \"claude-opus-4-7\",\n    \"messages\": [{\"role\": \"user\", \"content\": \"你好\"}]\n  }'",
    "fromOpenaiImportOpenaiClientOpenaiBase": "from openai import OpenAI\n\nclient = OpenAI(\n    base_url=\"{0}\",\n    api_key=\"$HANHUB_KEY\",\n)\n\nresp = client.chat.completions.create(\n    model=\"claude-opus-4-7\",\n    messages=[{\"role\": \"user\", \"content\": \"你好\"}],\n)\nprint(resp.choices[0].message.content)",
    "importOpenaiFromOpenaiConstClientNew": "import OpenAI from \"openai\";\n\nconst client = new OpenAI({\n  baseURL: \"{0}\",\n  apiKey: process.env.HANHUB_KEY,\n});\n\nconst resp = await client.chat.completions.create({\n  model: \"claude-opus-4-7\",\n  messages: [{ role: \"user\", content: \"你好\" }],\n});\nconsole.log(resp.choices[0].message.content);",
    "linyu": "林屿",
    "owner": "拥有者",
    "forest": "林",
    "zhouNan": "周楠",
    "administrator": "管理员",
    "week": "周",
    "chenXi": "陈曦",
    "developer": "开发者",
    "chen": "陈",
    "zhaoMin": "赵敏",
    "readOnly": "只读",
    "zhao": "赵",
    "baseUrlCopied": "已复制 base_url",
    "accessSettings": "接入设置",
    "quickAccessTeamMembersWebhookAlertsDefault": "快速接入 · 团队成员 · Webhook 告警 · 默认配置",
    "quickAccess": "快速接入",
    "copy": "复制",
    "openaiCompatibleProtocolChangeBaseUrlKey": "OpenAI 兼容协议 · 改 base_url + key 即可接入",
    "codeLanguage": "代码语言",
    "teamMember": "团队成员",
    "invitationLinkCopied": "邀请链接已复制",
    "inviteMembers": "邀请成员",
    "webhookAlert": "Webhook 告警",
    "callbackUrl": "回调 URL",
    "postToThisAddressWhenTheUsage": "用量超阈值 / 余额不足时 POST 到该地址",
    "usageAlarm": "用量告警",
    "balanceAlarm": "余额告警",
    "channelCircuitBreaker": "渠道熔断",
    "testEventSent": "测试事件已发送",
    "testSending": "测试发送",
    "defaultConfiguration": "默认配置",
    "defaultSpeedLimitReqMin": "默认限速（req/min）",
    "initialRateLimitForNewKeys": "新建密钥的初始限速",
    "defaultSpeedLimit": "默认限速",
    "defaultMagnificationGrouping": "默认倍率分组",
    "determineTheGatewaySPriceIncreaseBased": "决定网关在上游价基础上的加价",
    "economy": "经济（1.0×）",
    "standard": "标准（1.05×）",
    "highQuality": "高优（1.1×）",
    "economy2": "经济（1.0×）",
    "standard2": "标准（1.05×）",
    "highQuality2": "高优（1.1×）",
    "automaticallyRetryOnFailure": "失败自动重试",
    "upstreamXxSwitchChannelAndTryAgain": "上游 5xx / 超时时切换渠道重试",
    "automaticallyRetryOnFailure2": "失败自动重试",
    "numberOfRetries": "重试次数",
    "numberOfRetries2": "重试次数",
    "defaultConfigurationSaved": "默认配置已保存",
    "saveSettings": "保存设置",
  },
  en: {
    "curlValueChatCompletionsHAuthorizationBearer": "curl {0}/chat/completions \\\n -H \"Authorization: Bearer $HANHUB_KEY\" \\\n -H \"Content-Type: application/json\" \\\n -d '{\n \"model\": \"claude-opus-4-7\",\n \"messages\": [{\"role\": \"user\", \"content\": \"Hello\"}]\n }'",
    "fromOpenaiImportOpenaiClientOpenaiBase": "from openai import OpenAI\n\nclient = OpenAI(\n base_url=\"{0}\",\n api_key=\"$HANHUB_KEY\",\n)\n\nresp = client.chat.completions.create(\n model=\"claude-opus-4-7\",\n messages=[{\"role\": \"user\", \"content\": \"Hello\"}],\n)\nprint(resp.choices[0].message.content)",
    "importOpenaiFromOpenaiConstClientNew": "import OpenAI from \"openai\";\n\nconst client = new OpenAI({\n baseURL: \"{0}\",\n apiKey: process.env.HANHUB_KEY,\n});\n\nconst resp = await client.chat.completions.create({\n model: \"claude-opus-4-7\",\n messages: [{ role: \"user\", content: \"Hello\" }],\n});\nconsole.log(resp.choices[0].message.content);",
    "linyu": "Linyu",
    "owner": "owner",
    "forest": "forest",
    "zhouNan": "Zhou Nan",
    "administrator": "Administrator",
    "week": "week",
    "chenXi": "Chen Xi",
    "developer": "Developer",
    "chen": "Chen",
    "zhaoMin": "Zhao Min",
    "readOnly": "read only",
    "zhao": "Zhao",
    "baseUrlCopied": "base_url copied",
    "accessSettings": "Access settings",
    "quickAccessTeamMembersWebhookAlertsDefault": "Quick access · Team members · Webhook alerts · Default configuration",
    "quickAccess": "Quick access",
    "copy": "Copy",
    "openaiCompatibleProtocolChangeBaseUrlKey": "OpenAI compatible protocol · Change base_url + key to access",
    "codeLanguage": "code language",
    "teamMember": "team member",
    "invitationLinkCopied": "Invitation link copied",
    "inviteMembers": "Invite members",
    "webhookAlert": "Webhook alert",
    "callbackUrl": "callback URL",
    "postToThisAddressWhenTheUsage": "POST to this address when the usage exceeds the threshold/the balance is insufficient.",
    "usageAlarm": "Usage alarm",
    "balanceAlarm": "Balance alarm",
    "channelCircuitBreaker": "Channel circuit breaker",
    "testEventSent": "Test event sent",
    "testSending": "Test sending",
    "defaultConfiguration": "Default configuration",
    "defaultSpeedLimitReqMin": "Default speed limit (req/min)",
    "initialRateLimitForNewKeys": "Initial rate limit for new keys",
    "defaultSpeedLimit": "Default speed limit",
    "defaultMagnificationGrouping": "Default magnification grouping",
    "determineTheGatewaySPriceIncreaseBased": "Determine the gateway's price increase based on the upstream price",
    "economy": "Economy (1.0×)",
    "standard": "Standard (1.05×)",
    "highQuality": "High quality (1.1×)",
    "economy2": "Economy (1.0×)",
    "standard2": "Standard (1.05×)",
    "highQuality2": "High quality (1.1×)",
    "automaticallyRetryOnFailure": "Automatically retry on failure",
    "upstreamXxSwitchChannelAndTryAgain": "Upstream 5xx / switch channel and try again when timeout",
    "automaticallyRetryOnFailure2": "Automatically retry on failure",
    "numberOfRetries": "Number of retries",
    "numberOfRetries2": "Number of retries",
    "defaultConfigurationSaved": "Default configuration saved",
    "saveSettings": "Save settings",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanhub-app-settings-page",
  content: t(content),
};

export default dictionary;
