import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "internet": "互联网",
    "manufacturing": "制造",
    "finance": "金融",
    "medical": "医疗",
    "education": "教育",
    "retail": "零售",
    "logistics": "物流",
    "energy": "能源",
    "consultation": "咨询",
    "people": "1-50 人",
    "people2": "50-200 人",
    "people3": "200-500 人",
    "people4": "500-1000 人",
    "moreThanPeople": "1000 人以上",
    "linWanqing": "林晚晴",
    "salesDirector": "销售总监",
    "onTheJob": "在职",
    "zhouMingyuan": "周明远",
    "advancedSales": "高级销售",
    "highSensitivity": "高敏",
    "salesSpecialist": "销售专员",
    "chenCe": "陈策",
    "keyAccountManager": "大客户经理",
    "suXiao": "苏晓",
    "salesAssistant": "销售助理",
    "trialPeriod": "试用期",
    "salesDirector2": "销售总监",
    "advancedSales2": "高级销售",
    "keyAccountManager2": "大客户经理",
    "salesSpecialist2": "销售专员",
    "salesAssistant2": "销售助理",
    "alertsForNewOpportunityAssignments": "新商机分配提醒",
    "whenNewBusinessOpportunitiesAreAssignedTo": "有新商机分配给我时，站内 + 邮件通知",
    "customerFollowUpDueReminder": "客户跟进到期提醒",
    "alertMeWhenACustomerHasnT": "客户超过 7 天未跟进时提醒我",
    "orderStatusChangeNotification": "订单状态变更通知",
    "notifiedWhenTheStatusOfTheOrder": "我负责的订单状态变化时通知",
    "weeklyPerformanceReportEmail": "每周业绩周报邮件",
    "aSummaryOfLastWeekSPerformance": "每周一上午推送上周业绩汇总",
    "accountSecurityAlert": "账号安全告警",
    "securityEventsSuchAsRemoteLoginAnd": "异地登录、密码变更等安全事件",
    "hulianTechnologyCoLtd": "瑚琏科技有限公司",
    "hulianCrm": "瑚琏 CRM",
    "internet2": "互联网",
    "people5": "50-200 人",
    "zhangjiangHighTechParkPudongNewArea": "上海市浦东新区张江高科技园区",
    "aOneStopCrmServiceProviderFocusing": "专注中后台与销售管理的一站式 CRM 服务商。",
    "pleaseEnterCompanyName": "请输入公司名称",
    "salesSpecialist3": "销售专员",
    "pleaseEnterMemberName": "请输入成员姓名",
    "pleaseEnterYourEmail": "请输入邮箱",
    "emailMustContain": "邮箱需含 @",
    "inviting": "邀请中",
    "invitationSent": "邀请已发送",
    "valueValueHasBeenInvitedToJoin": "已邀请 {0}（{1}）加入团队",
    "systemSettings": "系统设置",
    "corporateInformation": "企业资料",
    "memberManagement": "成员管理",
    "notificationSettings": "通知设置",
    "saveChanges": "保存修改",
    "reset": "重置",
    "companyInformationHasBeenSaved": "企业资料已保存",
    "companyName": "公司名称",
    "companyAbbreviation": "公司简称",
    "industry": "所属行业",
    "companySize": "公司规模",
    "officialWebsite": "官网",
    "contactNumber": "联系电话",
    "companyAddress": "公司地址",
    "companyProfile": "公司简介",
    "companyLogo": "公司 Logo",
    "coral": "瑚",
    "uploadLogo": "上传 Logo",
    "demoOccupancyNoRealUpload": "demo 占位，未接真实上传",
    "clickToUpload": "点击上传",
    "dataCompleteness": "资料完整度",
    "dataCompleteness2": "资料完整度",
    "perfectingYourBusinessProfileHelpsBuildTrust": "完善企业资料有助于在客户侧建立信任。",
    "teamTotal": "团队共",
    "members": "名成员",
    "inviteMembers": "邀请成员",
    "editValue": "编辑 {0}",
    "memberPermissionsEditingDemo": "成员权限编辑（demo）",
    "edit": "编辑",
    "notificationChannel": "通知渠道",
    "selectTheChannelToReceiveNotificationsAnd": "选择接收通知的渠道，可同时开启多个。",
    "notificationChannel2": "通知渠道",
    "mail": "邮件",
    "sms": "短信",
    "siteMessage": "站内信",
    "dingtalk": "钉钉",
    "defaultHomePageView": "默认首页视图",
    "thePageThatJumpsByDefaultAfter": "登录后默认跳转的页面。",
    "defaultHomePageView2": "默认首页视图",
    "workbench": "工作台",
    "customerList": "客户列表",
    "businessOpportunityBoard": "商机看板",
    "mail2": "邮件",
    "sms2": "短信",
    "siteMessage2": "站内信",
    "dingtalk2": "钉钉",
    "workbench2": "工作台",
    "customerList2": "客户列表",
    "businessOpportunityBoard2": "商机看板",
    "notificationSettingsSaved": "通知设置已保存",
    "channelValueHomePageValueValueValue": "渠道：{0} · 首页：{1} · 已开启 {2}/{3} 项",
    "saveSettings": "保存设置",
    "dangerousOperation": "危险操作",
    "resettingTheDemoDataWillClearAll": "重置演示数据将清空所有内存态变更（客户 / 商机 / 订单），刷新页面即可还原，本操作仅在 demo 中生效。",
    "resetDemoData": "重置演示数据",
    "confirmToResetDemoData": "确认重置演示数据？",
    "thisOperationWillClearAllMemoryState": "此操作将清空所有内存态变更，刷新页面可还原。仅影响当前 demo 会话，不涉及真实数据。",
    "cancel": "取消",
    "demoDataReset": "演示数据已重置",
    "fullyRestoredAfterRefreshingThePage": "刷新页面后完全还原",
    "confirmReset": "确认重置",
    "inviteMembers2": "邀请成员",
    "sendInvitation": "发送邀请",
    "memberName": "成员姓名",
    "suchAsWangLei": "如：王磊",
    "email": "邮箱",
    "anInvitationLinkWillBeSentTo": "邀请链接将发送至此邮箱",
    "role": "角色",
  },
  en: {
    "internet": "Internet",
    "manufacturing": "Manufacturing",
    "finance": "Finance",
    "medical": "Healthcare",
    "education": "Education",
    "retail": "Retail",
    "logistics": "Logistics",
    "energy": "Energy",
    "consultation": "Consulting",
    "people": "1-50 people",
    "people2": "50-200 people",
    "people3": "200-500 people",
    "people4": "500-1000 people",
    "moreThanPeople": "More than 1000 people",
    "linWanqing": "Lin Wanqing",
    "salesDirector": "Sales Director",
    "onTheJob": "Active",
    "zhouMingyuan": "Zhou Mingyuan",
    "advancedSales": "Advanced Sales",
    "highSensitivity": "Gao Min",
    "salesSpecialist": "Sales representative",
    "chenCe": "Chen Ce",
    "keyAccountManager": "Key account manager",
    "suXiao": "Su Xiao",
    "salesAssistant": "sales assistant",
    "trialPeriod": "Trial",
    "salesDirector2": "Sales Director",
    "advancedSales2": "Advanced Sales",
    "keyAccountManager2": "Key account manager",
    "salesSpecialist2": "Sales representative",
    "salesAssistant2": "sales assistant",
    "alertsForNewOpportunityAssignments": "Alerts for new opportunity assignments",
    "whenNewBusinessOpportunitiesAreAssignedTo": "When new business opportunities are assigned to me, I will be notified on the site + by email",
    "customerFollowUpDueReminder": "Customer follow-up due reminder",
    "alertMeWhenACustomerHasnT": "Alert me when a customer hasn't followed up in more than 7 days",
    "orderStatusChangeNotification": "Order status change notification",
    "notifiedWhenTheStatusOfTheOrder": "Notified when the status of the order I am responsible for changes",
    "weeklyPerformanceReportEmail": "Weekly performance report email",
    "aSummaryOfLastWeekSPerformance": "A summary of last week's performance will be pushed every Monday morning",
    "accountSecurityAlert": "Account security alert",
    "securityEventsSuchAsRemoteLoginAnd": "Security events such as remote login and password changes",
    "hulianTechnologyCoLtd": "Hulian Technology Co., Ltd.",
    "hulianCrm": "Hulian CRM",
    "internet2": "Internet",
    "people5": "50-200 people",
    "zhangjiangHighTechParkPudongNewArea": "Zhangjiang High-tech Park, Pudong New Area, Shanghai",
    "aOneStopCrmServiceProviderFocusing": "A one-stop CRM service provider focusing on middle and back-end and sales management.",
    "pleaseEnterCompanyName": "Please enter company name",
    "salesSpecialist3": "Sales representative",
    "pleaseEnterMemberName": "Please enter member name",
    "pleaseEnterYourEmail": "Please enter your email",
    "emailMustContain": "Email must contain @",
    "inviting": "Inviting",
    "invitationSent": "Invitation sent",
    "valueValueHasBeenInvitedToJoin": "{0} ({1}) has been invited to join the team",
    "systemSettings": "System settings",
    "corporateInformation": "Corporate information",
    "memberManagement": "Member management",
    "notificationSettings": "Notification settings",
    "saveChanges": "Save changes",
    "reset": "Reset",
    "companyInformationHasBeenSaved": "Company information has been saved",
    "companyName": "Company name",
    "companyAbbreviation": "Company abbreviation",
    "industry": "Industry",
    "companySize": "Company size",
    "officialWebsite": "Official website",
    "contactNumber": "Contact number",
    "companyAddress": "Company address",
    "companyProfile": "Company Profile",
    "companyLogo": "Company logo",
    "coral": "coral",
    "uploadLogo": "Upload logo",
    "demoOccupancyNoRealUpload": "Demo occupancy, no real upload",
    "clickToUpload": "Click to upload",
    "dataCompleteness": "Data completeness",
    "dataCompleteness2": "Data completeness",
    "perfectingYourBusinessProfileHelpsBuildTrust": "Perfecting your business profile helps build trust on the customer side.",
    "teamTotal": "Team total",
    "members": "members",
    "inviteMembers": "Invite members",
    "editValue": "Edit {0}",
    "memberPermissionsEditingDemo": "Member permissions editing (demo)",
    "edit": "Edit",
    "notificationChannel": "Notification channels",
    "selectTheChannelToReceiveNotificationsAnd": "Select the channel to receive notifications, and you can open multiple channels at the same time.",
    "notificationChannel2": "Notification channels",
    "mail": "Mail",
    "sms": "SMS",
    "siteMessage": "In-app notification",
    "dingtalk": "DingTalk",
    "defaultHomePageView": "Default home page view",
    "thePageThatJumpsByDefaultAfter": "The page that jumps by default after logging in.",
    "defaultHomePageView2": "Default home page view",
    "workbench": "Dashboard",
    "customerList": "Customer list",
    "businessOpportunityBoard": "Business opportunity board",
    "mail2": "Mail",
    "sms2": "SMS",
    "siteMessage2": "In-app notification",
    "dingtalk2": "DingTalk",
    "workbench2": "Dashboard",
    "customerList2": "Customer list",
    "businessOpportunityBoard2": "Business opportunity board",
    "notificationSettingsSaved": "Notification settings saved",
    "channelValueHomePageValueValueValue": "Channel: {0} · Home page: {1} · {2}/{3} items opened",
    "saveSettings": "Save settings",
    "dangerousOperation": "Dangerous operation",
    "resettingTheDemoDataWillClearAll": "Resetting the demo data will clear all memory state changes (customers/opportunities/orders), which can be restored by refreshing the page. This operation only takes effect in the demo.",
    "resetDemoData": "Reset demo data",
    "confirmToResetDemoData": "Confirm to reset demo data?",
    "thisOperationWillClearAllMemoryState": "This operation will clear all memory state changes and can be restored by refreshing the page. Only affects the current demo session and does not involve real data.",
    "cancel": "Cancel",
    "demoDataReset": "Demo data reset",
    "fullyRestoredAfterRefreshingThePage": "Fully restored after refreshing the page",
    "confirmReset": "Confirm reset",
    "inviteMembers2": "Invite members",
    "sendInvitation": "Send invitation",
    "memberName": "Member name",
    "suchAsWangLei": "Such as: Wang Lei",
    "email": "Email",
    "anInvitationLinkWillBeSentTo": "An invitation link will be sent to this email",
    "role": "Role",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-crm-app-settings-page",
  content: t(content),
};

export default dictionary;
