import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "buildFailedNextBuildExitCodeType": "✗ 构建失败：next build 退出码 1（类型检查报错 3 处）",
    "deploymentQueuedForAvailableBuildContainer": "部署已排队，等待可用的构建容器…",
    "deploymentHasBeenCanceledByUser": "⚠ 部署已被用户取消",
    "theBuildOutputIsUnchangedInThis": "本次推送未改动构建输出，跳过部署。",
    "buildInProgress": "构建进行中…",
    "joinedTheTeam": "已入队",
    "deploymentQueue": "部署排队",
    "waiting": "等待中",
    "buildStarts": "构建开始",
    "buildFailed": "构建失败",
    "buildCompleted": "构建完成",
    "distributeToEdgeNetwork": "分发到边缘网络",
    "readyToDeploy": "部署就绪",
    "waitingForReady": "等待就绪",
    "waiting2": "等待中",
    "inProgress": "进行中…",
    "failed": "失败",
    "deploymentDoesNotExist": "部署不存在",
    "theDeploymentRecordMayHaveBeenCleaned": "该部署记录可能已被清理，或链接有误。",
    "returnToDeploymentHistory": "返回部署历史",
    "deploymentId": "部署 ID",
    "environment": "环境",
    "produce": "生产",
    "preview": "预览",
    "branch": "分支",
    "submit": "提交",
    "triggerMode": "触发方式",
    "manual": "手动",
    "gitPush": "Git 推送",
    "create": "创建",
    "timeConsumingToBuild": "构建耗时",
    "address": "地址",
    "project": "项目",
    "deploymentHistory": "部署历史",
    "accessDeployment": "访问部署",
    "redeploymentTriggered": "已触发重新部署",
    "valueValueIsRebuildingWithTheSame": "{0} · {1} 正在用相同提交重建。",
    "redeploy": "重新部署",
    "rollBackToThisDeployment": "回滚到此部署？",
    "productionTrafficWillBeSwitchedToValue": "生产流量将切换到 {0}（{1}）。",
    "confirmRollback": "确认回滚",
    "cancel": "取消",
    "rolledBack": "已回滚",
    "valueTheProductionEnvironmentHasBeenSwitched": "{0} 生产环境已切换到 {1}。",
    "rollBackHere": "回滚到此",
    "buildSteps": "构建步骤",
    "buildLog": "构建日志",
    "deploymentLifeCycle": "部署生命周期",
  },
  en: {
    "buildFailedNextBuildExitCodeType": "✗ Build failed: next build exit code 1 (type check error reported in 3 places)",
    "deploymentQueuedForAvailableBuildContainer": "Deployment queued for available build container...",
    "deploymentHasBeenCanceledByUser": "⚠ Deployment has been canceled by user",
    "theBuildOutputIsUnchangedInThis": "The build output is unchanged in this push and deployment is skipped.",
    "buildInProgress": "Build in progress...",
    "joinedTheTeam": "Joined the team",
    "deploymentQueue": "Deployment queue",
    "waiting": "Waiting",
    "buildStarts": "Build starts",
    "buildFailed": "Build failed",
    "buildCompleted": "Build completed",
    "distributeToEdgeNetwork": "Distribute to edge network",
    "readyToDeploy": "Ready to deploy",
    "waitingForReady": "Waiting for ready",
    "waiting2": "Waiting",
    "inProgress": "In progress...",
    "failed": "failed",
    "deploymentDoesNotExist": "Deployment does not exist",
    "theDeploymentRecordMayHaveBeenCleaned": "The deployment record may have been cleaned up, or the link may be incorrect.",
    "returnToDeploymentHistory": "Return to deployment history",
    "deploymentId": "Deployment ID",
    "environment": "environment",
    "produce": "produce",
    "preview": "Preview",
    "branch": "branch",
    "submit": "Submit",
    "triggerMode": "Trigger mode",
    "manual": "Manual",
    "gitPush": "Git push",
    "create": "create",
    "timeConsumingToBuild": "Time consuming to build",
    "address": "address",
    "project": "Project",
    "deploymentHistory": "Deployment history",
    "accessDeployment": "access deployment",
    "redeploymentTriggered": "Redeployment triggered",
    "valueValueIsRebuildingWithTheSame": "{0} · {1} is rebuilding with the same commit.",
    "redeploy": "Redeploy",
    "rollBackToThisDeployment": "Roll back to this deployment?",
    "productionTrafficWillBeSwitchedToValue": "Production traffic will be switched to {0} ({1}).",
    "confirmRollback": "Confirm rollback",
    "cancel": "Cancel",
    "rolledBack": "Rolled back",
    "valueTheProductionEnvironmentHasBeenSwitched": "{0} The production environment has been switched to {1}.",
    "rollBackHere": "Roll back here",
    "buildSteps": "Build steps",
    "buildLog": "Build log",
    "deploymentLifeCycle": "Deployment life cycle",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanship-components-deploy-detail",
  content: t(content),
};

export default dictionary;
