import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "produce": "生产",
    "preview": "预览",
    "projectDoesNotExist": "项目不存在",
    "theItemMayHaveBeenDeletedOr": "该项目可能已被删除或迁移。",
    "returnToProjectList": "返回项目列表",
    "rolledBackToProductionEnvironment": "已回滚生产环境",
    "valueAlreadyPointsToValueValue": "{0} 已指向 {1}（{2}…）",
    "redeploymentTriggered": "已触发重新部署",
    "rebuildingBasedOnValue": "正在基于 {0} 重新构建…",
    "environment": "环境",
    "deploymentAddress": "部署地址",
    "status": "状态",
    "view": "查看",
    "rollBackToThisDeployment": "回滚到此部署？",
    "theProductionEnvironmentWillImmediatelyPointTo": "生产环境将立即指向 {0}，用户访问的内容随之改变。",
    "rollback": "回滚",
    "cancel": "取消",
    "rollback2": "回滚",
    "redeploy": "重新部署",
    "redeployBasedOnThisCommit": "基于此提交重新部署",
    "project": "项目",
    "visitSite": "访问站点",
    "redeploy2": "重新部署",
    "productionEnvironment": "生产环境",
    "automaticDeploymentIsTurnedOn": "已开启自动部署",
    "automaticDeploymentIsTurnedOff": "自动部署已关闭",
    "automaticDeployment": "自动部署",
    "domainName": "域名:",
    "build": "· 构建",
    "details": "详情",
    "thereIsNoDeploymentInTheProduction": "生产环境暂无部署",
    "pushToProductionBranchOrManuallyTrigger": "推送到生产分支或手动触发一次部署。",
    "allDeployments": "所有部署",
    "all": "全部",
    "produce2": "生产",
    "preview2": "预览",
    "filterByEnvironment": "按环境筛选",
    "noDeploymentsMatchedTheFilter": "没有符合筛选的部署",
    "switchToAllToViewDeploymentsFor": "切换到「全部」查看所有环境的部署。",
    "staticSite": "静态站点",
  },
  en: {
    "produce": "produce",
    "preview": "Preview",
    "projectDoesNotExist": "Project does not exist",
    "theItemMayHaveBeenDeletedOr": "The item may have been deleted or moved.",
    "returnToProjectList": "Return to project list",
    "rolledBackToProductionEnvironment": "Rolled back to production environment",
    "valueAlreadyPointsToValueValue": "{0} already points to {1} ({2}...)",
    "redeploymentTriggered": "Redeployment triggered",
    "rebuildingBasedOnValue": "Rebuilding based on {0}...",
    "environment": "environment",
    "deploymentAddress": "Deployment address",
    "status": "Status",
    "view": "View",
    "rollBackToThisDeployment": "Roll back to this deployment?",
    "theProductionEnvironmentWillImmediatelyPointTo": "The production environment will immediately point to {0} and the content users access will change.",
    "rollback": "rollback",
    "cancel": "Cancel",
    "rollback2": "rollback",
    "redeploy": "Redeploy",
    "redeployBasedOnThisCommit": "Redeploy based on this commit",
    "project": "Project",
    "visitSite": "Visit site",
    "redeploy2": "Redeploy",
    "productionEnvironment": "production environment",
    "automaticDeploymentIsTurnedOn": "Automatic deployment is turned on",
    "automaticDeploymentIsTurnedOff": "Automatic deployment is turned off",
    "automaticDeployment": "Automatic deployment",
    "domainName": "Domain name:",
    "build": "· Build",
    "details": "Details",
    "thereIsNoDeploymentInTheProduction": "There is no deployment in the production environment yet",
    "pushToProductionBranchOrManuallyTrigger": "Push to production branch or manually trigger a deployment.",
    "allDeployments": "All deployments",
    "all": "All",
    "produce2": "produce",
    "preview2": "Preview",
    "filterByEnvironment": "Filter by environment",
    "noDeploymentsMatchedTheFilter": "No deployments matched the filter",
    "switchToAllToViewDeploymentsFor": "Switch to \"All\" to view deployments for all environments.",
    "staticSite": "Static site",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanship-components-project-overview",
  content: t(content),
};

export default dictionary;
