import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    "logicalFlaws": "逻辑缺陷",
    "runtimeErrorsSuchAsNullPointersBoundaries": "空指针、边界、并发等运行时错误",
    "safety": "安全",
    "securityRisksSuchAsInjectionAuthenticationAnd": "注入、鉴权、密钥泄露等安全风险",
    "performance": "性能",
    "nQueriesFutileReRenderingBlockingCalls": "N+1 查询、无谓重渲染、阻塞调用",
    "style": "风格",
    "namingFormattingAndReadabilityConventions": "命名、格式、可读性约定",
    "complexity": "复杂度",
    "circleComplexityDeepNestingAndUltraLong": "圈复杂度、深嵌套、超长函数",
    "testCoverage": "测试覆盖",
    "whetherNewLogicIsAddedToThe": "新增逻辑是否伴随测试",
    "theGateGuardsWereBranched": "门禁分支",
    "theAccessLine": "门禁线",
    "minimumQualityScore": "最低质量分",
    "seriousProblemsAtTheUpperLimit": "严重问题上限",
    "minimumCoverage": "最低覆盖率",
    "mustPassTheRuleSet": "必过规则集",
    "accessControlSimulator": "门禁模拟器",
    "dragThresholdsToPreviewPassBlockResults": "拖动阈值，实时预览最近 10 次审查的通过 / 阻断结果",
    "minimumQualityScore2": "最低质量分",
    "minimumMassThreshold": "最低质量分阈值",
    "seriousProblemsAtTheUpperLimit2": "严重问题上限",
    "upperLimitThresholdForSeriousProblems": "严重问题上限阈值",
    "minimumCoverage2": "最低覆盖率",
    "minimumCoverageThreshold": "最低覆盖率阈值",
    "basedOnTheCurrentThresholdInThe": "按当前阈值，最近 10 次审查中",
    "thisWillBeBlocked": "次会被阻断",
    "blockedCensorship": "被阻断的审查",
    "pleaseEnterTheAccessControlBranch": "请输入门禁分支",
    "theAccessControlHasBeenEstablished": "门禁已创建",
    "valueValueMinimumScoreValue": "{0} · {1} · 最低分 {2}",
    "qualityAccessControl": "质量门禁",
    "setEntryThresholdsForEachWarehouseBranch": "为每个仓库分支设定准入阈值，不达标的 PR 自动阻断合入",
    "aNewGateGateWasConstructed": "新建门禁",
    "aNewGateGateWasConstructed2": "新建门禁",
    "establishedAccessControls": "创建门禁",
    "targetWarehouse": "目标仓库",
    "targetWarehouse2": "目标仓库",
    "defaultBranchValue": "默认分支 {0}",
    "theGateGuardsWereBranched2": "门禁分支",
    "forExampleMainRelease": "如：main / release",
    "minimumQualityScore3": "最低质量分",
    "seriousProblemsAtTheUpperLimit3": "严重问题上限",
    "minimumCoverage3": "最低覆盖率（%）",
    "mustPassTheRuleSet2": "必过规则集",
    "mustPassTheRuleSet3": "必过规则集",
  },
  en: {
    "logicalFlaws": "Logical flaws",
    "runtimeErrorsSuchAsNullPointersBoundaries": "Runtime errors such as null pointers, boundaries, and concurrency",
    "safety": "Safety",
    "securityRisksSuchAsInjectionAuthenticationAnd": "security risks such as injection, authentication, and key leakage",
    "performance": "Performance",
    "nQueriesFutileReRenderingBlockingCalls": "N+1 queries, futile re-rendering, blocking calls",
    "style": "Style",
    "namingFormattingAndReadabilityConventions": "Naming, formatting, and readability conventions",
    "complexity": "Complexity",
    "circleComplexityDeepNestingAndUltraLong": "Circle complexity, deep nesting, and ultra-long functions",
    "testCoverage": "Test coverage",
    "whetherNewLogicIsAddedToThe": "Whether new logic is added to the test",
    "theGateGuardsWereBranched": "Protected branches",
    "theAccessLine": "The access line",
    "minimumQualityScore": "Minimum quality score",
    "seriousProblemsAtTheUpperLimit": "Serious problems at the upper limit",
    "minimumCoverage": "Minimum coverage",
    "mustPassTheRuleSet": "Must pass the rule set",
    "accessControlSimulator": "Quality gate simulator",
    "dragThresholdsToPreviewPassBlockResults": "Drag thresholds to preview pass/block results from the last 10 reviews in real time",
    "minimumQualityScore2": "Minimum quality score",
    "minimumMassThreshold": "Minimum mass threshold",
    "seriousProblemsAtTheUpperLimit2": "Serious problems at the upper limit",
    "upperLimitThresholdForSeriousProblems": "Upper limit threshold for serious problems",
    "minimumCoverage2": "Minimum coverage",
    "minimumCoverageThreshold": "Minimum coverage threshold",
    "basedOnTheCurrentThresholdInThe": "Based on the current threshold, in the last 10 reviews",
    "thisWillBeBlocked": "This will be blocked",
    "blockedCensorship": "Blocked censorship",
    "pleaseEnterTheAccessControlBranch": "Please enter the gate branch",
    "theAccessControlHasBeenEstablished": "Quality gate created",
    "valueValueMinimumScoreValue": "{0} · {1} · Minimum Score: {2}",
    "qualityAccessControl": "Quality gate",
    "setEntryThresholdsForEachWarehouseBranch": "Set merge requirements by repository and branch. Pull requests that fail the checks are blocked.",
    "aNewGateGateWasConstructed": "Create quality gate",
    "aNewGateGateWasConstructed2": "Create quality gate",
    "establishedAccessControls": "Configured quality gates",
    "targetWarehouse": "Target repository",
    "targetWarehouse2": "Target repository",
    "defaultBranchValue": "Default branch {0}",
    "theGateGuardsWereBranched2": "Protected branches",
    "forExampleMainRelease": "For example: main / release",
    "minimumQualityScore3": "Minimum quality score",
    "seriousProblemsAtTheUpperLimit3": "Serious problems at the upper limit",
    "minimumCoverage3": "Minimum Coverage (%)",
    "mustPassTheRuleSet2": "Must pass the rule set",
    "mustPassTheRuleSet3": "Must pass the rule set",
  },
} as const;

export type ContentKey = keyof typeof content["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = {
  key: "demo-hanreview-app-gates-page",
  content: t(content),
};

export default dictionary;
