import { t, type Dictionary } from "intlayer";
import { DOCS_LOCALE } from "../../../../../lib/docs-locale";

export const content = {
  "zh-CN": {
    bronzeMember: "铜牌会员",
    silverMember: "银牌会员",
    goldMember: "金牌会员",
    diamondMember: "钻石会员",
    weiZhang: "张伟",
    yuhangDistrictHangzhouZhejiang: "浙江省杭州市余杭区",
    hanyunTower969WestWenyiRoad: "文一西路 969 号瀚云大厦",
    weiZhangWork: "张伟（公司）",
    xihuDistrictHangzhouZhejiang: "浙江省杭州市西湖区",
    text588GudunRoad: "古墩路 588 号",
    noCouponsYet: "暂无优惠券",
    opening: "正在跳转去使用「",
    closingQuote: "」",
    available: "可用 (",
    used: "已用 (",
    expired: "过期 (",
    saveProfile: "保存资料",
    profileSaved: "资料保存成功",
    displayName: "昵称",
    hanshopCustomer: "瀚选用户",
    enterADisplayName: "请输入昵称",
    phoneNumber: "手机号",
    email: "邮箱",
    enterAnEmailAddress: "请输入邮箱",
    birthday: "生日",
    newRecipient: "新收货人",
    selectARegion: "请选择地区",
    streetAddress: "详细地址",
    addressAdded: "地址添加成功",
    addressDeleted: "地址已删除",
    defaultAddressUpdated: "已设为默认地址",
    default: "默认",
    setAsDefault: "设为默认",
    delete: "删除",
    region: "所在地区",
    selectProvinceCityDistrict: "选择省/市/区",
    addAddress: "确认添加",
    cancel: "取消",
    addShippingAddress: "+ 新增收货地址",
    accountSecurityDetails: "账户安全信息",
    signInPhone: "登录手机",
    text1388866Linked: "138****8866 · 已绑定",
    signInEmail: "登录邮箱",
    userLinked: "user@hulian.dev · 已绑定",
    password: "登录密码",
    setLastChangedJan152026: "已设置 · 上次修改 2026-01-15",
    accountStatus: "账户状态",
    active: "正常",
    openingPasswordSettings: "跳转修改密码页面",
    changePassword: "修改登录密码",
    deleteAccount: "注销账户",
    deleteThisAccount: "确认注销账户？",
    yourOrdersPointsAndFavoritesWillBePermanentlyDeletedThisCannotBeUndoneMakeSureAllPendingRefundsA: "注销后，您的账户数据（订单、积分、收藏）将被永久清除，此操作不可恢复。确认前请确保已处理完所有待退款订单。",
    accountDeletionRequestSubmittedProcessingMayTakeUpTo7BusinessDays: "账户注销申请已提交，将在 7 个工作日内处理",
    deleteAccount2: "确认注销",
    customerAvatar: "用户头像",
    use: "用",
    uidHs10086001: "UID：HS10086001",
    pointsToNextTier: "距 {1} 还差 {0} 积分",
    points: "积分",
    highestTierReached: "已达最高等级",
    balance: "余额",
    coupons: "张",
    coupons2: "优惠券",
    myCoupons: "我的优惠券",
    profile: "账户资料",
    shippingAddresses: "收货地址",
    accountSecurity: "账户安全",
  },
  en: {
    bronzeMember: "Bronze member",
    silverMember: "Silver member",
    goldMember: "Gold member",
    diamondMember: "Diamond member",
    weiZhang: "Wei Zhang",
    yuhangDistrictHangzhouZhejiang: "Yuhang District, Hangzhou, Zhejiang",
    hanyunTower969WestWenyiRoad: "Hanyun Tower, 969 West Wenyi Road",
    weiZhangWork: "Wei Zhang (Work)",
    xihuDistrictHangzhouZhejiang: "Xihu District, Hangzhou, Zhejiang",
    text588GudunRoad: "588 Gudun Road",
    noCouponsYet: "No coupons yet",
    opening: "Opening \"",
    closingQuote: "\"",
    available: "Available (",
    used: "Used (",
    expired: "Expired (",
    saveProfile: "Save profile",
    profileSaved: "Profile saved",
    displayName: "Display name",
    hanshopCustomer: "HanShop customer",
    enterADisplayName: "Enter a display name",
    phoneNumber: "Phone number",
    email: "Email",
    enterAnEmailAddress: "Enter an email address",
    birthday: "Birthday",
    newRecipient: "New recipient",
    selectARegion: "Select a region",
    streetAddress: "Street address",
    addressAdded: "Address added",
    addressDeleted: "Address deleted",
    defaultAddressUpdated: "Default address updated",
    default: "Default",
    setAsDefault: "Set as default",
    delete: "Delete",
    region: "Region",
    selectProvinceCityDistrict: "Select province / city / district",
    addAddress: "Add address",
    cancel: "Cancel",
    addShippingAddress: "+ Add shipping address",
    accountSecurityDetails: "Account security details",
    signInPhone: "Sign-in phone",
    text1388866Linked: "138****8866 · Linked",
    signInEmail: "Sign-in email",
    userLinked: "user@hulian.dev · Linked",
    password: "Password",
    setLastChangedJan152026: "Set · Last changed Jan 15, 2026",
    accountStatus: "Account status",
    active: "Active",
    openingPasswordSettings: "Opening password settings",
    changePassword: "Change password",
    deleteAccount: "Delete account",
    deleteThisAccount: "Delete this account?",
    yourOrdersPointsAndFavoritesWillBePermanentlyDeletedThisCannotBeUndoneMakeSureAllPendingRefundsA: "Your orders, points, and favorites will be permanently deleted. This cannot be undone. Make sure all pending refunds are resolved before continuing.",
    accountDeletionRequestSubmittedProcessingMayTakeUpTo7BusinessDays: "Account deletion request submitted. Processing may take up to 7 business days.",
    deleteAccount2: "Delete account",
    customerAvatar: "Customer avatar",
    use: "Use",
    uidHs10086001: "UID: HS10086001",
    pointsToNextTier: "{0} points to {1}",
    points: "Points",
    highestTierReached: "Highest tier reached",
    balance: "Balance",
    coupons: "coupons",
    coupons2: "Coupons",
    myCoupons: "My coupons",
    profile: "Profile",
    shippingAddresses: "Shipping addresses",
    accountSecurity: "Account security",
  },
} as const;

export type ContentKey = keyof (typeof content)["zh-CN"];

export function copy(key: ContentKey, ...values: readonly unknown[]): string {
  return values.reduce<string>((text, value, index) => text.replaceAll(`{${index}}`, String(value)), content[DOCS_LOCALE][key]);
}

const dictionary: Dictionary = { key: "demo-shop-shop-account-page", content: t(content) };
export default dictionary;
